### ISSUE TITLE
Unable to connect to xx.xx.xx.xx:6379

### ISSUE THREAD

**Issue by shihao1001** [lettuce-io/lettuce-core#1004]
## Bug Report

Pipeline contained one or more invalid commands; nested exception is io.lettuce.core.RedisException: io.lettuce.core.RedisConnectionException: Unable to connect to xx.xx.xx.xx:6379org.springframework.data.redis.connection.RedisPipelineException:Pipeline contained one or more invalid commands; nested exception is io.lettuce.core.RedisException: io.lettuce.core.RedisConnectionException: Unable to connect to xx.xx.xx.xx:6379at org.springframework.data.redis.connection.lettuce.LettuceConnection.closePipeline(LettuceConnection.java:530)at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)at com.sun.proxy.$Proxy351.closePipeline(Unknown Source)at com.CacheInterceptor$1.doInRedis(CacheInterceptor.java:419)at org.springframework.data.redis.core.RedisTemplate.lambda$executePipelined$1(RedisTemplate.java:324)at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:320)at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:310)at 

#### Environment

- Lettuce version(s): 5.0.2.RELEASE
- Redis version: 5.0

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Please make also sure to include the full stack trace as the trace is truncated.

**Comment by shihao1001** [comment]
Hi, mp911de, this error happened when flushCache calling doCache method, and it arises only occasionally.
Sorry about it. Because this error happened in product environment, so I can not provider more information about my company system code.

**Comment by mp911de** [comment]
The description issue is not about your code, it is about the cause of `RedisConnectionException`. Without the cause (that's the part that is missing from the stack trace), we cannot diagnose the issue.

**Comment by shihao1001** [comment]
I pasted the stack trace again, now it is the full stack trace. I have no idea about the cause of RedisConnectionException, so I come here to request your help. This error is strange, because the redis is ok, our app can connect to the redis server, but this error appears sometimes.

**Comment by shihao1001** [comment]
close
