### ISSUE TITLE
Optimized Multiple SET (and other Single Key Commands) Execution for Cluster With Grouping by Nodes Instead of Slot ID

### ISSUE THREAD

**Issue by azhukayak** [lettuce-io/lettuce-core#1009]
#### Is your feature request related to a problem? Please describe

Currently when executing MGET (or MSET) commands thru the RedisAdvancedClusterAsyncCommands interface, the keys are grouped by Slot ID and then executed.  However this is sub-optimal because for keys that have different Slot ID but are owned by the same cluster Node, they would be executed separately.

#### Describe the solution you'd like

We can group keys by Node ID (ownership) and executed.

#### Describe alternatives you've considered

I have experimented with using [hash tags ](https://redis.io/topics/cluster-spec)(ie "{hash tag}key")  so that the spread of keys are limited to a pre-determined number of slots, but this would require changing the keys and prefixing them with hash tag.  It works but would want a more general solution and reserve the hash tag uses for cases where we want to co-locate data.

#### Teachability, Documentation, Adoption, Migration Strategy

There should be no difference in usage of the API since it is an execution optimization only.

**Comment by mp911de** [comment]
Thanks for the request. Adding tags would change the actual key name and that's something we cannot do. What is the problem that you experience with sending multiple commands to the same node?

**Comment by azhukayak** [comment]
This is really performance request.  

I am using Redis Cluster and I want to use MGET and MSET to optimized bulk loading or getting of keys.   I assume that for keys that were served from the same Node would be execute pipelined together .. looking at the commands as received by the Redis nodes ... they are not.

Debugging thru the lettuce code ... looks like it groups by Slot ID ... so it misses opportunity to execute the keys that are on different Slot ID but is being served by the same Node.

**Comment by mp911de** [comment]
Lettuce uses pipelining as its default execution mode. Commands are written immediately to the transport instead of awaiting completion of a previous command. Because of this, we can execute commands asynchronously and reduce latency.

Redis requires separate commands issued per slot. Touching keys with a single command that are served by the same node but map to different slots are rejected by Redis with `-CROSSSLOT`.

**Comment by azhukayak** [comment]
I did not realize that.  So for MGET it would be impossible to optimize this way.

Would it be able to do this for GET/SET?

I tried disabling command autoFlush and executing 1000 SET commands to get pipelining with manual flushing.   I don't see the SET coming thru optimized.

**Comment by azhukayak** [comment]
I wrote a small program to test the difference between getting optimized pipelined execution vs not.

When I  executed the program without using Hash Tag, the execution as far as I can see on the Redis nodes are not grouped/pipelined.

When I executed manually passing args "useHashTag" to pre-optimized the keys with hash tag, the execution as seen on the Redis nodes seems to be more optimized/pipelined better.

So I would like to have this optimized behavior by using autoFlush off and executing a lot SET, flush at the end and then have the Lettuce client group/flush/pipeline all these SETs by nodes before sending to Redis.

This would give the optimized execution w/o having to pre-optimized with hash tagged keys.

Do you think this is doable single key commands like SET and GET?

```java
public class TestBatchedSet {

    public interface BatchedCommands extends Commands, BatchExecutor {
        @Command("SET ?0 ?1 EX ?2")
        void set(@Key String key, @Value String value, String expSeconds, CommandBatching batching);
    }

    public static void main(String[] args) throws Exception {

        boolean useHashTag = (args.length > 0 && args[0].equals("useHashTag")) ? true : false;

        System.out.println("useHashTag: " + useHashTag);

        RedisClusterClient client = RedisClusterClient.create("redis://localhost:7000");

        try (StatefulRedisClusterConnection<String, String> conn = client.connect(StringCodec.UTF8)) {

            RedisCommandFactory factory = new RedisCommandFactory(conn, Arrays.asList(StringCodec.UTF8));

            BatchedCommands commands = factory.getCommands(BatchedCommands.class);

            for (int i = 0; i < 1000; i++) {
                String key = "Key-" + i;
                if (useHashTag) {
                    key = "{" + (CRC16.crc16(key.getBytes()) % 20) + "}" + key;
                }

                commands.set(key, "Value-" + i, "10", CommandBatching.queue());
            }

            commands.flush();
        } finally {
            client.shutdown();
        }
    }
}
```

**Comment by mp911de** [comment]
All this starts getting too complicated. Don't give me a solution, give me a real problem that you want to solve, ideally with some perf numbers to make a proper decision.

**Comment by azhukayak** [comment]
Agreed, it does get much more complicated so might not be worth implementing in the base client layer.

Thanks,  I will close this for now.
