### ISSUE TITLE
ARGV eval parameters should be same type as the script (String or byte[])

### ISSUE THREAD

**Issue by danielsomekh** [lettuce-io/lettuce-core#1015]
## Bug Report

In `RedisScriptingCommands`, the generic `V` (corresponding to the values stored in the cache), is used as the argument type for the values that are passed into the `ARGV` Lua variable. But, these arguments have no direct relation to the data stored in the cache. Because the only use of these arguments is in the script, they should have the same type as the script (as discussed in https://github.com/lettuce-io/lettuce-core/issues/1010, the script type will be changed to `String` or `byte[]`).

https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/api/sync/RedisScriptingCommands.java#L77

**Comment by mp911de** [comment]
These aren't keys either. So basically, every approach is potentially wrong. One might want to use plain strings, other people put in JSON or use any other serialized format. That being said, we're not going to change `ARGV` from `V` to something different.
