### ISSUE TITLE
Multiple connections are getting created even when only one RedisAdvancedClusterAsyncCommands<String, String> is shared among multiple threads

### ISSUE THREAD

**Issue by sagarsitap596** [lettuce-io/lettuce-core#1019]
## Bug Report

single RedisAdvancedClusterAsyncCommands<String, String> instance is shared among multiple threads. But still I more than 4 connections are getting created and closed frequently

#### Current Behavior

I believe only connections should be created once and should be reused instead of closing it and again recreating new connections 

io.lettuce
5.1.6.RELEASE

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by sagarsitap596** [comment]
Sure,

Redis config :   AWS redis -  3 shards redis cluster with one replica each. So total 6 nodes.

In my application single instance of RedisAdvancedClusterAsyncCommands<String, String> is used for communicating with redis.

Its a multi threaded application which gets lacs of requests per minute and for every operation (create/update/delete) operation on key (HSET/HGET/HDEL) is performed.

I believe only one connection should get created as I have only one RedisAdvancedClusterAsyncCommands shared among multiple threads.

When I cheked Aws cludwatch I could see around 4-8 connections being created for every redis node.

So I am confused if it is expected behaviour or is ther anything wrong I am doing with lettuce.

This the way I am creating command


RedisURI redisUri = RedisURI.Builder.redis(redisNodeURL).build();
        RedisClusterClient clusterClient = RedisClusterClient.create(redisUri);
        asyncCommands = clusterClient.connect().async();


Can you also help me in taking decision on wheather I should use single instance of RedisAdvancedClusterAsyncCommands or should I go for pooling option like


GenericObjectPoolConfig genericObjectPoolConfig = createGenericObjectPoolConfig(app);

GenericObjectPool<StatefulRedisClusterConnection<String, String>> connectionPool = ConnectionPoolSupport.createGenericObjectPool(() -> clusterClient.connect(),
				genericObjectPoolConfig);

Thanks in advance

**Comment by mp911de** [comment]
Thanks a lot.

You should use a single connection unless using blocking operations (`BLPOP`, `BZPOP`, `XREAD`).
I updated the [reference docs](https://github.com/lettuce-io/lettuce-core/wiki/Redis-Cluster#connection-count-for-a-redis-cluster-connection-object) with the internals to help you understand why a single cluster connection creates multiple transport connections.

Check out the [pooling docs](https://github.com/lettuce-io/lettuce-core/wiki/Connection-Pooling-5.1) to understand when to use pooling.

Closing this ticket as there's nothing left to do here.

**Comment by sagarsitap596** [comment]
Thanks a lot.  (y)
