### ISSUE TITLE
redis key occasionally set fail

### ISSUE THREAD

**Issue by linchuyao** [lettuce-io/lettuce-core#1022]

**Comment by linchuyao** [comment]
![image](https://user-images.githubusercontent.com/32710423/56635334-ce5ff200-6697-11e9-9bd0-5a2b177d7f7f.png)

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by linchuyao** [comment]
![image](https://user-images.githubusercontent.com/32710423/56635473-57772900-6698-11e9-86a7-f92b28ac8b9c.png)

**Comment by mp911de** [comment]
Sorry, a screenshot of your code isn’t helpful. Please describe what you’re attempting to achieve, what happens and what you expect to happen. On failures, please attach a stack trace.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
