### ISSUE TITLE
custom codec causes Redis cluster failed to rebalance 

### ISSUE THREAD

**Issue by jeffreye** [lettuce-io/lettuce-core#1023]
## Bug Report

I have a Redis cluster with 6 masters + 6 slaves. I am using SerializationUtils from Apache Commons Lang for transcoding keys and values. Lettuce works fine with all operations, but rebalance/reshard clusters (using `redis-cli --cluster`) won't work.  When I use UTF-8 as codec, everything works well.

Please correct me if I should create the issue on Redis instead of here. 

#### Current Behavior

<details>
<summary>Stack trace</summary>

```redis-cli
CROSSSLOT Keys in request don’t hash to the same slot
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
import org.apache.commons.lang3.SerializationUtils;

public class MyRedisCodec implements RedisCodec<String, String> {

...

    @Override
    public ByteBuffer encodeKey(String key) {
        byte[] data = SerializationUtils.serialize(key);
        return ByteBuffer.wrap(data);

    }

...


}

```

</details>

#### Expected behavior/code

Redis cluster should be able to reshard/rebalance

#### Environment

- Lettuce version(s): 5.1.4.RELEASE
- Redis version: 5.0.3

#### Additional context

The SerializeUtils would put "\xac\xed\x00" as the prefix, this could be the root cause.

**Comment by mp911de** [comment]
> but it doesn't work when I try to rebalance/reshard

Could you elaborate a bit? I do not understand what's happening. Providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem would help.

**Comment by jeffreye** [comment]
Simply do `redis-cli --cluster reshard localhost`

**Comment by jeffreye** [comment]
1. Create a redis cluster with 3+ masters
2. Run the code attached in the zip.
3. `redis-cli --cluster reshard localhost` 


[codec-sample-project.zip](https://github.com/lettuce-io/lettuce-core/files/3167882/codec.zip)

**Comment by mp911de** [comment]
The reported issue is a shortcoming of `redis-cli`. Redis guarantees to be binary-safe. The stored data uses byte values below the ASCII range which is perfectly fine. However, the tooling around Redis needs to take this into consideration and handle data appropriately. I suggest filing an issue in https://github.com/antirez/redis.
