### ISSUE TITLE
Attach topology retrieval exceptions when Lettuce cannot retrieve a topology update

### ISSUE THREAD

**Issue by StillerRen** [lettuce-io/lettuce-core#1024]
## Feature Request

throw the "NOAUTH" exception instead of “Cannot retrieve initial cluster partitions”, in other words, clarify why lettuce can't initialize the partitions.

#### Is your feature request related to a problem? Please describe

if a cluster has password, but we don's configure it for lettuce RedisClusterClient.
when the RedisClusterClient would initialize the cluster partitions, lettuce would create a new connection. and then report the exception "Cannot retrieve initial cluster partitions", just some WARN logs that report "NOAUTH".
here is the error:

```
Caused by: io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='127.0.0.1', port=2882], RedisURI [host='127.0.0.1', port=2881]]
        at io.lettuce.core.cluster.RedisClusterClient.doLoadPartitions(RedisClusterClient.java:874)
        at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:844)
        at io.lettuce.core.cluster.RedisClusterClient.initializePartitions(RedisClusterClient.java:819)
        at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:345)
```

#### Describe the solution you'd like

add the info why lettuce cannot retrieve initial cluster partitions in the exception, connection refuse or "NOAUTH" or others.

**Comment by mp911de** [comment]
Redis Cluster partition retrieval is attempted from multiple hosts and hence multiple errors can happen. Lettuce does not fail on the first error but attempts to retrieve the topology from other nodes. Since each Redis node can be configured individually, one node can be configured with a wrong password while other nodes might succeed.

We attach the underlying cause as suppressed exceptions to `RedisException: Cannot retrieve initial cluster partitions`. Each topology retrieval attempt can fail with an individual cause (e.g. connection refused, unresolvable host, …).

Just reporting `NOAUTH` is a bit misleading because we do not have the context. Let me know what you think about how we could improve the debugging experience here.

**Comment by StillerRen** [comment]
if the cluster has no password, but I configure it for lettuce, the exception message that lettuce reports contains error message "no password is set", I can check the exception and try to create a connection without password.

if the cluster has password, but I don't configure it, the initial exception is just "Cannot retrieve initial cluster partitions", it is confused because I only know that Iettuce can't initialize partitions without any reason. So there is nothing I can do in my code to handle this situation like reloading password

**Comment by mp911de** [comment]
You can traverse exception hierarchy and inspect surpressed exceptions (`Throwable.getSuppressed()`) Have you tried this already?

**Comment by StillerRen** [comment]
yes, I do.
but I cannot find "NOAUTH", but in first situation, I can find the "no password is set"

the doLoadPartitions() method in RedisClusterClient throws a new RedisException if the partition is empty, but this exception has no other info.

**Comment by mp911de** [comment]
That's in place now and backported to 5.1.7.

**Comment by roottraveller** [comment]
Hi @mp911de 
I am facing a similar issue. what are the actual cause and possible fix?

**Comment by mp911de** [comment]
@roottraveller please file a new ticket containing debug information such as a stack trace, a thread dump and describing your case. We cannot derive any specific information from a generic "It does not work".

**Comment by roottraveller** [comment]
Thanks, @mp911de 
I have created a separate bug ticket https://github.com/lettuce-io/lettuce-core/issues/1088

**Comment by mp911de** [comment]
Thanks a lot!

**Comment by roottraveller** [comment]
I resolve this. working fine. solution mention here https://stackoverflow.com/questions/57179927/cannot-retrieve-initial-cluster-partitions-from-initial-uris-redisuri-host-12/57204633#57204633
