### ISSUE TITLE
Order pipeline commands in Async connection

### ISSUE THREAD

**Issue by marcottedan** [lettuce-io/lettuce-core#1046]
Hi,

According to the [Wiki Documentation] of pipelining (https://github.com/lettuce-io/lettuce-core/wiki/Pipelining-and-command-flushing), commands are independently run when using `.setAutoFlushCommands(false);`. 

I'm trying to do the following in a single client/server Roundtrip: 

```
// Start pipeline
HMSET myhash field1 "Hello" field2 "World"
EXPIRE myhash 10
// Flush pipeline
```

Looking at the documentation, it looks like the following code could either EXPIRE the key first then HMSET it, vice versa:

```
RedisAsyncCommands<String, String> commands = redisConnection.async();
commands.setAutoFlushCommands(false);
commands.hmset("key", myMap);
commands.expire("key", DAYS.toSeconds(1));
commands.flushCommands();

// I removed the RedisFuture + awaitAll code to avoid complexity in the example
```

Could you tell me if I'm wrong or if the documentation needs some adjustment please?

**Comment by mp911de** [comment]
Thanks for asking.

> commands are written and read independent of each other but in sequence

Independent means that you don't need to wait on a previous command to complete before sending another command. A dependent command would be if you have to await on the result of a command before you can issue another one.

When invoking commands in a particular sequence (assuming only one Thread invokes commands at a time), then command ordering is retained.

**Comment by marcottedan** [comment]
Ok great I get it. Just so you know I was not alone wondering about that question. It could be nice to adjust the Java example documentation with that note about sequencing. I understand now that it's clearly written in the doc but it's not really clear in the java example.

I'm closing the issue, have a good day and thanks for the support!

**Comment by mp911de** [comment]
I reopened the ticket to commit changes against the examples and to track that there is something to do.

**Comment by mp911de** [comment]
Wiki is updated now. Leaving https://github.com/lettuce-io/lettuce-core/wiki/Command-execution-reliability#message-ordering here as this wiki section explains ordering.
