### ISSUE TITLE
Support TLS connections in Sentinel mode

### ISSUE THREAD

**Issue by ae6rt** [lettuce-io/lettuce-core#1048]
## Feature Request

Redis open source will [support TLS](https://github.com/antirez/redis/pull/4855) in the not distant future.  TLS support in the Sentinel will likely follow soon thereafter.

Please implement TLS support in Lettuce to support Sentinel mode.  This would include not only connecting to the Sentinel over TLS, but also connecting to the sentinel-reported master over TLS.

#### Is your feature request related to a problem? Please describe

Financial services and enterprise users of Lettuce, including those using Lettuce by way of Spring Data Redis, are increasingly being asked to ensure all service traffic is encrypted via TLS.  

#### Describe alternatives you've considered

* removing calls to the Sentinel API in our code, migrating to the lower level Redis API for Redis Cluster (when it supports TLS - see link above) or Redis Enterprise.  This would be painful for the number of applications we have that program to the Sentinel API.
* stunnel and spiped, neither of which work well for how our services are deployed and maintained
* exotic IPSec solutions to encrypt traffic on the wire in lieu of first class TLS support in Sentinel mode

**Comment by mp911de** [comment]
That's done now and available with 5.2.0 snapshot builds.

**Comment by jornfranke** [comment]
The referenced pull request on Redis is still open. Do we need to wait for that one to use Sentinel with TLS?

**Comment by mp911de** [comment]
Redis has no built-in SSL support yet. Either you have a commercial Redis offering with baked-in SSL support or you use Stunnel (for now) in front of your Redis machine.
