### ISSUE TITLE
"Knowing Redis" section in documentation has the wrong link for meanings. 

### ISSUE THREAD

**Issue by Raghaava** [lettuce-io/lettuce-core#1050]
#### Current Behavior
"Knowing Redis" section in documentation has the wrong link for meanings.  Clicking on "meanings" is taking to "https://www.google.com/search?q=nosoql+acronym" instead of 
"https://www.google.com/search?q=nosql+acronym"

#### Expected behavior/code
Meanings should be tied to "https://www.google.com/search?q=nosql+acronym" instead of "https://www.google.com/search?q=nosoql+acronym"

#### Environment

5.1.6.RELEASE document 

#### Possible Solution

Fix associated link.

**Comment by mp911de** [comment]
Fixed via #1051
