### ISSUE TITLE
Pass Allocator as RedisStateMachine constructor argument

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#1053]

**Comment by anti-geek** [comment]
@mp911de  Hello sir, was this change originally for a potential memory leak in the RedisStateMachine buffer? We are using the old version with a static allocator. Recently, we got a leak report (as follows), and we wonder if this pull request will fix this problem.
--
LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.lettuce.core.protocol.RedisStateMachine.<init>(RedisStateMachine.java:58)
