### ISSUE TITLE
Lettuce waitForReplication command executes at slave

### ISSUE THREAD

**Issue by bugdivine** [lettuce-io/lettuce-core#1061]
#### Current Behavior

Lettuce client executes the WAIT command on slave nodes
It returns the following error:
<details>
<summary>Stack trace</summary>

```java
Caused by: com.lambdaworks.redis.RedisCommandExecutionException: ERR WAIT cannot be used with replica instances. Please also note that since Redis 4.0 if a replica is configured to be writable (which is not the default) writes to replicas are just local and are not propagated.
```

</details>
The above error is part of http://download.redis.io/redis-stable/src/replication.c where it is returned if command is executed on a slave node. But directly before the WAIT call, I am calling a SET command, so it seems highly unlikely that it is a mess up in topology

#### Expected behavior/code

The calls should only execute at MASTER node specifically

#### Environment

- Lettuce version(s): 4.4.3
- Redis version: 5.0

#### Additional context

I executed this on AWS ElastiCache Redis with cluster mode enabled and multiple shards

**Comment by mp911de** [comment]
Can you post some code that shows how you're using the command? Redis Cluster and Redis Master/Replica consider `WAIT` as a command to be run only on master nodes.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
