### ISSUE TITLE
Some executed commands are not in buffer when flushCommands called

### ISSUE THREAD

**Issue by jaeyeolshin** [lettuce-io/lettuce-core#1065]
## Bug Report
I used manual flushing for bulk importing. But sometimes in the middle processing, `LettuceFutures.awaitAll()` was not completed until timeout. I checked debug log and found some commands were missing when `flushCommands()` called.

#### Current Behavior
When `flushCommands()` called manually, some executed commands are not in buffer. So missing commands never be completed normally.

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
try (StatefulRedisClusterConnection<String, String> conn = redisClusterClient.connect()) {
    final RedisClusterAsyncCommands<String, String> commands = conn.async();
    commands.setAutoFlushCommands(false);
    final List<RedisFuture<?>> futures = new ArrayList<>();
    for (User user : users) {
        futures.add(commands.hset(...));
        futures.add(commands.hset(...));
        futures.add(commands.expire(...));
    }

    commands.flushCommands();
    if (!LettuceFutures.awaitAll(1, TimeUnit.MINUTES, futures.toArray(new RedisFuture[futures.size()]))) {
        // sometimes this block is executed
        log.error("Some data may not be inserted to redis cluster");
    }
}
```

</details>

#### Environment

- Lettuce version(s): 5.1.7.RELEASE
- Redis version: 5.0.5

#### Possible Solution

I think [this code](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/cluster/ClusterDistributionChannelWriter.java#L129) can cause the problem because it buffer commands asynchronously. But I'm not sure about it and have no idea on how to fix it.

#### Workaround
4.3.3.Final works well with manual flushing.

**Comment by mp911de** [comment]
How many commands do you run in the bulk? Please note that Redis with Redis Cluster are allocated lazily. So by the time calling `flushCommands()`, a connection to a particular cluster node might not be yet established and you bring the client into an invalid state.

Please either ensure that all connections are established prior to changing `setAutoFlushCommands ` state or do not use `setAutoFlushCommands` at all if you cannot guarantee that.

**Comment by jaeyeolshin** [comment]
I tried 50 and 1000 commands in the bulk. Regardless of the bulk size, missing commands are observed. Bulk insert code is executed in a loop because the total number of commands is much larger than the bulk size. The problem randomly happens in the middle of the loop.

Is there a way to use manual flushing safely?

**Comment by mp911de** [comment]
Manual flushing is safe on standalone-connections. For cluster connections, it's not safe when not all connections are initialized. Have you tried without `setAutoFlushCommands`?

**Comment by jaeyeolshin** [comment]
I thought that manual flushing works even on redis cluster. But it was my misunderstanding.
I just tried bulk insert without `setAutoFlushCommands`. It works well and is not too slow.
Thank you.
