### ISSUE TITLE
RedisCommandExecutionException: MOVED

### ISSUE THREAD

**Issue by zy93xy** [lettuce-io/lettuce-core#1066]
hello，i don`t understand this codes
![image](https://user-images.githubusercontent.com/28784625/60074643-021dcd80-9756-11e9-9ad0-6cb96d1f5831.png)
but ,this code have a exception ,please tell me that`s reason
![image](https://user-images.githubusercontent.com/28784625/60074757-40b38800-9756-11e9-927e-ad7e2ea3f98a.png)

**Comment by mp911de** [comment]
Please do not paste images. Please replace it with the actual stack trace.

**Comment by zy93xy** [comment]
ok，Let's look at where an exception is thrown  ; class is  LettuceFutures ,
` public static <T> T awaitOrCancel(RedisFuture<T> cmd, long timeout, TimeUnit unit) {

        try {
            if (!cmd.await(timeout, unit)) {
                cmd.cancel(true);
                throw ExceptionFactory.createTimeoutException(Duration.ofNanos(unit.toNanos(timeout)));
            }
            return cmd.get(); // Command [type=SETEX, output=StatusOutput [output=null, error='MOVED 9084 10.104.116.139:7003']]
        } catch (RuntimeException e) {
            throw e;
        } catch (ExecutionException e) { //java.util.concurrent.ExecutionException: io.lettuce.core.RedisCommandExecutionException: MOVED 9084 10.104.116.139:7003

            if (e.getCause() instanceof RedisCommandExecutionException) {
                throw ExceptionFactory.createExecutionException(e.getCause().getMessage(), e.getCause());
            }

            if (e.getCause() instanceof RedisCommandTimeoutException) {
                throw new RedisCommandTimeoutException(e.getCause());
            }

            throw new RedisException(e.getCause());
        } catch (InterruptedException e) {

            Thread.currentThread().interrupt();
            throw new RedisCommandInterruptedException(e);
        } catch (Exception e) {
            throw ExceptionFactory.createExecutionException(null, e);
        }
    }`

**Comment by zy93xy** [comment]
please , See the integration code for the lettuce version 5.1.6 and 2.1.8 with spring-data-redis

**Comment by mp911de** [comment]
Looks like your configuration uses Redis Standalone while you're connected to a Redis Cluster.

**Comment by zy93xy** [comment]
My configuration uses redis sentinel while i'm connected to a redis cluster,but when my configuration uses redis cluster  , it is well

**Comment by zy93xy** [comment]
Another ,my configuration uses redis sentinel while i'm connected to a redis cluster . It's also good to save values that are objects and not characters;Conversely, the same error occurs when the value is a character type

**Comment by mp911de** [comment]
Closing this ticket because we cannot do anything here.
