### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [lettuce-io/lettuce-core#1073]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/io/lettuce/core/LettuceStrings.java: Line number => 115: API name => MessageDigest:First parameter (with value "SHA1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/io/lettuce/core/LettuceStrings.java: Line number => 117: API name => MessageDigest:<BR>

**Comment by mp911de** [comment]
Thanks for report. SHA1 is not used in a crypto context. It is part of the Redis API to generate checksums.
