### ISSUE TITLE
Pass a String to eval regardless of codec value type

### ISSUE THREAD

**Issue by danielsomekh** [lettuce-io/lettuce-core#1080]
## Feature Request

A mechanism to support passing a String/s to eval regardless of the codec's value type, `V`.

#### Problem

I have what I think would be a fairly common usage of `eval`. I'd like to set a hash with an expiration using a non-string value codec (eg. `RedisCodec<String, byte[]>`). 

Here is the method signature for eval: 

`<T> T eval(String script, ScriptOutputType type, K[] keys, V... values);`

And here is the Lua script: 
```
local ret = redis.call('hset',KEYS[1],KEYS[2],ARGV[1])
redis.call('expire',KEYS[1],ARGV[2])
return ret
```

What this implies is that `ARGV[2]` must be of type `V`, but `V` must be a `String`, which means a `RedisCodec<String, byte[]>` would not work with this implementation.

**Comment by mp911de** [comment]
Thanks for report. Lettuce's API is built to provide the most convenience with as little drawbacks as possible. We cannot cater for all use-case scenarios, therefore Lettuce provides also a custom command API that allows you to use a specific codec on a per-command basis. See [Custom commands](https://github.com/lettuce-io/lettuce-core/wiki/Custom-commands%2C-outputs-and-command-mechanics) for further details.

Alternatively, check out [Redis Command Interfaces](https://github.com/lettuce-io/lettuce-core/wiki/Redis-Command-Interfaces) that allow a certain degree of command composition expressing type-safe commands.

**Comment by danielsomekh** [comment]
After looking through the documentation, it doesn't seem what I am trying to achieve is possible with custom commands or redis command interfaces. In the redis command interfaces docs, it says there is a restriction that "Keys and values are discovered by verifying their declared type assignability to RedisCodec key and value types.", but there doesn't seem to be a way to pass use a `String[]` that doesn't conform to the redis codec (ie. a `byte[]` value type).

**Comment by danielsomekh** [comment]
Is there something I am missing, or can we figure out a way to update the library for the use case I mentioned?

**Comment by mp911de** [comment]
You might want to continue to `Hinting command method parameters influences RedisCodec selection. Command method parameter types are just limited by the RedisCodecs that are supplied to RedisCommandFactory.`

You can supply custom codecs if you need to support data types beyond byte arrays and simple Strings. Call `new RedisCommandFactory(…)` with a `List` of codec instances you want to use.
