### ISSUE TITLE
How to pass client option to LettuceConnectionFactory

### ISSUE THREAD

**Issue by tanroopdhillon** [lettuce-io/lettuce-core#1082]
I initialise bean as follows

```
@Bean
  public ReactiveRedisTemplate<byte[], byte[]> reactiveRedisTemplate(
      ReactiveRedisConnectionFactory reactiveRedisConnectionFactory) {


    return new ReactiveRedisTemplate<>(
        reactiveRedisConnectionFactory,
        RedisSerializationContext.<byte[], byte[]>newSerializationContext()
            .key(ByteBuffer::array, ByteBuffer::wrap)
            .value(ByteBuffer::array, ByteBuffer::wrap)
            .hashKey(new StringRedisSerializer())
            .hashValue(new StringRedisSerializer())
            .build());
  }

```
ReactiveRedisConnectionFactory is instance of  LettuceConnectionFactory

Question:
How to pass topology refresh option to LettuceConnectionFactory?

Please help

**Comment by mp911de** [comment]
Take a look here:

https://github.com/spring-projects/spring-data-redis/blob/485ee1d5a2505f78b4f9121ea931082bc60fe3e1/src/test/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactoryUnitTests.java#L851-L858
