### ISSUE TITLE
Can Integration of lettuce with spring RedisTemplate support async operation?

### ISSUE THREAD

**Issue by henussf** [lettuce-io/lettuce-core#1085]
#### 

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

When I write mass data into redis Server Cluster,RedisTemplate sync operation has low performance, So I have to use RedisClusterClient as bean in springboot project.

#### Teachability, Documentation, Adoption, Migration Strategy

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by mp911de** [comment]
Spring Data Redis uses the synchronous and the reactive APIs of Lettuce. This is a Spring topic, though.

**Comment by henussf** [comment]
thx,I got ReactiveRedisTemplate in springboot, https://docs.spring.io/spring-data/data-redis/docs/current/reference/html/#new-in-2.1.0
