### ISSUE TITLE
RedisStreamCommands xRange Limit offset issue

### ISSUE THREAD

**Issue by torniketar** [lettuce-io/lettuce-core#1104]
hello,
when trying to use `List<StreamMessage<K, V>> xrevrange(K var1, Range<String> var2, Limit var3)`;
example : `streamRedisTemplate.xrevrange(key, Range.create("-", "+"), Limit.create(0, 5));`

it returns list with five items, but when increment offset, result is same.

please see examples on screenshots.
i have 27 item in list:
![1](https://user-images.githubusercontent.com/24752806/62621007-ccaaf900-b92b-11e9-918f-bbe4104c8c17.PNG)

next get with offset and count is correct:
 streamRedisTemplate.xrevrange(key, Range.create("-", "+"), Limit.create(0, 5));
![2](https://user-images.githubusercontent.com/24752806/62621106-23b0ce00-b92c-11e9-9ddb-1a4c123725f4.PNG)

same again with incremented offset but result is same:
![3](https://user-images.githubusercontent.com/24752806/62621222-6d99b400-b92c-11e9-8175-110c3557804e.PNG)

**Comment by mp911de** [comment]
Thanks for report.

`XRANGE`/`XREVRANGE` does not support `OFFSET`, only `COUNT`. Lettuce uses `Limit` to not introduce yet another value object. 

Please do not use screenshots of code or your IDE in future reports as that hurts readability and prevents from properly indexing issues.
