### ISSUE TITLE
RedisStreamCommands xRange Range.Boundary.exclude issue

### ISSUE THREAD

**Issue by torniketar** [lettuce-io/lettuce-core#1105]
trying to use Range.Boundary.exclude to exclude range parameter, but anyway it returns list with include, please see screenshot:
![4](https://user-images.githubusercontent.com/24752806/62621693-9c645a00-b92d-11e9-8575-fc0270b46d02.PNG)

**Comment by mp911de** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by mp911de** [comment]
This is the issue tracker for Lettuce. Please report your issue at https://jira.spring.io.
