### ISSUE TITLE
I using lettuce always get a warning

### ISSUE THREAD

**Issue by RevisitMoon** [lettuce-io/lettuce-core#1106]
<details>
<summary>Stack trace</summary>

```java

[lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.cluster.RedisClusterClient - io.netty.channel.ConnectTimeoutException: connection timed out: /172.16.0.10:10001
[lettuce-nioEventLoop-6-5] WARN  io.lettuce.core.cluster.RedisClusterClient - io.netty.channel.ConnectTimeoutException: connection timed out: /172.16.0.16:6380
[lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.cluster.RedisClusterClient - io.netty.channel.ConnectTimeoutException: connection timed out: /172.16.0.16:6381
[lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.cluster.RedisClusterClient - io.netty.channel.ConnectTimeoutException: connection timed out: /172.16.0.16:6380

```
</details>

<details>
<summary>Input Code</summary>

my properties:

REDIS_HOST=xxx.xxx.170.119:10001,xxx.xxx.170.119:10002,xxx.xxx.233.109:6379,xxx.xxx.233.109:6380,xxx.xxx.233.109:6381,xxx.xxx.233.109:6382

this is my initialization code:

```java
if ("cluster".equals(redisMode)) {
            lettuceConnectionFactory = new LettuceConnectionFactory(initRedisClusterConfiguration(), LettuceClientConfiguration.builder()
                    .shutdownTimeout(poolShutDownTimeOut)
                    .commandTimeout(poolMaxWaitTimeout)
                    .clientOptions(ClientOptions.builder()
                            .pingBeforeActivateConnection(true)
                            .autoReconnect(true)
                            .build())
                    .build());
 }

public RedisClusterConfiguration initRedisClusterConfiguration() {
        RedisClusterConfiguration clusterConfiguration = new RedisClusterConfiguration();
        if (host.contains(",")) {
            Set<RedisNode> nodeSet = new HashSet<>();
            String[] hostArray = StringUtils.split(this.host, ",");
            for (String host : hostArray) {
                String[] hostAndPort = StringUtils.split(host,":");
                nodeSet.add(new RedisNode(hostAndPort[0], StringUtils.isBlank(hostAndPort[1]) ? 6379 : Integer.valueOf(hostAndPort[1])));
            }
            if (!nodeSet.isEmpty()) {
                clusterConfiguration.setClusterNodes(nodeSet);
                clusterConfiguration.setMaxRedirects(3);
                clusterConfiguration.setPassword(password);
            }
        } else {
            String[] hostAndPort = StringUtils.split(host);
            clusterConfiguration.clusterNode(hostAndPort[0], StringUtils.isBlank(hostAndPort[1]) ? 6379 : Integer.valueOf(hostAndPort[1]));
        }

        return clusterConfiguration;
}
```
Why is it connected to the server local area network after running?

</details>

- Lettuce version(s): [e.g. 5.1.3.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 5.0.5]

**Comment by mp911de** [comment]
I'm not sure I follow. Do you want to know why you see connections to `172.16.0.10` instead of `xxx.xxx.170.119`?

**Comment by RevisitMoon** [comment]
Because this is a real online server, so some IP I use xxx instead, but it can be linked and yes! i want to know why use local linked these servers will get "connection timed out: /172.16.0.10:10001" and my  configuration does not point to the intranet ip and port

**Comment by RevisitMoon** [comment]
When I add code these exceptions are not output again, I am not sure if unexpected effects will occur  So I want to ask for your opinion
```java

ClientOptions.builder()
                            .cancelCommandsOnReconnectFailure(true)

```

**Comment by mp911de** [comment]
Lettuce uses Redis' topology information to obtain the cluster topology. Specifically, we use `CLUSTER NODES` to determine which node serves what slots and to obtain hostname/port number. If `CLUSTER NODES` reports the internal IP addresses, then this is likely the reason why you see timeouts to internal IP's. You could configure `MappingSocketAddressResolver` via `ClientResources` to translate internal IP addresses to external ones.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
