### ISSUE TITLE
how can I read or write mass data with AsyncPool?

### ISSUE THREAD

**Issue by henussf** [lettuce-io/lettuce-core#1108]
## Feature Request

when I use AsyncPool<StatefulRedisClusterConnection<String, String>> to read data from Redis Cluster, I only get one result; For Example:
CompletableFuture<String> setResult = pool.acquire().thenCompose(connection -> {
            RedisAdvancedClusterAsyncCommands<String, String> async = connection.async();
            System.out.println("testRedisAysnc B");
            return async.get("key08112wte").whenComplete((s, throwable) -> pool.release(connection));
        });
try {
            String value = setResult.get(4, TimeUnit.SECONDS);
            System.out.println("testRedisAysnc value " + value);
        }

However,I want read a bitch of data, So can you tell me what I can do ? thank you very much! 
I read and write mass data  in one StatefulRedisClusterConnection, the perfermance is not ideal. So I want to use AsyncPool. This is my current code.
RedisAdvancedClusterAsyncCommands<String, String> commands = clusterConnection.async();
        List<RedisFuture<String>> responses = new ArrayList<>(userIds.size());
        Map<String, UserStateDto> userStates = new HashMap<>();
        try {
            for (String userId : userIds) {
                responses.add(commands.get(userStateKey(userId)));
            }
        } finally {
            LettuceFutures.awaitAll(64, TimeUnit.SECONDS, responses.toArray(new RedisFuture[responses.size()]));
        }

#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Teachability, Documentation, Adoption, Migration Strategy

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by mp911de** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Why are you using connection pooling? Looking at the code, there's no need for pooling.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
