### ISSUE TITLE
Lettuce client just hangs for 20-30 in every 15 to 60 days interval

### ISSUE THREAD

**Issue by ravindrabhatt97** [lettuce-io/lettuce-core#1109]
Lettuce client just hangs for 20-30 in every 15 to 60 days interval, We are observing this issue very intermittently and hence need your help to solve this, right now we don't have any stacktraces to restricted access to server but can some suggest something by that time.

We are using lettuce client which comes spring boot 2.10 for redis session management.

**Comment by mp911de** [comment]
Without any stack traces or debug information we cannot diagnose any issue. 

From the description, I assume that we cannot get any debug details so closing the ticket. Feel free to reopen the ticket once you can provide more details.
