### ISSUE TITLE
when i use lettuce cluster pipline,can i set timeout,when overtime,get part data？

### ISSUE THREAD

**Issue by zgbgx** [lettuce-io/lettuce-core#1110]
i use lettuce cluster pipline in  recommender system model predict serving .in a model predictor process,service must query much data,but time delay is very important in online recommender system.can i set timeout,when overtime,get part data？is there any setting can help me solve the problem?

**Comment by mp911de** [comment]
Check out global timeouts, settable via [ClientOptions](https://lettuce.io/core/release/reference/index.html#client-options).
