### ISSUE TITLE
reactiveCommands.exec not returning expected TransactionResult when back to back calls are made at interval of few ms

### ISSUE THREAD

**Issue by jasmeetjagdev** [lettuce-io/lettuce-core#1115]
#### Current Behavior

When reactiveRedisCommands are used for a transaction then the transactionResult returned as part of Exec command does not return back the expected array of results. 

<details>

<summary>Attached project to replicate the issue</summary>
[test-redis-multi.zip](https://github.com/lettuce-io/lettuce-core/files/3576247/test-redis-multi.zip)

Prerequisite - you would need a redis running at port 6379 on localhost.

If you would run the application then it starts a server at port 8085.
You can hit the endpoint http://localhost:8085/load

This executes step1() and step2() one after the other after a short break. 

The resulting behavior of exec command can be observed in logs. It takes different paths. Sometimes the returned array is empty and other times it does not have the correct number of elements as expected.

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Multiple calls (with interval in ms) to this code will help to simulate the problem. Full code is also attached</summary>

```java
private void step1() {

		Map<String, String> map = new HashMap<>();
		for (int j = 0; j < 10; j++) {
			map.put("key" + j, "value" + j);
		}

		String key = "random-key";

		redisReactiveCommands.multi().subscribe(res -> {
			for (int i = 0; i < 10; i++) {
				redisReactiveCommands.hmset("map:" + key + i, map).subscribe();
				redisReactiveCommands.rpush(key + "1", "hey" + i).subscribe();
			}
			logger.info("1Going to run exec");
			redisReactiveCommands.exec().subscribe(r -> {
				logger.info("Executing Step1");
				if (r.wasDiscarded()) {
					logger.info("1Discarded1" + r.stream().map(s -> String.valueOf(s)).collect(Collectors.toList()));
				} else if (r.size() > 0 && r.size() == 20) {
					logger.info("1Everything was fine" + r.stream().map(s -> String.valueOf(s)).collect(Collectors.toList()));
				} else if (r.size() > 0) {
					logger.info("1Something is missing" + r.size() + r.stream().map(s -> String.valueOf(s)).collect(Collectors.toList()));
				} else {
					logger.info("1Everything is missing" + r.stream().map(s -> String.valueOf(s)).collect(Collectors.toList()));
				}

			});

		}, err -> {
			if (err.getMessage().contains(NESTED_MULTI_TRAN_ERROR)) {
				logger.info("1Error" + "MULTI");
				redisReactiveCommands.discard().subscribe(res2 -> {
					logger.info("1Discard" + res2);
				}, err2 -> {
					logger.info("1Discard Error" + err2);
				});
			}
		});

	}
```

</details>

#### Expected behavior/code

Expectation is that all the time when we subscribe to exec call then the transaction result should have all the results of commands queued between multi and exec

#### Environment

- Lettuce version(s): [e.g. 5.1.7.RELEASE, 4.1.36.Final]
- Redis version: [e.g. 5.0.5]

**Comment by mp911de** [comment]
Thanks for report. The behavior you're seeing happens because of missing synchronization in your code. The code is triggering two concurrent transactions. If you're lucky, the first transaction finishes before the second one starts. Please either use the synchronous API or use the reactive API fully with proper awaiting of completion of the first transaction.

Please also note that you share a single connection across multiple callers (calling `GET /load` by two clients) and this will interfere with the transactional state of the connection.

**Comment by jasmeetjagdev** [comment]
Thanks Mark ! 
I'll make those two modifications as you suggested and will try to see if I can reproduce the error. Thanks a lot.
