### ISSUE TITLE
Proposed improvement to Reactive MGET implementation

### ISSUE THREAD

**Issue by csunwold** [lettuce-io/lettuce-core#1116]
## Feature Request
This is not so much a feature request as a performance and throughput improvement. We run an AWS Elasticache Redis cluster with 50 shards in production. We are using the Reactive API and use MGET to retrieve between 300 and 1500 keys per application request. We've observed via load tests on our applications that our application throughput is severely constrained if we make use a single MGET call. To work around this, we have had to make parallel batch calls like this:

```scala
Flux.fromArray(keys.grouped(RedisBatchSize).toArray)
      .parallel()
      .runOn(scheduler)
      .flatMap[KeyValue[String, Array[Byte]]](mget)
```

```scala
private val mget: java.util.function.Function[Seq[String], Flux[KeyValue[String, Array[Byte]]]] =
  (keys: Seq[String]) => cache.mget(keys:_*)
```

We've found through testing that we can get better throughput and performance by removing the `.collectList` call in the existing reactive MGET implementation we were able to reduce our applications P999 latency by 30%.

Example of new MGET call pattern:

```scala
mget(keys)
      .parallel()
      // This allows us to handle the resulting values in parallel
      .runOn(Schedulers.parallel())
```

#### Describe the solution you'd like
Here is the proposed diff: https://github.com/lettuce-io/lettuce-core/compare/master...csunwold:remove-mget-collect.

I'd be happy to submit a pull request if you agree with this approach.

#### Describe alternatives you've considered

None considered.

#### Teachability, Documentation, Adoption, Migration Strategy
This change should be transparent to clients of Lettuce.

**Comment by mp911de** [comment]
Thanks for report. It makes sense to apply performance improvements especially given the significant improvement on latency.

The code that performs `collectList` and reordering makes sure that `MGET` behaves as per `MGET` contract on a single node. This is, to return elements in the order of how the keys were requested. When removing the reordering, the incoming key order does not necessarily match the result order.

**Comment by csunwold** [comment]
>The code that performs collectList and reordering makes sure that MGET behaves as per MGET contract on a single node. 
Since no tests failed on my branch when I made this change I'm assuming this was either missing test coverage or was at least not an important contract. The documentation for MGET does not seem to make any references to any guarantee of order of the resulting Flux. 

Perhaps as part of this change the documentation could be updated to include a note making it explicit that order is not guaranteed when using MGET against a cluster?

**Comment by mp911de** [comment]
Test success/failure relies on timing and tests around the `MGET` command for reactive and cluster aren't really extensive. Changing the behavior is a breaking change for clients that expect ordering. If we change the behavior now, that will require libraries and applications to adopt their code.

How about if we make `SlotHash.partition(…)` `public` so that you can use the partitioning utility to issue multiple `MGET` calls in your code?

**Comment by csunwold** [comment]
That might work. It could be a little weird to use since you have hold onto the codec, or at least another instance of the same type of codec, outside the scope of the RedisAdvancedClusterReactiveCommands. 

Here is what our code would roughly look like:

```scala
// Build connection
val codec = // create whatever necessary codec
val commands = RedisClient.create(uri).connect(codec).reactive()
....

val  keyList = LettuceLists.newList(keys);
val partitioned = SlotHash.partition(codec, keyList);

Flux.fromIterable(partitioned)
  .flatMap[KeyValue[String, Array[Byte]]](mget)
```

**Comment by csunwold** [comment]
I've thought about this a little more and I think what motivated me to go down this route may be a misunderstanding of the intent of the Reactive APIs Lettuce exposes. But I think there might be a workaround I can explore.

When I initially found Lettuce I was drawn to the ability to use Reactive APIs for interfacing with Redis. I've had success using the reactive paradigm in applications before and I was happy to see I could continue making use of it in my new app that would use Redis. When I saw that MGET returned a `Flux<KeyValue<K, V>>` my assumption was that all results would be streamed as results came back from Redis. 

What I'm understanding now (please correct me if I'm wrong here) is that this was not the intent of this API. The intent was to be closer to a reactive equivalent of the [async API](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java#L286). 

I think if I want a "true" streaming option for my MGET calls, perhaps I need to experiment with the [streaming API](https://github.com/lettuce-io/lettuce-core/wiki/Streaming-API). The only downside is that this is a callback pattern and one of the reasons I prefer being reactive is to not have to write callbacks. I think we can get back into a reactive paradigm by creating our own flux from the streaming API using something like this:

```scala
    val stream = EmitterProcessor.create[KeyValue[String, Array[Byte]]]()
    
    cache.mget(new KeyValueStreamingChannel[String, Array[Byte]] {
      def onKeyValue(key: String, value: Array[Byte]): Unit = {
        stream.onNext(KeyValue.fromNullable(key, value))
      }
    }, keys).map(_ => stream.onComplete())

    stream.subscribeOn(Schedulers.parallel())
      .map(kv => {
        // handle results
      })
```

Based on my reading of the streaming MGET call, there is no collectList so I should end up with comparable performance to the branch I have now and it wouldn't require any changes to lettuce.

**Comment by mp911de** [comment]
The callback API has no notion of backpressure. Depending on the queue size of `EmitterProcessor`, `stream.onNext(…)` can block if the queue is full (see #1086).

Try rather using `DirectProcessor`.

**Comment by csunwold** [comment]
Thank you for the suggestion @mp911de I wasn't aware of that behavior. I'll look at DirectProcessor.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by mp911de** [comment]
If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by shiyanhui** [comment]
I think the point is how to partition the keys and run on partitions parallelly. If we do in the parallel way, we don't need call collectList().

Strongly recommend to implement `mget` in the parallel way. Thanks.
