### ISSUE TITLE
How can i scan the entire cluster using cluster client ?

### ISSUE THREAD

**Issue by mjmanav4** [lettuce-io/lettuce-core#1121]
Not able to find any method that scan the all the nodes in cluster

Which class implements https://redis.io/commands/cluster-nodes methods ?

**Comment by mjmanav4** [comment]
No answer is provided for the shared issue  as well

**Comment by mp911de** [comment]
Thanks for asking. Lettuce provides an extensive library of documentation. Please take a look at the Javadocs at https://lettuce.io/core/release/api/index.html, specifically https://lettuce.io/core/release/api/io/lettuce/core/cluster/api/sync/RedisClusterCommands.html that contains the methods you're looking for.
