### ISSUE TITLE
getting a class not found error for RedisClient

### ISSUE THREAD

**Issue by froggware** [lettuce-io/lettuce-core#1125]
Trying to do a basic connect to Redis using lettuce. Its for a Denodo extension which limits me to eclipse oxygen and Java 8. I believe I read that Java 8 is fine with 5.1.8.

I have included lettuce through maven. Pom.XML includes it as 
  ```
  	<dependency>
  		<groupId>io.lettuce</groupId>
  		<artifactId>lettuce-core</artifactId>
  		<version>5.1.8.RELEASE</version>
  	</dependency>
```

Attempting to create a RedisClient with 

`RedisClient redisClient = RedisClient.create("redis://localhost?password=password");`

produces a throwable  with the following Stack Trace:

> java.lang.NoClassDefFoundError: io/lettuce/core/RedisClient
> ...    ...
> Caused by: java.lang.ClassNotFoundException: io.lettuce.core.RedisClient
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 

I don't understand how a class can not be found when it is included and imported, but I'm no Java expert. Any thoughts on how i messed up the inclusion would be appreciated.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by froggware** [comment]
turns out I needed and uber jar, so i used the maven assembly plugin and the problem was solved.
