### ISSUE TITLE
lettuce#ClusterTopologyRefresh is too slow，because of “client list”

### ISSUE THREAD

**Issue by xjs1919** [lettuce-io/lettuce-core#1126]
in my production environment，top20 slowlog  are all caused by "client list" :
20) 1) (integer) 153
    2) (integer) 1568342022
    3) (integer) 11580
    4) 1) "CLIENT"
       2) "LIST"
    5) "172.16.0.145:59994"
    6) "lettuce#ClusterTopologyRefresh"
but there is no option to close this behavior, because this is done in loadPartitions(), i hope you can supplier a different option to close recording client count, this count is meaningless to me,thx.

**Comment by mp911de** [comment]
Thank you for report. Do you have any detail on what slow means? How long does `CLIENT LIST` take? Do you know of an alternative to obtaining the client count? Client count is used to distributing connections evenly across a cluster and preventing that a single node experiences excess connections.

**Comment by xjs1919** [comment]
1. “client list” takes more than 10 milliseconds。
2.  “ info Clients“ can obtain  the client count。

**Comment by mp911de** [comment]
Using `INFO CLIENTS` would make a lot of sense as the data contains what we require. Do you want to submit a pull request?

**Comment by xjs1919** [comment]
i will have a try
