### ISSUE TITLE
”append” command Not working

### ISSUE THREAD

**Issue by RockeyCui** [lettuce-io/lettuce-core#1128]
## Bug Report

RedisStringCommands： append command Not working

#### Current Behavior

When I use the append command, found redis result has become the "replace string".
--I used the wrong way, or do I miss something？

#### Input Code
<details>
<summary>Input Code</summary>

```java
public class LettuceStringSyncTest {

    private static RedisClient redisClient;

    private static StatefulRedisConnection<String, String> connection;

    private static RedisStringCommands<String, String> stringCommands;

    private static RedisKeyCommands<String, String> keyCommands;


    static {
        redisClient = RedisClient.create("redis://xxx:6379/0");
        connection = redisClient.connect();
        stringCommands = connection.sync();
        keyCommands = connection.sync();
        connection.sync();
    }

    public static void main(String[] args) throws InterruptedException {
        // always print 2
        System.out.println(stringCommands.append("rock", "la"));

        connection.close();
        redisClient.shutdown();
    }
}
```

</details>

#### Expected behavior/code

append value but not “replace value”

#### Environment

- Lettuce version(s): [5.1.8.RELEASE]
- Redis version: [5.0.5]

**Comment by mp911de** [comment]
I wasn't able to reproduce the issue (see [tests for `APPEND`](https://github.com/lettuce-io/lettuce-core/blob/c98108dd7fbe9bee8702e468efff4b085a976374/src/test/java/io/lettuce/core/commands/StringCommandIntegrationTests.java#L66)).

Running the attached code reports `2`, `4`, `6`, … and so on.

**Comment by RockeyCui** [comment]
> I wasn't able to reproduce the issue (see [tests for `APPEND`](https://github.com/lettuce-io/lettuce-core/blob/c98108dd7fbe9bee8702e468efff4b085a976374/src/test/java/io/lettuce/core/commands/StringCommandIntegrationTests.java#L66)).
> 
> Running the attached code reports `2`, `4`, `6`, … and so on.
> 
> Please make sure that your Redis server does not run out of memory or discards the key.

Sorry, it is my fault.  I didn't find that I deleted the key somewhere else.  hahaha....I'm so careless
