### ISSUE TITLE
Allow deferred connection initialization

### ISSUE THREAD

**Issue by mors741** [lettuce-io/lettuce-core#1129]
#### Problem

1. I call `redisClient.connect()`
2. If connection fail, I get exception

In some cases, it is expected behaviour.
*But* my server can live without Redis. So, I don't want to kill server if Redis down - I want to retry connection later in background.

By the way this is exactly how the `redis-cli` works.

#### Solution

1. Introduce a ClientOption `allowDeferredConnection`.
2. If `true` and connection can't be established at init, then just left it in closed state (`isOpen()=false`).
3. Reconnect later in background using `ConnectionWatchdog`.

A clear and concise description of what you want to happen. Add any considered drawbacks.

Issue created in response to https://github.com/lettuce-io/lettuce-core/issues/254

**Comment by mors741** [comment]
I'll try to implement this feature myself

**Comment by mors741** [comment]
Integration tests on `unstable`  are failing because of changes in `unstable` branch of redis.
`CONFIG SET requirepass ""` does not disable password anymore.

Output of command `CONFIG GET requirepass` afterwards:
On 5.0.5 
```
1) "requirepass"
2) ""
```

On `unstable`
```
1) "requirepass"
2) "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
```

So, now  every test that use `WithPassword` causes other tests (running after it on the same redis) to fail

Already wrote to redis developers.
But no response yet.
https://github.com/antirez/redis/issues/3557#issuecomment-533009285

**Comment by mp911de** [comment]
Thanks for your proposal. Having this feature is quite interesting and I scheduled it for Lettuce 6. We're about to release 5.2 GA in the next days so we should not add new functionality that cannot be properly tested in within a short timeframe.

**Comment by mp911de** [comment]
We never could convince ourselves that this is a good idea as we will always impose additional complexity on connections. We expose asynchronous connection means for the majority of connection types. An initially failing connection brings a lot of complexity to HA arrangements such as Master/Replica, or Redis Cluster. Therefore we don't see how we can come up with a simple solution that doesn't leak any issues outside.
