### ISSUE TITLE
Infinite reconnect after restarting all my redis servers

### ISSUE THREAD

**Issue by edrichjspectrum** [lettuce-io/lettuce-core#1141]
#### Current Behavior

This only started happening after we restarted all of our servers, making sure to failover to the slaves first before restarting one by one.
<summary>Stack trace</summary>

![image](https://user-images.githubusercontent.com/44759434/65940531-eb70cc00-e452-11e9-8fa6-497192a6e08e.png)

</details>

#### Expected behavior/code

No recurring reconnect

#### Environment

- Lettuce version(s): 4.2.2
- Redis version: 3.2.10

**Comment by mp911de** [comment]
Are you able to upgrade to Lettuce 5 to check whether a newer version addresses the issue?
You can enable debug logging for the `com.lambdaworks` category to get details whether any errors occurred during reconnect.

Reconnects seem to happen in a regular interval of 11 seconds.

**Comment by edrichjspectrum** [comment]
The thing is, I can't get the bug to reproduce in our lab environment. I would happily upgrade if I could test this out first in lab, but right now the error only persists in our production environment. Do you have any other suggestions as to what might be causing this behavior?

**Comment by mp911de** [comment]
Without a reproducer or more details, there's nothing we can do here.
