### ISSUE TITLE
Read request is not dispatched to slave nodes evenly when ReadFrom.slave

### ISSUE THREAD

**Issue by ldwnt** [lettuce-io/lettuce-core#1148]
## Bug Report

I have a redis cluster of 3 master nodes & 6 slave nodes. There is a key named "a" on 1 master node and 2 slave nodes. I set ReadFrom = SLAVE and try to read the "a" key from both of the 2 slave nodes in concurrently rest calls. However, when I use jmeter to call the "test" API with 10 threads, only one of the 2 slave processes has high cpu rate while the other one seem to be idle. Am I missing some config here, or is lettuce designed to read from only one slave node, even when the ReadFrom.SLAVE option is used?

#### Current Behavior
Only one slave node has high cpu rate.

#### Input Code

```
    private RedisClusterClient client;
    private StatefulRedisClusterConnection<String, String> connection;
    private GenericObjectPool<StatefulRedisClusterConnection<String, String>> pool;

    @RequestMapping("/lettuce-init/{ip}/{port}")
    public void lettuceOpen(@PathVariable String ip, @PathVariable int port) throws Exception {
        client = RedisClusterClient.create(RedisURI.create(ip, port));
        connection = client.connect();
        connection.setReadFrom(ReadFrom.SLAVE);
        pool = ConnectionPoolSupport.createGenericObjectPool(() -> connection, new GenericObjectPoolConfig());
    }

    @RequestMapping("/test")
    public String lettuce() throws Exception {

        StatefulRedisClusterConnection<String, String> conn = pool.borrowObject();
        String result = conn.sync().get("a");
        conn.close();
        log.debug(result);
        return result;
    }
```

#### Expected behavior/code

All slave nodes receive roughly equal amount of requests.

#### Environment

- Lettuce version(s): 5.1.7
- Redis version: 5.0.5

**Comment by mp911de** [comment]
Works as designed. See #834 for details. Once #1145 is fixed, you can create your own `ReadFrom` implementations that can randomize load. Use `ReadFrom.ANY` until then.

**Comment by bhavikambani** [comment]
@mp911de Is this feature available now ? I am using 5.2.2.RELEASE, can't see there at least. I also have same usecase where I have multiple SLAVES and I want to distribute read between those nodes.

**Comment by mp911de** [comment]
#834 is in place since version 5.2.0.

**Comment by yunzhuoren** [comment]
Hi @mp911de . I am seeing the similar thing(6.0.5.RELEASE) when using redis in sentinel mode(one master, two replicas), with `readFrom` set to `replicaPrefered`. After some testing,  I think it is probably because the order is defined in terms of the `predicates` passed in, for `replicaPrefered`, it is 
 
``` 
static final class ReadFromReplicaPreferred extends OrderedPredicateReadFromAdapter {
        ReadFromReplicaPreferred() {
            super(IS_REPLICA, IS_UPSTREAM);
        }
    } 
```

and what I would expect from this code is to pick a random one from the first part of the list(the replicas).  
```
  if (OrderingReadFromAccessor.isOrderSensitive(readFrom) || selection.size() == 1) {
      return connections.filter(StatefulConnection::isOpen).next().switchIfEmpty(connections.next()).toFuture();
  }
```
https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/masterreplica/MasterReplicaConnectionProvider.java#L143

let me know whether I am looking at the wrong thing, thank you. (And thank you for this fantastic library!)
