### ISSUE TITLE
refactor simplify condition to invoke "resolveCodec" method in AnnotationRedisCodecResolver

### ISSUE THREAD

**Issue by machi1990** [lettuce-io/lettuce-core#1149]
While going through the `AnnotationRedisCodecResolver.java` class, I noticed that this condition 

https://github.com/lettuce-io/lettuce-core/blob/c98108dd7fbe9bee8702e468efff4b085a976374/src/main/java/io/lettuce/core/dynamic/codec/AnnotationRedisCodecResolver.java#L73-L76 can be improved. I have a refactor in place and I am preparing a PR.

**Comment by mp911de** [comment]
Thanks for having a look. The code tries to find whether there is a single key(value) codec and no or up to one value (key) codecs. Simplifying the condition to `keyTypes.size() == 1 || valueTypes.size() == 1` allows `valueTypes` to contain two items when `keyTypes` contains a single type. We don't have a test that that is able to fail in this case. 

Something like `String mixedCodecs(@Key String key1, @Key byte[] key2, @Value String value);` would be able to reproduce the issue.

**Comment by machi1990** [comment]
Hi @mp911de thanks for the feedback, what you are saying is `String mixedCodecs(@Key String key1, @Key byte[] key2, @Value String value)` should throw an `IllegalStateException` exception? 

if so I can add the test (looks like there is no test for this case) and make sure it passes. 

Thanks.

**Comment by mp911de** [comment]
Yes, please.

**Comment by machi1990** [comment]
@mp911de thanks for the inputs. Added a test commit. Let me know what you think regarding the PR.
