### ISSUE TITLE
redis 3.0 cluster , lettuce can not auto failover 

### ISSUE THREAD

**Issue by celesky** [lettuce-io/lettuce-core#1154]
redis version 3.2 and cluster  is build with official solution
https://redis.io/topics/cluster-tutorial 
i create the cluster:
master A and slave a
master B and slave b
master C and slave c

when my application started ,lettuce will auto create connect with master node A,B,C.
but when i killed node A , lettuce can not failover to a( a has upgrade to Master this time)
lettuce will always send command to A node, but the problem is, node A is down.

As a java redis client ，it should auto update the cluster infomation, and auto reconnect to the new master node a.

I wanted to make sure that I wasn't doing something wrong?

**Comment by mp911de** [comment]
Please enable topology refresh. See the [reference documentation](https://github.com/lettuce-io/lettuce-core/wiki/Client-Options#cluster-specific-options) for further details.

**Comment by celesky** [comment]
@mp911de thanks
will it recreate all connection when refresh triggerd? 
or it just refreshing the master-slave meta information ?

and i think, if an connection error is detected(or reach max-count in a time window ), a refresh is performed immediately, which is a better solution.
What's your opinion?

**Comment by celesky** [comment]
another question is in spring data redis, how can i define my ClientOptions.
i trace the source code , i cannot find the place to inject the configuration

LettuceConnectionConfiguration:
private LettuceClientConfiguration getLettuceClientConfiguration(
			ClientResources clientResources, Pool pool) {
		LettuceClientConfigurationBuilder builder = createBuilder(pool);
		applyProperties(builder);
		if (StringUtils.hasText(this.properties.getUrl())) {
			customizeConfigurationFromUrl(builder);
		}
		builder.clientResources(clientResources);
		customize(builder);
		return builder.build();
	}
