### ISSUE TITLE
Reload scripts on EVALSHA if Redis server is restarted

### ISSUE THREAD

**Issue by lpellegr** [lettuce-io/lettuce-core#1159]
#### Is your feature request related to a problem? Please describe

We have an application that connects to a Redis server with lettuce. The application makes use of 2 Lua scripts that are executed quite often. Since the script payload is not really small, the scripts are loaded to Redis on application start and then executed with `EVALSHA`.

The problem we have is that if the Redis server is restarted for any reason, the execution of the scripts fails with the following exception:

> io.lettuce.core.RedisNoScriptException: NOSCRIPT No matching script. Please use EVAL. at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:128)

We understand that Redis does not persist scripts.

#### Describe the solution you'd like

The solution we are suggesting is to add an optional retry mechanism. The Redis connection stores the scripts that are loaded. Upon a `RedisNoScriptException`, a retry could be performed by first reloading the script to Redis, and then re-executing the `EVALSHA` request. If an error happens again, no more attempts are made. 

#### Describe alternatives you've considered

As suggested in the error message, an alternative is to use EVAL instead. The issue is that it's not appropriate when the scripts are large and called often. This defeats the purpose of `EVALSHA`.

#### Teachability, Documentation, Adoption, Migration Strategy

As originally suggested, this could be an option. Although, enabling it by default should not break anything.

**Comment by mp911de** [comment]
The client does not store any uploaded Lua scripts and it has no reference to a script after it was sent to the server. Spring Data Redis provides such a feature with its `ScriptExecutor` as it models Lua scripts as a first-class concept instead of accepting just commands.

That being said, Lettuce is not the right place for this kind of functionality.
