### ISSUE TITLE
Does Lettuce ReadFrom Setting:NEAREST support latency check like heartbeat, and thus refresh automatically.

### ISSUE THREAD

**Issue by kevin-hans** [lettuce-io/lettuce-core#1171]
Hello everyone, I want your help!
I am using Lettuce in SpringBoot stack, behinds is AWS Elaticache as redis cluster.
Because AWS Elasticache consists of 3 zones, and thus bring out significant latency. I want the read always be redirect to the correct node with the smallest latency.
I found Lettuce ReadFrom Setting:NEAREST may be the one I am looking for.
But when I verify it I found that the request is always redirected to nodes that seemed to be decided once the SpringBoot app is started.

I want to know:
1:  Does Lettuce ReadFrom Setting:NEAREST support latency check like heartbeat, and thus refresh read node candidates.
2: If it is true, How can i customize it? 
3: If  I do nothing, what is the truth in Lettuce ReadFrom Setting:NEAREST mode?  

About lettuce ReadFrom Setting
https://github.com/lettuce-io/lettuce-core/wiki/ReadFrom-Settings

**Comment by mp911de** [comment]
Please post your question on StackOverflow so we can share it with a broader community.
