### ISSUE TITLE
Optimization of BITFIELD args generation

### ISSUE THREAD

**Issue by ianpojman** [lettuce-io/lettuce-core#1175]
#### Is your feature request related to a problem? Please describe

When measuring code that uses BITFIELD intensively in profiler, I saw that a non-trivial amount of time was spent creating Redis commands (more so than actually dispatching).

I replaced String.format w/ String concatenation and profiled the app under high load and it basically became insignificant

#### Describe the solution you'd like

I replaced my usage of lettuce 5.1.7.RELEASE with my 6.0 snapshot with these changes 
https://github.com/ianpojman/lettuce-core/pull/1

and per the profiler I saw I reasonable improvement in time spent in `AbstractRedisAsyncCommands.bitfield()` runtime.

#### Teachability, Documentation, Adoption, Migration Strategy

![image](https://user-images.githubusercontent.com/740335/68329447-d6f9a200-0096-11ea-8855-21a99e59cabe.png)
![image](https://user-images.githubusercontent.com/740335/68329467-e37dfa80-0096-11ea-978b-4f9a4a97935c.png)

**Comment by mp911de** [comment]
Thanks a lot for having a look. Do you want to submit a pull request to fix that issue?

**Comment by ianpojman** [comment]
https://github.com/lettuce-io/lettuce-core/pull/1178
