### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Lickem1** [lettuce-io/lettuce-core#1176]
Just trying to connect to my redis server

Code used:
https://i.imgur.com/nFKez0E.png

Stack trace
https://i.imgur.com/XFDd21Y.png

(Works perfectly fine with jedis)

**Comment by Lickem1** [comment]
I'm compiling all the dependencies too

**Comment by mp911de** [comment]
The `localhost` cannot be resolved for whatever reason. Please use an IP address directly.

**Comment by Lickem1** [comment]
I figured it out, the netty versions was different. I just relocated io.netty and it worked.

**Comment by mp911de** [comment]
Thanks for coming back and letting us know.
