### ISSUE TITLE
Multiple threads calling smembers is very slow.

### ISSUE THREAD

**Issue by Riya929** [lettuce-io/lettuce-core#1180]
## Bug Report

I have a case where many(100) threads call smembers at around similar time and it makes it very slow. If I have only 10 threads, it's faster.
May I know a good way to do it?
I am using lettuce with synchronous pool for a cluster.
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment]
It's a natural effect that when you put a higher load on something then the overall time is higher as there is more work to do. There are various factors such as pool configuration and response size that play into the actual processing time.

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. We're happy to look into profiling data if you think you found an issue.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
