### ISSUE TITLE
BoundedAsyncPool doesn't work with a negative maxTotal

### ISSUE THREAD

**Issue by sguillope** [lettuce-io/lettuce-core#1181]
#### Current Behavior

When using the `BoundedAsyncPool` with a negative `maxTotal`, new pool objects are not created. Trying to acquire a new object will fail with `io.lettuce.core.RedisException: java.util.NoSuchElementException: Pool exhausted`

This can be reproduced by creating a pool with the following config:
```java
BoundedPoolConfig.builder()
                .maxTotal(-1)
                .build();
```

#### Input Code
I've added 2 unit tests to `BoundedAsyncPoolUnitTests` based on the `5.2.x` branch to demonstrate the failures:
https://github.com/lettuce-io/lettuce-core/compare/5.2.x...sguillope:bounded-async-pool-with-negative-max-total?expand=1
- `shouldCreateObjectWhenMaxTotalIsNegative` fails with
```
io.lettuce.core.RedisException: java.util.NoSuchElementException: Pool exhausted

	at io.lettuce.core.LettuceFutures.awaitAll(LettuceFutures.java:88)
	at io.lettuce.core.LettuceFutures.awaitAll(LettuceFutures.java:46)
	at io.lettuce.test.Futures.get(Futures.java:98)
	at io.lettuce.test.Futures.get(Futures.java:116)
	at io.lettuce.core.support.BoundedAsyncPoolUnitTests.shouldCreateObjectWhenMaxTotalIsNegative(BoundedAsyncPoolUnitTests.java:72)
	at ...
Caused by: java.util.NoSuchElementException: Pool exhausted
	at io.lettuce.core.support.BoundedAsyncPool.acquire()(Unknown Source)
```
- `shouldCreateMinIdleObjectWhenMaxTotalIsNegative` fails with
```
org.opentest4j.AssertionFailedError: 
Expecting:
 <0>
to be equal to:
 <2>
but was not.
```

#### Expected behavior/code
- Min number of idle objects are created based on the `minIdle` config when the pool is initialised
- New objects are created and returned by the pool when calling `acquire()`

#### Environment

- Lettuce version(s): 5.2.1.RELEASE
- Redis version: AWS Elasticache

#### Additional context

We found this issue after upgrading from SB 2.1 to 2.2.1 and to Spring Data Redis 2.2.1. We use the following Spring `application.yml`-based Redis config:
```yaml
spring:
  redis:
    lettuce:
      pool:
        max-active: -1
        min-idle: 1
        max-idle: 10
```
When we upgraded our healthcheck (which include the redis component) started failing. Debugging found that `java.util.NoSuchElementException: Pool exhausted` was being thrown in [`RedisReactiveHealthIndicator`](https://github.com/spring-projects/spring-boot/blob/2.2.x/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/redis/RedisReactiveHealthIndicator.java#L54).

**Comment by mp911de** [comment]
There's no support for `-1` for `maxTotal` in `BoundedPoolConfig`. You're required to specify a max value, hence the name bounded pool. We have a utility (`CommonsPool2ConfigConverter`) that adapts a Commons Pool2 config to a `BoundedPoolConfig`. It would make sense to add a switch there to react to negative `maxTotal` settings and replace these with `Integer.MAX_VALUE`.

**Comment by sguillope** [comment]
Yeah I figured it might have been intended that way. Unfortunately the pool configuration declared through Spring's properties is used for both sync and async pools.

For now we've changed our `max-active` to a very high integer value to make it work. Automatically falling back to `Integer.MAX_VALUE` would work for us.

Thanks

**Comment by mp911de** [comment]
That's fixed now.
