### ISSUE TITLE
After a couple of days or weeks the channel subscription seems to die

### ISSUE THREAD

**Issue by tbrannt** [lettuce-io/lettuce-core#1182]
I'm running Spring Boot 2.2.0.RELEASE with the default `org.springframework.boot:spring-boot-starter-data-redis` dependency and I'm observing this problem for quite a while now. For all this time Lettuce was the underlying Redis client.

I created a redis message listener bean like so in my `RedisConfiguration:` 
```
@Bean
RedisMessageListenerContainer redisMessageListenerContainer(RedisConnectionFactory connectionFactory,
		MessageListenerAdapter listener1, MessageListenerAdapter listener2,
		MessageListenerAdapter listener3) {
	logger.info("Configuring redisMessageListenerContainer");

	RedisMessageListenerContainer container = new RedisMessageListenerContainer();
	container.setConnectionFactory(connectionFactory);
	container.addMessageListener(listener1,
			new PatternTopic(Listener1.REDIS_CHANNEL));
	container.addMessageListener(listener2,
			new PatternTopic(Listener2.REDIS_CHANNEL));
	container.addMessageListener(listener3,
			new PatternTopic(Listener3.REDIS_CHANNEL));

	return container;
}
```

After a couple of weeks (sometimes months) the listeners will all stop receiving messages over the channel they subscribed to. 
Checking Redis itself (4.0.9) tells me that Redis is still up and running and also the pub-sub mechanism still works fine when using `redis-cli`. Only the java Redis clients seem to not receive anything anymore. After restarting my application it works again.

**Comment by mp911de** [comment]
Can you provide a reproducible test case or debug into the application state when it is no longer working?

**Comment by tbrannt** [comment]
Forgot, of course I have the MessageListenerAdapter beans configured as well in my `RedisConfiguration`:

```
@Bean
MessageListenerAdapter sessionDeletedListenerAdapter(Listener1 listener1) {
	return new MessageListenerAdapter(listener1, "receiveMessage");
}

@Bean
MessageListenerAdapter notificationBubbleListenerAdapter(Listener2 listener2) {
	return new MessageListenerAdapter(listener2, "receiveMessage");
}

@Bean
MessageListenerAdapter lazydUpdateListenerAdapter(Listener3 listener3) {
	return new MessageListenerAdapter(listener3, "receiveMessage");
}
```

Sorry but I cannot really provide a reproducible test case now as this error takes weeks, sometimes months to happen and this project is not open source. If I reduce it to a just the redis part I'd not know if the error is still in there as it would have run months in producteion before that and even after months it would not be clear that the error will never happen again. But the redis pub-sub part is basically not more than I just posted here.

Would it make sense to provide some state of the `MessageListenerAdapter` beans as soon as this happens? What would be useful info?

**Comment by mp911de** [comment]
I'm not sure how to properly proceed here. We run resilience tests as part of our build to interrupt connections and test for their ability to reconnect and resubscribe once the connection could be re-established.

**Comment by tbrannt** [comment]
Ok, weird. That doesn't seem to happen. Once the pub-sub listener stops working it will not recover even after days.

**Comment by kevinWuqisheng** [comment]
i have the same problem in production， are you solved it . @tbrannt

**Comment by tbrannt** [comment]
@kevinWuqisheng no unfortunately not solved yet :/

**Comment by mp911de** [comment]
Unless we can reproduce the issue/state, we cannot progress here. Given that we cannot do anything right now, I'm closing this issue. Please reopen the ticket or add a comment once we can reproduce the issue.

**Comment by myfrontpocket** [comment]
Sorry to drudge up this old issue, but I'm seeing this exact same thing, with nearly the exact setup.  It's been happening for the last month or so without any real rhyme or reason.  I've turned on trace logging for `org.springframework.data.redis.connection` and `org.springframework.data.redis.listener`, but I don't see any logs that would indicate that the listener(s) have died or were stopped or anything like that.  Can't really provide any steps to reproduce because it "just happens".  And I only can tell it's happening because only one of the two API instances running produces a log from our `onMessage` implementation of `MessageListener`.

But we can assure you it IS an issue.

**Comment by mp911de** [comment]
There was an issue with the 6.0 development line where improper chunking of buffers could lead to a lock up. That's fixed with the most recent versions of Lettuce. Please upgrade to see whether the issue is gone.

**Comment by tbrandt-circle** [comment]
I can confirm that at some point after upgrading several times it did not happen anymore.

**Comment by myfrontpocket** [comment]
@mp911de @tbrandt-circle Thanks for the responses!  I've overridden the lettuce dependency to use the latest release; now I just have to wait and see. 🤞

**Comment by devane001** [comment]
The same problem in my production. I have 3 pods in the k8s cluster, one of them suddenly lost its subscription have been running for a long time.
```
org.springframework.data:spring-data-redis:jar:2.7.14
io.lettuce:lettuce-core:jar:6.1.10.RELEASE
```

And my redis is 5.0
Is there a new version solved it ?

**Comment by zzmmff** [comment]
> The same problem in my production. I have 3 pods in the k8s cluster, one of them suddenly lost its subscription have been running for a long time.
> 
> ```
> org.springframework.data:spring-data-redis:jar:2.7.14
> io.lettuce:lettuce-core:jar:6.1.10.RELEASE
> ```
> 
> And my redis is 5.0 Is there a new version solved it ?

Have your redis cluster been restarted?

**Comment by TrungHauad02** [comment]
Hi guys, i have the same problem. I have 3 pods in k8s cluster. At some point in production logs, the server stop recieving message and after that i have these logs:
```
2026-01-30 08:07:50.882 INFO  [core.protocol.ConnectionWatchdog] - Reconnecting, last destination was /xxx.xxx.xxx.xxx:6379
2026-01-30 08:07:50.917 INFO  [.c.protocol.ReconnectionHandler] - Reconnected to xxx.xxx.xxx.xxx/<unresolved>:6379
```
My server had been receiving messages from the subscribed topic, but after these logs, my server stopped printing any messages.
My setup:
```
@Bean
public RedisMessageListenerContainer redisMessageListenerContainer(
            RedisConnectionFactory connectionFactory,
            RedisKeyExpiredListener expirationListener) {
        RedisMessageListenerContainer listenerContainer = new RedisMessageListenerContainer();
        listenerContainer.setConnectionFactory(connectionFactory);
        SubscriptionAwareListener wrappedListener = new SubscriptionAwareListener(expirationListener);
        listenerContainer.addMessageListener(wrappedListener, topic());
        return listenerContainer;
    }
```
```
public class SubscriptionAwareListener implements MessageListener, SubscriptionListener {
@Override
    public void onPatternSubscribed(@NotNull byte[] pattern, long count) {
        log.info("SUBSCRIBED to pattern: {} (subscriptions: {})",
                new String(pattern, StandardCharsets.UTF_8), count);
    }
```
```
log.info("Manual restart requested for RedisMessageListenerContainer");
if (listenerContainer.isRunning()) {
            listenerContainer.stop();
            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
        listenerContainer.start();
```
After 'ReconnectionHandler Reconnected', my server didn't print 'SUBSCRIBED to pattern'. It only printed 'SUBSCRIBED to pattern: xxxxxxx (subscriptions: 1)' and started working again after I forced a restart of the listenerContainer through Swagger. I use spring-data-redis:3.1.0. lecture-core:6.2.4-RELEASE. Here the logs when i manual restart:
```
INFO  [DevController] - Manual restart requested for RedisMessageListenerContainer
INFO  [DevController] - Stopping container...
INFO  [DevController] - Starting container...
INFO  [DevController] - Container restarted. Running: true
INFO  [SubscriptionAwareListener] - SUBSCRIBED to pattern: xxxxxxx (subscriptions: 1)
```
I’m not sure if this helps, but has anyone solved this issue?
