### ISSUE TITLE
TCP RST will cause Validation of shared connection failed

### ISSUE THREAD

**Issue by ksewen** [lettuce-io/lettuce-core#1184]
sorry for my bad English, we use spring-data-redis with lettuce, and we use codis cluster(it's a open source proxy redis cluster solution, homepage:https://github.com/CodisLabs/codis), load balancing with haproxy.
sometime we can found `io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer` in the log. so i set `validateConnection=true`, then i found message `Validation of shared connection failed. Creating a new connection.`

i think `ConnectionWatchdog` will release connection and reconnect when redis send `FIN` to client, so i sniffer packet and analysis:
1. server reset connection at 17:18:44.212;
2. client will execute command at 17:18:44.213, and faild;
3. lettuce connecting to redis at 17:18:44.215;
4. lettuce connected at 17:18:44.215;

and i will show u some screenshot
![image](https://user-images.githubusercontent.com/29543410/69327998-6ef7ae00-0c89-11ea-931a-733060b346b0.png)
![image](https://user-images.githubusercontent.com/29543410/69328104-9e0e1f80-0c89-11ea-81e0-b16e9e5842c0.png)

**Comment by minghu-zhang** [comment]
we have the error too, how I can fix it ?

**Comment by ksewen** [comment]
> we have the error too, how I can fix it ?

it's not a bug of Lettuce.
check serverside, when close the TCP connection, server will send the FIN flag, then lettuce will close the current connection and establish a new connection.
if client not receive the FIN flag, lettuce can't reconnect, then it wll cause the exception.

**Comment by minghu-zhang** [comment]
Before that, I found some information. Here, it is because release() is called repeatedly
![Uploading image.png…]()

**Comment by minghu-zhang** [comment]
Before that, I found some information. Here, it is because release() is called repeatedly
![image](https://user-images.githubusercontent.com/28996118/99226010-fe478b00-2823-11eb-8f79-5b2daea73e95.png)

**Comment by ksewen** [comment]
u means a different exception u founded, this topic is about `io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer`, it's cause of one of the server close the TCP connection but the client not do anything.i think u was show the different issue.
