### ISSUE TITLE
Autoreconnect not happening

### ISSUE THREAD

**Issue by gee4vee** [lettuce-io/lettuce-core#1187]
#### Current Behavior

Autoreconnect is not happening after initial disconnect from local Redis. It is not clear why the disconnect happens in the first place. I increased the timeout from 0 to 30 in `redis.conf` but the app still gets disconnected very soon after booting up. With the client listener code, I can see the disconnect happens but never `onRedisConnected`.

#### Input Code

<details>
<summary>Input Code</summary>

```java
		boolean isLocal = Boolean.parseBoolean(ExternalizedStringUtils.getExternalValue("LOCAL_DEV"));
		redisClient = com.lambdaworks.redis.RedisClient.create(redisUrl);
		Builder optsBuilder = ClientOptions.builder();
		if (!isLocal) {
			SslOptions sslOptions = SslOptions.builder()
					.jdkSslProvider()
					.truststore(new File(redisTrustStoreLocation), redisTrustStorePassword)
					.build();
			optsBuilder.sslOptions(sslOptions);
		}
		ClientOptions clientOptions = optsBuilder
				.disconnectedBehavior(DisconnectedBehavior.DEFAULT)
				.autoReconnect(true)
				.build();
		redisClient.setOptions(clientOptions);

		redisClient.addListener(new RedisConnectionStateListener() {
			@Override
			public void onRedisConnected(final RedisChannelHandler<?, ?> redisChannelHandler) {
				logger.log(Level.INFO, "Connected to redis cluster");
				setConnectionStatus(ConnectionStatus.CONNECTED);
			}

			@Override
			public void onRedisDisconnected(final RedisChannelHandler<?, ?> redisChannelHandler) {
				logger.log(Level.WARNING, "Disconnected from redis cluster. Connection closed: " + redisChannelHandler.isClosed());
				setConnectionStatus(ConnectionStatus.DISCONNECTED);
			}

			@Override
			public void onRedisExceptionCaught(final RedisChannelHandler<?, ?> redisChannelHandler, final Throwable throwable) {
				logger.log(Level.SEVERE, "Redis exception caught: ", throwable);

				if (redisChannelHandler.isClosed()) {
					logger.log(Level.SEVERE, "Disconnected from redis cluster");
					setConnectionStatus(ConnectionStatus.DISCONNECTED);
				}
			}
		});
```
In this case, environment variable `LOCAL_DEV ` is set to true, thereby skipping SSL setup.

</details>

#### Expected behavior/code

Lettuce reconnects after being disconnected.

#### Environment

- Lettuce version(s): [5.2.1.RELEASE]
- Redis version: [4.0.14]

**Comment by mp911de** [comment]
There's no obvious reason why auto-reconnect is not happening. Auto reconnection is initiated by `ConnectionWatchdog`. You might want to increase the log level for `com.lambdaworks.redis.protocol` to `DEBUG` or set a breakpoint in `ConnectionWatchdog.channelInactive(…)` and `ConnectionWatchdog.run(…)` to see whether the watchdog gets notified.

**Comment by gee4vee** [comment]
Turns out it was because I was using the `rediss` scheme when setting up the client and the local server doesn't have SSL configured. Switched to using only host and port via `RedisURI.builder()` and now it connects.
