### ISSUE TITLE
Write too fast result in lost data

### ISSUE THREAD

**Issue by moranhuishoulzr** [lettuce-io/lettuce-core#1189]
[Main.zip](https://github.com/lettuce-io/lettuce-core/files/3944117/Main.zip)
#### Current Behavior

I use RedisClusterAsyncCommands<String, String> to hset datas.Then the part of the data will be lost.When you add a Thread ,in the thread do a empty while,will not be lost data.

I use lettuce-core-5.1.6.jar.
No Stack trace

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.1.16.RELEASE.jar]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment]
Can you provide us with a reproducer, ideally a GitHub repository that is able to demonstrate the issue? Right, we have a hard time understanding the issue.

**Comment by moranhuishoulzr** [comment]
CountDownLatch latch = new CountDownLatch(1);
        latch.await();
        add the two line code can resolve the problem.beacuse all Thrad run down.part of  the data not write to the tcp connect.
Sorry!
