### ISSUE TITLE
[Spring-Lettuce] Error creating bean with name 'redisLettuceConnectionFactory'

### ISSUE THREAD

**Issue by skoiloth** [lettuce-io/lettuce-core#1190]
While configuring the connection factory using spring-data-redis with lettuce, I receive the exception stated below. 

From pom.xml 
<dependency>
			<groupId>io.lettuce</groupId>
			<artifactId>lettuce-core</artifactId>
			<version>5.0.4.RELEASE</version>
		</dependency>

		
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
			
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>

		

		<dependency>
			<groupId>biz.paluch.redis</groupId>
			<artifactId>lettuce</artifactId>
			<version>3.5.0.Final</version>
		</dependency>

		<dependency>
			<groupId>io.reactivex</groupId>
			<artifactId>rxjava</artifactId>
			<version>1.1.0</version>
		</dependency>

		<dependency>
			<groupId>org.latencyutils</groupId>
			<artifactId>LatencyUtils</artifactId>
			<version>2.0.3</version>
		</dependency>

**Exception** 
java.lang.ClassNotFoundException: com.lambdaworks.redis.api.StatefulRedisConnection

Do you have a resolution for this ?

**Comment by mp911de** [comment]
It looks you're using quite dated versions. Lettuce 3.x and 4.x are end of life since over two years now. Please upgrade to Lettuce 5 and Spring Data Redis 2.2.
