### ISSUE TITLE
Add support for AUTH with user + password introduced in Redis 6

### ISSUE THREAD

**Issue by tgrall** [lettuce-io/lettuce-core#1202]
## Feature Request

In Redis 6 it is now possible to authenticate either using a simple password (legacy) or using a user + password

```
AUTH secret
AUTH default secret
```
See ACL documentation section in [Redis Doc](https://redis.io/topics/acl)

#### Is your feature request related to a problem? Please describe

No

#### Describe the solution you'd like

Just support new features of Redis 6

#### Describe alternatives you've considered

No alternative,

#### Teachability, Documentation, Adoption, Migration Strategy

Adding new parameter to the `auth()` method and URIs

**Comment by mikebell90** [comment]
While it would be hacky and awkward, can't you specify the password as a two part atom - user<space>password. I haven't checked the parser to see if this is an issue.

**Comment by mp911de** [comment]
The format `user:password` applies only to `RedisURI`. We should introduce for Lettuce a dedicated overload (`auth(String username, CharSequence password)`). Any kind of separator char would clash with valid Redis passwords.

**Comment by mikebell90** [comment]
I would go so far as to say considering creating an

auth(Principal principal) abstraction, with overloads for the username only and username/password is a better abstraction?

**Comment by IAmATeaPot418** [comment]
One thing I'd also like to bring up is that its not just for RESP 3 but also for RESP2 as well. Both will be supported in Redis 6.

**Comment by gkorland** [comment]
@mp911de what the release plan for it? since Redis 6 is backward compatible with RESP2 I don't think this issue should be blocked by the RESP3 implementation.

**Comment by mp911de** [comment]
I was a bit reluctant on releasing a first milestone as Redis 6's Sentinel with RESP3 (antirez/redis#6160) creates an impediment for RESP3 usage. Lettuce 6 attempts a RESP3 handshake by default and so the default behavior renders Sentinel arrangements unusable.
