### ISSUE TITLE
how to talk with slave instance under cluster environment?

### ISSUE THREAD

**Issue by wenweihu86** [lettuce-io/lettuce-core#1206]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Teachability, Documentation, Adoption, Migration Strategy

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by mp911de** [comment]
Check out the documentation for `ReadFrom` at https://lettuce.io/core/release/reference/index.html#readfrom.redis-cluster.
