### ISSUE TITLE
Un-deprecate ClientOptions.pingBeforeActivateConnection

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#1208]
Given that PING before connection activation turns out to be useful across various usecases (enabling and also disabling when using Lettuce 6 to disable the handshake with RESP2) we should un-deprecate `pingBeforeActivateConnection`.

See also #1201.

**Comment by chadlwilson** [comment]
Thanks @mp911de !

**Comment by DanielYWoo** [comment]
sure will do that. thanks anyway.
