### ISSUE TITLE
Custom codec using ByteBuffer put/get APIs directly to convert java object to/from ByteBuffer not working with lettuce/redis

### ISSUE THREAD

**Issue by Riya929** [lettuce-io/lettuce-core#1213]
I have a java object which has some int/string/enum fields

    public class Key{
          String name;
          int id;
          Map<Integer, Type> valueMap; //type is an enum
          
           public void write(final ByteBuffer byteBuffer) throws IOException {
            byteBuffer.clear();
            byte[] nameBytes=  name.getBytes(Charset.forName("UTF-8"));
            byteBuffer.putInt(nameBytes.length);
            byteBuffer.put(nameBytes);
            byteBuffer.putInt(id);
            writeMap(valueMap, byteBuffer);
        }
    
        private void writeMap(Map<Integer, Type> map, ByteBuffer byteBuffer) throws IOException
        {
            byteBuffer.putInt(map.size());
            for(Map.Entry<Integer, Type> e : map.entrySet()) {
                byteBuffer.putInt(e.getKey().getId());
                byteBuffer.putInt(e.getValue().getId());
            }
        }
    
        public static Key read(final ByteBuffer byteBuffer) throws IOException {
            int stringLen = byteBuffer.getInt();
            byte[] nameBytes=  new byte[stringLen];
            byteBuffer.get(nameBytes);
            String name= new String(name);
            int id= byteBuffer.getInt();
            Map<Integer, Type> valueMap= readMap(byteBuffer);
            return new Key(name, id, map);
        }
        
         private static Map<Integer, Type> readMap(ByteBuffer byteBuffer) throws IOException
        {
            int r = byteBuffer.getInt();
            if(r==-1) {
                return ImmutableMap.of();
            } else {
                ImmutableMap.Builder<Integer, Type> mm = ImmutableMap.builder();
                for(int i=0; i<r; i++) {
                    int k = byteBuffer.getInt();
                    Type v = Type.of(byteBuffer.getInt());
                    mm.put(k,v);
                }
                return mm.build();
            }
        }
    
        .....//constructor and getter/setter present
    }
    
    
    CustomCodec:
    
    
    
    public class CustomCodec implements RedisCodec<Key, Set<Long>> {
    
        @Override
        public Key decodeKey(ByteBuffer bytes) {
                try {
                    bytes.flip();
                    return Key.read(bytes);
                } catch (IOException e) {
                    return null;
                }
            
        }
    
        @Override
        public Set<Long> decodeValue(ByteBuffer bytes) {
                bytes.flip();
                int size = bytes.getInt();
                Set<Long> values = new HashSet<Long>();
                for(int i=0; i<size; i++){
                    values.add(bytes.getLong());
                }
                return values;
        }
    
    
        @Override
        public ByteBuffer encodeKey(Key key) {
            try {
                    ByteBuffer byteBuffer = ByteBuffer.allocate(100);
                    key.write(byteBuffer);
                    return byteBuffer;
                }
            } catch (IOException e) {
                return null;
            }
        }
    
        @Override
        public ByteBuffer encodeValue(Set<Long> value) {
            try {
                    ByteBuffer byteBuffer = ByteBuffer.allocate(value.size() * Long.BYTES + Integer.BYTES);
                    byteBuffer.clear();
                    byteBuffer.putInt(value.size());
                    value.stream().forEach(i -> byteBuffer.putLong(i));
                    byteBuffer.flip();
                    return byteBuffer;
            } catch (IOException e) {
                return null;
            }
        }
    
    
    }

Using this results in BufferUnderFlowException at encodeValue(). However, when i write a simple test to assert the encode and decode, it works fine
May i know if anyone knows if the java objects can be converted to Bytebuffer directly and can be used as redis keys using lettuce?

I tried using ByteArrayOutputStream/ByteArrayInputStream and it works fine with it. But i read somewhere it should be faster using the ByteBuffer directly.

Thanks a lot in advance!

**Comment by mp911de** [comment]
Thanks for reaching out. Looking at the codec, it reveals some flaws as the key buffer is not flipped before returning it. I suggest not worrying about encoding performance in the first place but rather using already existing serialization formats such as JSON, Kryo or msgpack (these require an additional integration as Lettuce does not ship `RedisCodec` implementations).

Allocating buffers and using Java 8 Stream API already neglects performance gains that could be potentially gained from a custom serialization scheme. On top, you also end up with a lot of additional complexity by maintaining your own binary format.

> somewhere it should be faster using the ByteBuffer directly.

It all boils down to tradeoffs. Here you trade about 1-2% of performance benefits for additional complexity.

So far, I haven't seen anyone implementing their own codec with their own, application-specific, binary format. Rather, folks use Java serialization or any other serialization utility to bridge buffers from Lettuce/Netty into their serialization library.
