### ISSUE TITLE
HMSET deprecated in version 4.0.0

### ISSUE THREAD

**Issue by hodur** [lettuce-io/lettuce-core#1217]
`HMSET` has been [considered deprecated since Redis 4.0.0](https://raw.githubusercontent.com/antirez/redis/4.0/00-RELEASENOTES). Instead `HSET` is variadic and returns the number of fields added.

I'd expect to be able to use `HSET` through `lettuce` with multiple key/value pairs. Looking at the code the obvious solutions seems to be adding `String hset(K key, Map<K, V> map);` to the api (along with the async and reactive equivalents). When executed against Redis servers <4.0.0 the error property on the command output would be set to what Redis throws on older versions.

**Comment by mp911de** [comment]
Thanks for the hint. It makes sense to reflect these changes in our API and introduce `long hset(K, Map)` including reactive and async variants and deprecate `hmset`. Care to submit a pull request? The API is generated and method templates can be found in `src/main/templates` and the generator is located in the test sources (`io.lettuce.apigenerator.GenerateCommandInterfaces`).

**Comment by hodur** [comment]
I'm getting errors after generating. When I run the generator on the `5.3.x` branch with the code untouched it removes both `dispatch(ProtocolKeyword ...` methods from all three `RedisSentinelCommands` interfaces.

**Comment by mp911de** [comment]
You might want to revert all touched classes except the Hash-related ones.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and forwardported now.

**Comment by hodur** [comment]
Glad to be of help.
