### ISSUE TITLE
springboot lettuce configuration with sentinel and random read slave

### ISSUE THREAD

**Issue by 029vaibhav** [lettuce-io/lettuce-core#1219]
We have sentinel master/slave configuration with 1 master and 2 slaves.
Following configuration gets all the slaves and uses only 1st slave always to get the data.

```
LettuceClientConfiguration lettuceClientConfiguration = LettucePoolingClientConfiguration.builder()
            .readFrom(ReadFrom.SLAVE_PREFERRED).build();
```

We have to support a TPS of 40k TPS its not possible to get that from a single slave and thus want to make use of all the redis nodes available.

Selection of random slave comes from PooledClusterConnectionProvider but thats only available for RedisClusterConfiguration and not RedisSentinelConfiguration.

Is there a way already to get the best of two worlds?

**Comment by mp911de** [comment]
Please use `ReadFrom.ANY` (available since Lettuce 5.2).
