### ISSUE TITLE
Allow selection of Heap or Direct buffers for CommandHandler.buffer

### ISSUE THREAD

**Issue by dantheperson** [lettuce-io/lettuce-core#1223]
#### Is your feature request related to a problem? Please describe

On my application during load spikes the command CommandHandler.stack grows to 250ish command and the buffer grows up to 1.5Gb.  (when redis data values being returned are only Kbs in size)
heap buffers being visible in heap dumps, aid in diagnosis of memory issues

#### Describe the solution you'd like

If you used alloc.buffer(...) instead of alloc.directBuffer(...) it would allow the user to choose between heap or direct buffers with  `-Dio.netty.noPreferDirect=true`

**Comment by mp911de** [comment]
That's in place now. Care to give Lettuce `5.3.0.BUILD-SNAPSHOT` a try? The aggregation buffer in `CommandHandler` isn't bounded. It could make sense to add an upper bound so that the fill ratio is hit earlier. On the other side, a bound can easily break applications that work with large values.
