### ISSUE TITLE
reconnect to sentinel constantly

### ISSUE THREAD

**Issue by vernalman01** [lettuce-io/lettuce-core#1228]
I want to know why there is a  thread named timer-1 to call createEventLoopGroup method?

21:59:22,116 DEBUG [Timer-1] DefaultEventLoopGroupProvider.createEventLoopGroup(DefaultEventLoopGroupProvider.java:138) - Creating executor io.netty.util.concurrent.DefaultEventExecutorGroup
21:59:22,116 DEBUG [Timer-1] DefaultClientResources.<init>(DefaultClientResources.java:194) - LatencyUtils/HdrUtils are not available, metrics are disabled
21:59:22,117 DEBUG [Timer-1] RedisClient.connectSentinelAsync(RedisClient.java:539) - Trying to get a Redis Sentinel connection for one of: []
21

**Comment by mp911de** [comment]
I cannot help you with `Timer-1`. Lettuce creates threads that are prefixed with `lettuce-timer`. Other than that, `createEventLoopGroup` creates the event loops required for connecting and working on the connections.
