### ISSUE TITLE
Use domain specific value object as return type for xpending.

### ISSUE THREAD

**Issue by christophstrobl** [lettuce-io/lettuce-core#1229]
## Feature Request

```java
interface RedisStreamCommands<K,V> {

    // instead of: List<Object> xpending(K key, K group); 
    PendingMessagesSummary xpending(K key, K group);

    // instead of: List<Object> xpending(K key, K group, Range<String> range, Limit limit); 
    List<PendingMessage> xpending(K key, K group, Range<String> range, Limit limit)
}
```

```java
interface RedisStreamReactiveCommands<K,V> {

    // instead of: Flux<Object> xpending(K key, K group); 
    Mono<PendingMessagesSummary> xpending(K key, K group);

    // instead of: List<Object> xpending(K key, K group, Range<String> range, Limit limit); 
    Flux<PendingMessage> xpending(K key, K group, Range<String> range, Limit limit)
}
```

#### Is your feature request related to a problem? Please describe

`xpending` uses `List<Object>` | `Flux<Object>` that require the user to run the result through the `PendingParser` to extract `PendingMessages` or `List<PendingMessage>` from the command result.

In a reactive scenario this requires to `collectList()` the command output first, to then pass it on. Because `null` values are omitted a result like

```bash
127.0.0.1:6379> "XPENDING" "key-1" "my-group"
1) (integer) 0
2) (nil)
3) (nil)
4) (nil)
``` 

ends up as `[0, []]` where it should have been `[0, null, null, []]`. This causes trouble with the `PendingParser`. Additionally the values (all `ByteBuffer` or `List` containing `ByteBuffer`) have to be converted into the correct format to pass type casts within the `PendingParser`.

#### Describe the solution you'd like

Change the method signature and apply required parsing internally. 
Drawback: breaking API change.

#### Describe alternatives you've considered

change nothing - let the user deal with it (not recommended)

#### Teachability, Documentation, Adoption, Migration Strategy

would be way easier than:

```java
reactiveClient.xpending(key, group).collectList().map(it -> {

	ArrayList<Object> fixMissingNulls = new ArrayList<>(it);
	if (fixMissingNulls.size() == 2 && fixMissingNulls.get(1) instanceof List) {
		fixMissingNulls.add(1, null);
		fixMissingNulls.add(1, null);
	}
        List<Object> target = fixMissingNulls.stream()
		.map(LettuceConverters::preConvertNativeValues) // convert ByteBuffer to String/Long/... believe me you don't want to see this ;)
                .collect(Collectors.toList());
        return PendingParser.parser(target);	
});
```

**Comment by dengliming** [comment]
Looks good
