### ISSUE TITLE
Introduce ThreadFactoryProvider to DefaultEventLoopGroupProvider for easier customization

### ISSUE THREAD

**Issue by apilling6317** [lettuce-io/lettuce-core#1243]
In order to propagate logging, tracing and other context information to netty threads, it would be useful to be able to specify custom ThreadFactory implementations.  As an example, if DefaultEventLoopGroupProvider were to change createEventLoopGroup to be non-static and introduce a protected getThreadFactory(String name) method then this class could be extended so that a custom ThreadFactory implementation could be used which would allow control of passing of context information from parent to child threads

**Comment by mp911de** [comment]
`EventLoopGroupProvider` is an extensible SPI where you can plug in your own implementation.

**Comment by apilling6317** [comment]
Understood but I hope you would agree that creating an implementation of that is a significant undertaking compared to providing a thread factory implementation.  What appears to be a small refactor would make the default extensible.

**Comment by mp911de** [comment]
Note that we already have support for tracing along with context propagation across commands. Happy to review a pull request to see what's needed in order to introduce a custom `ThreadFactory`.

**Comment by mp911de** [comment]
That's in place now.
