### ISSUE TITLE
fail to eval script by nativeConnection

### ISSUE THREAD

**Issue by maketubo** [lettuce-io/lettuce-core#1263]
## Bug Report

![image](https://user-images.githubusercontent.com/14799012/78779200-1c682580-79cf-11ea-8eb0-b1ecd371b970.png)
![image](https://user-images.githubusercontent.com/14799012/78779209-20944300-79cf-11ea-9248-3e88270cec2e.png)
![image](https://user-images.githubusercontent.com/14799012/78779215-2558f700-79cf-11ea-8be5-645503bb0857.png)

- Lettuce version(s): 5.2.1.RELEASE

when i use RedisAsyncCommandsImpl to eval script and send key and value which as String type,
it cause :
![image](https://user-images.githubusercontent.com/14799012/78779429-8680ca80-79cf-11ea-989b-e60d43cf7a87.png)
because the codec is ByteArrayCodec and it try to cast String to byte.

So i try to send key and value as byte[] type, it cause another exception:
![image](https://user-images.githubusercontent.com/14799012/78779700-f0996f80-79cf-11ea-9d97-aa0aaae16a0d.png)
It really confused me.

**Comment by mp911de** [comment]
note that Spring Data Redis uses the Byte Array Codec so your call must be `eval(…, BOOLEAN, new byte[][]{keys.getBytes()}, days.getBytes()`. Please also note that the second exception is caused by Redis itself.

**Comment by maketubo** [comment]
```
        try {
                RedisAsyncCommandsImpl conn = (RedisAsyncCommandsImpl) nativeConnection;
                RedisFuture eval = conn.eval(getAndSetBitLock, ScriptOutputType.BOOLEAN,
                        new byte[][]{key.getBytes()}, String.valueOf(days).getBytes());
                return (boolean) eval.get();
            } catch (Exception e) {
                e.printStackTrace();
            }
```
It works fine! Thanks sir, for save my time, although it still confusing that just change key.getBytes() to new byte[][]{keys.getBytes()} then work fine :(
Maybe Lettuce just not friendly to novices.
At last, i figure it by lettuce connection as follow.
![image](https://user-images.githubusercontent.com/14799012/78794524-73c5c000-79e6-11ea-947b-a50b332da464.png)
![image](https://user-images.githubusercontent.com/14799012/78794959-fa7a9d00-79e6-11ea-9fa4-83558ed5f2fa.png)
![image](https://user-images.githubusercontent.com/14799012/78795450-a02e0c00-79e7-11ea-978a-be16654e7be3.png)
