### ISSUE TITLE
Security vulnerability reported for io.netty:netty-codec

### ISSUE THREAD

**Issue by narayar** [lettuce-io/lettuce-core#1264]
## Bug Report

Security vulnerability reported for io.netty:netty-codec
The latest io.lettuce:lettuce-core:5.2.2.RELEASE has a hard dependency on io.netty:netty-handler:4.1.45.Final. But it in turn depends on io.netty:netty-codec:4.1.45.Final which has the following security vulnerability reported on 4/8/2020

<img width="1610" alt="Screen Shot 2020-04-09 at 6 31 21 PM" src="https://user-images.githubusercontent.com/10053175/78954247-5a794e00-7a90-11ea-8b85-5b35b123789b.png">

Please upgrade your lib to depend on the later versions of io.netty libs where the vulnerability is fixed.

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by narayar** [comment]
The following is the dependency tree for your latest version - 
<img width="377" alt="Screen Shot 2020-04-09 at 6 33 49 PM" src="https://user-images.githubusercontent.com/10053175/78954350-bb088b00-7a90-11ea-9821-aac006ea4c71.png">

**Comment by mp911de** [comment]
Lettuce isn't exposing a netty server and it's not using any netty ZLib codecs so there's no vulnerability when using Lettuce. In any case, we upgraded to Netty 4.1.48 already a while ago (see #1259).

**Comment by narayar** [comment]
@mp911de I dont see 5.3.0 available in maven central (https://repo1.maven.org/maven2/io/lettuce/lettuce-core/). Is it coming anytime soon?
