### ISSUE TITLE
Can't connect to ElastiCache cluster when transit encryption is on using lettuceConnectionfactory

### ISSUE THREAD

**Issue by ptanwar27** [lettuce-io/lettuce-core#1270]
## Bug Report
I am facing similar issue as mentioned in the closed issue https://github.com/lettuce-io/lettuce-core/issues/1227 with Encryption in-transit and Encryption at-rest "ON"

I am not using SSL or Paasword for elastic cache cluster and I have 8 shards with 1 replication.

#### Current Behavior
Case 1
My problem is when I connect using RedisClusterClient via below code it allows me to connect :

            RedisClusterClient client = this.getRedisClusterClient(DefaultClientResources.builder().dnsResolver(new DirContextDnsResolver()).build(), url);
            client.setOptions(ClusterClientOptions.builder().topologyRefreshOptions(ClusterTopologyRefreshOptions.builder().enableAdaptiveRefreshTrigger(new RefreshTrigger[]{RefreshTrigger.MOVED_REDIRECT, RefreshTrigger.PERSISTENT_RECONNECTS}).adaptiveRefreshTriggersTimeout(Duration.ofNanos(TimeUnit.SECONDS.toNanos(30L))).build()).build());
            return new RedisClusterProvider(client);

But when I checked the RedisClusterClient object partition value is null.

When I call write(key, value) method on this it allows me to write.

Case -2
But when I changed my connection details through lettuceConnectionFactory

@Bean

    public LettuceConnectionFactory connectionFactory() {
        LettuceClientConfiguration clientConfiguration = LettuceClientConfiguration.builder()
              .build();
        return new LettuceConnectionFactory(new RedisClusterConfiguration(nodes), clientConfiguration);
    }

    @Bean
    public RedisTemplate<String, ?> redisTemplate(RedisConnectionFactory factory) {
        RedisTemplate<String, ?> template = new RedisTemplate<>();
        template.setConnectionFactory(factory);
        return template;
    }

I have started getting below error , when I try to execute pipeline opertaion via redistemplate.

Caused by: io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='clustercfg.*******.cache.amazonaws.com', port=6379]]

If this is due to tcp port 16379 not being open, then why I am not getting error in case-1. Shouldn't it throw and error or the way io.lettuce.core.cluster.RedisClusterClient work is different

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): io.lettuce:lettuce-core:5.1.7.RELEASE
- Redis version: redis 5.0 cluster
-Spring-data-redis version : 2.1.6.RELEASE

Please note that if I turn off Encryption in-transit and Encryption at-rest it works fine in both the cases.

**Comment by mp911de** [comment]
Please provide the full stack trace including the suppressed exceptions. `Cannot retrieve initial cluster partitions from initial URIs` contains more details that contain the actual cause.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
