### ISSUE TITLE
Stream commands are not considered for ReadOnly routing. 

### ISSUE THREAD

**Issue by redviper** [lettuce-io/lettuce-core#1271]
## Bug Report
Redis Stream based commands are not considered for Read-Only routing. 

Checked with @mp911de and he verified the issue. 

#### Current Behavior
When using a Replica setup using ElastiCache clustered-mode, all xread commands are routed to the Master. 

#### Input Code
```java
        Flux.just(partitions.toArray(new String[0]))
                .flatMap(s -> Flux.just(XReadArgs.StreamOffset.from(key, "0-0")))
                .flatMap(streamOffset -> cmd.xread(streamOffset))
                .retry()

```

</details>

#### Environment

- Lettuce version(s): [ 5.0.0.RELEASE]
- Redis version: [5.0.6]

#### Possible Solution

Stream read-only commands should correctly pick a destination by using the ReadFrom configurationn.

**Comment by mp911de** [comment]
That's fixed now.
