### ISSUE TITLE
Add template method for EventLoopGroup creation

### ISSUE THREAD

**Issue by SMT15** [lettuce-io/lettuce-core#1273]
Good day, sirs! We are working with relatively big Redis clusters, and it's not unlikely to face network saturation or load disproportion. We strive to improve our monitoring system to be even more proactive to act as fast as possible to reduce any user impact. Better monitoring capabilities should also help a lot during performance test runs to identify any kind of degradation as early as possible.

For example, an alert if issued commands on the app side can't be pumped into Redis due to whatever reasons might help. To configure that alert either option might work:
- Utilize an existing EventBus mechanism to receive an event in case the number of pending tasks in Netty event loops reaches configured threshold;
- Get more or less real-time stats regarding the number of pending tasks in Netty event loops.

I must admit that it is currently possible to implement the latter option without any changes on the Lettuce side. Still, it requires an ugly combination of reflection and casting to get to NioEventLoop.pendingTasks() to fetch the data.

**Comment by mp911de** [comment]
There are various extension points you could use to hook in. Using a custom EventLoopGroupProvider that supplies a customized EventLoopGroup seems the easiest approach assuming you might want to introspect other netty-based libraries.

**Comment by SMT15** [comment]
Thanks for the suggestion! I get the idea; however, if I understand correctly, the only thing that I need/want to change is the behavior of DefaultEventLoopGroupProvider.createEventLoopGroup().

Unfortunately, I can't easily do that:

**Option 1.** Create custom EventLoopGroupProvider by extending DefaultEventLoopGroupProvider. Since createEventLoopGroup() is a static method and is invoked within DefaultEventLoopGroupProvider, the option won't work.
**Option 2.** Create custom EventLoopGroupProvider by copy-pasting the whole DefaultEventLoopGroupProvider, but I can't do that either as io.lettuce.core.resource.Futures class that is used in DefaultEventLoopGroupProvider is a package-private class and is inaccessible for me.

I surely must've missed something. However, for now, it seems that supplying a custom EventLoopGroupProvider to get the metrics won't be that simple, after all.

**Comment by mp911de** [comment]
The code around `Futures` dates back where netty did not provide `PromiseCombiner`. The code  in the `Futures` class can be considered obsolete.

**Comment by mp911de** [comment]
We introduced a template method `doCreateEventLoopGroup` in `DefaultEventLoopGroupProvider` to simplify customization of event loop groups.

**Comment by SMT15** [comment]
Awesome, thanks a ton!
