### ISSUE TITLE
RedisCluster execute scan command  just on the connect node!

### ISSUE THREAD

**Issue by JecketLiao** [lettuce-io/lettuce-core#1287]
## Feature Request

when I execute scan command,I fund that the result just include the keys in the client that it connect ed.How can I get all the keys on the Cluster. 
The sample is as follows：
` public RedisFuture<KeyScanCursor<byte[]>> scan() {
        return redisTemplate.execute((RedisCallback<RedisFuture<KeyScanCursor<byte[]>>>) connection -> {
            //Set<String> keys = Sets.newHashSet();

            if(connection.getNativeConnection() instanceof RedisAdvancedClusterAsyncCommands){
                RedisAdvancedClusterAsyncCommands redisAsyncCommands = (RedisAdvancedClusterAsyncCommands) connection.getNativeConnection();
                ScanArgs scanArgs = new ScanArgs();
                scanArgs.limit(10000L);

                RedisFuture<KeyScanCursor<byte[]>> redisFuture = redisAsyncCommands.scan(scanArgs);
                return redisFuture;

            }
            return null;
        });
    }`

**Comment by mp911de** [comment]
`RedisAdvancedClusterAsyncCommands` implements a cluster-wide scan when using the `scan(…)` method. Calling `scan(…)` with the resulting `ScanCursor` will give you the desired result.

**Comment by chenfeng8087** [comment]
@mp911de 
We have a cluster with 100 nodes and want a parallel scan over the nodes.
Is there any approach to start 100 threads, each thread contains a scan connected to a single node to avoid intersection?

Thanks.
