### ISSUE TITLE
A question in accessing from PC in a public network to Redis Cluster in private network on GCP

### ISSUE THREAD

**Issue by shkim1980** [lettuce-io/lettuce-core#1288]
**Just for a test purpose, my colleague has constructed our Redis cluster in a private network on GCP as follows, each of instances in the cluster is with public IP address.**

127.0.0.1:10001> cluster nodes
1926a4127f862c55ae03a35ae69d1be8f6661ddb 10.0.X.C:10001@20001 slave e7387d99a4e1ed99ecbba31012ae0c3aedf221fa 0 1589258736000 2 connected
ede32434d004a2387fd688f0a017e9d4202d3b86 10.0.X.C:10003@20003 master - 0 1589258738000 8 connected 10923-16383
203e86f85ed087ec2d0caed7fbdd3d9a7905ce34 10.0.X.A:10003@20003 slave ede32434d004a2387fd688f0a017e9d4202d3b86 0 1589258739375 8 connected
853adea9b44715c7a4c9939f8605e7750c014c8b 10.0.X.B:10002@20002 master - 0 1589258738367 2 connected 5461-10922
c79918e5bfbe20b7194752d0d94ddb16799cd353 10.0.X.A:10002@20002 slave 853adea9b44715c7a4c9939f8605e7750c014c8b 0 1589258735000 2 connected
e7387d99a4e1ed99ecbba31012ae0c3aedf221fa 10.0.X.A:10001@20001 myself,master - 0 1589258735000 1 connected 0-5460
100110cf05c66f16633248850e66b7b8f57f2d50 10.0.X.C:10002@20002 slave 853adea9b44715c7a4c9939f8605e7750c014c8b 0 1589258736363 3 connected
b5c56b9434e577b9ba85d4c04d135d7abf740794 10.0.X.B:10003@20003 slave ede32434d004a2387fd688f0a017e9d4202d3b86 0 1589258737000 8 connected
c7fd3e74abe4c1f52e77d8f8261329d1c29f7f14 10.0.X.B:10001@20001 slave e7387d99a4e1ed99ecbba31012ae0c3aedf221fa 0 1589258736000 3 connected
127.0.0.1:10001>
**Using spring-data-redis, he configured connections as below. At this time, the host is configured to use public IP address.**
...
		ClusterClientOptions clusterClientOptions = ClusterClientOptions.builder()
				.topologyRefreshOptions(clusterTopologyRefreshOptions)
				.autoReconnect(true)
				.pingBeforeActivateConnection(true)
				.cancelCommandsOnReconnectFailure(false)
				.suspendReconnectOnProtocolFailure(false)
				.requestQueueSize(Integer.MAX_VALUE)
				.disconnectedBehavior(DisconnectedBehavior.DEFAULT)
				.socketOptions(socketOptions)
				.sslOptions(sslOptions)
				.timeoutOptions(timeoutOptions)
				.publishOnScheduler(true)
				.build();
		
		LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
				.clientOptions(clusterClientOptions)
				.build();
		
		RedisClusterConfiguration clusterConfiguration = new RedisClusterConfiguration();
		clusterConfiguration.clusterNode(new RedisNode(redis1Host1, redis1Port1)); //host => public IP
		clusterConfiguration.setPassword(redis1Pass1);
		clusterConfiguration.clusterNode(new RedisNode(redis1Host2, redis1Port2)); //host => public IP
		clusterConfiguration.setPassword(redis1Pass2);
		clusterConfiguration.clusterNode(new RedisNode(redis1Host3, redis1Port3)); //host => public IP
		clusterConfiguration.setPassword(redis1Pass3);
		clusterConfiguration.clusterNode(new RedisNode(redis2Host1, redis2Port1)); //host => public IP
		clusterConfiguration.setPassword(redis2Pass1);
		clusterConfiguration.clusterNode(new RedisNode(redis2Host2, redis2Port2)); //host => public IP
		clusterConfiguration.setPassword(redis2Pass2);
		clusterConfiguration.clusterNode(new RedisNode(redis2Host3, redis2Port3)); //host => public IP
		clusterConfiguration.setPassword(redis2Pass3);
		clusterConfiguration.clusterNode(new RedisNode(redis3Host1, redis3Port1)); //host => public IP
		clusterConfiguration.setPassword(redis3Pass1);
		clusterConfiguration.clusterNode(new RedisNode(redis3Host2, redis3Port2)); //host => public IP
		clusterConfiguration.setPassword(redis3Pass2);
		clusterConfiguration.clusterNode(new RedisNode(redis3Host3, redis3Port3)); //host => public IP
		clusterConfiguration.setPassword(redis3Pass3);
		
		return new LettuceConnectionFactory(clusterConfiguration, clientConfig);
...
**The redis cluster is on GCP and a spring application operates in his local PC.
With public IP connection, it works normally as below.**

2020-05-12 14:11:58.865 [lettuce-nioEventLoop-6-1] DEBUG io.lettuce.core.RedisClient - Connecting to Redis at 34.X.Y.Z:10001: Success

**Then, as below, he has confirmed that successful execution of CLUSTER NODES command.**

2020-05-12 14:11:58.923 [lettuce-nioEventLoop-6-1] DEBUG io.lettuce.core.protocol.RedisStateMachine - Decoded TimedAsyncCommand [type=CLUSTER, output=StatusOutput [output=1926a4127f862c55ae03a35ae69d1be8f6661ddb 10.0.X.C:10001@20001 slave e7387d99a4e1ed99ecbba31012ae0c3aedf221fa 0 1589260316342 2 connected
ede32434d004a2387fd688f0a017e9d4202d3b86 10.0.X.C:10003@20003 master - 0 1589260318347 8 connected 10923-16383
203e86f85ed087ec2d0caed7fbdd3d9a7905ce34 10.0.X.A:10003@20003 slave ede32434d004a2387fd688f0a017e9d4202d3b86 0 1589260319349 8 connected
853adea9b44715c7a4c9939f8605e7750c014c8b 10.0.X.B:10002@20002 master - 0 1589260314000 2 connected 5461-10922
c79918e5bfbe20b7194752d0d94ddb16799cd353 10.0.X.A:10002@20002 slave 853adea9b44715c7a4c9939f8605e7750c014c8b 0 1589260317000 2 connected
e7387d99a4e1ed99ecbba31012ae0c3aedf221fa 10.0.X.A:10001@20001 myself,master - 0 1589260315000 1 connected 0-5460
100110cf05c66f16633248850e66b7b8f57f2d50 10.0.X.C:10002@20002 slave 853adea9b44715c7a4c9939f8605e7750c014c8b 0 1589260317000 3 connected
b5c56b9434e577b9ba85d4c04d135d7abf740794 10.0.X.B:10003@20003 slave ede32434d004a2387fd688f0a017e9d4202d3b86 0 1589260317344 8 connected
c7fd3e74abe4c1f52e77d8f8261329d1c29f7f14 10.0.X.B:10001@20001 slave e7387d99a4e1ed99ecbba31012ae0c3aedf221fa 0 1589260317000 3 connected
, error='null'], commandType=io.lettuce.core.protocol.Command], empty stack: true

**According to cluster information, each node in the cluster is with private IP address and lettuce is trying to connect to private IP addresses in my local PC.** 

2020-05-12 14:11:58.957 [http-nio-11580-exec-1] DEBUG io.lettuce.core.RedisClient - Connecting to Redis at 10.0.X.B:10001

**Needless to say, it cannot be connected.**

io.netty.channel.ConnectTimeoutException: connection timed out: /10.146.0.73:10001
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**So, I would like to know whether or not connecting from lettuce in my local PC to the nodes in the GCP through public IP address is possible. If possible, would you please let me know how to enable this?**

**Comment by mp911de** [comment]
Cluster operations rely on the topology reported by Redis Cluster. Specifically, Lettuce uses the `CLUSTER NODES` command to gather topology information and uses the addresses from there. Please configure your cluster in a way that it announces the public address. These are the following options:

```
cluster-announce-ip 10.1.1.5
cluster-announce-port 6379
cluster-announce-bus-port 6380
```

Alternatively, you can configure a `SocketAddressResolver` (see also `MappingSocketAddressResolver`) through `ClientResources` to translate addresses before Lettuce attempts to connect to these.
