### ISSUE TITLE
Topology refresh trying to connect to 127.0.0.1

### ISSUE THREAD

**Issue by rokcarl** [lettuce-io/lettuce-core#1289]
## Bug Report

This problem might be because of my bad redis configuration or it might be redis's fault, but it could be fixed inside Lettuce.

I have a redis cluster, three servers, each one running a master and a replica. When I use `RedisClusterClient` to connect, I get the following error:

```bash
redisClient ==> io.lettuce.core.cluster.RedisClusterClient@75f9eccc
May 13, 2020 11:26:32 AM io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh lambda$openConnections$11
WARNING: Unable to connect to [127.0.0.1/<unresolved>:7000]: finishConnect(..) failed: Connection refused: /127.0.0.1:7000
connection ==> io.lettuce.core.cluster.StatefulRedisClusterConnectionImpl@f26a0ec
```

I'm guessing the cluster client asks something like `CLUSTER NODES` on redis to get the topology. The problem with this is that `CLUSTER NODES` sometimes gives me 127.0.0.1 for the node on the server I'm connecting to. I filed this with redis as well in [this issue](https://github.com/antirez/redis/issues/6811#issuecomment-628415007).

This might be redis's fault, but it could at least partially be solved in Lettuce by either of the following:
* If you see 127.0.0.1 from redis when using the cluster client, just remove this node. 
* Let me configure the behavior of Lettuce of what to do when you encounter 127.0.0.1.
* Replace 127.0.0.1 with the actual IP.

**Comment by mp911de** [comment]
Thanks for bringing this up. `127.0.0.1` is a valid cluster node address when running Redis Cluster locally. Removing the entry isn't the right thing as we would compensate for Redis mis-configuration.

Lettuce provides a `SocketAddressResolver` that allows transformation of a host and port into a `SocketAddress`. We provide also a mapping variant that accepts a mapping function so you can remap the address to a different one.

**Comment by luongtrieuvy202** [comment]
I encountered the identical problem. Could you please explain how you resolved the issue ? Thank you

**Comment by sonaysevik** [comment]
I also started facing this problem today locally. Does anyone know a recent change that might cause it?

**Comment by ChanHoHan** [comment]
I faced the same issue, and this is my solution code

```java
MappingSocketAddressResolver resolver = MappingSocketAddressResolver.create(DnsResolvers.UNRESOLVED,
                hostAndPort -> {
                    HostAndPort andPort = hostAndPort;
                    if (hostAndPort != null && hostAndPort.getHostText().contains("127.0.0.1")) {
                        List<String> nodes = cluster.getNodes();
                        String[] node = nodes.get(0).split(":");
                        andPort = HostAndPort.of(node[0], Integer.parseInt(node[1]));
                    }
                    return andPort;
                }
        );
```

But I don't know why this issue happened.
