### ISSUE TITLE
Report coorrect error after received EXECABORT

### ISSUE THREAD

**Issue by bakomchik** [lettuce-io/lettuce-core#1290]
Hi folks! I faced with issue with handling EXECABORT in lettuce.
Now after receiving EXECABORT lettuce  just throws RedisCommandExecutionException with message "EXECABORT Tanscation  discarded because of previous errors"
but does not reports these *previous errrors*  
in case of MISCONF for example.
In debug logs i see errors but it would be great to append previous errors to RedisCommandExecutionException thrown after EXEC
Thanks!

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by bakomchik** [comment]
Hi @mp911de . 
Sorry forgot to provide sample:

1) You need redis configured with max memory(small value for test , 5 mb  for example)
2) run Main class Main#main from https://github.com/bakomchik/lettuce-error-reproduce/tree/master
3) Observe exception with message : EXECABORT Transaction discarded because of previous errors
4) Observe  OOM command not allowed when used memory > 'maxmemory'. in logs

**Comment by mp911de** [comment]
Thanks a lot. Command responses to commands issued at invocation time (after the connection entered `MULTI`) are not available through the synchronous API. Each queued command gets accepted with `QUEUED`. Similarly, command failures are not propagated to the caller.

Please use the asynchronous API if you need access to command failures.
