### ISSUE TITLE
Single connection has performance problem, as well as connection pool has deadlock problem.

### ISSUE THREAD

**Issue by vihunk** [lettuce-io/lettuce-core#1292]
#### Expected behavior/code

**1. Single connection(sharing mode) has performance problem**
![微信图片_20200521214234](https://user-images.githubusercontent.com/19635037/82564902-26736b80-9bac-11ea-8705-4f9312d35360.png)

When using single conncetion for redis op，the response call back( **call complete()**, just call these for **other ops**) will be happend at the netty single thread( in especial gateway works with spring redis session ). 
If the other ops maybe take a long time, and the performance will fall heavily. 

**2. Connection pool cause deadlock(maybe live lock)**
**Assumption:**
    Connection pool maxSize: 8
    Netty IO Threads: 4
**Debug:**
    When http threads build 4 redis connetions and send 4 redis commands, and 4 redis IO threads send and recv responses from redis server, and they prepare to call complete().
    Now http threads continue to recv more requests and has been requested the existing 4 connections to access redis op(these redis commands will be added into the queue of Netty).
    The next step of these callbacks(4 redis IO threads) is going to access redis op again,  they can build new 4 connections( current 4 connetions below the maxSize 8), So they build 4 requests of create connetion and wait for finished(these commands will be queued in the same queue of Netty). 
     How terrible the 4 Redis IO is blocking by themselves, because the creating connection requests must be consumed by the redis io threads.
     So deadlock(in fact is a live lock) happens... 
#### Environment

- Lettuce version(s): 5.2.2.RELEASE
- Redis version: 4.0

#### Possible Solution
We can use other thread pool to call command complete's method, and it will resove the above 2 problems at the same time.
CommandHandler.java complete method():
`command.complete();` 
will be replaced like this:
`Schedulers.parallel().schedule(()->command.complete());`

**Comment by mp911de** [comment]
Which API are you using? The asynchronous or the reactive one?

**Comment by vihunk** [comment]
reactive api， thanks.

**Comment by mp911de** [comment]
You might want to explore the ClientOption `publishOnScheduler` that uses a scheduler, specifically the `EventExecutorGroup`, for signal dispatch. The [reference documentation](https://lettuce.io/core/release/reference/index.html#client-options) contains additional information about this topic.

Regarding the locking issue, there's nothing we can do if the pool is exhausted and you try to allocate new connections. Please note that Lettuce ships with support for the blocking commons2-pool and a non-blocking `AsyncPool` implementation.

**Comment by vihunk** [comment]
I'm sorry, maybe I didn't descibe clearly.
For problem 1: I'll try later, thanks!
For problem 2: The pool wasn't exhausted, and it just can allocate new connnections(Because pool max is 8, and current is 4).
It just the 4 connnections was hold by http threads, and redis io threads(recv redis response and call complete, the complete step contains redis op again) can allocate new connnections, so there is lock by itself.

**Comment by vihunk** [comment]
add one picture for explain how problem happens.
![deadlock  with connection pool](https://user-images.githubusercontent.com/19635037/82675655-b3cfc200-9c77-11ea-9f06-35ba03c9364a.png)

**Comment by mp911de** [comment]
Do you have a pointer to the code that calls `Future.get()`? The internals of Lettuce should never call `Future.get` on a EventLoop thread as this invocation blocks the event loop from progressing.

**Comment by vihunk** [comment]
threads are blocked on get() when deadlock
 happens.

![E61B47E4-76CA-46D5-945A-DFC7B41BFFA5](https://user-images.githubusercontent.com/19635037/82860149-5378a300-9f4b-11ea-9830-05fa6d3a1b34.jpeg)
![094E54EF-7602-4ED3-9D5C-83E0AE701AD9](https://user-images.githubusercontent.com/19635037/82860167-5c697480-9f4b-11ea-82a5-1f99bb8c8d4d.jpeg)

**Comment by mp911de** [comment]
Thanks for sharing. Calling the imperative/blocking API on a EventLoop thread is wrong in the first place. As mentioned above, this way you can easily lock up your entire application. When your code runs on the EventLoop thread, please use the Reactive Spring Data Redis API.

There's nothing we can do here.

**Comment by vihunk** [comment]
Hi @mp911de, I have used the reactive Spring data Redis API, and the calling was triggered by lettuce-core. 
We are using Spring session(distributed sesion base on redis), and if has two continuous redis ops, the thread will be switch on the lettuce io thread for response and continue to run next steps, so it will cause the deadlock problem.

**Comment by mp911de** [comment]
Can you share the full stack trace?

**Comment by vihunk** [comment]
Hi @mp911de, there is the full stack trace, please help me to review this, thanks! 

[app-stack.log](https://github.com/lettuce-io/lettuce-core/files/4698738/app-stack.log)

**Comment by mp911de** [comment]
Thanks a lot. The excerpt below shows that `TestHandler` is being called on a EventLoop thread and that this class is invoking blocking Redis operations. Since the EventLoop must not be blocked, there's nothing we can do here. Instead, your code must use non-blocking API.

```
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultValueOperations.getAndSet(DefaultValueOperations.java:70)
	at com.xxxx.group.gateway.handler.TestHandler.testRedis(TestHandler.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:147)
	at org.springframework.web.reactive.result.method.InvocableHandlerMethod$$Lambda$1386/574308305.apply(Unknown Source)
```

**Comment by vihunk** [comment]
Thanks, I'm sorry. This is specify interface for deadlock. I'll recheck this
