### ISSUE TITLE
CompletableFuture get slow

### ISSUE THREAD

**Issue by summitxf** [lettuce-io/lettuce-core#1294]
## Bug Report

CompletableFuture get slow

#### Current Behavior

Got a bad performance under 50qps, pinpoint tracking as below:

|Method|StartTime|Gap(ms)|Exec(ms)|Self(ms)|Class|API|
|:-----|:--------|:-----:|:------:|:------:|:---:|:-:|
|get(Object key)|15:34:29 161|7|0|0|AbstractRedisAsyncCommands|REDIS|
|Asynchronous Invocation|15:34:32 547|3,386|89|63||ASYNC|
|complete(Object value)|15:34:32 590|43|26|26|CompletableFuture|FUTURE|
|get(long timeout, TimeUnit unit)|15:34:29 169|8|3,447|3,447|CompletableFuture|FUTURE|

#### Additional context

springboot 2.2.5
springdataredis 2.2.5
lettuce-core 5.2.2

**Comment by madisonleavo** [comment]
Hello! I'm having a little trouble following what you're measuring. Would you please provide an example? And I wonder specifically, how/where are you measuring these?

Does it matter which operation? `mset` `get` etc?

I know this isn't Spring, but something along the lines of?
```
var start = System.currentTimeMillis();
var ret = conn.async().mget(keys.toArray(new String[0])).toCompletableFuture()
  .thenApply(innerRet -> {
    logger.info("mget {} in {}", keys.size(), System.currentTimeMillis() - start);
    return innerRet;
});
ret.get();
```

**Comment by mp911de** [comment]
Dropping a table of numbers without context isn't helpul in particular. Happy to discuss your findings over a proper benchmark fixture.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
