### ISSUE TITLE
Add mTLS support

### ISSUE THREAD

**Issue by rokcarl** [lettuce-io/lettuce-core#1297]
## Feature Request

It would be great if Lettuce supported mutual TLS authentication.

The current implementation checks if the redis server has the correct SSL certificate. But any client with the access to the network and the optional redis password can access the data on the redis server. By using mTLS we'd be able to verify that the client has a certificate that has been issued by the trusted CA.

The official redis client [supports this](https://redis.io/topics/encryption), the Python redis clients [supports this](https://github.com/andymccurdy/redis-py/issues/780#issuecomment-244786179) as well, envoy [too](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#example-configuration).

The solution would allow the lettuce client to specify the client certificate key pair to use when connecting to a server that requires the client certificates.

**Comment by rokcarl** [comment]
Ah, this is probably supported by using the [`keystore`](https://lettuce.io/core/6.0.0.M1/api/io/lettuce/core/SslOptions.Builder.html#keystore-java.io.File-) functionality, right?

**Comment by mp911de** [comment]
Mutual TLS authentication works by providing a keystore with a private key. 

Here’s a test for mTLS: https://github.com/lettuce-io/lettuce-core/blob/master/src/test/java/io/lettuce/core/SslIntegrationTests.java

**Comment by rokcarl** [comment]
Great, thank you!
