### ISSUE TITLE
Provide Tracing extension point to handle RedisURI

### ISSUE THREAD

**Issue by anuraaga** [lettuce-io/lettuce-core#1312]
## Feature Request

Currently, `SocketAddress` is provided to `Tracing` to allow a span to have endpoint information. There is some information that's only available in the `RedisURI` though, the database name and user when enabling ACLs. It would be nice to provide `RedisURI` to the extension point.

#### Is your feature request related to a problem? Please describe

I am implementing an OpenTelemetry implementation of tracing, and there are some attributes we would like to add to match semantic conventions of a database but without the `RedisURI`, we can't. They aren't high priority attributes but it'd be nice.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md

#### Describe the solution you'd like

Passing both `SocketAddress` and `RedisURI` to `createEndpoint`.

#### Describe alternatives you've considered

Pass both `Endpoint` and `RedisURI` to `remoteEndpoint`. Both seem reasonable.

#### Teachability, Documentation, Adoption, Migration Strategy

Users implementing `Tracing` will be able to find the extension point.

**Comment by mp911de** [comment]
In `CommandHandler`, we do not have access to `RedisURI`. `RedisURI` is the intent to establish a connection. The database name and other properties (such as the actual hostname) may change during connect/while working with a connection.

In Redis Cluster/Sentinel arrangements, we only have a single `RediURI` while the cluster might consist of multiple nodes.

I'd suggest to subclass `InetSocketAddress` for your setup and configure a custom `SocketAddressResolver`. Your customized `InetSocketAddress` would carry the details you require for tracing. You can apply environmental detail through the Tracing SPI (`Span.remoteEndpoint`).

Let me know if you require any further details.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by anuraaga** [comment]
Apologies for the lack of feedback - the approach you suggested looks like it'll work though so will try it out, thanks!
