### ISSUE TITLE
lettuce and google cloud redis offering

### ISSUE THREAD

**Issue by thesreyas** [lettuce-io/lettuce-core#1313]
I am evaluating lettuce for my microservice that works with redis.  Microservice may be deployed in any cloud. In that context i would like to know following:

Does lettuce support connecting to google memory store?
If yes, does it support Redis clustering mode and are there any gaps?

The example listed there only mentions Jedis.
https://cloud.google.com/memorystore/docs/redis/connect-redis-instance-gce#java_1

**Comment by mp911de** [comment]
I have no knowledge about Google Memory store and I'm not familiar with it at all. Please refer to their docs.
