### ISSUE TITLE
Lettue:Cannot retrieve initial cluster partitions from initial URIs

### ISSUE THREAD

**Issue by vinaysdeveloper** [lettuce-io/lettuce-core#1321]
#### Current Behavior

We are trying to connect to AWS Elastic Cache Cluster mode enabled and KMS enabled, it is redis cache. When trying to connect to cache server we get below error 

``
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is com.lambdaworks.redis.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='clustercfg.lfrzs12h5kpj7ho.dh3efy.use1.cache.amazonaws.com', port=6379]]

Caused by: com.lambdaworks.redis.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='redis-cluster----0001-001.redis-cluster---.usw2.cache.amazonaws.com', port=6379], RedisURI [host='lredis-cluster----0001-002.redis-cluster---.usw2.cache.amazonaws.com', port=6379]]
at com.lambdaworks.redis.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:745)
at `com.lambdaworks.redis.cluster.RedisClusterClient.initializePartitions(RedisCluster`

I am currently using 4.2.2.final for lettuce and spring data redis 1.8.23, below is the code which uses cluster nodes, i tried with 
Cluster endpoint as well with no luck 

```
@Bean
      public LettuceConnectionFactory getLettuceConnectionFactory() {
            List<String> clusterNodes = Arrays.asList("redis-cluster----0001-001.redis-cluster---.usw2.cache.amazonaws.com:6379", "redis-cluster----0001-002.redis-cluster---.usw2.cache.amazonaws.com:6379");
            final LettuceConnectionFactory lettuceConnectionFactory = new LettuceConnectionFactory(new RedisClusterConfiguration(clusterNodes));
            lettuceConnectionFactory.setTimeout(10000);
            lettuceConnectionFactory.setUseSsl(true);
            lettuceConnectionFactory.setVerifyPeer(false);
            lettuceConnectionFactory.setStartTls(false);
            lettuceConnectionFactory.afterPropertiesSet();
            return lettuceConnectionFactory;
      }

```

please let me know if the code is proper to connect to aws elastic redis cache with cluster mode and KMS enabled
I cannot use Spring data redis 2.0 or higher version

**Comment by mp911de** [comment]
Please post either the full stack trace of a debug log of the connect sequence (setting `com.lambdaworks` loggers to `DEBUG`) so we can diagnose the issue.

**Comment by vinaysdeveloper** [comment]
Thanks for checking this issue , i was able to connect to Redis Cluster , the cluster was protected hence had to pass password and it worked. 

Since its AWS environment how do i handle scale up and scale down  in Spring data Redis 1.8.23 and Lettuce: 4.5.0-FINAL,
can you please provide code example for that .

I cannot use  ClusterClientOptions/LettuceClientConfiguration  due to version restriction.

Additional i get below warning , is something wrong with my code i write to cache using below code

	`` public LettuceConnectionFactory getLettuceConnectionFactory() {
          List<String> clusterNodes = Arrays.asList("clustercfg.redisclustrer.jsdfsdi.use1.cache.amazonaws.com:6379");
          RedisClusterConfiguration redisConfig = new RedisClusterConfiguration(clusterNodes);
          final LettuceConnectionFactory lettuceConnectionFactory = new LettuceConnectionFactory(new RedisClusterConfiguration(clusterNodes));
          lettuceConnectionFactory.setPassword("1234567890123456");
          lettuceConnectionFactory.afterPropertiesSet();
          return lettuceConnectionFactory;
    }

    public RedisTemplate<String, Object> redisTemplate() {
          final RedisTemplate<String, Object> redisTemplate = new RedisTemplate<String, Object>();
          redisTemplate.setKeySerializer(new StringRedisSerializer());                                           
          redisTemplate.setValueSerializer(new GenericJackson2JsonRedisSerializer());
          redisTemplate.setConnectionFactory(getLettuceConnectionFactory());
          return redisTemplate;
    }``

`HashOperations hashOperations =redisTemplate.opsForHash();
		hashOperations.put("key","id" , "cacheData");`

**Comment by mp911de** [comment]
Thanks for the details. Please ask questions on stackoverflow.

**Comment by umang92** [comment]
Is your cluster in-transit encryption enabled?

**Comment by vinaysdeveloper** [comment]
Yes, in transit encryption is enabled.

**Comment by barbarosalp** [comment]
@mp911de Why does this need to be called? 
`lettuceConnectionFactory.afterPropertiesSet();`
