### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by kengan** [lettuce-io/lettuce-core#1322]
I use spring-data-redis with lettuce to connect redis 3.2.6
I often get the exception "Connection reset by peer"
I capture the packet on the server where my application on and on the server where redis on.
I found that when the tcp-keepalive setting took affect, the FIN  package is lost. Please the following image.So my application can not know the connection is close.
Can you tell me how to solve this problem with Lettuce. Thank you.
 
![image](https://user-images.githubusercontent.com/18627678/85756820-ba9f9800-b741-11ea-8919-ce9611881e48.png)

**Comment by mp911de** [comment]
Please check that your Redis server does not disconnect idle clients and does not disconnect clients when a max client limit is met. There's nothing we can do as TCP business is handled by the kernel/Java I/O system.
