### ISSUE TITLE
Problems with Azure Redis Cluster and Lettuce

### ISSUE THREAD

**Issue by atikatantiya** [lettuce-io/lettuce-core#1328]
Hi, I'm using Spring Boot Starter Parent version 1.5.12, Spring Data Redis version 1.8.11 and Lettuce version 4.2.2. I'm trying to connect to an AWS Redis Cache Cluster through my spring boot application using the Lettuce client. 
However when multiple instances of my app (deployed on the cloud) try to connect to the redis remote cache, it shows up the following error:
2020-07-02T11:04:24.94+0530 [APP/PROC/WEB/1] ERR java.lang.IllegalArgumentException: Connection to xxx.xxx.xxx.cache.amazonaws.com:1171 not allowed. This connection point is not known in the cluster view.

I saw previous issues raised due to this same error, however using the validateClusterNodeMembership(false) method requires me to use LettuceClientConfiguration class which is not available in Spring Data 1.8.11.

My code currently looks like this:

        @Bean
        public RedisConnectionFactory redisConnectionFactory() {		
            RedisClusterConfiguration clusterConfiguration = new RedisClusterConfiguration(Arrays.asList(redisHost + ":" + redisPort));
   
            LettuceConnectionFactory factory = new LettuceConnectionFactory(clusterConfiguration);
            factory.setPassword(redisPassword);
            factory.setUseSsl(true);
        
            ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder().closeStaleConnections(true)
                .enableAllAdaptiveRefreshTriggers().build();
        
            ClusterClientOptions clusterClientOptions = ClusterClientOptions.builder().autoReconnect(true)
                .topologyRefreshOptions(topologyRefreshOptions).validateClusterNodeMembership(false)
                .build();
        
         
	        return factory;	 
	  }

    @SuppressWarnings("rawtypes")
	@Bean
    public RedisTemplate redisTemplate() {
        RedisTemplate template = new RedisTemplate<>();
        template.setConnectionFactory(redisConnectionFactory());
        return template;
    }

I don't know how to connect the ClusterClientOptions to my LettuceConnectionFactory without using the LettuceClientConfiguration class. Kindly help me as to what methods I can use to set the validateClusterNodeMembership to false.

**Comment by mp911de** [comment]
Spring Data 1.x and Lettuce 4.x are no longer maintained. Spring Data Redis 1.8 doesn’t allow for configuring `ClientOptions`. Please upgrade to a newer version that allows configuring `ClientOptions` though `LettuceClientConfiguration`.

**Comment by atikatantiya** [comment]
I am using this dependency for lettuce because without this my app gives an AbstractRedisClient not found error.

<dependency>
    <groupId>biz.paluch.redis</groupId>
    <artifactId>lettuce</artifactId>
    <version>4.5.0.Final</version>
</dependency>
