### ISSUE TITLE
RedisAdvancedClusterAsyncCommandsImpl scriptKill is incorrectly calling scriptFlush

### ISSUE THREAD

**Issue by azhukayak** [lettuce-io/lettuce-core#1340]
While reading some of the implementation just notice that the scriptKill method is actually doing a scriptFlush command instead.  That's probably not the intention?

https://github.com/lettuce-io/lettuce-core/blob/dbab9668c379f7931b1e2d50dbb232d4823abea9/src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java#L418

**Comment by dengliming** [comment]
You were right. I think it's a bug. fixed [https://github.com/lettuce-io/lettuce-core/pull/1341](https://github.com/lettuce-io/lettuce-core/pull/1341)

**Comment by mp911de** [comment]
That's fixed now. Thanks for the report.
