### ISSUE TITLE
AWS Elasticache Clustered mode Redis Auto Failover putting the client in bad state

### ISSUE THREAD

**Issue by umang92** [lettuce-io/lettuce-core#1344]
## Bug Report

I checked several issues. This one seems most similar. But I did not any suggested fixes/ workarounds.
https://github.com/lettuce-io/lettuce-core/issues/984

#### Current Behavior

I am using 
1. Lettuce-core 5.3.0.RELEASE. 
2. AWS Elasticache clustered mode Redis, 12 shards. 1 Replica node for each shard.

I am testing the auto failover behavior by failing one of the masters and verifying if the system is able to recover. There are couple of issues that I see:

1. Even after 4-5 minutes of the failover operation, I see RedisCommandTimeoutException in the logs.
2. The client never really recovers from the failover, and all the threads just get hung on the Redis calls. I am using following redis commands:
a. rpush
b. lpop
c. pexpire

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

         //startup code
         RedisURI.Builder builder = RedisURI.Builder.redis(redisDetails.getHost(), redisDetails.getPort());

           logger.info("Enable SSL");
            builder=builder.withSsl(Boolean.TRUE);
            builder=builder.withPassword(properties.getRedisPassword());
       

        RedisURI redisURI = builder.withTimeout(Duration.ofSeconds(5)).build();
        redisClusterClient = RedisClusterClient.create(redisURI);
        if (redisClusterClient == null) {
            logger.info("Could not create Redis connection.");
            throw new Exception("Could not create redis connection.");
        } else
            logger.info("Redis connection created successfully.");

        ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enablePeriodicRefresh(Duration.ofSeconds(properties.getRedisTopologyRefreshInterval()))
                .build();
        // periodic refresh interval is set to 15 seconds

        redisClusterClient.setOptions(ClusterClientOptions.builder()
                .topologyRefreshOptions(topologyRefreshOptions)
                .build());
        GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
        poolConfig.setMaxTotal(properties.getMaxRedisConnections());
        poolConfig.setMaxIdle(properties.getMaxRedisConnections());
        poolConfig.setMinIdle(properties.getMinRedisConnections());

        GenericObjectPool<StatefulRedisClusterConnection<String, byte[]>> pool = ConnectionPoolSupport
                .createGenericObjectPool(() -> redisClusterClient.connect(new StreamRedisCodec()), poolConfig);

       //per request code
       try {
            StatefulRedisClusterConnection<String, byte[]> connection =  pool.borrowObject();
            connection.sync().rpush(......)
          } catch(Exception ex){
            throw new IOException(ex);
          }

<details>
<summary>Input Code</summary>
 connection.sync().rpush(......) calls never return in a failover scenario. 
Also, strange thing is performing failover of only one shard out of 12 shards, is affecting all the requests. None of the requests during the failover seems to be successful. What am I doing wrong?

```java
// your code here;
```

</details>

#### Expected behavior/code

Expected behavior is that after the 1 or 2 periodic refreshes(once the failover is complete, which usually completes in 30 seconds), the client should come back to normal and all the requests must succeed as usual.
 There should not be a need to manually restart the client code.
#### Environment

- Lettuce version(s): 5.3.0.RELEASE
- Redis version: AWS elasticache Redis 5.0.6

**Comment by mp911de** [comment]
> Even after 4-5 minutes of the failover operation, I see RedisCommandTimeoutException in the logs.

Please capture the topology (`Partitions`) to investigate why commands are routed to nodes that aren't responding.

> failover of only one shard out of 12 shards, is affecting all the requests.

Lettuce routes commands according to their key. Commands with keys that should be routed to a different shard should not be affected. Please check the `Partitions` object regarding the routing table.

**Comment by SushmaReddyLoka** [comment]
In which case, can a client connect to a redis server and would not be able to get response for command ? What does not node responding means ? 
cc @mp911de

**Comment by mp911de** [comment]
Either if Redis is overloaded or if the EventLoop is blocked and Lettuce cannot process command responses.

Closing this ticket since this ticket doesn't look like we can do here something useful.
