### ISSUE TITLE
ReadFrom Feature

### ISSUE THREAD

**Issue by saturnLong** [lettuce-io/lettuce-core#1352]
## Feature Request
my redis have two far away computer room，and  topology is：
room1 ： master, slave1
room2:  slave2

how the room2  program exclude slave1(redis).  can RedisNodeDescription add the ping info message ，then i can use ping info 
 to exclude the slave nodes which The delay  is large .

**Comment by mp911de** [comment]
I have trouble understanding what you are actually asking for. If you want to exclude particular nodes from a `ReadFrom` strategy, then implement such a feature yourself by subclassing `ReadFrom` and implementing `select(…)`.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
