### ISSUE TITLE
Feature request: add a cluster-capable version of `flushallAsync`

### ISSUE THREAD

**Issue by jchambers** [lettuce-io/lettuce-core#1359]
`RedisAdvancedClusterCommands` has an implementation of [`flushall`](https://lettuce.io/core/6.0.0.M1/api/io/lettuce/core/cluster/api/sync/RedisAdvancedClusterCommands.html#flushall--) that will:

> Remove all keys from all databases on all cluster masters with pipelining.

It does _not_, however, have a matching implementation of [`flushallAsync`](https://lettuce.io/core/6.0.0.M1/api/io/lettuce/core/api/sync/RedisServerCommands.html#flushallAsync--), which instead lives in the world of [single-node commands](https://lettuce.io/core/6.0.0.M1/api/io/lettuce/core/api/sync/RedisServerCommands.html). That can lead to some surprising behavior:

```java
connection.sync().flushall(); // Clears the whole cluster, but blocks
connection.sync().flushallAsync(); // Clears just one shard of the cluster asynchronously
```

To be fair, there is a viable workaround:

```java
connection.sync().masters().commands().flushallAsync(); // Clears the whole cluster asynchronously
```

…but it's very easy to fall into the trap of _thinking_ you've cleared your whole cluster even if only one shard was cleared. I'm writing to suggest adding a cluster-capable version of `flushallAsync()` to `RedisAdvancedClusterCommands` and its async/reactive cousins.

**Comment by mp911de** [comment]
Great proposal. Do you want to submit a pull request?

**Comment by jchambers** [comment]
Sure. I may need some help understanding some plumbing, but I'll open a draft and we can work through the specifics there.
