### ISSUE TITLE
BoundedAsyncPool object is ready to be manipulated with even though a connection is not created yet

### ISSUE THREAD

**Issue by little-fish** [lettuce-io/lettuce-core#1363]
#### Is your feature request related to a problem? Please describe

`BoundedAsyncPool` is ready to be manipulated with even though there is no connection available yet. This causes errors like:

```java
java.util.concurrent.CompletionException: java.util.NoSuchElementException: Pool exhausted
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:670)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at io.lettuce.core.support.AsyncConnectionPoolSupport$1.acquire(AsyncConnectionPoolSupport.java:121)
```

#### Describe the solution you'd like

Either wait for a connection (`min-idle`) to be ready upon object pool creation or provide a way to check, whether there are any available connections.

---

Documentation of the `BoundedAsyncPool` says:
```
This object pool allows pre-warming with idle objects upon construction.
```
I would probably rephrase this sentence to make it clear that it actually _requests_ the idle objects to be created only.

#### Describe alternatives you've considered

Currently I have to _sleep_ for a fixed amount of ms to work-around this behavior. Which is pretty ugly.

#### Question
What is the proper way to `work-around` this behavior?

Thank you.

**Comment by mp911de** [comment]
Thanks for raising the issue. It's indeed an issue that creation completion cannot be awaited. I think we should introduce a new factory method (`BoundedAsyncPool.create(…)`) that returns a `CompletableFuture` so pre-warming can be properly synchronized. We also need to reflect this behavior in the documentation.

**Comment by mp911de** [comment]
That's in place now.

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/91426617-55763900-e88f-11ea-814c-6d71fa68b370.png)
Thanks, I will try to update to the new version.
