### ISSUE TITLE
mTLS/TLS Issues

### ISSUE THREAD

**Issue by etherrien** [lettuce-io/lettuce-core#1373]
## Bug Report

Currently I am running Redis 6 with ACL and mTLS with a C# client just fine. I am trying to update our Java side to also use ACL and mTLS but have been running into issues. I am primarily focused on mTLS at the moment and have not been getting anywhere with it. This could be user fault in these that I have not used Java for 5-6 years before attempting to do this, so please advise. 

Trace:
```

#### Current Behavior

<!-- A clear and concise description of the behavior.-->

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment]
Check out the documentation at https://lettuce.io/core/release/reference/index.html#ssl. You might want to look into `SslOptions` for further configuration options. Client certificate authentication is enabled once the server-side requests a client certificate. 

Please note that we use GitHub to track bug reports and feature requests. Please use StackOverflow or our [Gitter](https://gitter.im/lettuce-io/Lobby) channel for questions.

**Comment by etherrien** [comment]
It appears the issue might lay in the fact the address gets lost somewhere along the way, found after debug logging was enabled. Could this actually be a bug?
See below:
```
(vert.x-worker-thread-1) URI: rediss://localhost:6379
2020-07-30 12:38:40,518 DEBUG [io.let.cor.AbstractRedisClient] [{}] (vert.x-worker-thread-1) Connecting to Redis at {}
2020-07-30 12:38:41,210 DEBUG [io.let.cor.AbstractRedisClient] [{}] (lettuce-nioEventLoop-4-1) Connecting to Redis at {}, initialization: {}
```

**Comment by etherrien** [comment]
# # #

**Comment by mp911de** [comment]
The braces indicate an issue with the underlying logging framework. That doesn't happen with logback or log4j2.
