### ISSUE TITLE
Generate an OSGi-enabled MANIFEST.MF

### ISSUE THREAD

**Issue by dmandalidis** [lettuce-io/lettuce-core#1389]
#### Is your feature request related to a problem? Please describe

We have an issue deploying our application which depends on `lettuce-core` is an OSGi container (e.g. Payara). Since `lettuce-core` manifest file doesn't come with bundle information the only way (AFAIK) is to manually shade the `lettuce-core` jar and modify our libraries to avoid importing lettuce package in their respective manifest file.

#### Describe the solution you'd like

We think it would be beneficial to have `maven-bundle-plugin` to generate the necessary information on-build and have the `maven-jar-plugin` use that information instead of generating a manifest on its own. That would be a good start to unveil other potential OSGi-related issues down the road (such as problems when and if using classloaders etc.) but we could follow this up.
The proposed `pom.xml` amendment is not expected to cause any regressions since the manifest file is only enhanced with OSGi info which are irrelevant in non-OSGi environments.

**Comment by mp911de** [comment]
Thanks for bringing this up. We decided earlier that we don't want to maintain OSGi metadata as we don't have the know-how, the demand and capacity to maintain it. Worse, we don't even know when we break something.
