### ISSUE TITLE
How to detect that cluster topology is not refreshed by client

### ISSUE THREAD

**Issue by SushmaReddyLoka** [lettuce-io/lettuce-core#1393]
https://github.com/lettuce-io/lettuce-core/issues/672#issuecomment-363482104, as suggested here , having my cluster bound to change, how do i know if there is a change in cluster topology, and client is not up to date with it. Any suggestions ?

**Comment by SushmaReddyLoka** [comment]
Any specific type of exceptions I can track and determine this state .

**Comment by SushmaReddyLoka** [comment]
Can some one respond to this ?

**Comment by mp911de** [comment]
Lettuce emits a `ClusterTopologyChangedEvent` through its [Event mechanism](https://github.com/lettuce-io/lettuce-core/wiki/Connection-Events). 

Much more difficult to know is when Lettuce should have refreshed the topology but it didn't do it (yet). The only way to know this is polling for the topology.
