### ISSUE TITLE
LPOS command sends FIRST instead of RANK

### ISSUE THREAD

**Issue by christophstrobl** [lettuce-io/lettuce-core#1410]
`LPosArgs` uses `FIRST` instead of `RANK` causing a `syntax error`

```bash
"RPUSH" "mylist" "a" "b" "c" "1" "2" "3" "c" "c"
"LPOS" "mylist" "c" "COUNT" "2" "FIRST" "-1"
> ERR syntax error
"LPOS" "mylist" "c" "COUNT" "2" "RANK" "-1"
> [7,6]
```

Please rename `LPosArgs.first` to `LPosArgs.rank` and send the `RANK` option if present.

Commit https://github.com/redis/redis/commit/a5a3a7bbc61203398ecc1d5b52c76214f5672776 changed the option name.

**Comment by mp911de** [comment]
That's fixed now.
