### ISSUE TITLE
Partitions#partitions ConcurrentModificationException

### ISSUE THREAD

**Issue by brucelwl** [lettuce-io/lettuce-core#1421]
``io.lettuce.core.cluster.models.partitions.Partitions#partitions`` Non thread safe,

When topology refresh is on,

invoke ``org.springframework.data.redis.connection.RedisClusterCommands#clusterGetNodes``

An ``ConcurrentModificationException`` may be triggered

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

Adding a stack trace it the first step here.

**Comment by mp911de** [comment]
`Partitions` is mutable by design. Iterating over `Partitions` by obtaining `iterator()` uses the read-only view that remains stable after obtaining the iterator. `getPartitons()` requires external synchronization, see Javadoc of the method.
