### ISSUE TITLE
Explicit AWS and AZURE compatibility on README

### ISSUE THREAD

**Issue by raphaelauv** [lettuce-io/lettuce-core#1425]
Lettuce-core is compatible with AWS and AZURE in cluster mode

It's present in the documentation and on the github TAGS of the repo but not on the main README of the project.

Explicit compatibility on the readme would be nice 

Thank you.

**Comment by mp911de** [comment]
That's in place now.

**Comment by raphaelauv** [comment]
Nice ! Thanks
