### ISSUE TITLE
Suggestion: clarify documentation about `multi` in reactive/async environments.

### ISSUE THREAD

**Issue by max-grigoriev** [lettuce-io/lettuce-core#1427]
Right now it's not clear that `multi` command requires the dedicated connection. And it means that the right usage is almost impossible with async/reactive commands as they usually don't use a connection pool.  They just don't need it. I think such note should be added to [the documentation](https://lettuce.io/core/release/reference/#transactions-using-the-asynchronous-api).

**Comment by mp911de** [comment]
FWIW, the docs (https://github.com/lettuce-io/lettuce-core/wiki) start with connection sharing limits. We should add the note to the transaction chapter (https://github.com/lettuce-io/lettuce-core/wiki/Transactions).

**Comment by mp911de** [comment]
That's done now.
