### ISSUE TITLE
Provide a Coroutine variant of ScanStream/ScanIterator

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#1435]
We should expose a more user-friendly interface to allow using `[H|S|Z]SCAN` commands through Coroutines following the design of `ScanStream`.

**Comment by SokoMishaLov** [comment]
Should it be a breaking replacement for existing "cursor" API or just a bunch of extensions for `...Commands`?

**Comment by mp911de** [comment]
I think a Kotlin class (or extension) should be fine. Maybe even an extension providing static extension functions accepting e.g. `RedisHashSuspendableCommands`, `RedisKeySuspendableCommands`, … returning `Flow` would be fine, too.
