### ISSUE TITLE
Rename StatefulRedisConnection.suspendable() to .coroutines() and command interfaces accordingly

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#1436]
@SokoMishaLov raised the point to adjust our Kotlin Coroutine support naming from `…suspendable…` to `…coroutine…` since a few methods aren't Coroutines (some are plain imperative such as `isOpen():boolean` or return `Flow`).

We have two variants for naming:

```kotlin
// variant 1: suspendable
val api: RedisClusterSuspendableCommands<String, String> = connection.suspendable()
// variant 2: coroutine
val api: RedisClusterCoroutineCommands<String, String> = connection.coroutine()
```

See also #1422.

**Comment by mp911de** [comment]
Asking on the Kotlin Slack yielded an answer to stick with `suspendable`.

**Comment by mp911de** [comment]
Note: We should sort out this issue for 6.0 GA which targets 02.10.2020

**Comment by SokoMishaLov** [comment]
So naming stays as is, right?

**Comment by mp911de** [comment]
Not sure yet. I wanted to get other opinions before finally deciding what to do. I also wanted to ask the Spring team as they have a good view on naming.

**Comment by SokoMishaLov** [comment]
Yeah, sure. 
The only thing I'm worried about is that the "root" package name for the API should be equal to the command interface "subnames".
For now, it is a divergence - while the package named 'coroutines' commands contain a `Suspendable` in its name.

**Comment by mp911de** [comment]
According to further feedback, going with `Coroutines` instead of `Suspendable` seems the preferred way to go. I'm going to change it that way.

**Comment by sokomishalov** [comment]
Okay, great!
And at least the package name would stay the same
