### ISSUE TITLE
Introduce extended Keep-Alive options

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#1437]
## Feature Request

We should support extended Keep-Alive configuration (enabled, idle, interval, count) for more fine-grained control of keep-alive.

#### Is your feature request related to a problem? Please describe

Detection of dead peers, see #1428.

#### Describe the solution you'd like

Applying Keep-Alive channel options automatically.

#### Describe alternatives you've considered

Manual configuration, see https://github.com/lettuce-io/lettuce-core/issues/1428#issuecomment-699992158 and https://github.com/lettuce-io/lettuce-core/issues/1428#issuecomment-700518527.

**Comment by mp911de** [comment]
`ExtendedSocketOptions.TCP_KEEPIDLE` was introduced with Java 11.

**Comment by yangbodong22011** [comment]
@mp911de hello, I noticed `DEFAULT_INTERVAL = 1`, code see [here](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/SocketOptions.java#L283).

But according to Linux kernel [default parameter](https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html), it should be 75:
```
net.ipv4.tcp_keepalive_time=7200
net.ipv4.tcp_keepalive_intvl=75
net.ipv4.tcp_keepalive_probes=9
```
Not sure if it is reasonable to discuss this issue under the closed issue, if need to open a new issue, let me know.

**Comment by mp911de** [comment]
I'm not sure about the defaults. These seem to be different across platforms. It think it's fine to update the interval to 75. Feel free to submit a pull request.

**Comment by yangbodong22011** [comment]
thanks, i will submit a PR.
