### ISSUE TITLE
Add  acquire(timeout:Duration) for AsyncPool

### ISSUE THREAD

**Issue by hepin1989** [lettuce-io/lettuce-core#1457]
## Feature Request
alias with :
io.lettuce.core.support.AsyncPool#acquire

**Comment by mp911de** [comment]
Thanks for reporting the ticket. A timeout would only apply locally to the acquisition. It would also require a worker/thread to monitor the future until it is completed. We don't have any active threading infrastructure in `BoundedAsyncPool` and we do not want to introduce such. That being said, you're better off with implementing a wrapper around `BoundedAsyncPool` and perform the cancellation yourself.
