### ISSUE TITLE
Queue BoundedPoolConfig.acquire() calls

### ISSUE THREAD

**Issue by hepin1989** [lettuce-io/lettuce-core#1459]
`BoundedPoolConfig` should provide a default timeout config for the user to config the default Timeout of acquiring instead of an immediately `NoSuchElementException`

**Comment by hepin1989** [comment]
refs: https://github.com/lettuce-io/lettuce-core/issues/1457

**Comment by mp911de** [comment]
We're not queueing pending requests and fail fast right now. While we don't intend to add a timeout, it would be possible to queue calls to acquire and clean these up upon cancel or when adding/returning connections to the pool.

**Comment by mp911de** [comment]
The asynchronous pool provides minimal functionality for a fully asynchronous arrangement. For more sophisticated asynchronous pools, please use appropriate pool implementations, such as [Reactor Pool](https://github.com/reactor/reactor-pool).
