### ISSUE TITLE
LettuceStrings does not handle -nan which is returned by FT.INFO in redisearch

### ISSUE THREAD

**Issue by krm1312** [lettuce-io/lettuce-core#1482]
Opened in LettuceSearch project here https://github.com/RediSearch/lettusearch/issues/33, but, fix will need to be made in lettuce-core and then they can delete their copy (which has no other changes as far I can tell).

FT.INFO info command can/does return "-nan" for at least one double (avarage_cycle_time_ms).  This causes a NumberFormatException.

```
44)  1) "bytes_collected"
     2) "0"
     3) "total_ms_run"
     4) "0"
     5) "total_cycles"
     6) "0"
     7) "avarage_cycle_time_ms"
     8) "-nan"
     9) "last_run_time_ms"
    10) "0"
    11) "gc_numeric_trees_missed"
    12) "0"
    13) "gc_blocks_denied"
    14) "0"
```

That project appears to have patched (and copied!) LettuceStrings to address this but that is not a workable solution since it relies on classpath ordering among other reasons.

PR shortly.

**Comment by dengliming** [comment]
Closed by #1483 and Thanks to @krm1312
