### ISSUE TITLE
NestedMultiOutput does not implement set(double)

### ISSUE THREAD

**Issue by jruaux** [lettuce-io/lettuce-core#1484]
#### Current Behavior

`io.lettuce.core.output.NestedMultiOutput` does not implement `CommandOutput.set(double number)` 

#### Environment

- Lettuce 6.0.0.RELEASE
- RediSearch v2.0

#### Possible Solution

PR: #1485

**Comment by mp911de** [comment]
Care to provide a bit context where that is needed?

**Comment by jruaux** [comment]
RediSearch [FT.INFO](https://oss.redislabs.com/redisearch/Commands/#ftinfo) command returns doubles as part of its array response and it started to break with Lettuce 6.0.0.RELEASE

**Comment by mp911de** [comment]
Thank you. Then probably it's not a bug, but rather enhancement. In any case, happy to include that change.

**Comment by dengliming** [comment]
@jruaux Thanks.
