### ISSUE TITLE
Multi Tenancy support

### ISSUE THREAD

**Issue by itzikiusa** [lettuce-io/lettuce-core#1496]
## Feature Request

Hi, i'm trying to use lettuce reactive with multi tenant application, after few calls requests start to get stuck
when using single redis endpoint all works perfectly

#### Is your feature request related to a problem? Please describe

yes, i need to use non reactive client for reactive application

#### Describe the solution you'd like

add support to multiple reds connections in single redis client configuration

#### Describe alternatives you've considered

using async client instead, it works

#### Teachability, Documentation, Adoption, Migration Strategy

no additional notes

**Comment by mp911de** [comment]
There's no such concept in Lettuce and we don't plan to provide any multi-tenancy support. The only thing that would work in that regard is splitting multiple tenants onto multiple databases.
