### ISSUE TITLE
Extend CommandDetailParser to include ACL details

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#1503]
We should pick up ACL details if available through `CommandDetailParser`

**Comment by sokomishalov** [comment]
I am not clear with this a bit - how exactly we should pick up ACL details and how it is related to command details?

**Comment by mp911de** [comment]
The output of `COMMAND` has changed between Redis 5 and 6. In Redis 6.


Redis 5:
```
127.0.0.1:6379> command info set
1) 1) "set"
   2) (integer) -3
   3) 1) write
      2) denyoom
   4) (integer) 1
   5) (integer) 1
   6) (integer) 1
```

Redis 6 (element 7 was added): 
```
127.0.0.1:6379> command info set
1) 1) "set"
   2) (integer) -3
   3) 1) write
      2) denyoom
   4) (integer) 1
   5) (integer) 1
   6) (integer) 1
   7) 1) @write
      2) @string
      3) @slow
```

**Comment by sokomishalov** [comment]
Ops, haven't noticed this change.
Thanks, I got it now. 
Related PR: https://github.com/lettuce-io/lettuce-core/pull/1539
