### ISSUE TITLE
Implement bloom filters

### ISSUE THREAD

**Issue by heneyin** [lettuce-io/lettuce-core#1514]

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to implement the feature, please spend some time describing it.

**Comment by mp911de** [comment]
Closing this ticket since as we can't do anything here. Feel free to provide more details so we can reopen this ticket if necessary.

**Comment by jianwenl** [comment]
@[mp911de](https://github.com/mp911de) Does lettuce support bloom filter like as in hyperloglog: https://lettuce.io/lettuce-4/4.5.0.Final/api/com/lambdaworks/redis/api/sync/RedisHLLCommands.html ? Thanks!
