### ISSUE TITLE
Messages read from stream not being passed to application

### ISSUE THREAD

**Issue by peterspikings** [lettuce-io/lettuce-core#1515]
#### Current Behavior

RedisLabs advised me to raise this.

When messages are read from a stream consumer group using XREADGROUP intermittently (when under load) messages are being read by Lettuce but not passed to the application (Spring Boot using a ReactiveRedisTemplate). The messages concerned then end up on the pending entries list permanently as the application does not acknowledge.

In the below you can see an example of a problem message with an ID of 1605114758691-0 being received followed by application logging showing other messages being received. The below Lettuce log message mentioning that ID is the only time that ID appears in the log and the message is left in the PEL. I'll include the code receiving the messages from the template. The problem seems to occur in short bursts with multiple messages being affected that arrive at similar times.

<details>
<summary>Log output with io.lettuce set to trace</summary>

```text
io.lettuce.core.protocol.RedisStateMachine Decoded LatencyMeteredCommand [type=XREADGROUP, output=StreamReadOutput [output=[], error='null'], commandType=io.lettuce.core.RedisPublisher$SubscriptionCommand], empty stack: false
io.lettuce.core.protocol.CommandHandler [channel=0x5a5fa311, /10.0.3.78:45020 -> redis/10.0.3.7:6379, chid=0x1d02] Buffer: G>
*2
$15
1605114758180-0
*2
$7
payload
$31
<SF_MSG>FHSF2739171228</SF_MSG>
*2
$15
1605114758182-0
*2
$7
payload
$31
<SF_MSG>Y1SF617C171227</SF_MSG>

..... SNIP .....

*2
$15
1605114758684-0
*2
$7
payload
$39
<CA_MSG>VCCA053805322B87171229</CA_MSG>
*2
$15
1605114758691-0
*2
$7
payload
$31
<SF_MSG>X0SF405C171229</SF_MSG>
*2
$15
1605114758699-0
*2
$7
payload
$31
<SF_MSG>MPSF69F8171229</SF_MSG>
*2
$15
1605114758700-0
*2
$7
payload
$39
<CA_MSG>DYCAB30553321S52171229</CA_MSG>
*2
$15
1605114758704-0
*2
$7
payload
$35
<CC_MSG>ZGCCGDXT1P51171229</CC_MSG>
*2
$15
1605114758706-0
*2
$7
payload
$39
<CA_MSG>Q1CA042004182W43171229</CA_MSG>
*2
$15
1605114758709-0
*2
$7
payload
$31
<SF_MSG>A2SF1A18171229</SF_MSG>
```
immediately followed by (same thread) to show the application is receiving some messages:

```
reactor.Flux.Lift.1 onNext(ObjectBackedRecord{recordId=1605114757650-0, value=<CA_MSG>MECA007400705H60171226</CA_MSG>})
reactor.Flux.Lift.1 onNext(ObjectBackedRecord{recordId=1605114757616-0, value=<SF_MSG>X0SF53EB171226</SF_MSG>})
reactor.Flux.Lift.1 onNext(ObjectBackedRecord{recordId=1605114757577-0, value=<CA_MSG>DRCA024902554E24171226</CA_MSG>})
reactor.Flux.Lift.1 onNext(ObjectBackedRecord{recordId=1605114757538-0, value=<SF_MSG>DYSF4F00171226</SF_MSG>})
reactor.Flux.Lift.1 onNext(ObjectBackedRecord{recordId=1605114757513-0, value=<SF_MSG>D4SF2C0D171226</SF_MSG>})

.... etc
```
</details>

#### Receiving code

Here's the code that reads from the template (log() added temporarily). The ReactiveRedisConnectionFactory is setup by Spring Boot without any special config, the poll timeout is 1000ms.

<details>
<summary>Receiving Code</summary>

```java
    private Publisher<Message<ObjectRecord<String, String>>> createTrainDescriberUpdatesPublisher()
    {
        return createPublisher(redisProperties.getTrainDescriberUpdates())
                .log()
                .map(objectRecord -> MessageBuilder.withPayload(objectRecord).build());
    }

    private Flux<ObjectRecord<String, String>> createPublisher(final StreamProperties streamProperties)
    {
        return StreamReceiver.create(reactiveRedisConnectionFactory, StreamReceiver.StreamReceiverOptions.builder()
                .objectMapper(new TypedJsonHashMapper(String.class))
                .targetType(String.class)
                .pollTimeout(redisProperties.getPollTimeoutInMillis())
                .build())
                .receive(createConsumer(redisProperties.getTrainDescriberUpdates()),
                         createStreamOffset(redisProperties.getTrainDescriberUpdates()))
                .doOnError(error -> LOG.error("Error reading message", error))
                .onErrorResume(RedisExceptionHelper::isNoGroupError,
                        (Throwable throwable) -> logErrorAndCreateConsumerGroup(throwable, streamProperties));
    }
```

</details>

#### Expected behavior/code

All messages to be received by application

#### Environment

- Lettuce version(s): [e.g. 5.3.4.RELEASE]
- Redis version: [e.g. 6.0.9]

#### Additional context

I appreciate this is probably not enough information to diagnose, let me know if there's anything else I can provide.

**Comment by mp911de** [comment]
Can you reproduce the issue with using Lettuce only? We need to sort out first, whether it's a Lettuce or a Spring Data issue.

**Comment by peterspikings** [comment]
Hi,

Thanks for that, this was verified as a Spring Data issue relating to StreamReceiver, when using Lettuce directly the problem went away.

Thanks!

**Comment by mp911de** [comment]
Can you file the same issue at https://jira.spring.io/browse/DATAREDIS as that's the issue tracker for Spring Data Redis?
