### ISSUE TITLE
Consider reinstating master-replica wording

### ISSUE THREAD

**Issue by perlun** [lettuce-io/lettuce-core#1518]
(Follow-up to https://github.com/lettuce-io/lettuce-core/issues/1308#issuecomment-726705530)

Very late to the party, but I happened to see the `UPSTREAM`-terminology being used now while looking at the Lettuce Wiki for Lettuce 6. I'm not so sure this deprecation fully makes sense @mp911de. Lettuce is a Redis driver and AFAIK, Redis uses the "master-replication" terminology, as in https://redis.io/topics/replication. Note how that page quite elegantly avoids using the word "slave", which I think is the more potentially offensive language.

"Upstream", AFAIK, is not a word that is being actively used in Redis terminology (please correct me if I'm wrong!), so us using it feels like it does more harm than good.

Some more reading on the subject:

- Upstream Redis issue, discussing the move from master-slave terminology: https://github.com/redis/redis/issues/5335
-  @antirez blog post on the subject (September 2018): http://antirez.com/news/122

----

**TL;DR**: As far as I understand it, Redis uses the "master-replication" terminology. I think we are doing ourselves and the community harm if we deviate from this terminology, it just confusing. If you think this terminology is wrong/bad, I think we should try to get Redis to stop using it as well. 

I personally find "master-replica" a good compromise between the "very progressive" and "very traditionalist" viewpoints. It's a balance to be had, and I think @antirez did a good job in https://github.com/redis/redis/issues/5335.

**Comment by mp911de** [comment]
That's in place now, also in 6.0.x.

**Comment by perlun** [comment]
> That's in place now, also in 6.0.x.

Greatly appreciated @mp911de, thanks for listening. :bow:
