### ISSUE TITLE
Whether a heartbeat request is provided in cluster mode

### ISSUE THREAD

**Issue by house0128** [lettuce-io/lettuce-core#1521]
Environment：
Lettuce version(s): Lettuce 5.1.7.RELEASE
spring-date-redis version：2.1.9.RELEASE

We currently use the cluster mode of Redis, and the server sets config set Timeout 60.
The log will output Reconnection information continuously

2020-11-16 08:56:06.205[][INFO][lettuce-eventExecutorLoop-1-2][io.lettuce.core.protocol.ConnectionWatchdog:106]Reconnecting, last destination was /xxx.xxx.xxx.xxx:6379

These are all IP addresses of slave nodes
Are there any heartbeat mechanisms available to avoid reconnection?

**Comment by mp911de** [comment]
You can disable auto-reconnect, check out https://lettuce.io/core/release/reference/#client-options. Other than that, there's no regular heartbeat that can be configured and we don't plan to add one.

**Comment by house0128** [comment]
Ok.Thanks
