### ISSUE TITLE
Add support for io_uring

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#1522]
https://netty.io/news/2020/11/16/io_uring-0-0-1-Final.html

**Comment by yueki1993** [comment]
@mp911de (FYI) Sorry if you already know this and maybe I should raise new ticket, 
but I tried io_uring and found I need to bump netty to 4.1.54.Final to enable io_uring:
https://github.com/netty/netty/commit/d4defc30b880072db6e9e5c7459506e6a153f2f3

**Comment by mp911de** [comment]
Thanks for letting me know, done with #1541
