### ISSUE TITLE
Using AbandonedConfig in ConnectionPoolSupport

### ISSUE THREAD

**Issue by umang92** [lettuce-io/lettuce-core#1531]
#### Describe the solution you'd like

I am currently using redis connection pool based on the examples provided here. https://github.com/lettuce-io/lettuce-core/wiki/Connection-Pooling

But I also want to implement an AbandonedConfig, using which a connection which has not been returned to the pool for a threshold amount of time can be automatically deleted and replenished from the pool.

But seems like the ConnectionPoolSupport class does not provide an interface for GenericObjectPool which accepts an AbandonedConfig. 

Please add support for the same.
#### Describe alternatives you've considered

THE alternatives I am considering right now is to copy ConnectionPoolSupport and ConnectionWrapping classes in my project and working with it. Then changing the ConnectionPoolSupport to add a new interface to Support AdabdonedConfig.

#### Teachability, Documentation, Adoption, Migration Strategy

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by mp911de** [comment]
Not sure I follow. `ConnectionPoolSupport` defines `GenericObjectPool<T> createGenericObjectPool(…)` which gives you full access to `GenericObjectPool`.

**Comment by umang92** [comment]
genericObjectPool has the following constructor:
```
GenericObjectPool(PooledObjectFactory<T> factory, GenericObjectPoolConfig<T> config, AbandonedConfig abandonedConfig)
```

But this is not exposed through the ```ConnectionPoolSupport``` class.

**Comment by mp911de** [comment]
What about `GenericObjectPool.setAbandonedConfig(…)`?

**Comment by umang92** [comment]
Oops. My bad there. Didn't notice something like exists. That will surely work. Thanks.
