### ISSUE TITLE
disconnectedBuffer Queue dos'not release command

### ISSUE THREAD

**Issue by yongyijian** [lettuce-io/lettuce-core#1533]
i can't foud the io.lettuce.core.cluster.ClusterNodeEndpoint.disconnectedBuffer
 where release the command recources, it caused my program oom,becourse the  disconnectedBuffer hold too many objects 
references.

**Comment by mp911de** [comment]
`disconnectedBuffer` gets GC'd once the connection is closed and there are no more references to the actual cluster connection.

If that doesn't work for some reason, please provide a minimal example that is able to demonstrate the issue.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
