### ISSUE TITLE
Lettuce client reconnecting every few seconds when using sentinels

### ISSUE THREAD

**Issue by JayChandler** [lettuce-io/lettuce-core#1535]
I am using Lettuce in a spring boot project. I have configured it using sentinels.

    sentinel:
      master: redismaster
      nodes:
        - redis01:26379
        - redis02:26379
        - redis03:26379
    lettuce:
      read-from: slave

Basically everything works but i see a lot of these log messages lately. It tries to reconnect every 10 to 16 seconds ? 

```
[xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /172.20.120.146:6379
[ioEventLoop-4-7] i.l.core.protocol.ReconnectionHandler    : Reconnected to 172.20.120.146:6379
```
Why ? How can i prevent that, it fills up my logs ? Any way to configure this behaviour?

**Comment by JayChandler** [comment]
Btw this is the timeout setting in redis.conf

```
# Close the connection after a client is idle for N seconds (0 to disable)
timeout 0
```

**Comment by mp911de** [comment]
Can you enable debug logging to see what caused the disconnect?

**Comment by JayChandler** [comment]
I was able to fix the issue by myself. Th reason was a sentinel from an other cluster joined this cluster and caused this issues. It was just missconfiguration!
