### ISSUE TITLE
Support for ACL commands

### ISSUE THREAD

**Issue by GraemeMitchell84** [lettuce-io/lettuce-core#1538]
It would be great if lettuce could be able to support the [ACL * commands] (https://redis.io/commands), such as ACL GETUSER, ACL SETUSER, etc.  I have looked through the docs and don't see any evidence of support just yet, and I know this is relatively new in Redis.

The reason for this is that redis currently has a limitation (in my eyes) when managing users in a cluster.  The ACL is managed independently on each node in the server, rather than being propagated to each node automatically.  [See this question that I raised](https://github.com/redis/redis/issues/7988) on the redis github.

This raises a challenge for administrators to manually keep their cluster in sync with regards to access management.  I want this to be a simple administrative activity for our teams, and would like to manage this through a UI / API services. I don't want the potential for human error in these important processes.  While I don't want to have to manually keep the cluster in sync, providing access to the core ACL commands in Lettuce would allow me to programmatically keep our clusters in sync, or choose how I want to manage users in our clusters.  

Should Redis choose to implement this feature in future to sync ACL across a cluster, it would still be good to have ACL commands in lettuce to allow for administrative management programmatically, so that modern applications may be written to manage it.

**Comment by mp911de** [comment]
Thanks a lot. Given that usecase, it makes sense to provide a programmatic API. ACL should be stable by now so we can provide proper API support here.
