### ISSUE TITLE
the methods of RedisAsyncCommands should not throw any Exception directly.They should return a RedisFuture with error.

### ISSUE THREAD

**Issue by libinglong** [lettuce-io/lettuce-core#1542]
Throwing Exception directly is not the right way when the returnType of a method is CompleteStage.
Thinking about the following code:
```java
Mono.fromCompletionStage(primaryAsyncCommands.get("a"))
                .onErrorResume(throwable -> Mono.fromCompletionStage(secondaryAsyncCommands.get("a")))
                .subscribe(System.out::println);
```
If we throw Exception directly, the code do not work properly.
We have to do write the code like this:
```java
Mono.fromCompletionStage(wrap(() -> primaryAsyncCommands.get("a")))
                .onErrorResume(throwable -> Mono.fromCompletionStage(wrap(() -> secondaryAsyncCommands.get("a"))))
                .subscribe(System.out::println);

private <T> CompletionStage<T> wrap(Callable<CompletionStage<T>> callable){
        try {
            return callable.call();
        } catch (Exception e){
            CompletableFuture<T> f = new CompletableFuture<>();
            f.completeExceptionally(e);
            return f;
        }
}
```

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

Also, please note that Lettuce has a reactive API returning Project Reactor types.

**Comment by libinglong** [comment]
@mp911de thank you! I am sorry for my careless.The reactive api has solved my problem.
By the way, throwing exception directly is not a good idea when returnType of a method is Completestage.

**Comment by mp911de** [comment]
Please note that we've changed the async API behavior in 6.0.
