### ISSUE TITLE
callback on calls inside ScanIterator for metrics

### ISSUE THREAD

**Issue by jmhodges-signal** [lettuce-io/lettuce-core#1548]
#### Is your feature request related to a problem? Please describe

We'd like to see if certain sections of a large dataset in a zscan call are taking longer than others to be received from redis. The current choice for doing that is to write your own cursor handling code which can be a little annoying.

#### Describe the solution you'd like

One possible solution that would allow us to use the nicer ScanIterator tooling would be a callback when an underlying redis command runs so we can capture latency metrics for it, specifically.

#### Describe alternatives you've considered

Writing your own cursor handling code.

**Comment by mp911de** [comment]
See https://github.com/lettuce-io/lettuce-core/wiki/Command-Latency-Metrics for command metrics. We're not going to add additional instrumentation.
