### ISSUE TITLE
Observing very high latencies with Lettuce Redis Cluster Configuration

### ISSUE THREAD

**Issue by theakshaypilania** [lettuce-io/lettuce-core#1550]
#### Overview
We are planning to migrate our blocking Spring boot micro-service to a non-blocking IO Spring webflux. We are keen to use Lettuce for our Redis related dependencies.

But during load testing and comparison testing of a small micro-service with our old service, we found out that we are observing very high latencies while fetching data from the Redis cluster using Lettuce.

#### Current Behavior

Apache Jmeter load testing results: 
All latencies are in ms. 
Number of threads/users : 1000
ramp-up time = 60sec
Object/Payload size = A simple 100KB JSON string fetched from Redis Cluster.

New Test Service using Lettuce client

![Screenshot from 2020-12-07 21-40-41](https://user-images.githubusercontent.com/28848612/101375220-22ebcb80-38d5-11eb-989f-117b86683c4d.png)

While that of our old service using Jedis client, the latencies are:
![Screenshot from 2020-12-07 21-48-52](https://user-images.githubusercontent.com/28848612/101376080-259af080-38d6-11eb-8dcb-8b23912b24f0.png)

<details>
<summary>Stack trace</summary>
One thing I noticed in logs while trying some cases like to put the 'Redis get' code in different Schedulers is that everytime the same thread was used for every request. i.e. even if I put the Redis fetching code to be run in a, like say Schedulers.elastic() it will still run in the same one thread i.e. "[lettuce-epollEventLoop-7-5]". Pasting a very small chunk of a stack trace showing the name of the thread.

```
:25,621 INFO  [lettuce-epollEventLoop-7-5] r.M.S.3:274:[, ] - onComplete()
2020-12-07 22:02:25,651 INFO  [reactor-http-epoll-7] r.M.S.6:274:[, ] - onSubscribe(MonoSubscribeOn.SubscribeOnSubscriber)
2020-12-07 22:02:25,651 INFO  [reactor-http-epoll-7] r.M.S.6:274:[, ] - request(unbounded)
2020-12-07 22:02:25,687 INFO  [lettuce-epollEventLoop-7-5] r.M.S.2:274:[, ] - onNext({"230":{"applyOn":"COUPON_AMOUNT","name":"DD_BKTTRIBE","version":"1","updateOn":"Thu Feb 14 12:29:25 IST 2019","dimensions":{}},"110":{"applyOn":"COUPON_AMOUNT","name":"DD_BKTTRIBE","version":"1","updateOn":"Fri Feb 15 13:11:25 IST 2019","dimensions":{"DD_BKTTRIBE":{"weight":100,"scale":30,"text"
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

Configuration Class:
ApplicationConfig.java
```java
@Configuration
public class ApplicationConfig {
  @Bean
  public ReactiveRedisConnectionFactory reactiveRedisConnectionFactory() {
    List<String> list = new ArrayList<>();
    list.add("172.16.47.79:7000");
    return new LettuceConnectionFactory(new RedisClusterConfiguration(list));
  }
}
```
Backend Service code:
DDService.java
```
@Service
@Slf4j
public class DDService {
  @Autowired
  private ReactiveRedisTemplate<String, String> redisTemplate;

  public Mono<String> getPolicyObjFromCache(String key) {
    return redisTemplate.opsForValue().get(key);
  }
}
```

</details>

#### Expected behavior/code

IMHO, the latencies should be somewhat similar if not better to that of the old Blocking Service using Jedis Client.

#### Environment

- Lettuce version(s): 6.0.1.RELEASE
- Redis version: 3.2.4

#### Possible Solution
NA

#### Additional context
We are not using any connection pooling in the old service as well as in the new test service.

**Comment by mp911de** [comment]
Reactive throughput is almost always worse than blocking because blocking has no context switching involved as everything stays on the same thread. 

In any case, try enabling publishOnScheduler via ClientOptions. What happens here is deserialization on the I/O Thread whereas in blocking land deserialization was a caller thread task.

**Comment by theakshaypilania** [comment]
Can you provide with a small reference/example of how you're suggesting it?

**Comment by mp911de** [comment]
Something like https://github.com/lettuce-io/lettuce-core/blob/main/src/test/java/io/lettuce/examples/ConnectToRedisCluster.java.

**Comment by theakshaypilania** [comment]
Can you highlight what is the difference between connecting this way and that way?

**Comment by theakshaypilania** [comment]
> Can you highlight what is the difference between connecting this way and that way?

Gotcha, what you were saying.

**Comment by theakshaypilania** [comment]
Btw, can you suggest something, other than this?
Do we really need connection pooling when connecting with Redis like with Lettuce or for that matter any other client? Does providing a connection pool helps in increasing performance, decreasing latencies when multiple requests hit?

Also, if we don't use any connection pool, does lettuce at least keep one connection opened even if no requests come for some time?

**Comment by mp911de** [comment]
Closing since this discussion isn't going in a helpful way. We don't have enough context to diagnose a problem.

**Comment by 13520001752** [comment]
@theakshaypilania 
we are facing the similar issue as yours 
how do you get rid of this problem
