### ISSUE TITLE
BooleanOutput set function is incorrect

### ISSUE THREAD

**Issue by paladin4409** [lettuce-io/lettuce-core#1553]
#### Current Behavior

use xgroup delconsumer command to delete a consumer for redis stream, the result returns pending messages count.
but invoke LettuceStreamCommands xGroupDelConsumer, return BooleanOutput object, the BooleanOutput set output function:

public void set(long integer) {
        output = (integer == 1) ? Boolean.TRUE : Boolean.FALSE;
}

so, if the pending messages is more than one, this BooleanOutput set Boolean.FALSE! but it is actually success.

#### Environment

- Lettuce version(s): [5.3.0.RELEASE]
- Redis version: [5.0.0]

**Comment by mp911de** [comment]
That was fixed with #1377 for version 6.0
