### ISSUE TITLE
Missing support for TYPE parameter of SCAN command

### ISSUE THREAD

**Issue by mvmn** [lettuce-io/lettuce-core#1559]
TYPE option in [ScanArgs](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/ScanArgs.java) for SCAN command is missing.

As of version 6.0 Redis SCAN command supports TYPE argument (which is not supported for HSCAN, ZSCAN or SSCAN): https://redis.io/commands/scan#the-type-option
This option allows one to filter keys by specific key type (types are same as returned by [TYPE](https://redis.io/commands/type) command: string, list, set, zset, hash and stream).

However, Lettuce does not support this argument.

Notes on possible ways to implement: Supposedly an extension to ScanArgs like KeyScanArgs could be added which would include such field, or the field could be added to ScanArgs directly. The Redis connection should of course accept this type for scan(...) methods and pass it to Redis accordingly.

**Comment by mvmn** [comment]
Draft PR: https://github.com/lettuce-io/lettuce-core/pull/1560

This does NOT include tests for new parameter, though existing tests are updated.

Please update as you see fit - I'm using Eclipse and can't make Kotlin work :-(

**Comment by mp911de** [comment]
Thanks a lot. We will take the PR from here. It makes sense to have a `KeyScanArgs` type (subclassing `ScanArgs`).
