### ISSUE TITLE
Add support for ReadFrom.subnet

### ISSUE THREAD

**Issue by yueki1993** [lettuce-io/lettuce-core#1569]
## Feature Request
I want `ReadFrom.Subnet` feature which read from any node in the configured subnets. 
Original motivation of this proposal is, I want to read from a (AWS elasticache) redis node in the same availability zone from an application. 
Reading from the same availability zone reduces latency and costs as AWS charges traffics between different availability zones. 
While AWS claims `AZs are engineered to provide low latency network connectivity to other AZs in the same region` ([see link](https://aws.amazon.com/elasticache/faqs/)), a simple benchmark shows crossing availability zone leads bad latency:
```bash
$ redis-cli -h <same AZ node>  --latency
min: 0, max: 19, avg: 0.38 (2088 samples)
$ redis-cli -h <different AZ node>  --latency
min: 1, max: 21, avg: 1.21 (2061 samples)
```

Currently lettuce supports `ReadFrom.NEAREST`, a option of reading from any node with the lowest latency.
For my usecase it would work well if there is only one node in an availability zone.
However if there are more than two nodes in an availability zone, the option may lead unbalanced loads between the nodes.
Imagine that an extreme case - there are two read replicas in an availability zone and one lettuce application with `NEAREST` option deployed to the same availability zone with the replicas, the application always reads from one read replica and the other one is not used until the next topology refresh. (I did not test `NEAREST` actually, sorry if I am wrong)

I believe lettuce should be vendor-independent and avoid AWS specific APIs,  so I want to propose to use subnets to read from a node of the same availability zone.
I think we can use this feature for other clouds or on-premises.

As you know lettuce is well-designed and I can implement such `ReadFromSubnet` class by myself in my project, but I believe this feature will be in demand to other developers.

If my proposal seems reasonable I can submit a PR.

#### Is your feature request related to a problem? Please describe
Crossing availbility zone leads bad latency and costs.

#### Describe the solution you'd like
Add support `ReadFromSubnet` feature:
```java
    static final class ReadFromSubnet extends ReadFrom {

        private final List<IpSubnetFilterRule> rules = new ArrayList<>();

        ReadFromSubnet(String... cidrNotations) {
            // ...
        }

        @Override
        public List<RedisNodeDescription> select(Nodes nodes) {
            ArrayList<RedisNodeDescription> result = new ArrayList<>();
            for (RedisNodeDescription node : nodes) {
                if (isInSubnetRange(node.getUri())) {
                    result.add(node);
                }
            }

            return result;
        }

        private boolean isInSubnetRange(RedisURI redisURI) {
            // return true if redisURI is in the subnets otherwise false.
        }
    }
``` 
To calculate subnet netty's `IpSubnetFilterRule` seems good as we do not need additional dependency.

#### Describe alternatives you've considered
AWS API like [DescribeCacheClusters](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeCacheClusters.html) would work,
but we need an elephant `awssdk` dependency and this makes lettuce vendor locked-in.

#### Teachability, Documentation, Adoption, Migration Strategy
We need to add information to [wiki page](https://github.com/lettuce-io/lettuce-core/wiki/ReadFrom-Settings).

#### Example
![image](https://user-images.githubusercontent.com/7314410/103394108-e0cb4800-4b69-11eb-89dd-cbdda9b07aa0.png)

**Comment by yueki1993** [comment]
https://github.com/lettuce-io/lettuce-core/pull/1570
I've just submitted a PR of this proposal.
If this proposal is nonsense, please close this issue and pull request.
(In Japan we have long new year holidays but you know, due to covid-19 I need to stay home and am really bored to stay home. Sorry for sending PR before your response. Happy new year and stay safe!)

**Comment by mp911de** [comment]
Thanks a lot. It makes sense to use netty utilities to build a subnet-based `ReadFrom` rule. Not depending on AWS SDK makes sense as we don't want to include any cloud-vendor specific dependencies.
