### ISSUE TITLE
Random node selection can keep selecting the same node again and again

### ISSUE THREAD

**Issue by debarshiraha** [lettuce-io/lettuce-core#1571]
Redis: 5.0, 2 replicas per shard.
Lettuce: 5.2.1

When a node fails/goes down for some reason, and a new node if being added (replacing old node), Lettuce can keep sending some requests to the same bad node (see [this](https://github.com/redis/redis/issues/8208)). [This](https://github.com/lettuce-io/lettuce-core/issues/625) is one of the issues we keep hitting, in addition to requests timing out and other errors.

Looks like Lettuce [randomly selects](https://github.com/lettuce-io/lettuce-core/blob/9e30d62fe52b3ce41277d7858729795e303745b6/src/main/java/io/lettuce/core/cluster/PooledClusterConnectionProvider.java#L310) a node. At high tps, some percentage of the requests still hit the bad node even after multiple retries. This can be easily reproduced locally, note below how node 1 was selected 10 consecutive times, when node 0 was healthy.

```
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 0
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 0
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 1 due to Command timed out after 100 millisecond(s)
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 2 due to Command timed out after 100 millisecond(s)
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 3 due to Command timed out after 100 millisecond(s)
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 4 due to Command timed out after 100 millisecond(s)
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 5 due to Command timed out after 100 millisecond(s)
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 6 due to Command timed out after 100 millisecond(s)
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 7 due to Command timed out after 100 millisecond(s)
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 8 due to Command timed out after 100 millisecond(s)
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 9 due to Command timed out after 100 millisecond(s)
(pool-3-thread-3) Random selection attempt: 0, selectedReaderCandidates.length: 2, random index selected: 1
io.lettuce.core.RedisCommandTimeoutException detected, attempt number: 10 due to Command timed out after 100 millisecond(s)
```

I've tried round-robin node selection which is working better in this scenario. Retries always succeed within \#replicas retries.

**Comment by mp911de** [comment]
Randomization happens only if the configured `ReadFrom` object is not order-sensitive. You can provide one that cares about ordering. Our check mostly validates that the connection is connected and not whether the connection can complete commands.

**Comment by debarshiraha** [comment]
If we select order-sensitive ReadFrom, then I think it'll select the same node always? So even if we have three nodes/replicas, and two of them might be healthy, all retries may go to the same unhealthy node? Let me know if that is not the case.

**Comment by mp911de** [comment]
> If we select order-sensitive ReadFrom, then I think it'll select the same node always

Yes, that's the case. Lettuce doesn't consider any kind of healthiness in terms of whether a command completed successfully or exceptionally. The only metric we have is whether a connection is established. If you want to include that kind of metrics, you need to track the details on your side and provide a `ReadFrom` implementation that omits unhealthy nodes.

**Comment by debarshiraha** [comment]
How about round-robin selection instead of random selection?

That will guarantee we'll try every possible node within #replicas retries before hitting the same node again. So as long as there is one healthy node, retries are guaranteed to go there and succeed. Let me know your thoughts.

**Comment by mp911de** [comment]
Round robin requires state. Our ReadFrom implementations are stateless. ReadFrom returns always a list of read candidates that are then checked whether the connection is open.

We would require to associate the command with the target node to know how that command completed on a particular node. I don't have a good idea how to model something like that.

**Comment by debarshiraha** [comment]
For our application, storing the index in a threadLocal in PooledClusterConnectionProvider works. Because we always retry on the same thread. Even if someone schedules the retries on a different thread, then retry can go to any random node (same behavior as today). So the below change completely mitigates this issue, and from my test calls always succeed with 2nd retry itself during failover. With this we do not need any complex node state management and tracking, as first thing we do when something fails is retry, and this only guarantees that retry doesn't land on the same node.

```
+    private static final ThreadLocal<Integer> COUNTER = new ThreadLocal<>();

-            int index = ThreadLocalRandom.current().nextInt(selectedReaderCandidates.length);
+            int index = (getCounter() + 1) % selectedReaderCandidates.length;
+            setCounter(index);

getCounter() {
+        if(COUNTER.get() != null) {
+            return COUNTER.get();
+        } else {
+            COUNTER.set(0);
+            return COUNTER.get();
+        }
+    }
+
setCounter(int counter) {
+        COUNTER.set(counter);
+    }
```

**Comment by mp911de** [comment]
Great to hear. Closing the ticket as we intend to keep the API and functionality as-is.
