### ISSUE TITLE
High concurrency problem

### ISSUE THREAD

**Issue by chengjiafeng** [lettuce-io/lettuce-core#1575]
Now  I have a problem。 I use cluster  mode client。 When high concurrency，t took more than 5s to return the result。127 machines access 15 billion data every day。

**Comment by mp911de** [comment]
Tracing down performance issues in a high load arrangement is always subject to configuration, network and environment issues, nothing we can really do here unless you can spot a bottleneck. Please measure command latencies, TCP buffer fill ratios and profile your application to identify which parts cause the slowdown.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
