### ISSUE TITLE
io.lettuce.core.RedisCommandTimeoutException multiple times without selecting other nodes

### ISSUE THREAD

**Issue by debarshiraha** [lettuce-io/lettuce-core#1591]
Redis: 5.0, 2 replicas per shard.
Lettuce: 5.2.1

During a node failover, we got hundreds of erros, even after multiple retries. Every retry waited for the configured timeout time and timed out:

```
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 100 millisecond(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
```

I've logging [here](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/cluster/PooledClusterConnectionProvider.java#L304) and [here](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/protocol/DefaultEndpoint.java#L416) but there was no log statements from there. So it didn't go through that branch. So looks like it didn't try to select other nodes during retry. Did it take a different branch? 

I know if only one node is available then it won't try to select other nodes. But I can confirm that we saw ReconnectFailedEvent and ```io.lettuce.core.protocol.ConnectionWatchdog: Cannot reconnect to [*]``` for just one node, out of 3.

We didn't enable debug logging as it may generate lot of logs. Any idea what may've happened? Thanks

**Comment by mp911de** [comment]
Without further information we're not able to diagnose any issue. Likely, all commands that should go to the disconnected node failed.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by debarshiraha** [comment]
Hi, we didn't have any other information, but the issue happens. As I mentioned before, the code didn't go through that branch, which either means shard has just 1 node (which isn't the case here), or the client didn't even send the command to the server. After a recent outage we think it may be the second case. We've reduced the command timeout to milliseconds range as our application is latency sensitive. Team thinks that when a node dies, after topology refresh Lettuce tries to first connect to that node when executing a command, and gets RedisCommandTimeoutException as timeout is low and socket connect timeout is higher. And this keeps going on for every retry. That's why every retry meets RedisCommandTimeoutException and it doesn't go through the code path mentioned above (to select a node to send request). Can this be the case?

**Comment by mp911de** [comment]
Command timeouts are independent of socket timeouts. The command timeout timer starts as soon as a command gets dispatched. Encoding and sending a command to Redis is an asynchronous process. If you receive a response within the command timeout (that might include reconnecting, sending, processing and receiving the response from Redis), then the command succeeds. If the command isn't completed within that time (because a reconnect takes longer or Redis takes longer to reply), then you see timeouts.

**Comment by debarshiraha** [comment]
Right, the question is why do we see command timeouts when we have 3 nodes per shard and just one of them fails. Why is it not highly available when there are two good nodes available and we still see outage? Do we need to tune client configuration/timeouts?

**Comment by mp911de** [comment]
> just one of them fails

The only indicator is whether the connection is open. If a server is slow or unresponsive, then Lettuce cannot detect that.

Generally, Lettuce selects a node to which it sends a command, and then it expects a response. There's no such thing as retry on timeout.

**Comment by debarshiraha** [comment]
We do the retry on the application side.
