### ISSUE TITLE
Ping command is not supported in Pub/Sub connection

### ISSUE THREAD

**Issue by TsybulskyStepan** [lettuce-io/lettuce-core#1601]
#### Current Behavior

When I try to send `PING` command into Pub/Sub connection I'm getting a following error message:

```
io.lettuce.core.RedisException: Command PING not allowed while subscribed. Allowed commands are: [PSUBSCRIBE, QUIT, PUNSUBSCRIBE, SUBSCRIBE, UNSUBSCRIBE]
```

#### Test

```java
@Test
public void whenPingInPubSub_PongIsReturned() {
    RedisClient client = RedisClient.create(RedisURI.builder().withHost("localhost").withPort(6379).build());

    RedisPubSubReactiveCommands<String, String> pubsub = client.connectPubSub().reactive();

    Mono<Void> subscribe = pubsub.subscribe("channel-test");
    Mono<String> ping = Mono.delay(Duration.ofSeconds(1)).flatMap(tick -> pubsub.ping());

    Mono<String> pingAfterSubscription = subscribe.then(ping);

    StepVerifier
        .create(pingAfterSubscription)
        .expectNextMatches("PONG"::equals)
        .verifyComplete();
}
```

#### Expected behavior/code

As [it was already discussed](https://gitter.im/lettuce-io/Lobby?at=600e71c7dfdbc1437fae807a) Lettuce version 6.0.x and above should permit `PING` command in Pub/Sub channels as it has already being supported by Redis 6.

#### Environment

- Lettuce version: 6.0.1.RELEASE
- Redis version: 6.0.9

#### Possible Solution

It's required to extend a [list of allowed commands](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/pubsub/PubSubEndpoint.java#L55).

**Comment by mp911de** [comment]
That's in place now.
