### ISSUE TITLE
setAutoFlushCommand on async() and sync() commands 

### ISSUE THREAD

**Issue by bahui80** [lettuce-io/lettuce-core#1604]
**Lettuce version: 6.0.2.RELEASE**

I am implementing a Rate Limit library using Redis. This library will use a Redis Cluster to handle the distributed rate limit. 

Also this library needs to call some external endpoints (which I will be caching using Redis taking advantage of it to avoid flooding other clients). 

My rate limit library has only one 
```
StatefulRedisClusterConnection<String, String> redisClusterConnection;
```
This one is a Spring `@Bean` instantiated when the app starts. So basically I am only creating one connection per instance of the Rate Limit.

Since I am using Redis for both Rate Limit and caching, it has two parts of it:
- algorithm that rate limits: does several calls to Redis, so i take advantage of the `async()` commands to issue them and send them all together. 
- algorithm that gets from cache: this is a simple get() and setex() commands. Since I need the commands to know if the cache is populated or not, in this case the commands are issued with `sync()` 

This is the part of the code of the cache:
```
String hashedToken = Hashing.sha256().hashString(someToken, StandardCharsets.UTF_8).toString();
String cache = redisClusterConnection.sync().get(hashedToken);
.... SOME CALCULATIONS....
if (cache == null) {
    redisClusterConnection.sync().setex(....);
}   
```

This is part of the code for the rate limit:
```
RedisAdvancedClusterAsyncCommands<String, String> asyncRedisCommands = redisClusterConnection.async();
List<String> redisTime = asyncRedisCommands.time().get(redisClusterConnection.getTimeout().toMillis(), TimeUnit.MILLISECONDS);
...... DO SOME INTERNAL CALCULATIONS WITH THE TIME....
List<RedisFuture<?>> futures = Lists.newArrayList();
asyncRedisCommands.setAutoFlushCommands(false);
futures.add(asyncRedisCommands.get(pastKey));
futures.add(asyncRedisCommands.incr(currentKey));
futures.add(asyncRedisCommands.expire(currentKey, 2 * timeWindowInMilliseconds - currentMillisecond));
asyncRedisCommands.flushCommands();
..... DO SOME MORE CALCULATIONS....
```

A request arrives and code is executed on this order:
1. Cache code is called, first time the cache is empty. It will retrieve the endpoint call and store that into Redis
2. It will call rate limit algorithm. Here it will `setAutoFlushCommands` to `false`
This first pass works perfect

Now a new request comes in and the flow goes like this:
1. Cache code is called, cache is not empty. But here my app breaks. `.get()` command throws me a CommandTimeoutException. 

After understanding a little bit whats going on, the problem is that since I set the `setAutoFlushCommands` to `false`, the second time it runs, the `sync()` never flushes the command. 

Now my question here is, how do I handle connections in which I need to do some `sync()` and `async()` commands???
I thought the `setAutoFlushCommands` was being done at the `RedisAdvancedClusterAsyncCommands` only but seems it's affecting the whole Redis connection. 
Should i make my calls in the cache code `async()` and use the `.get()` method with timeouts, the same way it's done for the `time()` method? 

Also I have to say that this will serve multiple parallel requests so I might have one part of the code executing the async part and one the sync part so I cant go modifying the `setAutoFlushCommands` all the time from true to false and viceversa

**Comment by mp911de** [comment]
Switching `setAutoFlushCommands` to false is only recommended for single-threaded connection use that wants to optimize command buffering for batch imports.

Lettuce works in general in a non-blocking, multiplexing mode regardless of the API that you're using. You can use synchronous, asynchronous, any reactive APIs with the same connection.

That being said, if you don't touch `setAutoFlushCommands`, you should be good.

**Comment by bahui80** [comment]
@mp911de great that worked!! Thanks! 
Anyways, I thought the `setAutoFlushCommands` was done at `RedisAdvancedClusterAsyncCommands` and not at connection level. 
That was my confusion!
