### ISSUE TITLE
MicrometerCommandLatencyRecorder is missing from 6.0.x release

### ISSUE THREAD

**Issue by jnopnop** [lettuce-io/lettuce-core#1613]
Hi,

I was about to try out the micrometer integration (see https://github.com/lettuce-io/lettuce-core/issues/795). But it appears that both `io.lettuce.core.metrics.MicrometerCommandLatencyRecorder` and `io.lettuce.core.metrics.MicrometerOptions` are missing in the `6.0.2.RELEASE`. 
Those classes are present in `main` but were not transferred to `6.0.x`.
Since the documentation mentions Micrometer integration (see https://lettuce.io/core/snapshot/reference/#command.latency.metrics.micrometer), I guess this is an issue.
Could you please make release with those classes included?

Thank You!

**Comment by mp911de** [comment]
The Micrometer integration is shipped with Lettuce 6.1 (see https://lettuce.io/core/snapshot/reference/#observability.metrics). We build the docs from the unversioned GitHub wiki and that is why some newer features appear in the documentation.

**Comment by jnopnop** [comment]
Got it. Sorry for misunderstanding. Looking forward for 6.1 release 🙂
