### ISSUE TITLE
How to connect via LettuceConnectionFactory -> RedisClusterConfiguration to azure redis over SSL.

### ISSUE THREAD

**Issue by pranilkadam** [lettuce-io/lettuce-core#1617]
Can we have some example to connect Azure Redis over SSL?

Creating RedisClusterConfiguration and passing it to the LettuceConnectionFactory. this is the existing code to connect Azure redis via non-ssl port.

I want to connect now via SSL. Could you please help with this?
Following are the versions are used.
compile group: 'io.lettuce', name: 'lettuce-core', version: '5.3.2.RELEASE'
id 'org.springframework.boot' version '2.1.13.RELEASE'

Please let me know if you need any info.

**Comment by mp911de** [comment]
Have you checked out the existing [tickets](https://github.com/lettuce-io/lettuce-core/issues?q=azure) regarding Azure SSL connectivity?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
