### ISSUE TITLE
XREADGROUP skips messages if body is nil

### ISSUE THREAD

**Issue by asalabaev** [lettuce-io/lettuce-core#1622]
#### Current Behavior

I have a capped stream and a consumer has read messages and did no acknowledge. Then those messages got trimmed, but they remain in PEL of the consumer. Lettuce seems to return items skipping like if body nil fooled it

<details>
I have 10 pending messages via redis-cli:

```
> xreadgroup GROUP clickhouse5 LogToCH-1 count 12500 streams LOG 0-0
1) 1) "LOG"
   2)  1) 1) "1613148827078-6"
          2) (nil)
       2) 1) "1613149395197-12"
          2) (nil)
       3) 1) "1613151931878-5"
          2) (nil)
       4) 1) "1613152648864-7"
          2) (nil)
       5) 1) "1613157152132-67"
          2) (nil)
       6) 1) "1613159691817-0"
          2) (nil)
       7) 1) "1613161933879-11"
          2) (nil)
       8) 1) "1613162164941-3"
          2) (nil)
       9) 1) "1613164598204-0"
          2) (nil)
      10) 1) "1613169116881-8"
          2) (nil)
```
then I run the same reading command in lettuce

```
15:21:40.990 [thread-1] DEBUG RedisStreamClientRead - LOG:clickhouse5:LogToCH-1> (1613218900989) reading Pending after 0-0
15:21:40.990 [thread-1] TRACE RedisStreamClientRead - LOG:clickhouse5:LogToCH-1: begin reading from stream 25000 items
15:21:41.160 [thread-1] TRACE RedisStreamClientRead - LOG:clickhouse5:LogToCH-1 xreadGroup returned 5 items timetaken 169 ms
15:21:41.161 [thread-1] DEBUG RedisStreamClientRead - LOG:clickhouse5:LogToCH-1> (1613218900989) received 5: 1613148827078-6 - 1613164598204-0
```
In the last line the log reports the first and the last read message ID

after the messages are processed and acknowledged I check the PEL in redis-cli again

```
> xreadgroup GROUP clickhouse5 LogToCH-1 count 12500 streams LOG 0-0
1) 1) "LOG"
   2) 1) 1) "1613149395197-12"
         2) (nil)
      2) 1) "1613152648864-7"
         2) (nil)
      3) 1) "1613159691817-0"
         2) (nil)
      4) 1) "1613162164941-3"
         2) (nil)
      5) 1) "1613169116881-8"
         2) (nil)
```

You can see that every even message remained in the PEL and every odd is gone.
</details>

#### Expected behavior/code

I would assume that the xreadgroup should return all messages like the redis-cli does. I also do not know any good way of bringing down the PEL to 0 other than doing it log2 times

#### Environment

- Lettuce version(s): 5.3.1.RELEASE
- Redis version: 5.0.5

**Comment by mp911de** [comment]
That issue happens only when using RESP2. That's fixed now.
