### ISSUE TITLE
Adding a mget(Iterable) to RedisAdvancedClusterAsyncCommands for easy Kotlin usage

### ISSUE THREAD

**Issue by adwsingh** [lettuce-io/lettuce-core#1623]
#### Is your feature request related to a problem? Please describe

If I want to pass a `Collection<K>` to mget from Kotlin or Java, I would first need to convert it to a array. This requires copying those elements and is not desirable.

#### Describe the solution you'd like

Add a `mget(Iterable<K>)` method to the interface. This is already present in the [implmentation](https://github.com/lettuce-io/lettuce-core/blob/7c5e6220fa523898ab5d3ed8f49cd9265107ca94/src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java#L284)

#### Describe alternatives you've considered

Converting to array before passing.

#### Teachability, Documentation, Adoption, Migration Strategy

User can now directly pass a collection via it's iterator to mget.

**Comment by mp911de** [comment]
We generally do not provide overloads accepting collection types for the API as Lettuce is a low-level API. You could use something like Spring Data which comes with a much more extended API catering for various use-cases. I'm somewhat reluctant adding Kotlin extensions or other sugar as we export over 3000 methods already.

**Comment by adwsingh** [comment]
While I do agree this makes sense for non-batch APIs, the sole point of batch APIs is to process multiple keys. In which case just having a vararg input seems way too restrictive.

**Comment by mp911de** [comment]
Not sure I want to follow the argument. Basically, you're saying that `rpush`, `zadd`, `sinter`, `mget` (82 commands in total) should receive overloads accepting a collection instead of an array which are 410 new methods (synchronous, asynchronous, reactive, Cluster Node Selection, Kotlin API).

Sorry, but no. 

We are already at capacity in terms of maintaining the driver and we're not keen on loading up another set of methods to be maintained.

**Comment by adwsingh** [comment]
But this forces everyone to convert their collection to an array before invoking any of the batch APIs. This is both expensive and extremely undesirable. Almost everyone coding in modern Java uses Collections rather than Arrays, even Spring Data is forced to convert a given collection to an array as the lower level APIs do not support a collection.
