### ISSUE TITLE
Order of pipeline execution

### ISSUE THREAD

**Issue by woowahankingbbode** [lettuce-io/lettuce-core#1627]
According to the [Wiki Documentation] of pipelining (https://github.com/lettuce-io/lettuce-core/wiki/Pipelining-and-command-flushing), commands are independently run when using.

https://github.com/lettuce-io/lettuce-core/issues/1046

"When invoking commands in a particular sequence (assuming only one Thread invokes commands at a time), then command ordering is retained."

However, the results of my experiment were different.

```
conn.openPipeline();
conn.get(a);
conn.get(b);
conn.del(a);
conn.del(b);
List<Object> results = conn.closePipeline();
```

In the code above, the results of the experiment varied.

```
[null, null, 1, 1]
[Object, null, 1, 1]
[null, Object, 1, 1]
[Object, Object, 1, 1]
```

I am using the `master/slave` configuration, and I am using `ReadFrom Slave`.
The `get` command was executed in `Slave`, and the `del` command was executed in `Master`.

Please check if it is a problem with my version or if there is any additional information in the documentation.

version: 5.1.6.RELEASE

**Comment by mp911de** [comment]
You're using Spring Data Redis API, Lettuce doesn't have a `openPipeline` method.

Can you reproduce the issue using Lettuce directly by obtaining futures?

```java
StatefulRedisConnection conn  =…;

RedisFuture f1 = conn.async().get(a);
RedisFuture f2 = conn.async().get(b);
RedisFuture f3 = conn.async().del(a);
RedisFuture f4 = conn.async().del(b);

// f1.get(); etc.
```

**Comment by woowahankingbbode** [comment]
Sorry. I was mistaken for lettuce.
There seems to be a problem with the implementation in Spring Data Redis.

**Comment by FULaBUla** [comment]
> Sorry. I was mistaken for lettuce. There seems to be a problem with the implementation in Spring Data Redis.

do you create issue in spring data redis？ could u tell me which version has resolved this problem？
