### ISSUE TITLE
ZAdd with ZAddArgs XX unexpected response

### ISSUE THREAD

**Issue by paualarco** [lettuce-io/lettuce-core#1630]
#### Current Behavior

Hello, I have noticed an unexpected behaviour when using `zadd` with `ZAddArgs.xx`, what happens is that the return value when is always 0, whereas from those cases where the ScoredValue I am expecting the return type to be equal to the number of updated values.

#### Java code

```
RedisSortedSetReactiveCommands reactiveCmd

reactiveCmd.zadd("key1", new ZAddArgs().xx(), 1, "value").block() //should be 0 and is 0

reactiveCmd.zadd("key1", new ZAddArgs().xx(), 1, "value").block() //should be 1 and is 1

reactiveCmd.zadd("key1", new ZAddArgs().xx(), 2, "value").block() //should be 1 and is 0

//if you get the SortedSet "key1", the actual values is 2, though the return one makes think that nothing has been updated.
```

#### Environment

- Lettuce version(s): 6.0.2.RELEASE
- Redis version (docker):  6.2-rc3

**Comment by mp911de** [comment]
Not sure we're on the same page. On `redis-cli` I get:

```
127.0.0.1:6379> flushall
OK
127.0.0.1:6379> zadd key1 xx 1 value
(integer) 0
127.0.0.1:6379> zadd key1 xx 1 value
(integer) 0
127.0.0.1:6379> zadd key1 xx 2 value
(integer) 0
```

**Comment by paualarco** [comment]
Thanks for the quick response, interesting to see that I could have just tested it through the command line to verify.
I was wrong thinking that the long-reply also reflected the score updates...

@mp911de sorry for the misunderstanding. Closing ticket.
