### ISSUE TITLE
RedisClusterClient may have memory leak

### ISSUE THREAD

**Issue by StillerRen** [lettuce-io/lettuce-core#1642]
## Bug Report

I happens to a problem that RedisClusterClient may have memory leak when I got a network problem that the client cannot connect to some cluster nodes.

then we got the error:
![image](https://user-images.githubusercontent.com/35724820/109781047-89695700-7c42-11eb-83e5-47843c90203e.png)

jmap result：
![image](https://user-images.githubusercontent.com/35724820/109781304-c2a1c700-7c42-11eb-8c17-0b1b6413f20b.png)

there are many RedisClusterClient parameter objects with the similar number.

#### Expected behavior/code

lettuce don't report the error: cannot allocate direct memory

#### Environment

- Lettuce version(s): 5.3.0.RELEASE
- Redis version: 4.0.11

#### Possible Solution

I think when the client cannot connect to cluster nodes, lettuce would rebuild connections, but myabe the old connection wouldn't release normally, so the direct memory would be used up

but I don't know where caused this problem, it takes a long time and after restarting client, it because normal

**Comment by StillerRen** [comment]
sorry, I cannot reproduce this problem in test environment
firstly, I think maybe connections would be released slowly, but new connections would be created fast, it would cause direct memory to use up. I restart client 5 hours after network recovery, so it is not the reason.

**Comment by mp911de** [comment]
Since we cannot proceed on this ticket without further information, we're going to close the ticket. 
If you would like us to look at this issue, please provide additional information and we will re-open the issue.
