### ISSUE TITLE
Rename zrandmemberWithscores to zrandmemberWithScores

### ISSUE THREAD

**Issue by dengliming** [lettuce-io/lettuce-core#1663]

**Comment by dengliming** [comment]
@mp911de We don't have a release for this command yet. Can we keep consistent with other places?

**Comment by mp911de** [comment]
Sure. Do you want to submit a PR? Commands introduced in the 6.1 line can be changed right away. We should only watch out for commands that were introduced in earlier versions to not break their signature. I plan to ship 6.1 RC1 today so we can use it in Spring Data Redis.

**Comment by dengliming** [comment]
Got it. I will submit a PR to do this later.
