### ISSUE TITLE
[Feature]: Lose redis hash command `HRANDFIELD` 

### ISSUE THREAD

**Issue by GStones** [lettuce-io/lettuce-core#1665]
## Why
 `HRANDFIELD`  is very useful in sometimes

> https://redis.io/commands/hrandfield

**Comment by dengliming** [comment]
Thanks for reporting this. We already support this command in `6.1` see [https://github.com/lettuce-io/lettuce-core/commit/7755da8cd587499dc319f897d0d6fbff5a470804](https://github.com/lettuce-io/lettuce-core/commit/7755da8cd587499dc319f897d0d6fbff5a470804) and will release today.
