### ISSUE TITLE
Update target jdk version for maven compiler plugin

### ISSUE THREAD

**Issue by dengliming** [lettuce-io/lettuce-core#1669]
Seems JDK 8 source code does not include the Java Flight Recorder implementation. Should we upgrade it? @mp911de 

```
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
 <configuration>
     <source>1.8</source>
     <target>1.8</target>
</configuration>
```

![image](https://user-images.githubusercontent.com/7796156/111325351-93f60880-86a6-11eb-9b5a-bd25280af3e2.png)

**Comment by mp911de** [comment]
You need to upgrade your JDK to at least JDK 8 update 262 or later.

**Comment by dengliming** [comment]
OK
