### ISSUE TITLE
Lettuce slower than redis-benchmark utility. Is there any performance tuning guide for lettuce?

### ISSUE THREAD

**Issue by ckbhatt** [lettuce-io/lettuce-core#1674]
I am using Lettuce in my java service and look up of a single record to a redis cluster is taking between 1.5~3 mili seconds while the same look up using redis-benchmark utility is taking less than 0.5 milliseconds. Is there any performance tuning of lettuce client that I can do to reach the level of less than 0.5 milliseconds.

**Comment by mp911de** [comment]
Lettuce is a multi-threaded client that involves a lot of activity when sending Redis commands. It depends a bit where you're heading to. Generally speaking, when using Lettuce it makes the most sense to keep a single connection (unless you're using transactions or blocking operations) as Lettuce auto-pipelines commands.

**Comment by karussell** [comment]
Sorry for hijacking this issue. Are calls to `connection.sync()` blocking operations or what could be an example?

**Comment by mp911de** [comment]
Closing due to lack of actionability. If you would like us to look at this issue, please provide additional information and we will re-open the issue.
