### ISSUE TITLE
Security finding in dependencies

### ISSUE THREAD

**Issue by kinglite** [lettuce-io/lettuce-core#1682]
My security scanner found an issue in one of the dependencies.
Trying the newest version didn't resolve the issue.
As mentioned in the security policy, I hereby opened an issue without much of info.

**Comment by mp911de** [comment]
Thanks a lot. If it's an issue within the dependencies, then feel free to provide more details here or submit directly a pull request to upgrade to a fixed version of a dependency. We're asking for responsible disclosure for findings that relate directly to our code.

**Comment by kinglite** [comment]
Ok, great. This concerns Netty Project dependencies with version 4.1.59.Final.

This is was the scanner found: 
https://cwe.mitre.org/data/definitions/444.html
https://cwe.mitre.org/data/definitions/295.html

The suggested solution would be to upgrade to version 4.1.60.Final

**Comment by mp911de** [comment]
That was addressed last week with #1618.

**Comment by mp911de** [comment]
Lettuce 6.0.3 was released on March 16 (https://repo1.maven.org/maven2/io/lettuce/lettuce-core/6.0.3.RELEASE/lettuce-core-6.0.3.RELEASE.pom).
