### ISSUE TITLE
Lettuce prints a lot of logs during its execution. Is there a switch to stop it from logging

### ISSUE THREAD

**Issue by WuJingLearn** [lettuce-io/lettuce-core#1688]
Lettuce prints a lot of logs during its execution. Is there a switch to stop it from logging

**Comment by mp911de** [comment]
Yes: Configure your logging properly. Lettuce uses `DEBUG` and `TRACE` levels to log a lot of diagnostic information. When using `INFO` then you should not see any output (except for disconnects/auto-reconnect) at all.
