### ISSUE TITLE
This approach uses Lettuce's latency collector and the publication mechanism to push metrics to Micrometer. I would rather suggest providing a `CommandLatencyCollector` implementation for Micrometer and using `Timer` directly. This is, to leave aggregation and sampling up to Micrometer/your monitoring system instead of using pre-aggregated results.

### ISSUE THREAD

**Issue by pranaykumar123456789** [lettuce-io/lettuce-core#1691]
This approach uses Lettuce's latency collector and the publication mechanism to push metrics to Micrometer. I would rather suggest providing a `CommandLatencyCollector` implementation for Micrometer and using `Timer` directly. This is, to leave aggregation and sampling up to Micrometer/your monitoring system instead of using pre-aggregated results.

_Originally posted by @mp911de in https://github.com/lettuce-io/lettuce-core/issues/795#issuecomment-478892450_

**Comment by mp911de** [comment]
Can you help us understand the purpose of this ticket? It's a copy of a comment from a closed ticket.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
