### ISSUE TITLE
Support for client-side cache maximum size and eviction policies

### ISSUE THREAD

**Issue by ascamargo** [lettuce-io/lettuce-core#1702]
## Feature Request

The current implementation of ClientSideCaching adds elements to local cache when fetched from remote Redis cache however this local cache can grow indefinitely, there is no limit and no eviction policy.
It would be great to able to configure the local cache with a maximum size and a eviction policy to be able to limit the size and remove selected elements when local cache is full.

#### Is your feature request related to a problem? Please describe

The current client-side caching implementation can add elements indefinitely which can consume all available memory.

#### Describe the solution you'd like

Pass a maximum size an a eviction policy to ClientSideCaching which in turn will check the map size upon each put operation and perform the eviction when cache is full.

**Comment by mp911de** [comment]
Lettuce doesn't try to abstract a fully fledged client-side cache, its support is limited to cache value loading and eviction upon notification. The map implementation is a simple variant to explain how the Map interface can be used to leverage proper cache implementations (Infinispan, Ehcache, Caffeine).
