### ISSUE TITLE
Too many Lettuce/CLUSTER/onComplete and Lettuce/INFO/accept

### ISSUE THREAD

**Issue by anryHan** [lettuce-io/lettuce-core#1704]
### I used Lettuce to connect to the redis cluster, and it happens occasionally too many "Lettuce/CLUSTER/onComplete" and "Lettuce/INFO/accept". redis response is very slow , what state will this problem occur？

[
<img width="1050" alt="屏幕快照 2021-04-02 18 38 39" src="https://user-images.githubusercontent.com/13831076/113409076-1d197900-93e3-11eb-9aa9-8ea5330bcf05.png">
](url)
[
<img width="1048" alt="屏幕快照 2021-04-02 18 38 55" src="https://user-images.githubusercontent.com/13831076/113409105-2acefe80-93e3-11eb-9e5b-75d6e70432d7.png">
](url)

**Comment by anryHan** [comment]
I used Lettuce to connect to the redis cluster, and it happens occasionally too many Lettuce/CLUSTER/onComplete and Lettuce/INFO/accept. Under what state will this problem occur？

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by anryHan** [comment]
> If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

The picture above is our business monitoring. This is an occasional problem, but it is very frequent.When will Lettuce/CLUSTER/onComplete and Lettuce/INFO/accept be triggered？

**Comment by mp911de** [comment]
I don't even understand the individual items in the list, what accept or oncomplete are.
