### ISSUE TITLE
`AsyncPool<T>.acquire` may lead to data consistency issue

### ISSUE THREAD

**Issue by duxing** [lettuce-io/lettuce-core#1705]
## Feature Request

I've done my research and didn't find anything but feel free to correct me:
when a connection pool (`AsyncPool<T>`) is used, the `acquire` method does not provide a way to consistently fetch the same connection by a particular key / attribute.

I think adding the following method to `AsyncPool<T>` is necessary:
`CompletableFuture<T> acquireBy(Supplier<Integer> seedSupplier)`

#### Is your feature request related to a problem? Please describe

this would be necessary to ensure data consistency when using multiple connections.
for example: 
 - an application uses Redis to store user data and issues both `set` and `get` calls.
 - a connection pool of multiple connections are used.
 - application code triggers a `set` followed by a `get` for the same key (same connected user)
 - `set` was dispatched to `connection0` and `get` was dispatched to `connection1`. 
 - due to a networking blip on `connection0`, `get` was received prior to `set` on Redis server, thus wrong data are returned.

#### Describe the solution you'd like

with the proposed method: `CompletableFuture<T> acquireBy(Supplier<Integer> seedSupplier)`

the application can call:
`pool.acquireBy(() -> user.getId())` or `pool.acquireBy(() -> key.hashCode())` to ensure that operations on the same key is always mapped to the same connection, thus ensuring the data consistency.

#### Describe alternatives you've considered

doing the same kind of mapping by creating an array of `StatefulRedisClusterConnection` or `RedisClient`, and manage the mapping logic in my application code.

**Comment by mp911de** [comment]
The asynchronous pool provides minimal functionality for a fully asynchronous arrangement. For more sophisticated asynchronous pools, please use appropriate pool implementations, such as [Reactor Pool](https://github.com/reactor/reactor-pool). This is mostly because Lettuce is primarily a Redis client and we don't want to have an overly complex connection pool implementation.

**Comment by duxing** [comment]
sounds good to me. thanks for the explanation!
