### ISSUE TITLE
The latest version don't support netty 5（netty 5 support jdk11）

### ISSUE THREAD

**Issue by funs690** [lettuce-io/lettuce-core#1713]
## Feature Request

The latest version don't support netty 5（netty 5 support jdk11），so in the jdk11  environment we need upgrade the netty version to 5.X， but there has a problem that io/netty/resolver/DefaultAddressResolverGroup  class not found . It may dosen't work in some  scene，please fix it in the next version！

**Comment by mp911de** [comment]
That is correct and netty 5 will require likely a lot more changes. Since netty 5 isn't final yet, we will have to wait until the netty team generally releases netty 5.
