### ISSUE TITLE
IllegalArgumentException after upgrading to latest version

### ISSUE THREAD

**Issue by mcgizzle** [lettuce-io/lettuce-core#1719]
#### Current Behavior

Since upgrading to `0.6.1-RELEASE` we are seeing a runtime exception.

We have a test suite which tests a custom Scala wrapper of `lettuce` that we have built.

We are seeing some weird behaviour when we update to the latest stable version.

After starting up `sbt`; running our tests for the first time will not show the error, but any subsequent runs will fail before any of the tests run, throwing the below error.
If we wait a minute or so and run the tests again the error will not throw the first time, before subsequently failing.

```java
 IllegalArgumentException: java.lang.ClassCastException@57a480c4
[error]
[error]   null:-1                                      sun.reflect.GeneratedConstructorAccessor191#newInstance
[error]   DelegatingConstructorAccessorImpl.java:45    sun.reflect.DelegatingConstructorAccessorImpl#newInstance
[error]   Constructor.java:423                         java.lang.reflect.Constructor#newInstance
[error]   JfrEventRecorder.java:108                    io.lettuce.core.event.jfr.JfrEventRecorder#createEvent
[error]   JfrEventRecorder.java:48                     io.lettuce.core.event.jfr.JfrEventRecorder#record
[error]   AbstractRedisClient.java:376                 io.lettuce.core.AbstractRedisClient#initializeChannelAsync
[error]   RedisClient.java:325                         io.lettuce.core.RedisClient#connectStatefulAsync
[error]   RedisClient.java:287                         io.lettuce.core.RedisClient#connectStandaloneAsync
[error]   RedisClient.java:264                         io.lettuce.core.RedisClient#connectAsync
```

</details>

#### Input Code

We create the client like so:

```
RedisClient.create()
```

We create an async bounded connection pool like this:

```
AsyncConnectionPoolSupport
  .createBoundedObjectPoolAsync(
     new Supplier[java.util.concurrent.CompletionStage[StatefulRedisConnection[String, String]]] {
       def get(): ConnectionFuture[StatefulRedisConnection[String, String]] =
         client.connectAsync(StringCodec.UTF8, RedisURI.create(config.host, config.port))
     },
```

</details>

#### Expected behavior/code

Expect this error to not occur.

#### Environment

- Lettuce: 6.1.0.RELEASE
- Redis Bloom version: 2.2.5
- Scala version: 2.13.4
- Java version: I've tried 8,11 & 13 
- Sbt version: 1.5.0

#### Possible Solution

N/A

#### Additional context

This is the Redis Bloom module, running in a Docker container.

PS: Thanks for builing lettuce!

**Comment by mp911de** [comment]
We introduced recently `JfrEventRecorder` as a utility that looks for a class starting with `Jfr` and the event name in the same package as the actual event to be emitted. We lookup the first constructor (which is expected to take the original event as a constructor argument). Creating the JFR event object fails for some reason fails with a `ClassCastException`.

We planned to ship a service release today so it would make sense to consider this problem for a fix. Can you provide a bit more details? I'm not able to reproduce the issue, so it would be good if you can step through `JfrEventRecorder` and specifically inspect the constructor that was determined to be used and how the event class and the JFR types play together in terms of class loader origins and assignability.

**Comment by mcgizzle** [comment]
Thanks for the quick reply! Let me see if I can get a minimal reproducible

**Comment by mp911de** [comment]
Given that I know next to nothing about Scala and SBT, I'm not keen on spending time learning these things so shortly before a release.

**Comment by mcgizzle** [comment]
Just to give you an update.

The error is not occuring when I run via my IDE so I am struggling to debug it. It does happen on CI though, so its not just my machine.

I tried to produce a java repro, but could not trigger the error.

**Comment by mp911de** [comment]
It sounds a bit as if class loaders are involved. Moving on with the 6.1.1 release as we cannot do here anything short-term.

**Comment by mcgizzle** [comment]
You were indeed correct about it being a classpath issue, thanks for the hint! 

I am straying into unfamilair teritories here, but after reading [this](https://www.scala-sbt.org/1.x/docs/In-Process-Classloaders.html) I changed the strategy to:
> Flat - No layering is used. The full classpath, as specified by the fullClasspath key of the task is loaded in the outermost layer. Consider using as an alternative to fork if any issues are experienced with ScalaLibrary or if the application requires all classes to be loaded in the same ClassLoader, which may be the case for some uses of java serialization. 

And the error disapeared!

My IDE uses `jdk.internal.loader.ClassLoaders` while sbt uses its own class loader, which explains why it wasn't failing there.

I'm going to do some investigation into class loaders to see what this all means...
