### ISSUE TITLE
Dynamic Redis Command API: Command MSET requires at least 2 parameters but method declares 1 parameter(s)

### ISSUE THREAD

**Issue by mikelewheely** [lettuce-io/lettuce-core#1730]
#### Current Behavior

Using dynamic command interfaces the **mset** command is not taking Map of values as a parameter for input and throws **CommandMethodSyntaxException** 

<details>
<summary>Stack trace</summary>

```java
io.lettuce.core.dynamic.CommandMethodSyntaxException: Command MSET requires at least 2 parameters but method declares 1 parameter(s). Offending method: public abstract rx.Observable<java.lang.String> com.my.services.cache.MyCommands.mset(java.util.Map<java.lang.String, byte[]>)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
public interface MyCommands extends Commands {

  Observable<byte[]> get(String key);
  Observable<byte[]> mget(String... keys);
  Observable<String> set(String key, byte[] value, SetArgs args);
  Observable<String> mset(Map<String, byte[]> values);// offending command
  Observable<String> hmset(String key, Map<String, byte[]> values);
  Observable<Long> del(String... keys);
  Observable<Boolean> expire(final String key, final int seconds);
  Observable<Map<String, byte[]>> hgetAll(final String key);
  Observable<Long> ttl(final String key);
  Observable<Long> exists(final String key);
  Observable<Long> rpush(final String key, final byte[][] strings);
  Observable<Long> rpushx(final String key, final byte[] string);
  Observable<Long> llen(final String key);
}

RedisCommandFactory factory = new RedisCommandFactory(client.connect());

....

newCommands = factory.getCommands(MyCommands.class);

    public Observable<String> mset(Map<String, byte[]> values) {
        return newCommands.mset(values);
    }



```

</details>

#### Expected behavior/code

Expected it to work like the previous versions of **biz.paluch.redis** that used _RedisReactiveCommands_

#### Environment

- Lettuce version(s): 6.1.0.RELEASE
- Redis version: 6.0.9

#### Additional context

I am migrating from **biz.paluch.redis**  version _4.4.5.Final_ to **io.lettuce** _6.1.0.RELEASE_ previously the reactive command _RedisReactiveCommands.mset_ was taking one parameter (a Map) and this is what we were using but I am now using command interfaces to return a _rx.Observable_ and it is giving me this exception.

**Comment by mp911de** [comment]
`RedisReactiveCommands` is a static API where the given map is being translated to key-value tuples. The example above declares in a dynamic Redis command method and the interface has no way to know how the map should be serialized (key key key value value value, key value, key value, …). Dynamic command methods resemble somewhat the Redis CLI and ideally expect fixed parameters to pass the command validation.

You can disable command validation on `RedisCommandFactory`.

**Comment by mikelewheely** [comment]
Thanks for this, this got me past that error, but I am facing something similar for **hgetAll**

> java.lang.IllegalArgumentException: Cannot resolve CommandOutput for result type rx.Observable<java.util.Map<java.lang.String, byte[]>> on method public abstract rx.Observable com.my.services.cache.MyCommands.hgetAll(java.lang.String).

Again this was the return type in the previous versions of the RedisReactiveCommands API before the breaking changes to the return type.

Do you know how to resolve this?

Same Command interface above with 

` 
         public rx.Observable<Map<String, byte[]>> hgetAll(String key) {
            return newCommands.hgetAll(key));
        }`

**Comment by mikelewheely** [comment]
Can anyone help me with the above issue?

**Comment by mp911de** [comment]
You see the failure because Lettuce registers only symmetric codecs (`StringCodec`, `ByteArrayCodec`) where key and value types are the same (`Map<String, String>` or `Map<String, byte[]>`).  You can address the issue by providing a `RedisCodec<String, byte[]>`.
