### ISSUE TITLE
The web application [ROOT] appears to have started a thread named [lettuce-eventExecutorLoop-1-1] but has failed to stop it.

### ISSUE THREAD

**Issue by sj0227kim** [lettuce-io/lettuce-core#1733]
#### Current Behavior
I made the batch application by using CommandLineRunner.
This batch application is triggered by Jenkins Cron Scheduler.
When the batch application is triggered, read and write a data in redis repository. 
The problem is occurred on the step of stopping the application.

I am curious about the reason of occuring WARN Message. - "The web application [ROOT] appears to have started a thread named [lettuce-eventExecutorLoop-1-1] but has failed to stop it. This is very likely to create a memory leak."

Please see below stack trace for more details.

<details>
<summary>Stack trace</summary>
2021-04-27 16:43:48.514  WARN [facebook-batch,,,] [127.0.0.1] [localhost] 47132 --- [           main] o.a.c.loader.WebappClassLoaderBase       [o.a.j.l.DirectJDKLog > log:173] : The web application [ROOT] appears to have started a thread named [lettuce-eventExecutorLoop-1-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
 io.netty.util.concurrent.SingleThreadEventExecutor.takeTask(SingleThreadEventExecutor.java:256)
 io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:64)
 io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
 io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.lang.Thread.run(Thread.java:748)

</details>

#### Input Code

<details>
<summary>Input Code</summary>

application.yml
redis.cluster.pool.minIdle: 2
redis.cluster.pool.maxIdle: 4
redis.cluster.pool.maxTotal: 6
redis.cluster.pool.jmxEnable: false
redis.cluster.pool.maxWaitMillis: -1
redis.cluster.pool.testOnBorrow: false
redis.cluster.pool.testOnReturn: false
redis.cluster.pool.testWhileIdle: true
redis.cluster.commands.timeoutMilliSeconds: 1500
redis.cluster.commands.asyncTimeoutMilliSeconds: 3000
redis.cluster.commands.setBaseExpireSeconds: 86400

RedisClusterPoolConfig.java
public class RedisClusterPoolConfig {

    private final RedisClusterProperties redisClusterProperties;

    @Bean
    public ClusterTopologyRefreshOptions clusterTopologyRefreshOptions() {
        ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enablePeriodicRefresh(Duration.ofSeconds(30))
                .enableAllAdaptiveRefreshTriggers()
                .build();
        return topologyRefreshOptions;
    }

    @Bean
    public ClusterClientOptions clusterClientOptions() {
        return ClusterClientOptions.builder()
                .topologyRefreshOptions(clusterTopologyRefreshOptions())
                .build();
    }

    @Bean
    public LettuceConnectionFactory redisConnectionFactory() {
        RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration();
        redisClusterConfiguration.setClusterNodes(redisClusterProperties.getRedisNodes());
        redisClusterConfiguration.setPassword(redisClusterProperties.getPassword());

        LettuceClientConfiguration lettuceClientConfiguration = LettuceClientConfiguration
                .builder()
                .readFrom(ReadFrom.REPLICA_PREFERRED)
                .clientOptions(clusterClientOptions())
                .commandTimeout(Duration.ofMillis(redisClusterProperties.getCommands().getTimeoutMilliSeconds()))
                .build();

        return new LettuceConnectionFactory(redisClusterConfiguration, lettuceClientConfiguration);
    }
}
</details>

#### Expected behavior/code

I saw the usage of cpu and memory on VisualVM.
But I could not find any problems.
The status of the thread [lettuce-eventExecutorLoop-1-1] was PARK.
There were another threads [lettuce-eventExecutorLoop-1-2, lettuce-eventExecutorLoop-1-3] that the status is PARK. 
But only the thread [lettuce-eventExecutorLoop-1-1] was mentioned in the log file.

#### Environment

- Lettuce version(s): 5.3.3.RELEASE
- Redis version: 5.0.8

**Comment by mp911de** [comment]
Lettuce starts I/O threads to do its work. Make sure to properly shut down `LettuceConnectionFactory` so that Lettuce worker threads get stopped upon application shutdown.

**Comment by sj0227kim** [comment]
I appreciate your quick reply, would you let me know more details about the solution?

**Comment by mp911de** [comment]
Make sure that `LettuceConnectionFactory.destroy()` gets called, specifically `RedisClient.shutdown()` and `ClientResources.shutdown()`. That all should be handled by `LettuceConnectionFactory`.

**Comment by sj0227kim** [comment]
As your advice I called LettuceConnectionFactory.destroy() at the end of the batch job and therefore the problem was fixed. 
Thank you for your guidance.

**Comment by ankitaCogno** [comment]
Where did you exactly called destroy method in your code
