### ISSUE TITLE
ClusterTopologyRefresh may cause the leakage of connections.

### ISSUE THREAD

**Issue by Rena1ssanc3** [lettuce-io/lettuce-core#1736]
First of all, it's indeed my fault to construct an extreme case, which i've never seen before. I've spent hour reading issues and wiki for the solution, but unfortunately there's nothing about it.

The cluster is wrongly built, which cluster-announce-ip is not configured (application is unable to connect to the inner ip). It leads to the wrong answer of  nodes' addresses. When trying to refresh it's topology, lettuce will send a info request to nodes, and take the wrong addresses. I found that RedisURIs increase from 6 to 12. Half of them are inner ip addresses. Since the addresses are unreachable, lettuce should close those connection to nodes, but it doesn't work. After many retries, thousands of connections are established. All those connections are named lettuce#ClusterTopologyRefresh, with only one command labeled info, and just waiting for the next request.

There's no limit of ClusterTopologyRefresh's connections, neither the safety ensurance of closing those unused connection. 

- Lettuce version: 5.2.2.RELEASE
- Redis version: 4.0.11

Should I upgrade my lettuce?

**Comment by mp911de** [comment]
I think earlier Lettuce versions could leave connections open. Please upgrade at least to Lettuce 5.3, better 6.1.

**Comment by mp911de** [comment]
Duplicates #1342

**Comment by applike-ss** [comment]
Having the same issue with 6.5.0 using dragonfly 1.25.2. refs: https://github.com/dragonflydb/dragonfly/issues/4244

**Comment by tishun** [comment]
Hey @applike-ss ,

Do I read the comment in https://github.com/dragonflydb/dragonfly/issues/4244#issuecomment-2517004988 right and it confirms that the issue is on the server side?

**Comment by applike-ss** [comment]
Hey @tishun,

It does sound like it, however we can only be 100% certain once it doesn't happen frequently anymore after they released a patches version.
I will continue to support them in hope that they can resolve it quickly.

**Comment by tishun** [comment]
> Hey @tishun,
> 
> It does sound like it, however we can only be 100% certain once it doesn't happen frequently anymore after they released a patches version. I will continue to support them in hope that they can resolve it quickly.

Sure, makes sense.
