### ISSUE TITLE
Introduce API to allow for extending RedisClusterClient and its connections

### ISSUE THREAD

**Issue by jruaux** [lettuce-io/lettuce-core#1754]
## Feature Request

I'm working on an extension of Lettuce to support modules, and similar to issue [#33](https://github.com/lettuce-io/lettuce-core/issues/33) I would like to introduce 2 methods in `RedisClusterClient`:
- `newStatefulRedisConnection`
- `newStatefulRedisClusterConnection`

Also in `StatefulRedisClusterConnectionImpl` constructor:
```
this.async = newRedisAdvancedClusterAsyncCommandsImpl();
this.sync = newRedisAdvancedClusterCommandsImpl();
this.reactive = newRedisAdvancedClusterReactiveCommandsImpl();
```

Happy to submit a PR for this.

**Comment by mp911de** [comment]
Sure, feel free.

**Comment by jruaux** [comment]
Submitted PR #1755
