### ISSUE TITLE
How to select db for cluster ？

### ISSUE THREAD

**Issue by yuruyigit** [lettuce-io/lettuce-core#1758]
How to select db for redis cluster

**Comment by yuruyigit** [comment]
Jedis cluster supports select db

**Comment by pendula95** [comment]
From Redis website - [link](https://redis.io/topics/cluster-spec)

> Redis Cluster does not support multiple databases like the stand alone version of Redis. There is just database 0 and the SELECT command is not allowed

**Comment by yuruyigit** [comment]
> From Redis website - [link](https://redis.io/topics/cluster-spec)
> 
> > Redis Cluster does not support multiple databases like the stand alone version of Redis. There is just database 0 and the SELECT command is not allowed

Some cloud services support cluster selection db, should we also support it?
