### ISSUE TITLE
RedisURI.toURI() lost port info while using default Redis port 6379

### ISSUE THREAD

**Issue by yuan-yao-rft** [lettuce-io/lettuce-core#1771]
Code example;

```
RedisURI redisURI = RedisURI.create("127.0.0.1",6379);
URI uri = redisURI.toURI();
URI uri1 = URI.create("redis://127.0.0.1:6379");
System.out.println(redisURI);
System.out.println(redisURI.getPort());
System.out.println(uri);
System.out.println(uri.getPort());
System.out.println(uri1);
System.out.println(uri1.getPort());

```

output (we can see `uri` has lost the port info)
```
redis://127.0.0.1
6379
redis://127.0.0.1
-1
redis://127.0.0.1:6379
6379
```

Causes:
`if(port == DEFAULT_REDIS_PORT)`
then `getPortPart()` 
returns `""` instead of `":"+port` 

under `toURI()`
`URI.create(this.createUriString(false))`
is now `URI.create("redis://127.0.0.1")` 
no port info, leads to a default port -1 of `URI`

**Comment by mp911de** [comment]
Care to submit a pull request?

**Comment by yuan-yao-rft** [comment]
> ~Care to submit a pull request?~
> 
> Actually, let's hold off for a bit. If a URI doesn't specify a port, then the scheme-default port applies. You wouldn't want to write `http://localhost:80` either but rather represent the URI with `http://localhost` and let the participating component determine the right port.

That's true for createUriString(), but not true when converting back to URI.
The port info should remain when converting to URI, as there is no way to set port after creating URI object.

URI.create("redis://127.0.0.1") will resulting "redis://127.0.0.1" with port "-1"
RedisURI.create("redis://127.0.0.1") will resulting "redis://127.0.0.1" with port "6379"

as it behaves differently, the default port should remain when using RedisURI.toURI()

I agree that participating component should determine the right port, however, when I tried to use JedisPool with URI converted from RedsiURI, no default port comes to play. I will make sure that later.

**Comment by mp911de** [comment]
`RedisURI` is not `URI` and `URI` therefore does not know the port. `RedisURI` is a more capable representation of Redis connection details and can therefore handle port defaulting unless a port different than the Redis default port was used.

We do not want to change the API here. If you need to adjust URI creation, feel free to do this in your own code.
