### ISSUE TITLE
cancelCommandsOnReconnectFailure should have appropriate warnings.

### ISSUE THREAD

**Issue by tawAsh1** [lettuce-io/lettuce-core#1787]
#### Is your feature request related to a problem? Please describe

These problems may be caused by `cancelCommandsOnReconnectFailure` being set to `true`.
https://github.com/lettuce-io/lettuce-core/issues/1753
https://github.com/lettuce-io/lettuce-core/issues/1645
https://github.com/lettuce-io/lettuce-core/issues/915

#### Describe the solution you'd like
When `cancelCommandsOnReconnectFailure` is `true`, `reset()` may be called if reconnect fails.
The `reset()` command can cause serious issue, as pointed out in these issues.

https://github.com/lettuce-io/lettuce-core/issues/907#issuecomment-434392684
https://github.com/lettuce-io/lettuce-core/blob/ee3e70f613074531aef9874a01bbbeb72dbd2cbb/src/main/java/io/lettuce/core/RedisChannelWriter.java#L73

However, the `cancelCommandsOnReconnectFailure` option does not any warnings about the possibility of causing a protocol offset now.
https://github.com/lettuce-io/lettuce-core/blob/cda3be6b9477da790365ad098c6e39c8687f5002/src/main/java/io/lettuce/core/ClientOptions.java#L203
https://github.com/lettuce-io/lettuce-core/wiki/Client-Options

Therefore, at the least, these possibility should be fully explained.

**Comment by tokuhirom** [comment]
@mp911de 

I think `cancelCommandsOnReconnectFailure ` option should be deprecated. If I understand correctly, this option is not needed after Lettuce implements the SSL feature.

**Comment by mp911de** [comment]
These options were introduced indeed in a time where Lettuce SSL had to be used through SSL tunnels like `stunnel`. We  should deprecate that option for removal with Lettuce 7. Do you want to submit a pull request?

**Comment by mp911de** [comment]
I updated the reference docs via https://github.com/lettuce-io/lettuce-core/wiki/Client-Options/_compare/4c890e4b690a4d1713d2944e57deb1476352ef2d...6a47d87c416f88c3a63120fe50aebb6eece4b7fe

**Comment by tawAsh1** [comment]
Since the impact of protocol offsets is critical, I think it is necessary not only to deprecate it, but also to announce it to the community if possible.

**Comment by mp911de** [comment]
Thanks a lot. We're going to mention it in the release notes properly.
