### ISSUE TITLE
Question: Get the original bytes of redis' response

### ISSUE THREAD

**Issue by jjz921024** [lettuce-io/lettuce-core#1794]
## Feature Request
Hi, all

#### Is your feature request related to a problem? Please describe

In lettuce, these any way get redis's bytes response without decode?

For example, there is a <key1, value1> pair in redis. 
When i send `get key1` using lettuce, i will get original bytes array of redis `$6\r\nvalue1\r\n` instead of `value1`

Because of, i am working a proxy of redis.  When outbound, i don't need any process,
so, this will be very convenient,  if i can get orginal bytes, i can return directly client

#### Describe the solution you'd like
I guess, can we implement a `CommandOutput` without decode?
But i can't find where lettuce decode bytes?

I'd appreciate if someone can let me know how to do
also, I'd like to work on it if it really need this feature

**Comment by mp911de** [comment]
> In lettuce, these any way get redis's bytes response without decode?

No there isn't and what you're trying is going to be difficult with Redis. Take a look at Netty's Redis Codecs at https://netty.io/4.1/api/io/netty/handler/codec/redis/RedisDecoder.html.
