### ISSUE TITLE
Can not combine with other RedisFuture

### ISSUE THREAD

**Issue by spongebobZ** [lettuce-io/lettuce-core#1795]
I am trying to combine two redisFuture object via the method thenCombineAsync but got the exception of type mismatch.Here's the detail
`
val category_name_fut: RedisFuture[String] = async.hget(s"category.${input._1}", "category_name")
val item_name_fut: RedisFuture[String] = async.hget(s"item.${input._2}", "item_name")

category_name_fut.thenCombineAsync(item_name_fut,
        (t: String, u: String) => {
          (input._1, t, input._2, u)
        })
        .thenAccept(x => resultFuture.complete(Iterable(x)))

exception info:
type mismatch;
 found   : io.lettuce.core.RedisFuture[String]
 required: java.util.concurrent.CompletionStage[_ <: U]
      category_name_fut.thenCombineAsync(item_name_fut,
`

**Comment by mp911de** [comment]
Not sure what the code is supposed to do. We cannot support you with questions that are specific to your programming language.
