### ISSUE TITLE
Make possible to set up intent for Lua script

### ISSUE THREAD

**Issue by QIvan** [lettuce-io/lettuce-core#1799]
Hi! 

First of all, it's just for the record for people who met with 
```
ERR Error running script: -READONLY You can't write against a read only replica.   
```
as a result of some Lua script execution. That happens because you, probably, set up `readFrom` settings for your Redis connection as non `UPSTREAM` or `null` value. That leads to making "intent" for your operation as "read" ([see these lines of code](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/cluster/PooledClusterConnectionProvider.java#L129-L131)). But your script, probably, has some write operations. So, regarding https://redis.io/commands/readonly 
```
When the connection is in readonly mode, the cluster will send a redirection to the client only if the operation involves keys not served by the replica's master node
```
and regarding the fact, our beloved lettuce library is smart enough and can place your request to the right node according to the keys you provided, you end up with a read-only connection that is being used for a write operation. 

Please note, in this case, there will be no `MOVED` results, because you're already talking to the right node and it tries to serve your request. 

### Questions to the lettuce developers

Ok, now when we all know an existed issue please, let me ask few questions and raise some concerns:
1. First of all, seems like your change with renaming `MASTER` to `UPSTREAM` broke the default behaviour for `MASTER`. [The same lines of code](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/cluster/PooledClusterConnectionProvider.java#L129-L131) show us that even if we set up `readFrom = MASTER` all your Lua scripts will have `read` intention. That, probably, might lead to having requests on a replica node, instead of an upstream one (but correct me if I'm wrong)
2. It would be super nice if a user could provide `intention` for `eval` or `evalsha` calls. For example, in my application, we have 2 different Lua scripts: read-only and with write operations. Right now I don't see any solutions other than keeping 2 different `StatefulRedisClusterConnection`: with `readFrom = UPSTREAM` and `readFrom = REPLICA_PREFERRED` (or something similar), which is, IMHO, a complete resource-wasting, but without it, I have a risk either to be deprived of  `REPLICA_PREFERRED` benefits for the read queries or having issues as I described above. 

Would be glad to discuss this case and please, feel free to correct me if I'm mistaken at any point. 

Sorry for a long read, thank you very much for your time. 
I bet someone's brought up this issue already, but I hadn't been able to find one, feel free to redirect me.

**Comment by mp911de** [comment]
Thanks for reaching out. We should fix the issue with the `UPSTREAM`/`MASTER` constants. The intent is actually used to determine the right type of connection. You can route commands yourself by obtaining a node-connection through `connection.getConnection(Intent.WRITE, slot).async().eval(…)`. Only the slot remains to calculate, you can use the `SlotHash` utility for that.

Commands are defined on group interfaces (`RedisScriptingCommands`) that aren't tied to the Redis operation mode at all and introducing that concept would break the existing design.

**Comment by QIvan** [comment]
oh, wow, thanks @mp911de this approach would really help! 
but at the moment I kinda struggle to understand how can I access this `getConnection` method. We're talking about the method 
```
io.lettuce.core.cluster.PooledClusterConnectionProvider#getConnection(io.lettuce.core.cluster.ClusterConnectionProvider.Intent, int)
``` 
right? Could you help with the exact lines? 
```java 
RedisClusterClient client = RedisClusterClient.create(Collections.singleton(RedisURI.create("127.0.0.1", port)));
StatefulRedisClusterConnection<String, String> connection = client.connect();
// ???
// I found this way, but it won't compile 
// ((StatefulRedisClusterConnectionImpl) externalRedisConnection).getClusterDistributionChannelWriter().getClusterConnectionProvider().getConnection(ClusterConnectionProvider.Intent.WRITE, 42);
```

But even if I could access this method, the `io.lettuce.core.cluster.ClusterConnectionProvider.Intent` enum is package private. So users outside the library can't "officially" use it. 

Sorry, for maybe a dumb question, still getting familiar with the library. 
thank you for the help once again

**Comment by mp911de** [comment]
Sorry, my bad. I wanted to refer to `StatefulRedisClusterConnection` that exposes a `getConnection()` method returning a master connection.

**Comment by QIvan** [comment]
ah, ok, so, imagine we have a code like 
```java
RedisFuture<?> redisEval =
        connection()
            .async()
            .eval(
                script,
                ScriptOutputType.MULTI,
                keys,
                values);
```
you're saying it could be rewritten with 
```java
StatefulRedisConnection<String, String> nodeConnection =
    connection()
        .getConnection(
            connection()
                .getPartitions()
                .getPartitionBySlot(SlotHash.getSlot(keys[0]))
                .getNodeId());
RedisFuture<?> redisEval = nodeConnection.async()
    .eval(
        script,
        ScriptOutputType.MULTI,
        keys,
        values);
```

am I right?

**Comment by mp911de** [comment]
Yeah, the code from above is exactly what you need.

**Comment by Chivenh** [comment]
I see you have changed the src/main/java/io/lettuce/core/masterreplica/ReadOnlyCommands.Com mandName read-only command definition, want to ask, this change can take effect in which version?
