### ISSUE TITLE
Attach the completion first and then start the span

### ISSUE THREAD

**Issue by zmapleshine** [lettuce-io/lettuce-core#1803]
## Bug Report

The code in the following line：
https://github.com/lettuce-io/lettuce-core/blob/a39b05b564ade64c27cd3deae3e660a442060b00/src/main/java/io/lettuce/core/protocol/CommandHandler.java#L429

When  the ``start()`` method of span is called , and before attaching the callback to the command, the callback function may not be executed due to system load problems.

This means that whether or not the span can be closed is affected by the system load or other factors and timeout setting, which is obviously not appropriate. The span should ensure that it can be closed 100% correctly, as if it were in a "finally" block.
#### Current Behavior

The span is not always closed because the callback function is not always executed.
#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Expected behavior/code

After span starts, there will be an opportunity to close.

#### Environment

- Lettuce version(s): [5.1.x,5.3.x]
- Redis version: [4.0.x]

#### Possible Solution

Add a mechanism to check if a span is closed, such as a delayed queue, or some other way to ensure that the span is closed correctly.

#### Additional context

see #1652

**Comment by mp911de** [comment]
Thanks for the report. After investigating the linked code vs. the current implementation, I found that we already follow this approach in Lettuce 6:

https://github.com/lettuce-io/lettuce-core/blob/7a8fd312b65e311514522270df816a37a71df447/src/main/java/io/lettuce/core/tracing/BraveTracing.java#L346-L368

The referenced commit a39b05b564ade64c27cd3deae3e660a442060b00 points to an outdated version that isn't maintained anymore. Therefore I would like to close this ticket.

**Comment by zmapleshine** [comment]
The problem may have nothing to do with the order of "Set Callback" and "Start Span." Although the callback function is set first, there is no guarantee that the callback will be executed if the timeout exceeds after the span has started and before the ChannelHandlerContext executes the write method.

**Comment by mp911de** [comment]
As soon as the callback function is attached to the command, it will be called as part of the command completion/timeout. The command doesn't need to be written to make spans work.
