### ISSUE TITLE
When connected and use async hset-function ，find a problem

### ISSUE THREAD

**Issue by aloserman** [lettuce-io/lettuce-core#1818]
## Bug Report

When connected and use async hset-function ，and thenAcceptAsync function  will returned a boolean value ，if key and field and value exist，the returned value is FALSE，the source value will be not overwirte。

show my code ：
```
                   long l = System.currentTimeMillis();
                    StatefulRedisConnection<String, String> connection = redisClient.connect();
                    RedisFuture<Boolean> hset = connection.async().hset(value.get(0), value.get(1), value.get(2));
                    hset.thenAcceptAsync(new Consumer<Boolean>() {
                        @Override
                        public void accept(Boolean aBoolean) {
                            if (aBoolean) {
                                Boolean expire = connection.sync().expire(value.get(0), 60 * 10);
                                if (count % 10000 == 0) {
                                    System.out.println(count + "_" + expire);
                                }
                                connection.close();
                                System.out.println(System.currentTimeMillis() - l);
                            } else {
                                connection.close();
                                System.out.println("failed");
                            }
                        }
                    });
                } catch (Exception e) {
                    e.printStackTrace();
                }
````

**Comment by mp911de** [comment]
Please stop using synchronous API within asynchronous callbacks as that will block the eventloop. Instead, please use the async API all the way.

**Comment by aloserman** [comment]
> Please stop using synchronous API within asynchronous callbacks as that will block the eventloop. Instead, please use the async API all the way.

now the code as follow ,but the problem is also;
`                    long l = System.currentTimeMillis();
                    StatefulRedisConnection<String, String> connection = redisClient.connect();
                    RedisFuture<Boolean> hset = connection.async().hset(value.get(0), value.get(1), value.get(2));
                    hset.thenAcceptAsync(new Consumer<Boolean>() {
                        @Override
                        public void accept(Boolean aBoolean) {
                            if (aBoolean) {
                                connection.async().expire(value.get(0), 60 * 10).thenAcceptAsync(new Consumer<Boolean>() {
                                    @Override
                                    public void accept(Boolean aBoolean) {
                                        connection.close();
                                        System.out.println(System.currentTimeMillis() - l);
                                    }
                                });
                            } else {
                                connection.close();
                                System.out.println("failed");
                            }
                        }
                    });
                } catch (Exception e) {
                    e.printStackTrace();
                }`

**Comment by mp911de** [comment]
` connection.close();` is a blocking method. Please rather use `closeAsync`.
