### ISSUE TITLE
High volume of repeated queries

### ISSUE THREAD

**Issue by Z3r0byte** [lettuce-io/lettuce-core#1819]
## Bug Report

We currently use the lettuce library as a redis client in one of our applications (it's a great library btw). A couple of days ago we noticed an increased load on our servers. After investigating a packet dump, we found that our application was sending a large volume of the same query to the redis server at a very high rate (1000+/second). 

#### Current Behavior

A large amount of the same query is sent at a high rate to our redis server. The redis replies with the correct value. This does not stop until the application is restarted. 

This behaviour seems to start at seemingly random moments and the query sent differs and originates from different places in the application. Since one of the queries we spotted should immediately be followed by another query and taking into account that the queries we spotted came from different places in our applications it seems unlikely there is a bug (such as a infinite loop) in our code causing this.

What we know (most of the info below is anecdotally collected from 3 packet dumps):

- The query is an HGET command (although most of the commands we issue are HGET, so this might not necessarily mean that it's related).
- The issue happens on multiple servers (at different times from what we can tell from metrics)
- The issue sometimes causes average bandwidth of about 10 Mbit/s between client and server (normal average is about 1 Mbit/s)
- It sometimes sends one query and then waits for the response after which it repeats the same query
- It sometimes sends multiple queries, waits for a reply to all those queries (which arrives in one packet) and then repeats those same queries. In the one packet dump that showed this behaviour, every query of this "batch" was the same.
- No errors are shown in the console or our error collection service.
- It can run fine for hours until it starts showing this behaviour.

#### Input Code

Our java code uses the synchronous interface of lettuce to get data from the Redis database. It uses a standalone master/slave setup using the `ReadFrom.NEAREST` read strategy (which most of the time results in reads from the master).  The same command interface is used across the entire application (which is multi-threaded). The default timeout is set to one second.

I wouldn't know which piece of code would be of particular interest, but let me know if there's anything specific you'd like to see.

#### Expected behavior/code

The client should not keep repeating those queries.

#### Environment

- Lettuce version(s): 6.1.4-Release
- Redis version: 6.2.5

#### Possible Solution

If I had to guess, this looks like some retry logic going wrong.

#### Additional context

Packet dump of command-response-repeat behaviour: (.11 is client, .128 is the redis master)
![afbeelding](https://user-images.githubusercontent.com/8726909/127985391-a83b1691-f5e2-415e-80f2-60d1c39f51eb.png)

I hope this information will be sufficient. I have added all the details I could think of, but if there's anything you'd like to know, please say so.

**Comment by mp911de** [comment]
Without knowing where the command originates, it's impossible to tell what triggers the increased load. If you're able to reproduce the issue in a debugger, please look into `DefaultEndpoint.write` and check what triggers the command.

**Comment by Z3r0byte** [comment]
Thanks for the reply.
The connection itself is created as a singleton and initialized as follows:
```
        RedisURI upstreamUri = RedisURI.Builder.redis(host, port).build();
        RedisClient redisClient = RedisClient.create();
        redisClient.setDefaultTimeout(Duration.ofSeconds(1));

        StatefulRedisMasterReplicaConnection<String, String> redisConnection = MasterReplica.connect(redisClient, StringCodec.UTF8, upstreamUri);
        redisConnection.setReadFrom(ReadFrom.NEAREST);

        try {
            RedisCommands<String, String> commandInterface = redisConnection.sync();
        } catch (RedisException e) {
            System.out.println("Could not connect to redis: " + e.getMessage());
        }
```

After this, the `commandInterface` is shared between threads (every request to the app uses its own thread) and queries are made as follows:\
`redisInterface.hget(mapName, key)`

I'll try to replicate the issue in a debugger, but given that it usually takes hours before the issue is triggered this may be a bit difficult. Just to confirm, you want me to look into `DefaultEndpoint.write`? I'm not familiar with the underlying architecture, but this sounds like it has something to do with write commands, while the issue showed only with read commands up until this point. Also, could you tell me how I would access this `DefaultEndpoint.write` (ie is it part of the connection or is it located somewhere else)? Thanks

**Comment by Z3r0byte** [comment]
Hello,

Using some thread dumps I was able to find an issue in our software which explains most of the issues we've experienced. The other few instances were probably just me not looking carefully enough at the logs (and were probably expected behaviour) and I don't expect to see them again. Apologies for wasting your time with this issue and thanks again for creating this library.

**Comment by mp911de** [comment]
Thanks for your feedback.
