### ISSUE TITLE
AbstractCollection.removeAll() causes all threads blocked

### ISSUE THREAD

**Issue by pccpccpcc** [lettuce-io/lettuce-core#1824]
Hi Mark:  
I use lettuce 4.3.1 version.
All threads blocked when trying to lock stateLock, because AbstractCollection.removeAll() method own it long time.
![image](https://user-images.githubusercontent.com/32184501/128992314-ea12ceac-c93b-4d6d-a7b9-a7e26a80143a.png)
![image](https://user-images.githubusercontent.com/32184501/128992400-ccff4fcd-5498-4ee5-9bfd-71c6b4eb34cd.png)
Can someone help me?

**Comment by mp911de** [comment]
Version 4.x is no longer supported. Also, the behavior is by intent to synchronize if multiple threads try to access a shared resource. Please upgrade to lettuce 6 at your earliest convenience.

**Comment by pccpccpcc** [comment]
> Version 4.x is no longer supported. Also, the behavior is by intent to synchronize if multiple threads try to access a shared resource. Please upgrade to lettuce 6 at your earliest convenience.

you mean if i upgrade to lettuce 6,the bug can be fix?Thanks for you reply
