### ISSUE TITLE
Support `RedisConnectionStateListener` registration for individual connections

### ISSUE THREAD

**Issue by btthorstenwitt** [lettuce-io/lettuce-core#1838]
Hello, 

we develop a springboot application with `lettuce-core 6.1.4` in combination with the azure service: `Azure Cache for Redis 6`.

There is a simple class that manages the connection to the redis server:

```
@Component
public class SimpleRedisCache {


    private final Map<String,String> clientCache = new ConcurrentHashMap<>();
    private CacheFrontend<String, String> frontendCache;
    private StatefulRedisConnection<String, String> redisConnection;

    public String get(String key) {
        return frontendCache.get(key);
    }

    public String get(String key, Callable<String> valueLoader) {
        return frontendCache.get(key, valueLoader);
    }

    public void close() {
        frontendCache.close();
    }

    @PreDestroy
    public void preDestroy() {
        close();
    }

    @PostConstruct
    public void postConstruct()  {
        RedisClient client = RedisClient.create(getRedisURI());
        this.redisConnection = client.connect();
        this.frontendCache = ClientSideCaching.enable(
                CacheAccessor.forMap(clientCache),
                redisConnection,
                TrackingArgs.Builder.enabled());
    }

    private RedisURI getRedisURI(){
        return RedisURI.builder()
                 ...
                .build();
    }

```

As you can see we have activated the ClientTracking with:

```
this.frontendCache = ClientSideCaching.enable(
                CacheAccessor.forMap(clientCache),
                redisConnection,
                TrackingArgs.Builder.enabled());
```

This works fine at the startup of the application. But after 5 minutes the connection between Azure Redis Cache and the application gets lost and the ConnectionWatchdog does the reconnect: 

```
2021-09-01 11:32:29.098  INFO 1 --- [xecutorLoop-8-1] i.l.core.protocol.ConnectionWatchdog    : Reconnecting, last destination was demo-redis.redis.cache.windows.net/20.101.116.187:6380
2021-09-01 11:32:29.170  INFO 1 --- [lEventLoop-10-2] i.l.core.protocol.ReconnectionHandler    : Reconnected to demo-redis.redis.cache.windows.net:6380
```

This works very nice and I can see in the logs that the connection is open and the client has access to the keys in the cache. But after Watchdog does the Reconnect, the client tracking seems to be not active anymore.

Is this a bug or could you please tell me how to reactivate the client tracking?

**Comment by mp911de** [comment]
This is a known limitation and I currently don't have a good idea how to approach it. You could approach it through a ˋ RedisConnectionStateListenerˋ but that doesn't work well with multiple connections being used for different purposes. 

Maybe some per-connection listener registration could work.

**Comment by mp911de** [comment]
For a first step, I added `addListener(RedisConnectionStateListener)` to `StatefulConnection` so client code can register  listeners for particular connections and react to connects/disconnects. You can call `connection.async().clientTracking(tracking)` within the `onRedisConnected` method to re-enable client-side tracking of keys.

However, due to the disconnect, Redis doesn't have the information for which particular keys you want to get notified. There haven't been any keys touched in the context of the new connection.
