### ISSUE TITLE
Why does the reactive API doesn't have a method to delete keys?

### ISSUE THREAD

**Issue by gabrieeel** [lettuce-io/lettuce-core#1841]
## Feature Request

I'm using the reactive API, the RedisStringReactiveCommands interface in particular, and I'm wondering why there is no del() method in it.
All the interfaces and classes that extend/implement this interface have an implementation for this method, so is this something that could be added?

I know we have getdel() but it's not supported in older version of Redis.

Thanks!

**Comment by mp911de** [comment]
Have you seen `RedisKeyReactiveCommands.del(…)`. As per Redis' documentation, `DEL` is a key command, not a string command.
