### ISSUE TITLE
use"redisTemplate.opsForList().rightPop()"to return timeout

### ISSUE THREAD

**Issue by GoudanL** [lettuce-io/lettuce-core#1849]
## Bug Report

this's errorMessage: "Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 300 millisecond(s)"

#### Current Behavior

using"redisTemplate.opsForList().rightPop(LogUtil.getLogKeyOpsForHash(), 300, TimeUnit.MILLISECONDS);"to return timeout。but using "jedis" will not report an error.

this's configInfo" 
redis:
    timeout: 1000ms
this`s is maven:
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>   

```java
// your stack trace here;
String message = redisTemplate.opsForList().rightPop(LogUtil.getLogKeyOpsForHash(), 300, TimeUnit.MILLISECONDS);

- spring-boot-starter-data-redis version is 2.2.6.RELEASE
- lettuce-core is 5.2.2.RELEASE

**Comment by mp911de** [comment]
Jedis is implemented differently, they reconfigure the socket read timeout. We cannot do here anything as that concerns entirely the Jedis driver.
