### ISSUE TITLE
Can lettuce provide distributed locks in the future?

### ISSUE THREAD

**Issue by maozhen520** [lettuce-io/lettuce-core#1860]
hello， this is not a bug: 
Can lettuce provide distributed locks in the future? Similar to redisson, it can even renew the expiration time of the lock. I know that although I can directly use redisson as a redis client, our project has already used lettuce , It is good, but we need to use redis to implement distributed locks, so ask, will lettuce support lock-related operations later, or why not do lock-related things, I am curious about your ideas

**Comment by mp911de** [comment]
Thanks for reaching out. Lettuce is a pure driver that doesn't provide higher-level utilities built on top of Redis data structures. You might want to check out [Redisson](https://github.com/redisson/redisson).
