### ISSUE TITLE
Security Vulnerability reported for io.netty:netty-codec

### ISSUE THREAD

**Issue by ramsha-tariq** [lettuce-io/lettuce-core#1869]
#### Current Behavior

The project is using spring-boot-starter-date-redis v2.5.2, which is pulling in lettuce-core v6.1.3.RELEASE which has netty-codec:4.1.65.RELEASE.

The netty-codec has the following security vulnerability: https://github.com/advisories/GHSA-grg4-wf29-r9vv

#### Environment

- Lettuce version(s): [e.g. 6.1.3.RELEASE]
- Redis version: [e.g. 2.5.2]

**Comment by mp911de** [comment]
Duplicates #1264
