### ISSUE TITLE
ConnectionPool would be better if prepared before used

### ISSUE THREAD

**Issue by HashZhang** [lettuce-io/lettuce-core#1870]
First of all, we are aware of that we should use one connection because lettuce is non-blocking and reactive. But for applications where there are many redis transactions or redis pipeline commands, we should use connection pool to prevent connection creation for each call.

Secondly, the redis connection activation of lettuce is split into mainly two process:

1. TCP connection
2. Handshake, maybe some commands should be sent.

While we are using connection pool, there is a min-idle in the configuration. We expect there are min-idle connections in the connection pool before the application is ready, that is, there would be a  large amount of requests when the  application is ready and we expect all connections are ready before handing request in case connection failed because the handsahke command reach command timeout.

**Comment by mp911de** [comment]
`GenericObjectPool` doesn't automatically pre-populate its pool up to `min-idle` size, rather it uses `min-idle` as lower bound to retain a number of active connections in the pool. Generally speaking, pre-warming the pool is an application-specific requirement that may not be generally valid for all usages. If you feel that you need a pre-warmed pool, then please call `GenericObjectPool.prepare()` in your application. A `GenericObjectPool` is a pool with minimal resource allocation semantics and thus it creates connections on demand.

**Comment by HashZhang** [comment]
> `GenericObjectPool` doesn't automatically pre-populate its pool up to `min-idle` size, rather it uses `min-idle` as lower bound to retain a number of active connections in the pool. Generally speaking, pre-warming the pool is an application-specific requirement that may not be generally valid for all usages. If you feel that you need a pre-warmed pool, then please call `GenericObjectPool.prepare()` in your application. A `GenericObjectPool` is a pool with minimal resource allocation semantics and thus it creates connections on demand.

I see, maybe I should add this feature to spring-data-redis, thanks

**Comment by mp911de** [comment]
FWIW, Spring Data Redis doesn't pre-populate connections for Jedis or Lettuce. In any case, an interesting enhancement so closing this ticket here.
