### ISSUE TITLE
AWS ElastiCache Redis reconnection problem

### ISSUE THREAD

**Issue by naman-patel** [lettuce-io/lettuce-core#1873]
We use lettuce to connect to AWS ElastiCache Redis. Few days ago while upgrading redis we had an issue. 

1. We deployed the new app. The system was working fine.
2. We issued modify instance type to AWS.
3. When the new instance was created it came live and old instance was removed. The DSN name was the same but it had a new IP Address.
4. The connection still kept on making attempt to reconnect to old IP / PORT. 
5. We needed a bounce to APP.

On startup we have: `java.security.Security.setProperty("networkaddress.cache.ttl", "30")`

The connection kept on reconnecting to old IP Address for more than 10 minutes till we bounced the instances.

Lettuce version: 5.2.2

**Comment by yaboong** [comment]
@naman-patel 
I had exactly the same issue. I'm using ElastiCache with cluster mode enabled and accessing the cluster via configuration endpoint.

I'm not sure if it's okay to not use DNS caching as @mp911de mentioned, so I tried enablePeriodicRefresh to true like below.
```java
LettuceClientConfiguration.LettuceClientConfigurationBuilder builder = LettuceClientConfiguration.builder();

final var topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                                                                .enablePeriodicRefresh()
                                                                .build();
final var clientOptions = ClusterClientOptions.builder()
                                                        .topologyRefreshOptions(topologyRefreshOptions)
                                                        .build();
return builder.clientOptions(clientOptions).build();
```
It seems the default refresh interval is 60s when the refreshPeriod is not provided, and it works fine. 

Please let me know if there's a better way to solve this problem.
