### ISSUE TITLE
Add suggestions for plug-ins to support test coverage and test case execution success reports.

### ISSUE THREAD

**Issue by cjs1992-github** [lettuce-io/lettuce-core#1888]
One problem I found was that lettuce added support for jacoco, but following normal commands only got jacoco.exe and needed to be parsed by the user. In the community, test case coverage, test case execution success rate, and some details are unavailable.After a plug-in is added, developers can choose whether to use the plug-in as required.
display, so I have introduced three plug-ins to the POM to solve this problem. 
The solution is as follows:

![image](https://user-images.githubusercontent.com/74575955/138557532-74f4dc4c-816a-4a98-a41b-0e038cc25906.png)
![image](https://user-images.githubusercontent.com/74575955/138557539-065f4715-b2ba-4453-b9d5-52dc51618792.png)
After the plug-in is added, the command output is as follows:
![image](https://user-images.githubusercontent.com/74575955/138557559-b449e246-b3d0-489c-bb1e-12e1caa7b266.png)

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
