### ISSUE TITLE
`RoundRobinSocketAddressSupplier` is not refreshing when `RedisURI` changes

### ISSUE THREAD

**Issue by langchristian96** [lettuce-io/lettuce-core#1909]
## Bug Report
RoundRobinSocketAddressSupplier is not refreshing nodes IPs if only IPs change while nodeIds remain the same. Because of this the ConnectionWatchdog keeps retrying to connect with an old IP. (seems to be similar to what was reported under #1343 )

#### Current Behavior
- Redis cluster with 6 nodes running under Kubernetes
- Remove redis pods 2 by 2 until all of them get new IPs
- After a while, the connection is remade and io.lettuce.core.cluster.RoundRobinSocketAddressSupplier#get is being called
- Partitions supplier gives us the correct partition with same node Ids but different IPs (which is correct)
- The following reset code inside the if block does not get executed
`        if (!roundRobin.isConsistent(partitions)) {
            resetRoundRobin(partitions);
        }`
because the equals method from RedisClusterNode only compares the node ids
- We end up reconnecting using the old ip

#### Expected behavior/code
If the nodes IPs change, we should do the round robin rebuild. 

#### Environment

- Lettuce version(s): 6.1.5.RELEASE
- Redis version: 6.2.6

#### Possible Solution
Modify the equals method from RedisClusterNode to check the ip/uri as well

#### Additional context
dynamicRefreshSources was set to false and the DNS resolver used was DirContextDnsResolver

**Comment by langchristian96** [comment]
On a second thought, comparing the URIs might not be the most correct approach since there can be aliases and it might affect other parts of the code. I think it might be better to go on another route and modify the reset conditions to check specifically if anything changed from an URI pov. Any thoughts on this?

**Comment by mp911de** [comment]
I'm happy for suggestions on how we can improve here.

**Comment by langchristian96** [comment]
@mp911de, I've made the changes I suggested. Mind taking a look when you have time please?

**Comment by langchristian96** [comment]
Managed to test the problematic scenario as well today and confirmed it works fine with the fix
