### ISSUE TITLE
Cannot determine own partition of redis cluster

### ISSUE THREAD

**Issue by journey51** [lettuce-io/lettuce-core#1911]
## Bug Report

Connect to Alibaba cloud redis cluster through direct connection，
Error: java.net.ConnectException: Connection refused: connect

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
