### ISSUE TITLE
A question about the letuce CI project view

### ISSUE THREAD

**Issue by cjs1992-github** [lettuce-io/lettuce-core#1914]
#### Current Behavior
I'm concerned about the whole lettuce build, so I wanted to look at the lettuce build project and see that lettuce useshttps://www.travis-ci.com/lettuce-io/lettuce-coreaddress to build, but I couldn't find anything after I linked it through the README.md link,The interface reports 404, but I clicked the codecov next to it and found that the link is available, please check whether this is a problem?

<details>
<summary>Stack trace</summary>
![image](https://user-images.githubusercontent.com/74575955/141985746-1c7bcee5-46a3-4f1c-a091-00347d3c79e9.png)

If you go through this link, the 404 interface will appear. I confirm that you have logged in to travis-ci and associate github with travis-ci.
I'm not sure if it's my operation or if the link is really unavailable, please check it out.

**Comment by mp911de** [comment]
Travis CI has switched to a more commercial model with a set of free minutes for OSS projects. We're not using Travis CI anymore as it creates a lot of hassle and we need to clean up the CI descriptors.

**Comment by cjs1992-github** [comment]
Thanks for your attention. Recently, I was compiling lettuce. I found the number and coverage of test cases that I executed using mvn test and directly executed using make test-coverage PROFILE=${PROFILE:-ci}" in .travis.yml.
It's not the same. I think you did the shielding. When I execute the .travis.yml process, I need to install a lot of software and import environment variables. Is there a guide for local compilation?

**Comment by mp911de** [comment]
Yes, there is at https://github.com/lettuce-io/lettuce-core#building.

However, it doesn't say which packages to install because each platform and each linux distro uses different package names.

**Comment by cjs1992-github** [comment]
Thanks for your reply, I've compiled it successfully. I found the cause of the problem above, and the "build" connection is now pointed tohttps://www.travis-ci.com/lettuce-io/lettuce-coreIf this address is used, 404 will be reported, but
The previous address should be "https://www.travis-ci.org/github/lettuce-io/lettuce-coreIf you use this address, the connection is available. I see you said you want to clean up the connection, did CI project change the address?

**Comment by mp911de** [comment]
TravisCI switched all OSS projects to paid plans and I have no intentions to pay for TravisCI as the only value is a publicly visible CI. I have a private Jenkins machine running for Lettuce.

![Bildschirmfoto 2021-11-26 um 13 48 43](https://user-images.githubusercontent.com/1035015/143583531-afb3e8c9-8128-4ff4-af1c-f02ae0fb185e.png)

**Comment by mp911de** [comment]
Removed TravisCI.
