### ISSUE TITLE
Decreasing number of connection in redis cluster mode

### ISSUE THREAD

**Issue by armasanea** [lettuce-io/lettuce-core#1915]
## Feature Request

This a question first and foremost, which might turn into a feature request

#### Is your feature request related to a problem? Please describe

We're using lettuce in a microservice-based architecture. We have relatively many small(ish) services that mostly scale horizontally, due to which we have many service instances (thousands in a single cluster). We have some shared Redis clusters to which each service instance connects. Due to this we are seeing connection counts in the tens of thousands on the shared redis clusters (an AWS hosted Redis in cluster topology). 
We use readFrom=ANY mostly to offload the heavy read workload to replicas.
The lettuce docs have the documentation on how many connections a single lettuce object creates: https://lettuce.io/core/release/reference/#redis-cluster.connection-count
I was able to confirm that in cluster mode with readFrom=ANY the replicas get 2 connections: one with flags=N (normal connection) and a second one with flags=r (readonly connection). Leaders get 2 connections too, only both with flags=N.
Based on limited observations it seems that the flags=r connection and one of the leader connection has last command=ping, though unsure if that's always the case.

#### Describe the solution you'd like

First a question: where does the need to have 2 connections per node in cluster mode come from? Is it just a matter of ease of implementation or is there something gained by having the separate connections?
Assuming the extra connections are not giving us some benefit, it would be nice to have a single connection per node since the flags=N connection should be able to satisfy all the workload.

#### Describe alternatives you've considered

There are optimizations in the number of lettuce objects we create per service instance, but once we implement those the lettuce driver limits are the next optimization opportunity.

#### Teachability, Documentation, Adoption, Migration Strategy

Having a lower connection count per lettuce object will be a useful feature for large-scale Redis users which might be creeping up towards the connection limits (for AWS the connection limits are at 65K per node).

**Comment by mp911de** [comment]
> where does the need to have 2 connections per node in cluster mode come from

This comes from the fact that we use different connections for read and write operations. Read connections need to have the `READONLY` bit set to avoid redirections.

```
127.0.0.1:7382> get a
(error) MOVED 15495 127.0.0.1:7380
127.0.0.1:7382> READONLY
OK
127.0.0.1:7382> get a
"b"
```

You can use Redis Cluster with `RedisClient` and individually open connections to your cluster nodes. There isn't much Lettuce can do. Connections are created lazily so if you use read-only connections only then you avoid read-write connections to replicas.
