### ISSUE TITLE
Avoid routing to cluster replicas that are loading data

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#1923]
Nodes that have joined the cluster and still load data should not receive any traffic unless they are fully replicated. As per @madolson, if the `master_repl_offset` is `0`, we should skip that node from command routing.

**Comment by mp911de** [comment]
Removing replicas based on the repl-offset will also remove replicas that cannot contact the master/upstream node although the node is functional otherwise. That is quite a significant change in comparison to leniently accept all replicas.

**Comment by jhmartin** [comment]
Is there a middle ground? Accept nodes that have /ever/ replicated successfully, and ignore nodes that have /never/ replicated?

**Comment by madolson** [comment]
Starting in 6.2, repl-offset is preserved until the point the data is flushed, which means that it is no longer able to usefully serve traffic (except for pubsub, but I would posit we don't care about that here).

**Comment by mp911de** [comment]
For the time being, we have that switch avoids command routing to replicas without data within the routing mechanism. If it turns out to be too invasive, we can move things into the individual `ReadFrom` strategies so it can be controlled by applications whether they want to talk to replicas without data.

**Comment by mp911de** [comment]
Refined the description, we're using `INFO REPLICATION` and the `master_repl_offset` field to determine the repl-offset.
