### ISSUE TITLE
GraalVM + SortedSet not working

### ISSUE THREAD

**Issue by accurithm** [lettuce-io/lettuce-core#1924]
#### Current Behavior

<details>
<summary>Lettuce SortedSet commands not functional with GraalVM native image</summary>

```java
// your stack trace here;
```

Has anyone faced similar problems?

I have a quarkus + kotlin service which uses redis cluster client with a functional to use sorted sets, recently i was able to successfully build a native image with the latest quarkus (2.5.1) and GraalVM 21.3.

All functionality works well except sorted sets, there is no exception dump or stack trace in logs.

However, when i deploy the JVM version it works fine without issue.

For the native build, i did not make any changes to the lettuce's bundled reflection.json, however, i had to add these additional arguments to application properties for graalvm builds.

--initialize-at-run-time=io.lettuce.core.resource.AddressResolverGroupProvider\\,io.lettuce.core.resource.DefaultClientResources\\,io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper\\,io.netty.buffer.ByteBufUtil$HexUtil\\,io.netty.buffer.PooledByteBufAllocator\\,io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper\\,io.netty.util.concurrent.GlobalEventExecutor\\,io.netty.resolver.dns.DnsNameResolver\\,io.netty.resolver.HostsFileEntriesResolver\\,io.netty.buffer.AbstractReferenceCountedByteBuf\\,io.lettuce.core.resource.DefaultClientResources\\,io.lettuce.core.resource.AddressResolverGroupProvider\\,io.netty.util.concurrent.ScheduledFutureTask\\,io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder\\,io.netty.buffer.ByteBufAllocator\\,io.netty.buffer.ByteBufUtil

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): lettuce-core:6.1.5.RELEASE
- Redis version: Bitnami Redis Cluster Helm (Redis v6.2.6)

**Comment by mp911de** [comment]
I'm not familiar with GraalVM Native at all. Happy to include a change if you find something we can improve.

**Comment by accurithm** [comment]
Hi @mp911de

Found the root cause, it was due to Gson().toJson unable to serialize ScoredValue for native image, the same is working with JVM.

I was able to fix the issue by adding ScoredValue and Value (below) to reflection-config.json

ScoredValue and Value has private constructors, i guess setting allDeclaredConstructors did the trick

  {
	"name": "io.lettuce.core.ScoredValue",
	"allDeclaredConstructors": true,
	"allPublicConstructors": true,
	"allDeclaredMethods": true,
	"allPublicMethods": true,
	"allDeclaredFields": true,
	"allPublicFields": true
  },
  {
	"name": "io.lettuce.core.Value",
	"allDeclaredConstructors": true,
	"allPublicConstructors": true,
	"allDeclaredMethods": true,
	"allPublicMethods": true,
	"allDeclaredFields": true,
	"allPublicFields": true
  }

**Comment by mp911de** [comment]
As this issue relates to JSON serialization (and frankly, Lettuce objects aren't intended for that as Lettuce cannot know what you're trying to do), closing as invalid.
