### ISSUE TITLE
Can it support dynamic (runtime jvm) changes to the ReadFrom strategy

### ISSUE THREAD

**Issue by goudai** [lettuce-io/lettuce-core#1926]
I want to modify the ReadFrom strategy without restarting the application.

**Comment by mp911de** [comment]
`ReadFrom` can be set on the [Cluster](https://lettuce.io/core/release/api/io/lettuce/core/cluster/api/StatefulRedisClusterConnection.html#setReadFrom-io.lettuce.core.ReadFrom-) or Master/Replica connection.

**Comment by goudai** [comment]
This setting will only take effect when init connection, not when the redis command is issued

**Comment by goudai** [comment]
I want to dynamically determine the strategy when I initiate a command

**Comment by mp911de** [comment]
`ReadFrom` affects commands that qualify for replica reads only, commands cannot be accessed in `ReadFrom`.
