### ISSUE TITLE
My redis message is usually larger than 10kb, how should I configure the connection pool size

### ISSUE THREAD

**Issue by goudai** [lettuce-io/lettuce-core#1928]
My redis message is usually larger than 10kb, how should I configure the connection pool size

**Comment by mp911de** [comment]
I don't know how the message size relates to the pool size. The initial question would be why do you want a connection pool in the first place? A single connection is sufficient for most cases unless you're using transactions or blocking commands.

**Comment by goudai** [comment]
A single connection cannot support the readfrom strategy of the redis cluster

**Comment by mp911de** [comment]
Internally, cluster connections are comprised of multiple TCP connections to individual nodes. However, there are no settings to configure the internal connection mechanism. Closing this ticket as it isn't actionable.
