### ISSUE TITLE
RedisTimeOut Exception when adding replica in ElastiCache for get call

### ISSUE THREAD

**Issue by daisyweiluo** [lettuce-io/lettuce-core#1930]
Hello,

While I'm adding more replica in ElastiCache, I noticed there are RedisTimeOut Exception for get calls from the newly added replica. Is there a way to tune Lettuce client to connect when a replica is actually ready?

Thanks.

**Comment by mp911de** [comment]
The reference documentation explains how to approach timeout issues at https://lettuce.io/core/release/reference/#faq.timeout.

You need to find out the actual reason why Redis doesn't send a response in time. This sounds a bit related to #1923
