### ISSUE TITLE
RedisCommandTimeoutException: Command timed out after 10 second(s)

### ISSUE THREAD

**Issue by 1YJY1** [lettuce-io/lettuce-core#1935]
The configuration of our project is shown in the figure, the topology refresh mechanism has been configured.

![image](https://user-images.githubusercontent.com/43983148/145757411-cfe7fa9c-bc16-4055-978c-141685b94c87.png)

It's been normal for a month, but there's a problem today.

`2021-12-13 10:29:50,920 [http-nio2-8080-exec-128] ERROR com.paytm.pgplus.redis.RedisBridgeWorker.get():94 {REQUEST_ID=1595523588463} - Exception while reading from redis cluster: 
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy211.get(Unknown Source)
`

The problem is that we see that the connection exists on the service. Use command `lsof - I :port` also can see connection.

I'm sorry, because it was an emergency, we restarted the machine without leaving stack or IO log。

SpringBoot version: 2.3.1.RELEASE

Lettuce version: 5.3.1.RELEASE

**Comment by mp911de** [comment]
Check out the [reference documentation on timeouts](https://lettuce.io/core/release/reference/#faq.timeout).

**Comment by 1YJY1** [comment]
I've seen it, but It doesn't work.

now I set up Netty keepLive, I hope it works.

`ClientResources clientResources = ClientResources.builder()
                .nettyCustomizer(new NettyCustomizer() {
                    @Override
                    public void afterChannelInitialized(Channel channel) {
                       
                        channel.pipeline().addLast(new IdleStateHandler(10, 0, 0));
                        channel.pipeline().addLast(new ChannelDuplexHandler() {
                            @Override
                            public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
                                if (evt instanceof IdleStateEvent) {
                                    ctx.disconnect();
                                }
                            }
                        });
                    }
                }).build();`

**Comment by mozhe007** [comment]
I got same Exception.  My situation is after long time without operation ,  studdenly  send request more than thirty times , then this exception happen
