### ISSUE TITLE
AddressResolverGroupProvider not protecting from ClassNotFoundExceptions.

### ISSUE THREAD

**Issue by NfNitLoop** [lettuce-io/lettuce-core#1940]
## Bug Report

Javadocs in [AddressResolverGroupProvider]  say:

```
 * Wraps and provides {@link AddressResolverGroup} classes. This is to protect the user from {@link ClassNotFoundException}'s
 * caused by the absence of the {@literal netty-dns-resolver} library during runtime. This class will be deleted when
 * {@literal netty-dns-resolver} becomes mandatory. Internal API.
```

[AddressResolverGroupProvider]: https://github.com/lettuce-io/lettuce-core/blob/a7a1bda/src/main/java/io/lettuce/core/resource/AddressResolverGroupProvider.java

#### Current Behavior

But, I'm getting the following ClassNotFoundException stack trace with lettuce-core 6.1.5.RELEASE:

```
java.lang.NoClassDefFoundError: io/netty/resolver/dns/DnsCnameCache
	at io.lettuce.core.resource.AddressResolverGroupProvider.<clinit>(AddressResolverGroupProvider.java:35)
	at io.lettuce.core.resource.DefaultClientResources.<clinit>(DefaultClientResources.java:112)
	at io.lettuce.core.AbstractRedisClient.<init>(AbstractRedisClient.java:123)
	at io.lettuce.core.cluster.RedisClusterClient.<init>(RedisClusterClient.java:183)
	at io.lettuce.core.cluster.RedisClusterClient.create(RedisClusterClient.java:252)
	at io.lettuce.core.cluster.RedisClusterClient.create(RedisClusterClient.java:239)
        …
```

#### Input Code

I'm trying to come up with a minimal example. Unfortunately the issue seems intermittent and I haven't yet been able to reproduce it reliably in a minimal code set.  

#### Expected behavior/code

AddressResolverGroupProvider claims to protect against just this case, so I'd expect it to do so. 😊 

#### Environment

- Lettuce version(s): lettuce-core 6.1.5.RELEASE
- Redis version: not applicable.

#### Possible Solution

🤷 

#### Additional context

If you think of things I can test to help debug this, I'm happy to give it a try.

**Comment by NfNitLoop** [comment]
Oh! more context:

I'm running into this issue from a Kotlin .main.kts script, via a transitive `@file:DependsOn(…)` dependency.  My first thought was that some transitive dependencies weren't getting loaded, but seeing the above source, it seems that if netty-dns-resolver isn't present, it should have a safe fallback.

I've seen some bugs regarding Kotlin script classloader shenanigans so maybe you're running into this? I can't immediately see how `LettuceClassUtils.isPresent()` could return true if the classes aren't there. Maybe it depends on which classloader isPresent() ends up checking via getDefaultClassLoader()?  🤷

**Comment by NfNitLoop** [comment]
Hmm!  Maybe it's because that class seems to be available from within Kotlin even though I haven't specified any dependencies.

```kotlin
#!/usr/bin/env kotlin

// See: https://github.com/lettuce-io/lettuce-core/issues/1940
// and: https://github.com/lettuce-io/lettuce-core/blob/a7a1bda/src/main/java/io/lettuce/core/resource/AddressResolverGroupProvider.java#L30

// @file:DependsOn("io.lettuce:lettuce-core:6.1.5.RELEASE")

val isPresent = classPresent("io.netty.resolver.dns.DnsAddressResolverGroup")
println("isPresent: $isPresent")
// println(io.lettuce.core.resource.DefaultClientResources.DEFAULT_ADDRESS_RESOLVER_GROUP.javaClass.name)


fun classPresent(klass: String): Boolean {
  // return io.lettuce.core.internal.LettuceClassUtils.isPresent(klass)
    try {
        this.javaClass.classLoader.loadClass(klass)
        return true
    } catch (e: Throwable) {
        return false
    }
}
```

So there could be conflicting versions of the classes on the classpath? 😣

**Comment by mp911de** [comment]
Thanks for investigating the issue. It seems that there's a mismatch either in dependencies or the class loader. We use the default class loader (`Thread.currentThread().getContextClassLoader()`, fall back to `LettuceClassUtils.class.getClassLoader()`) to determine whether the `DnsAddressResolverGroup ` class is on the class path. It can be that the default class loader sees the class but the one that is used to load the class is not seeing it.

There's not much we can do from our side.

**Comment by NfNitLoop** [comment]
Well, I think I may have gotten this train of thought too derailed onto "this is broken in Kotlin Script.".

The real issue is that you've got a check that claims to protect you from a ClassNotFoundException  (probably actually intended: NoClassDefFoundError), but it doesn't.

If you want to unconditionally protect for that case, why not just use Java's built-in try-catch?

Instead of:

```java
        // Doesn't properly protect from NoClassDefFoundError:
        boolean dnsResolverAvailable = LettuceClassUtils.isPresent("io.netty.resolver.dns.DnsAddressResolverGroup");

        AddressResolverGroup<?> group;
        if (dnsResolverAvailable) {
            logger.debug("Starting with netty's non-blocking DNS resolver library");
            group = DefaultDnsAddressResolverGroupWrapper.INSTANCE;
        } else {
            logger.debug("Starting without optional netty's non-blocking DNS resolver library");
            group = DefaultAddressResolverGroup.INSTANCE;
        }
        ADDRESS_RESOLVER_GROUP = group;
```

do:


```java
        AddressResolverGroup<?> group = DefaultAddressResolverGroup.INSTANCE;
        try {
            group = DefaultDnsAddressResolverGroupWrapper.INSTANCE;
            logger.debug("Starting with netty's non-blocking DNS resolver library");
        } catch (NoClassDefFoundError _ignored) {
            logger.debug("Starting without optional netty's non-blocking DNS resolver library");
        }
        ADDRESS_RESOLVER_GROUP = group;
```

**Comment by NfNitLoop** [comment]
You might even prefer to catch [LinkageError](https://docs.oracle.com/javase/7/docs/api/java/lang/LinkageError.html) to protect against more error cases.

**Comment by NfNitLoop** [comment]
@mp911de ⬆️ Is that enough to re-open the ticket?
