### ISSUE TITLE
Add one switch for cluster topology refresh

### ISSUE THREAD

**Issue by StillerRen** [lettuce-io/lettuce-core#1946]
#### Is your feature request related to a problem? Please describe

I have a cluster A with 4 nodes(1, 2, 3, 4), then I delete 1 nodes(4) from the cluster and add this old nodes into the other cluster B;

the client do not restart, so the seed nodes are still these 4 nodes(1,2 ,3 4);

for OS upgrade, I restart the cluster A hosts, then I find the clients connect to cluster B;

I check the code and find that lettuce would use the seed nodes to refresh cluster topology when the dynamic nodes are useless;

it would cause my problem in this situation. 

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Describe alternatives you've considered

I want a switch to control whether the client use seed nodes to refresh cluster topology when the dynamic nodes are useless;

otherwise I should restart my client process after cluster node changed.

**Comment by mp911de** [comment]
This is documented in the reference docs. Check out https://lettuce.io/core/release/reference/#clientoptions.cluster-specific-options for periodic/adaptive topology refresh.

**Comment by StillerRen** [comment]
Frequent periodic topology refresh would cause cluster node high CPU usage, because lettuce would send cluster nodes command to all cluster nodes, this command casting a lot of time; So I set 3600s for this；

the cluster B is normal so adaptive topology refresh can not switch client to cluster A because lettuce use dynamic nodes first
