### ISSUE TITLE
`BoundedPoolConfig` with `-1`  as `maxTotal` does not work as unlimited pool

### ISSUE THREAD

**Issue by fedigiorgio** [lettuce-io/lettuce-core#1953]
#### Current Behavior
When create BoundedPoolConfig with maxTotal = -1 and try to acquire a connection from pool throws java.util.NoSuchElementException: Pool exhausted.

Documentation says: 

```
        /**
         * Configures the maximum number of objects that can be allocated by the pool (checked out to clients, or idle awaiting
         * checkout) at a given time. When negative, there is no limit to the number of objects that can be managed by the pool
         * at one time.
         *
         * @param maxTotal maximum number of objects that can be allocated by the pool.
         * @return {@code this} {@link Builder}.
         */
        public Builder maxTotal(int maxTotal)
```
#### Expected behavior/code
To have a Pool able to acquire connections with no limit.

#### Environment

- Lettuce version(s): [6.1.5.RELEASE]
- Redis version: [6.2.3]

**Comment by mp911de** [comment]
Thanks for filing a bug report. It is indeed a bug and we're going to fix it.
