### ISSUE TITLE
lost data

### ISSUE THREAD

**Issue by LittleJZ** [lettuce-io/lettuce-core#1957]
#[#1951 ](https://github.com/lettuce-io/lettuce-core/issues/1951)

I tested this issue and found that it was not that only some of the commands were refreshed, but that the commands were executed out of order
![image](https://user-images.githubusercontent.com/51402665/148334662-1b93e974-7ad2-4161-b479-a77be8a214c4.png)
![image](https://user-images.githubusercontent.com/51402665/148334924-d16a8f48-fcc8-41f0-9b0c-81a3d6bda4d4.png)

 can find first set key key-test-20, followed by del key key-test-20

thank you for your reply

**Comment by LittleJZ** [comment]
I am using the monitor command of redis for monitoring

**Comment by LittleJZ** [comment]
and the redis cluster I tested was a single node

**Comment by mp911de** [comment]
When using Redis Cluster, you need to make sure that all node-connections are established. Otherwise, only a subset of commands will be flushed, because connections are in the state of being initialized.
