### ISSUE TITLE
does lettuce support dynamically reload SSL certificate and key for SSL connection?

### ISSUE THREAD

**Issue by ExploreNcrack** [lettuce-io/lettuce-core#1971]
Is it possible to dynamically reload the SSL certificate and key for the existing connection so that we can avoid making new connection when certificate and key files have changed?

**Comment by mp911de** [comment]
Yes, it does:

```
         * Sets the key file and its certificate to use for client authentication. The key is reloaded on each connection
         * attempt that allows to replace certificates during runtime.
```

**Comment by ExploreNcrack** [comment]
@mp911de Thank you for replying. I just have one more question, does this `cert and key reloading on each connection` apply to async connection pooling as well? for example when I `pool.acquire().thenCompose(connection -> {})`, will this reload the SSL cert and key? or I would have to close the pool and re-create the pool in order to reload them? Thanks in advance.

**Comment by mp911de** [comment]
SSL handling happens on a per-connection basis and that includes pooled connections and reconnects.
