### ISSUE TITLE
Lettuce Timer does not shutdown

### ISSUE THREAD

**Issue by patrickjamesbarry** [lettuce-io/lettuce-core#1972]
## Bug Report

Lettuce timer thread does not shutdown

#### Current Behavior

Using a pool of connections, and hitting it with multiple threads, I see the lettuce-timer thread does not get shutdown. Using lettuce core 6.1.6 Release

<details>
Run test where you create a pool of connections, make multiple calls using various threads and then shutdown pool and client.  See the lettuce-timer thread persisting even after calling close
</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
package com.problems.core.cache.redis.client;

import io.lettuce.core.ClientOptions;
import io.lettuce.core.RedisClient;
import io.lettuce.core.RedisURI;
import io.lettuce.core.SocketOptions;
import io.lettuce.core.api.StatefulRedisConnection;
import io.lettuce.core.resource.DefaultClientResources;
import io.lettuce.core.resource.Delay;
import io.lettuce.core.resource.DirContextDnsResolver;
import io.lettuce.core.support.ConnectionPoolSupport;
import org.apache.commons.pool2.impl.GenericObjectPool;
import org.apache.commons.pool2.impl.GenericObjectPoolConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import static java.time.Duration.*;
import static java.util.concurrent.TimeUnit.MILLISECONDS;

public class PoolProblem {
    static Logger logger = LoggerFactory.getLogger(PoolProblem.class);

    public static void main(String[] args) throws InterruptedException {
        RedisURI elasticacheUri = RedisURI.Builder.redis("xxxx", 6379)
                .withPassword("mysecret".toCharArray())
                .withSsl(true)
                .build();

        RedisClient redisClient = RedisClient.create(DefaultClientResources.builder()
                .ioThreadPoolSize(8)
                .computationThreadPoolSize(8)
                .dnsResolver(new DirContextDnsResolver())
                .reconnectDelay(Delay.exponential(0, 1500, MILLISECONDS, 2))
                .build(), elasticacheUri);

        SocketOptions socketOptions = SocketOptions.builder()
                .connectTimeout(ofSeconds(2))
                .keepAlive(true)
                .build();

        redisClient.setOptions(ClientOptions.builder()
                .autoReconnect(true)
                .cancelCommandsOnReconnectFailure(true)
                .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                .pingBeforeActivateConnection(true)
                .requestQueueSize(10)
                .socketOptions(socketOptions)
                .build());

        GenericObjectPoolConfig<StatefulRedisConnection<String, String>> config = new GenericObjectPoolConfig<>();
        config.setMinIdle(2);
        config.setMaxTotal(10);
        config.setMaxIdle(10);
        config.setMaxWait(ofSeconds(1));
        config.setMinEvictableIdleTime(ofMinutes(5));
        config.setTestOnBorrow(true);
        config.setTimeBetweenEvictionRuns(ofMinutes(5));

        List<Callable<String>> tasks = new ArrayList<>();
        GenericObjectPool<StatefulRedisConnection<String, String>> pool = ConnectionPoolSupport.createGenericObjectPool(redisClient::connect, config);

        for (int i = 0; i < 5; i++) {
            ExecutorService execService = Executors.newFixedThreadPool(5);
            for (int count = 0; count < 5; count++) {
                Callable<String> c = () -> {
                    try (StatefulRedisConnection<String, String> connection = pool.borrowObject()) {
                        logger.info("Running test on pool {}, connection {}", System.identityHashCode(pool), System.identityHashCode(connection));

                        return connection.sync().set("key", "100");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    return "{}";
                };
                tasks.add(c);
            }
            List<Future<String>> results = execService.invokeAll(tasks);
            logger.info("Completed {} tests", results.size());
            execService.shutdownNow();
        }
        logger.info("Done");

        pool.close();

        redisClient.shutdown(ZERO, Duration.ofSeconds(20));
        List<String> threadsStillAlive = new ArrayList<>();
        for (Thread t : Thread.getAllStackTraces().keySet()) {
            if (t.getName().contains("lettuce-") || t.getName().contains("pool")) {
                threadsStillAlive.add(t.getName());
            }
        }
        logger.info("Threads still alive after attempted shutdown: {}", threadsStillAlive);
    }
}

```

</details>

#### Expected behavior/code

Was expecting all threads created by client to be shutdown

#### Environment

- Lettuce version(s): 6.1.6 Release
- Redis version: 6.2

#### Possible Solution

I using this as a workaround. Not sure if it is safe... but it does shutdown cleanly

timer = new HashedWheelTimer(new DefaultThreadFactory("my-lettuce-timer", true));
        ClientResources clientResources = DefaultClientResources.builder()
                .dnsResolver(new DirContextDnsResolver())
                .reconnectDelay(Delay.exponential(0, 1500, MILLISECONDS, 2))
                .timer(timer)

**Comment by patrickjamesbarry** [comment]
For my workaround, I have to save an instance of the Timer I provide and then manually call .stop() on it.

**Comment by patrickjamesbarry** [comment]
Side question-  While running the test provided, you'll see the thread names print off in the logging statements.  Why does the pool number  keep incrementing?   example pool-1-thread-49, pool-2-thread-24, pool-3-thread-12.   As far as I can tell, we are only using 1 pool.

**Comment by mp911de** [comment]
If you create `DefaultClientResources`, then you must call `shutdown()` afterwards. Alternatively, you can create `RedisClient` without passing `ClientResources` to let the client manage the resources and shut down these upon client shutdown.

**Comment by patrickjamesbarry** [comment]
Hmm, I had that in my  original code but forgot to carry  over into test provided. However, I reran a  couple of times and the  lettuce-timer thread is being cleaned up now, so moving on:)  Any explanation on my side question?  

"Why does the pool number keep incrementing? example pool-1-thread-49, pool-2-thread-24, pool-3-thread-12. As far as I can tell, we are only using 1 pool."

**Comment by mp911de** [comment]
Each time you create a `RedisClient` or `ClientResources`, the pool counter is incremented as the counter is a `static AtomicInteger` in `io.netty.util.concurrent.DefaultThreadFactory`.

**Comment by patrickjamesbarry** [comment]
In the code  provided, I am only creating one RedisClient/ClientResource. Then the  pool is  instantiated with 
_ConnectionPoolSupport.createGenericObjectPool(redisClient::connect, config);_

Are new RedisClients or ClientResources created when calling connect()?  I'm  not  seeing that in the code, but must be  overlooking something.

**Comment by mp911de** [comment]
> Are new RedisClients or ClientResources created when calling connect()? 

No, only once when the client respective `ClientResources` are built.

**Comment by patrickjamesbarry** [comment]
Ok- should I file as new bug?  Not quite sure where to go from here.

**Comment by mp911de** [comment]
That isn't a problem, because the `DefaultThreadFactory` is created three times:

1. For the event executor (computation pool)
2. For the I/O event loop (I/O pool, each transport (kqueue, epoll, nio) gets its own pool)
3. For the timer (single thread)


If you run the application with a profiler you'll see the creation of various and potentially inactive threads and that is how thread creation works in netty and Lettuce.

**Comment by patrickjamesbarry** [comment]
I  can confirm I see DefaultThreadFactory in play for the 3  items above. However,  the  DefaultThreadFactory does not seem to be part of GenericObjectPool that is producing the logging line that is confusing. The line printing the current thread is:
pool-*-thread*   .  It is confusing because it should only ever  print pool-1-thread-*, showing that only one  GenericObjectPool is in  play.  

So even though I have 1 RedisClient,  1 ClientResource, 1 GenericObjectPool for connections, I am  seeing  logging statements showing  a pool counter (in thread name) incrementing.

**Comment by patrickjamesbarry** [comment]
Example:
10:40:30.345 [pool-1-thread-2] INFO  c.g.i.c.c.redis.client.PoolProblem - Running test on pool 1361393151, connection 1667280102
10:40:30.345 [pool-1-thread-6] INFO  c.g.i.c.c.redis.client.PoolProblem - Running test on pool 1361393151, connection 1813114945
10:40:30.345 [pool-1-thread-10] INFO  c.g.i.c.c.redis.client.PoolProblem - Running test on pool 1361393151, connection 356433410
10:40:30.345 [pool-1-thread-5] INFO  c.g.i.c.c.redis.client.PoolProblem - Running test on pool 1361393151, connection 323558435
10:40:30.486 [main] INFO  c.g.i.c.c.redis.client.PoolProblem - Completed 100 tests
10:40:30.487 [pool-2-thread-2] INFO  c.g.i.c.c.redis.client.PoolProblem - Running test on pool 1361393151, connection 494265234
10:40:30.488 [pool-2-thread-3] INFO  c.g.i.c.c.redis.client.PoolProblem - Running test on pool 1361393151, connection 824272885
10:40:30.488 [pool-2-thread-4] INFO  c.g.i.c.c.redis.client.PoolProblem - Running test on pool 1361393151, connection 215587862
10:40:30.489 [pool-2-thread-6] INFO  c.g.i.c.c.redis.client.PoolProblem - Running test on pool 1361393151, connection 359152269
10:40:30.489 [pool-2-thread-5] INFO  c.g.i.c.c.redis.client.PoolProblem - Running test on pool 1361393151, connection 1704268131
