### ISSUE TITLE
StatefulConnection.isOpen() does not work correctly when the connection is lost

### ISSUE THREAD

**Issue by yelliver** [lettuce-io/lettuce-core#1973]
#### Current Behavior

`StatefulConnection.isOpen()` returns true when the connection is lost.
The document says that "true if the connection is open (connected and not closed)." But in my case, the connection is not closed (I am still using it), the connection to the Redis server is lost.

</details>

#### Expected behavior/code

`isOpen()` should return false when the connection is lost (but not closed)

#### Environment

- Lettuce version(s): 6.1.5.RELEASE

**Comment by mp911de** [comment]
Care to provide more details? `StatefulConnection.isOpen()` is only useful for single-node connections. In multi-node arrangements, such as Redis Cluster or Master/Replica, the `isOpen` method returns the state of the default node and doesn't represent the connect state of _any_ node.

**Comment by yelliver** [comment]
I run my code from localhost to connect to a remote Redis Cluster, when I disconnect my computer from the internet, the isOpen() still returns true.

**Comment by mp911de** [comment]
Depends on what you mean with disconnect from the internet. If you pull the plug on your computer, then the network interface should tell the OS to close all ports. If you shut down any active component and your computer doesn't see that it assumes it's still connected.

The open/close functionality only gets updated once the process notices that it is actually disconnected (ICMP traffic, TCP timeout, TCP RST packet).

**Comment by yelliver** [comment]
I disconnect from the wifi network, and I have a loop to check `isOpen()` every few seconds, but it still shows `true` forever. I am reading the source code & know that it returns the status of boolean `active` var, but not found where it is updated if there is any connection issue.

**Comment by mp911de** [comment]
Inactivation happens through `DefaultEndpoint.notifyChannelInactive()` which calls `RedisChannelHandler.deactivated()` setting `active` to `false` when netty signals `channelInactive`.
