### ISSUE TITLE
DefaultClientResources is not closed  when unable to establish a connection to Redis

### ISSUE THREAD

**Issue by yelliver** [lettuce-io/lettuce-core#1975]
#### Current Behavior

I have a retry mechanism to connect to Redis, after several times of errors that cannot connect to Redis, once it is able to connect to Redis, there is a warning:

` DefaultClientResources - io.lettuce.core.resource.DefaultClientResources was not shut down properly, shutdown() was not called before it's garbage-collected. Call shutdown() or shutdown(long,long,TimeUnit) 
`

#### Input Code

```java
      while (true) {
        try {
          log.info("Creating Redis connection...");
          conn = RedisClusterClient.create(redisUri).connect(codec);
          log.info("Successful to create Redis connection");
          break;
        } catch (Exception e) {
          log.error("Fail to create Redis connection, Retrying in {}s: {}", redisRetry, e.toString());
          sleep(redisRetry);
        }
```

**Comment by mp911de** [comment]
Please read the error message and the docs of the client as resources must be closed.

**Comment by yelliver** [comment]
If I pass the DefaultClientResources instance that I created, I can shut down it, but I did not pass, so it was created automatically. Can this be considered as a feature request that if the DefaultClientResources is created automatically (not explicitly pass it into connect() method) then it will be shut down automatically as well?
