### ISSUE TITLE
Does ReadFrom=NEAREST work for Redis Cluster set up by binami/redis-cluster

### ISSUE THREAD

**Issue by angelorobo** [lettuce-io/lettuce-core#1977]
We're using binami redis-cluster

We have 2 different datacenter serving users from 2 regions. Both are connected via AWS direct connect. We've our Redis cluster with another node from another EKS (Kubernetes) Cluster. So the API server on another EKS cluster can read from Redis much faster. Does ReadFrom=NEAREST work in this case to read from the closest master?

**Comment by mp911de** [comment]
There's no reason that it would not work.
