### ISSUE TITLE
DNS cache

### ISSUE THREAD

**Issue by Hehor** [lettuce-io/lettuce-core#1986]
Hi, 
Is there any possible reconnect to the redis using DNS, not cashed ip ? 
For example DNS use round robin algorithm and return a few ip adresses, but if lettuce loose connection to one of ip, it don't try to use DNS for reconnection, it use cached ip. 
Thanks.

**Comment by mp911de** [comment]
Check out https://lettuce.io/core/release/reference/#clientresources.advanced-settings regarding the DNS resolver settings.
