### ISSUE TITLE
Process reconnection if requests doesn't appears

### ISSUE THREAD

**Issue by Ulinay1** [lettuce-io/lettuce-core#1991]
Hi,
Does it possible to process disconnection if any requests to Redis doesn't appear ?

**Comment by mp911de** [comment]
Not sure what you're asking. Lettuce auto-reconnects once it sees an unintended disconnect. This is not related to whether the application is issuing commands.

**Comment by Ulinay1** [comment]
For example if my application don't use redis for 5 minutes can lettuce process disconnection ?

**Comment by mp911de** [comment]
Lettuce doesn't auto-disconnect, rather if Lettuce sees an unintended disconnect, it attempts to reconnect toe connection.
