### ISSUE TITLE
6.2 Release Date

### ISSUE THREAD

**Issue by jamesh4** [lettuce-io/lettuce-core#1996]
Is there an estimated release date for Lettuce 6.2?
Particularly interested in the version that would fix this issue: https://github.com/lettuce-io/lettuce-core/issues/1923

**Comment by jhmartin** [comment]
I believe that was included in 6.1.6: https://github.com/lettuce-io/lettuce-core/releases/tag/6.1.6.RELEASE

**Comment by jamesh4** [comment]
Thanks, it appears to have solved my problem.
