### ISSUE TITLE
Log the key when getValue fails on a nil value.

### ISSUE THREAD

**Issue by chankang17** [lettuce-io/lettuce-core#1999]
#### Is your feature request related to a problem? Please describe

https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/Value.java#L148

When the key value pair retrieved has a nil value, `lettuce` throws an exception but the error doesn't show any further detail that could help the developer to figure out where the error originally came from. Logging out the key for which the value is null seems like a good thing to log here.

We just had a bunch of errors in production where `getValue` failed and threw `NoSuchElement` exception but we have no clue which keys are causing problem out of millions of keys we have in our cluster.

#### Describe the solution you'd like
See above.

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Teachability, Documentation, Adoption, Migration Strategy

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by mp911de** [comment]
`Value` is built similar to Java's `Optional`. Prior to value retrieval, make sure to call `isEmpty`. Lettuce itself calls only `getValue()` with proper guarding and we do not want to log every exception.
