### ISSUE TITLE
strange short link service with SSL issues

### ISSUE THREAD

**Issue by rusefillc** [lettuce-io/lettuce-core#2001]
See https://github.com/lettuce-io/lettuce-core/wiki/_compare/73fbdb351f12f14b60adb223ef47abb193b131df...9c6b97cb8d4fbae0a4bce60c9e39641c448c3db2

out wiki was affected same way - random contributor injecting short URL

**Comment by mp911de** [comment]
Thanks a lot for the hint. I'm going to close the wiki for non-contributor edits.
