### ISSUE TITLE
connection pooling vs single connection shared by threads ?

### ISSUE THREAD

**Issue by ExploreNcrack** [lettuce-io/lettuce-core#2008]
I am wondering if I have many (hundreds to thousands) threads that will need to access a connection in order to send the (non-blocking) commands, in such case, would it better for me to use sync connection pooling vs just a single connection? If no, how about if the server side is multi-threaded instead of single threaded processing, would I get any performance benefits by using connection pooling?

**Comment by mp911de** [comment]
Redis itself is single-threaded so unless you're using blocking commands (e.g. `BLPOP`) or transactions, a single connection for all units of work is typically the best option.
