### ISSUE TITLE
How to set idle amount of idle connections ?

### ISSUE THREAD

**Issue by Ulinay1** [lettuce-io/lettuce-core#2009]
Hi, how to set max idle amount and min idle amount using LettuceClientConfiguration ? And how to set idle timeout ?

**Comment by mp911de** [comment]
Have you already checked out the reference documentation at https://lettuce.io/core/release/reference/#connecting-redis?

**Comment by Ulinay1** [comment]
I use LettuceConnectionFactory.    
Is it possible to set my parameters to clientConfiguration ?

`ReactiveRedisConnectionFactory reactiveRedisWriterConnectionFactory() {
var clientConfiguration = LettuceClientConfiguration.builder().build();
return new LettuceConnectionFactory(new RedisStandaloneConfiguration(getWriteEndpoint(), getPort()), clientConfiguration);
    }`
