### ISSUE TITLE
Add trace context propagation for redis streams

### ISSUE THREAD

**Issue by lrozek** [lettuce-io/lettuce-core#2014]
## Feature Request

In the spring boot project we use `sleuth` (https://spring.io/projects/spring-cloud-sleuth) for distributed tracing and `spring-data-redis` (https://spring.io/projects/spring-data-redis) as a layer on top of lettuce to add entries to streams and to receive them. I thought that propagation has to be implemented in spring related projects, however I was redirected to this project.

Please refer for more information to the original issue I raised in `sleuth` project:
- https://github.com/spring-cloud/spring-cloud-sleuth/issues/2117

And to the sample project that shows lack of trace context propagation using mentioned frameworks and provides more detailed description
- https://github.com/lrozek/redis-stream-trace-context-propagation

**Comment by lrozek** [comment]
Actually both cases could be supported.
- context being propagated from the producer into the consumer. This is the case when tracing context has been already established prior adding stream entry
- context being created on the consumer in case stream entry does not contain trace context data. That might be the case when producing application does not support distributed tracing. Therefore distributed tracing starts on consumer side on retrieval of stream entry. It can be propagated further via REST calls, etc

**Comment by lrozek** [comment]
@mp911de I also have a similar sample project with rabbimq as a middleware where I evaluated trace context propagation. For rabbitmq both cases are supported. If that would be helpful I could also attach it. Just let me know

**Comment by mp911de** [comment]
This isn't a question of can vs. can not. Redis Streams provide a body only without the possibility to attach metadata such as headers. In consequence, we would need to change the message body (i.e. interfere with user data) to attach a trace/span Id to make it happen.

Going forward one could also ask to perform context propagation with Redis Pub/Sub which is even worse as the Pub/Sub message is just a collection of bytes without a structured message format.

I think for the time being it makes sense to have utilities that extract context identifiers and store these along the stream. On the consumer side, you would consume these identifiers and create a trace context.

I'm somewhat undecided whether this is a good idea to be enabled in any case as stream consumption may happen at a later time or the stream could be consumed again and that leads to strange representations of spans.

**Comment by mp911de** [comment]
This isn't something we can do because we would actively tamper user data structures leading to a lot of surprises. It would make much more sense to build an adapter on top of Lettuce.
