### ISSUE TITLE
Lettuce connection shared by multiple threads limit?

### ISSUE THREAD

**Issue by ExploreNcrack** [lettuce-io/lettuce-core#2015]
Hi, I am wondering on average how many threads can a single Lettuce connection handle for non-blocking operations? or how many threads can share the same Lettuce connection without causing overhead problem?
Would I get more performance by overriding the default ioThreadPoolSize in ClientResources?

**Comment by mp911de** [comment]
> how many threads can a single Lettuce connection handle for non-blocking operations

That depends on your workload. Benchmarking is your friend.
