### ISSUE TITLE
`CommandArgs` using `Long.MIN_VALUE` results in `0`

### ISSUE THREAD

**Issue by StillerRen** [lettuce-io/lettuce-core#2019]
#### Current Behavior

use lettuce incrby command: incrby key Long.MIN_VALUE, the result is 0, not Long.MIN_VALUE

command: incrby key Long.MIN_VALUE

excepted value:  Long.MIN_VALUE

actual value: 0

#### Environment

- Lettuce version(s):  5.2.0.RELEASE
- Redis version: 4.0.11

#### Possible Solution

io.lettuce.core.RedisCommandBuilder incrby method would add count to CommandArgs
![image](https://user-images.githubusercontent.com/35724820/155093305-deb80a96-b2e7-48ce-a23a-546194612225.png)
then go IntegerArgument.of() method
![image](https://user-images.githubusercontent.com/35724820/155093424-d1b33858-7cd4-46f8-9ec0-b014dd40b86a.png)

and for this place, -Long.MIN_VALUE == Long.MIN_VALUE, so the result is true
![image](https://user-images.githubusercontent.com/35724820/155093612-e24b364a-6aee-4d4a-a272-b9db4c6bf3ea.png)

finally this place would make the count as 0
![image](https://user-images.githubusercontent.com/35724820/155093859-2524e707-ca68-4363-9a96-a5653dcf5916.png)

so the command: incrby  key Long.MIN_VALUE result is 0

**Comment by mp911de** [comment]
That's fixed now.
