### ISSUE TITLE
Async connection pool question

### ISSUE THREAD

**Issue by ExploreNcrack** [lettuce-io/lettuce-core#2021]
under the context that only sending non-blocking commands:
If I want to have a connection pool that will always return a connection from the pool without blocking whenever a thread makes a get method call and each connection in the connection pool can be shared by multiple threads, (for example we have thread A and B, but there is only one connection in the pool, so A and B can get the connection at the same time from the pool and use it for sending commands), would this be a use case to use Lettuce`Asynchronous Connection pool` ? Or I would have to create a custom "connection pool" myself to support that? Since each Lettuce connection itself is async under the hood and connection is safe to share by multiple threads.

**Comment by mp911de** [comment]
No, the `AsyncPool` allows single-allocation only. What you're looking for is something like round-robin and that's not provided by Lettuce.
