### ISSUE TITLE
PushListener does not receive PubSub messages with AWS ElastiCache (Master-Replica)

### ISSUE THREAD

**Issue by travispeloton** [lettuce-io/lettuce-core#2022]
## Bug Report

Lettuce `6.1.6.RELEASE`:

I'm using AWS ElastiCache, in Master-Replica mode, and found that `StatefulRedisConnection#addListener(PushListener)` works with Redis on my local desktop, but is never invoked for PubSub message when deployed in AWS and connected to AWS ElastiCache.

When I switched to use `StatefulRedisPubSubConnection#addListener(RedisPubSubListener)`, everything worked fine. In both cases I published to the primary node and subscribed on a read-only replica.

If this is expected behavior, then it should be clearly documented. A comment on `PushListener` says "Requires Redis 6+ using RESP3", but Google searches didn't clearly state if that was the underlying distinction.

**Comment by mp911de** [comment]
`PushListener`'s Javadoc clearly says that push messages are only available as of Redis 6 using the RESP3 protocol version. How would you improve the current documentation to make things more clear?

**Comment by travispeloton** [comment]
It would be helpful to see a compatibility matrix in the [written documentation](https://lettuce.io/core/release/reference/index.html) or a note about this limitation. It already mentions AWS ElastiCache in a few areas.

**Comment by travispeloton** [comment]
Doh. Turns out a colleague copy-n-pasted some config, so I was on Redis 4.x for ElastiCache.
