### ISSUE TITLE
Add support for `CLUSTER SHARDS` command

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#2025]
Allows us to replace our `CLUSTER NODES` approach for topology discovery. 

See https://github.com/redis/redis/pull/10293

**Comment by mp911de** [comment]
For the time being, we will stick to `CLUSTER NODES` to avoid incompatibilities in requiring a newer Redis version. It would make sense to have a config flag in `ClusterClientOptions` that determines whether to use `CLUSTER NODES` vs `CLUSTER SHARDS`. The latter command comes with `replication-offset` details allowing to skip nodes that are not yet fully replicated.

**Comment by mp911de** [comment]
Note: `PooledClusterConnectionProvider` uses `Partitions.getPartitionBySlot(…)` for `getWriteConnection` which may fail because `getPartitionBySlot` does not distinguish between replicas and master nodes.

**Comment by srgsanky** [comment]
If Lettuce supports CLUSTER SHARDS, we can make use of [its health field](https://redis.io/commands/cluster-shards/#:~:text=health%3A%20Either%20online%2C%20failed%2C%20or%20loading.%20This%20information%20should%20be%20used%20to%20determine%20which%20nodes%20should%20be%20sent%20traffic.%20The%20loading%20health%20state%20should%20be%20used%20to%20know%20that%20a%20node%20is%20not%20currently%20eligible%20to%20serve%20traffic%2C%20but%20may%20be%20eligible%20in%20the%20future.) to filter out replicas that are LOADING. The health is determined based on the replication offset which is exchanged by nodes as part of gossip. But https://github.com/lettuce-io/lettuce-core/issues/2488 mentions that CLUSTER SHARDS does not expose MYSELF.
