### ISSUE TITLE
I can't use lettuce-core to link to a Docker-built "bitnami-Redis-cluster" cluster.

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [lettuce-io/lettuce-core#2041]
I can't use lettuce-core to link to a Docker-built "bitnami-Redis-cluster" cluster.

It always takes the internal IP of the Docker and links it to the port number.

**Comment by Conmi-WhiteJoker** [comment]
The cluster is not on the local machine and cannot be resolved using "network_mode: host". This is the main solution on the stack, but this problem can occur if you want to debug with a remote cluster. @mp911de

**Comment by mp911de** [comment]
This is a forum for Lettuce-specific topics, we cannot help with general Docker connectivity issues.
