### ISSUE TITLE
Redis cluster refresh of large clusters keeps I/O threads busy

### ISSUE THREAD

**Issue by be-hase** [lettuce-io/lettuce-core#2045]
#### Current Behavior

For large redis cluster, using [enablePeriodicRefresh](https://github.com/lettuce-io/lettuce-core/blob/a462cc1ca2dc009f8d1ea3d7af8fd3614348b077/src/main/java/io/lettuce/core/cluster/ClusterTopologyRefreshOptions.java#L258) causes serious performance problems.

The processing time required for `DefaultClusterTopologyRefresh.getNodeSpecificViews` increases in proportion to the cluster size.
Unfortunately, this is executed in the NIO event loop thread.

![](https://raw.githubusercontent.com/be-hase/lettuce-with-large-cluster/main/img/framegraph.png)

See the repository README below for details.
https://github.com/be-hase/lettuce-with-large-cluster

#### Input Code

I have prepared the code that can reproduce this problem.
https://github.com/be-hase/lettuce-with-large-cluster

#### Expected behavior/code

Even if we use enablePeriodicRefresh with large redis cluster, the performance will not deteriorate.

#### Environment

- Lettuce version(s): 6.1.6.RELEASE
- Redis version: 6.2.0

##### Idea 1

Stop running `DefaultClusterTopologyRefresh.getNodeSpecificViews` on the NIO event loop.

I won't go into details, but if I customized `DefaultClusterTopologyRefresh` and ran it on another thread, the
performance improved.

My team is considering adopting this method as a workaround.

##### Idea 2

Looking at the previous framegraph, it seems that the overhead is large in the processing using BitSet.
Why not change to a more primitive method like `boolean[]` ?

However, I'm not sure if the performance will improve.

#### Additional context

NONE

**Comment by be-hase** [comment]
In my actual environment, I use both `periodic refresh` and `adaptive refresh`.

Should I use only `adaptive refresh` in a large cluster?
Are there any disadvantages when using only `adaptive refresh` ?

**Comment by be-hase** [comment]
Ah, it seems good to use `dynamicRefreshSources(false)` for a large cluster.

**Comment by mp911de** [comment]
`BitSet` has a much smaller memory footprint than `boolean[]` and it is easier in usage. Generally, if you increase the periodic refresh period and rely more on adaptive refresh, then you will likely experience less refreshes.

It would be possible to use a different scheduler in `DefaultClusterTopologyRefresh.loadViews(…)` as we're using future chaining. What is the underlying cause for the ticket, how did you find out about this issue? Was it motivated by an incident or something similar?

**Comment by be-hase** [comment]
I had this problem when I upgraded from lettuce5 to lettuce6.
We are using a large redis cluster(96 nodes).

After investigating the cause, it was determined that it was due to `DefaultClusterTopologyRefresh.getNodeSpecificViews` running on the NIO event loop thread.
Asynchronous Cluster Topology Refresh has appeared from lettuce6, so I think it is the influence.

**Comment by mp911de** [comment]
Feel free to submit a pull request to use `ClientResources.eventExecutorGroup()` in the future chaining in `DefaultClusterTopologyRefresh.getNodeSpecificViews`

**Comment by be-hase** [comment]
OK. I'll try to submit PR later.

**Comment by be-hase** [comment]
@mp911de 
Submited PR. Please check 🙏 
https://github.com/lettuce-io/lettuce-core/pull/2048
