### ISSUE TITLE
Unable to connect due to Caused by: java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by ExploreNcrack** [lettuce-io/lettuce-core#2050]
I am using lettuce 6.0.2 Sync connection pooling (fixed size 10 connections min=max=10, setTimeBetweenEvictionRunsMillis(5000)) with SSL enabled for each client. 
I have many clients establishing connections to the server in different order. So clients are able to connect the server without any issue until at a certain point, newer clients are not able to connect to the server and getting the following exception
```
io.lettuce.core.RedisConnectionException: Unable to connect to xxxxx at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
Caused by: java.nio.channels.ClosedChannelException
    	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1113)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
```
what does this exception mean? is it caused by too many connections?
or connection timeout too quickly? which does not provide enough time to finish the ssl handshake?
I also noticed that the connection pooling is also constantly destroying and creating connections for unknown reasons, and the connections are not destroyed by Borrow Validation. is this an expected behavior?

**Comment by mp911de** [comment]
This can be either due to timeouts (command/connect/handshake timeouts) or a general SSL issue. You can raise the log level to debug for `io.netty.handler` to enable debug logging for the SSL handshake.

**Comment by ExploreNcrack** [comment]
@mp911de Thank you for replying! I also just want to confirm again is it normal if lettuce connection pool starting to destroyed 
some of the existing connections and creating new connections after running for a period of time (like 20-30 min)? And it seems like this will go on periodically. The connections that got destroyed by the pool are not destroyed by Borrow Validation which is a bit confusing to me. What other reasons would it cause the pool to destroy an existing connection? I have been monitoring it by collecting the [getCreatedCount](https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#getCreatedCount--)()  [getDestroyedCount](https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#getDestroyedCount--)()  [getDestroyedByBorrowValidationCount](https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#getDestroyedByBorrowValidationCount--)() and subtracting the previous value from the current value

**Comment by ExploreNcrack** [comment]
It turns out that this issue was caused by the max connection limit reached on the server side. And also the connection pool periodically destroying and creating connection problem is due to the default pool eviction policy, so once the idle connection time > config.getIdleEvictTime() 
it will destroy the connection even if that is a healthy connection and since I configured the minIdle = maxIdle=totalConnection, it will then create new connections and add to the pool

**Comment by mp911de** [comment]
Thanks for letting us know.
