### ISSUE TITLE
Offensive Code Terms

### ISSUE THREAD

**Issue by GoldenChirs** [lettuce-io/lettuce-core#2051]
Notice Lettuce 6.1.6.RELEASE API has replaced some offensive code terms 
https://lettuce.io/core/release/api/io/lettuce/core/models/role/RedisInstance.Role.html#SLAVE

but there are other places not replaced yet 
e.g 
https://lettuce.io/core/release/api/io/lettuce/core/models/role/RedisInstance.Role.html#MASTER

https://lettuce.io/core/release/api/io/lettuce/core/cluster/models/partitions/RedisClusterNode.html#getSlaveOf--

Is it possible to do a full code term scan and replace all offensive code terms. 

referencing https://developers.google.com/style/word-list

**Comment by mp911de** [comment]
Hey @GoldenChirs thanks for reaching out.

Things aren't as binary as we would like to have them. Redis decided a few years ago to revise its terminology. However, this process is still ongoing and [Redis API still exposes symbols](https://github.com/redis/redis/blob/b69636d377cce0eb8c1fae3ac80240387e31d78f/src/server.c#L5604) that do not fit our wishful thinking. While our code can clearly use independent terminology to describe things that read offending, we would rather create harm in the usage of Redis API as the concepts and meanings no longer match with what Redis provides.

As you already noticed, some work has happened with Redis providing replacements. Our API deprecates symbols that read offensive, however, we can only progress as far as Redis progresses.

**Comment by GoldenChirs** [comment]
thanks for answering this!

**Comment by mp911de** [comment]
After discussion the matter with the Redis maintainers, this migration will still be a multi-year effort and maybe with Redis 8 we can see some progress.

**Comment by GoldenChirs** [comment]
thanks for the update !
