### ISSUE TITLE
general way of catching connection related lettuce redis exceptions

### ISSUE THREAD

**Issue by ExploreNcrack** [lettuce-io/lettuce-core#2067]
Hi. I am trying to implement my own custom reconnection logic handling such that whenever there are any exceptions throwing related to connection problem it will trigger this custom reconnection logic to create a new lettuce client (through Load Balancer). Is there a general way to catch all connection related exceptions? I have seen many connection problem that are `instanceof` `RedisException` (which is very general). Can you offer any tips?
I am currently using lettuce connection pooling as my client

**Comment by mp911de** [comment]
There's typically no need to reconnect from the application since each disconnect leads to a retry loop that attempts to re-establish a Redis connection.

You can always hook into the netty `ChannelPipeline` to catch disconnect and error notifications. Can you elaborate a bit on your motivation on reimplementing something that's already there?

**Comment by ExploreNcrack** [comment]
So We have a Load Balancer gate in front of all Redis nodes. Whenever client wants to establish a new connection to one of the node, the client will first go through the Load Balancer and Load Balancer will direct it to one of the healthy node and that client will binds to that node until the end of lifetime(either the node goes down or client choose to close). All following requests from the client will directly send to the node that was bind to initially. Similarly for reconnect, I also want the client to go through the Load Balancer and same procedure to find a new healthy node to connect to. Is there a way provided by lettuce for me to customize such reconnect behavior?
Can I achieve that with `DefaultClientResources.builder().dnsResolver(host -> custom_reconnect_logic(host));` ?

**Comment by ExploreNcrack** [comment]
Hi @mp911de  so do you think that I can customize the reconnect behavior such that whenever connect or reconnect is triggered it will invoke the custom connect logic with `DefaultClientResources.builder().dnsResolver(host -> custom_reconnect_logic(host))`?

**Comment by mp911de** [comment]
For that case, please configure a custom `SocketAddressResolver`. DNS resolvers might not be used when using e.g. domain sockets.
