### ISSUE TITLE
support a common Redis*Commands interface that is all the various segmented Commands interfaces sans the Transactional ones

### ISSUE THREAD

**Issue by jinyius** [lettuce-io/lettuce-core#2068]
#### Is your feature request related to a problem? Please describe

(Focusing on the async versions to make concrete, but applies to all the different calling pattern interfaces.)

I want to be able to code against a single Commands interface that doesn't care if the connection is a clustered connection or not.  Currently, RedisAsyncCommands and RedisAdvancedClusterAsyncCommands only share the the various segmented *Commands interfaces with the AdvancedCluster one not including the RedisTransactionalAsyncCommands interface.  This is annoying in my code as I have to maintain two types of lettuce based clients when using a standalone or clustered redis instance.

AbstractRedisAsyncCommands seems to fit the bill for my needs, but it's not clean/easy for me to use this abstraction.

Cleary, everyone who needs to use transactional commands will already only use the non-clustered approaches explicitly, and those who want to use clusters or standalone would benefit from having a single commands interface to code against.  The latter case is probably very true for people who use clusters extensively, but like to run standalone instances locally for development or when deploying to dev environments which may not want to use a full cluster setup.

#### Describe the solution you'd like

There's a couple of options (ordered from what I think is acceptable/easy to the least):
1. Create a simple interface that only includes all the common commands between the clustered and standalone connections (everything but Transactional stuff afaiu).  This preserves compile time prevention of transactional calls while allowing users to deal with a single type.
2. Stop caring about the transactional commands separation in terms of compile time check, and just let it throw an UnsupportedOperationException if trying to be used in a clustered connection when the transactional commands are being called.
3. Make AbastractRedisAsyncCommands (and the like) easy to code against.

#### Describe alternatives you've considered

See above.  For my current working solution, I have some boilerplate code (2 classes for clustered vs standalone approaches) dealing with this split in interface.

#### Teachability, Documentation, Adoption, Migration Strategy

Option 1 is the least invasive and most backwards compatible.  We would create a `RedisCommonAsyncCommands` (or some other better name) interface that extends all but the Transactional segmented Redis*Commands.  Then, the connection specific aggregated interfaces like RedisAsyncCommands and RedisAdvancedClusterAsyncCommands would extend this new interface.

No existing clients need to migrate/adoption if they don't want to.  It does unlock the ability for downstream users to code against a single interface for non-transactional stuff.

**Comment by mp911de** [comment]
You can use `RedisClusterCommands` that defines all data type commands and `CLUSTER` commands.

The actual connection retrieval (Standalone, Cluster, Master/Replica) isn't something that we can change.

**Comment by asalabaev** [comment]
It is great if that will be covered in stackoverflow or elsewhere.
The applications/servers that are evolved from simpler architectures to more complicated  would start using non-clustered version and then they decide to use cluster. What to do in this case? does it mean the code should be rewritten? Could it be prevented on earlier stages? is there a known path to add cluster to the architecture with the minimal code change? That type of how to would be very helpful. Yes, a lot of restrictions come from the redis itself and those who know the redis itself well enough may be ok with "lower" level APIs but Lettuce may be considered as a guide to the redis world for java developers so an extra help would be really appreciated.

**Comment by jinyius** [comment]
> You can use `RedisClusterCommands` that defines all data type commands and `CLUSTER` commands.
> 
> The actual connection retrieval (Standalone, Cluster, Master/Replica) isn't something that we can change.

cool... `RedisClusterAsyncCommands` worked for me.
