### ISSUE TITLE
How to connect from Websphere liberty to a redis v6.2.6 cluster which is TLS enable using lettuce client

### ISSUE THREAD

**Issue by gochs1** [lettuce-io/lettuce-core#2073]
Scenario:
We want to connect to a redis cluster which is setup with the 6.2.6 TLS support.
No sTunnel based scenario.
Redis is setup in cluster mode using TLS for client and gossip.
The lettuce client is running within a websphere liberty 22.0.0.3
We want to connect using TLS certs to the redis cluster using the lettuce client running within websphere liberty.
I got the redis cluster running with TLS enabled and could connect to it via redis-cli and the certificates to the cluster. 
I was able to set/get/delete entries in redis using the redis-cli.
We now want to connect using the lettuce java client.
We struggle at the following points:
* In websphere liberty you get a SSLContext object when you setup a SSL connection
* The lettuce library expects an SSLConfig object.
Question is how to convert between them and what are the assumptions regarding the properties in the Certs that the client can successfully establish an SSL connection?
* How should the TLS certificates look like that lettuce can connect to the redis cluster?
* Is there an e2e example which shows how the certs, redis cluster and lettuce client have to be setup and which properties in the certs should be set?
At the moment we end-up with a variety of SSL exceptions which might be caused by the conversion between SSLContext and SSLConfig and how the properties in the SSL certs are set.
Regards

#### Environment

- Lettuce version(s): [6.1.1.RELEASE]
- Redis version: 6.2.6
- Websphere Liberty 22.0.0.3
- ibmjava v8 j9vm 8.0.7.5

**Comment by mp911de** [comment]
The documentation contains quite some details on SSL connections at https://lettuce.io/core/release/reference/#ssl
