### ISSUE TITLE
slaveofNoOne

### ISSUE THREAD

**Issue by yellowUmbrellaTM** [lettuce-io/lettuce-core#2075]
#### Current Behavior

slaveofNoOne   can not work  ,  because the right commad is "sof no one " not "SLAVEOF no one" 
I already try this tow command in my redis-server
my redis-server version is 6.0.5  

I see the code in CommandType Enum,  it is wright as SLAVEOF, I think it is wrong

<details>
<summary>Stack trace</summary>

```java
    Command<K, V, String> slaveofNoOne() {
        CommandArgs<K, V> args = (new CommandArgs(this.codec)).add(CommandKeyword.NO).add(CommandKeyword.ONE);
        return this.createCommand(CommandType.SLAVEOF, new StatusOutput(this.codec), args);
    }


(error) ERR unknown command `SLAVEOF`, with args beginning with: `NO`, `ONE`, 
```

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 6.1.8.RELEASE]
- Redis version: [e.g. 6.0.5 ]

**Comment by mp911de** [comment]
According to the documentation, the command syntax is `SLAVEOF NO ONE` (https://redis.io/commands/slaveof/), exactly what Lettuce does.
