### ISSUE TITLE
Why periodicRefreshEnabled defaults to False?

### ISSUE THREAD

**Issue by crazy-pizza** [lettuce-io/lettuce-core#2080]
My Redis Cluster went down a node, but it quickly picked the master. If periodicRefreshEnabled is not enabled, the Lettuce command will always timeout unless the service is restarted.

so, I wonder why periodicRefreshEnabled is false by default？

**Comment by mp911de** [comment]
There's no good default for periodic refreshes. Typically, adaptive refresh is the better strategy but it always depends on the actual environment.
