### ISSUE TITLE
docker redis use  inner net Unable to connect to

### ISSUE THREAD

**Issue by i3587616** [lettuce-io/lettuce-core#2118]
springboot 2.7.0
yml redis config like this
  redis:
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数
        max-idle: 5 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    cluster:
      nodes:
                 - 外网ip1:6391
                 - 外网ip2:6391
                 - six nodes i used 
      then problem:i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [10.31.248.235:6396]: java.nio.channels.ClosedChannelException
ip outer and inner 不是实际使用的。只是随便写的。
就是我在spring yml里配的连的是外网的IP。但是报错里给的是内网的IP，我建集群没问题，用redis-cli -c -h 外网ip -p 端口号是
可以正常访问的。

I use redis-cli -c -h outer ip -p port  can  use redis  cluster  good.
but  in springboot  ,use  lettuce  is  wrong .  logs is :
i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [outerip:6396]: 
used outer ip i donot  write .use outerip instead of  used outer ip.

**Comment by i3587616** [comment]
我知道docker  redis.conf 里的cluster-announce-ip 改为公网IP就行了。
但我设内就是内网IP啊。springboot里配外网IP不就行了。
用rediscli用 外网ip连接集群就是正常的啊。

**Comment by i3587616** [comment]
为什么还要去获取集群里的内网IP哪，我yml配置里已经给全了外网IP啊
rediscli访问就没这个问题

**Comment by LongShengWen** [comment]
> 我知道docker redis.conf 里的cluster-announce-ip 改为公网IP就行了。 但我设内就是内网IP啊。springboot里配外网IP不就行了。 用rediscli用 外网ip连接集群就是正常的啊。

兄弟，这问题解决了吗

**Comment by heihei180** [comment]
> Since all this is Chinese and I'm not able to understand it, closing the ticket.

haha.  sorry : i will translate this issue:

he use ·spring-boot`  to access redis.  the yaml is spring-redis's config file. and the config file's redis host is external host, but when he start program , the program throw an exception : 
```text
then problem:i.l.c.c.t.DefaultClusterTopologyRefresh : Unable to connect to [10.31.248.235:6396]: java.nio.channels.ClosedChannelException
```
I think his problem is why the program tips:  ip: `10.31.248.235:6396` is internal host rather than external host.

**Comment by mp911de** [comment]
Thanks a lot. It looks as if the server would use SSL but the client is not configured to use SSL. In any case, Lettuce uses the IP addresses that are announced configured and then the ones announced by Redis.
