### ISSUE TITLE
Lettuce only connecting to master for channel subscription and not slave

### ISSUE THREAD

**Issue by Madhusudhanjr99** [lettuce-io/lettuce-core#2122]
#### Current Behavior

Lettuce is connecting only to master for channel subscriptions. It seems like ReadFrom command has no impact on subcriptions. This hugely impacts scalability. We are using sentinel configuration.

<details>
<summary>Stack trace</summary>

```java
None

```
</details>

#### Input Code
		LettuceClientConfiguration clientConfig = LettucePoolingClientConfiguration.builder()
				.poolConfig(genericObjectPoolConfig)
				.readFrom(ReadFrom.REPLICA)
				.clientOptions(clientOptions)
				.build();

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Expected behavior/code

To connect to replica for subscription.

#### Environment

- Lettuce version(s): 6.18
- Redis version: 5.0.9

**Comment by mp911de** [comment]
Using the master node is the only way Pub/Sub works in a sentinel-managed arrangement. In contrast to Redis Cluster, nodes within a sentinel setup do not replicate pub/sub messages to replicas.

**Comment by mp911de** [comment]
Thanks, today I learned that `PUBLISH` commands get replicated as well. For the time being, we do not plan to add out of the box functionality to connect to replicas to consume pub/sub messages. You can achieve the same with just a bit of code. That is, obtain the list of replicas from the Sentinel, connect to the replica and subscribe:

```java
RedisURI redisURI = RedisURI.create("redis-sentinel://localhost:26379,localhost:26380/0#mymaster");
RedisClient client = RedisClient.create();

StatefulRedisSentinelConnection<String, String> sentinelConnection = client.connectSentinel(StringCodec.UTF8, redisURI);
List<Map<String, String>> slaves = sentinelConnection.sync().slaves("mymaster");
sentinelConnection.close();

Map<String, String> firstReplica = slaves.get(0);
RedisURI firstReplicaUri = RedisURI.create("redis://" + firstReplica.get("ip") + ":" + firstReplica.get("port"));

StatefulRedisPubSubConnection<String, String> replicaPubSub = client.connectPubSub(firstReplicaUri);
// …
```

The code could be optimized to reuse `ClientResources`.
