### ISSUE TITLE
RedisConnectionException: Cannot connect to a Redis Sentinel

### ISSUE THREAD

**Issue by Madhusudhanjr99** [lettuce-io/lettuce-core#2127]
#### Current Behavior

Getting some exception  that says "RedisConnectionException: Cannot connect to a Redis Sentinel". But all our sentinels are up and running and we have no issues while connecting to them in the server. Only some of our microservices connecting to same sentinel reported this issue and others were not having issue to connect. And this exception was being thrown until we restarted the service. We used one master and two replica with sentinels.
<details>
<summary>Stack trace</summary>

"Error subscribing to redis channels , channelNames : [classified, classified] : org.springframework.data.redis.RedisConnectionFailureException: Redis connection failed; nested exception is io.lettuce.core.RedisConnectionException: Could not create pool\n\tat org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:66)\n\tat org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)\n\tat org.springframework.data.redis.connection.lettuce.LettuceReactiveRedisConnection.lambda$translateException$0(LettuceReactiveRedisConnection.java:293)\n\tat reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)\n\tat reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:210)\n\tat reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1863)\n\tat reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:340)\n\tat reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onError(MonoCacheTime.java:363)\n\tat reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)\n\tat reactor.core.publisher.Operators.error(Operators.java:198)\n\tat reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:48)\n\tat reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)\n\tat reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)\n\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:55)\n\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)\n\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)\n\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: io.lettuce.core.RedisConnectionException: Could not create pool\n\tat io.lettuce.core.support.AsyncConnectionPoolSupport.lambda$null$0(AsyncConnectionPoolSupport.java:165)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)\n\tat io.lettuce.core.support.BoundedAsyncPool.lambda$closeAsync$13(BoundedAsyncPool.java:442)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)\n\tat io.lettuce.core.RedisChannelHandler.lambda$closeAsync$0(RedisChannelHandler.java:162)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)\n\tat io.lettuce.core.internal.Futures.lambda$adapt$1(Futures.java:120)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)\n\tat io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)\n\tat io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)\n\tat io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)\n\tat io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:756)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)\n\tat io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:61)\n\tat io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:611)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)\n\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\nCaused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Cannot allocate object\n\tat java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)\n\tat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)\n\tat java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1284)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1307)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)\n\tat java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)\n\tat java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2225)\n\tat io.lettuce.core.support.BoundedAsyncPool.createIdle(BoundedAsyncPool.java:188)\n\tat io.lettuce.core.support.AsyncConnectionPoolSupport.createBoundedObjectPoolAsync(AsyncConnectionPoolSupport.java:159)\n\tat io.lettuce.core.support.AsyncConnectionPoolSupport.createBoundedObjectPool(AsyncConnectionPoolSupport.java:120)\n\tat org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.lambda$getConnectionAsync$3(LettucePoolingConnectionProvider.java:122)\n\tat java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)\n\tat org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnectionAsync(LettucePoolingConnectionProvider.java:120)\n\tat org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnectionAsync(LettuceConnectionFactory.java:1624)\n\tat org.springframework.data.redis.connection.lettuce.LettuceReactiveRedisConnection$AsyncConnect.lambda$new$0(LettuceReactiveRedisConnection.java:367)\n\tat reactor.core.publisher.Mono.lambda$fromCompletionStage$1(Mono.java:572)\n\tat reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)\n\tat reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)\n\tat reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)\n\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:55)\n\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)\n\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)\n\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\t... 1 more\nCaused by: java.lang.IllegalStateException: Cannot allocate object\n\tat io.lettuce.core.support.BoundedAsyncPool.lambda$makeObject0$9(BoundedAsyncPool.java:270)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)\n\tat io.lettuce.core.DefaultConnectionFuture.lambda$null$0(DefaultConnectionFuture.java:257)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)\n\tat java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)\n\tat java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:110)\n\tat io.lettuce.core.DefaultConnectionFuture.lambda$thenCompose$1(DefaultConnectionFuture.java:254)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)\n\tat reactor.core.publisher.LambdaMonoSubscriber.doError(LambdaMonoSubscriber.java:155)\n\tat reactor.core.publisher.LambdaMonoSubscriber.onError(LambdaMonoSubscriber.java:150)\n\tat reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)\n\tat reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)\n\tat reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)\n\tat reactor.core.publisher.MonoUsingWhen$ResourceSubscriber.onError(MonoUsingWhen.java:203)\n\tat reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:80)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)\n\tat reactor.core.publisher.MonoToCompletableFuture.onError(MonoToCompletableFuture.java:77)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)\n\tat reactor.core.publisher.Operators.error(Operators.java:198)\n\tat reactor.core.publisher.MonoError.subscribe(MonoError.java:53)\n\tat reactor.core.publisher.Mono.subscribe(Mono.java:4400)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)\n\tat reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)\n\tat reactor.core.publisher.Operators.error(Operators.java:198)\n\tat reactor.core.publisher.MonoError.subscribe(MonoError.java:53)\n\tat reactor.core.publisher.Mono.subscribe(Mono.java:4400)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)\n\tat reactor.core.publisher.Operators.error(Operators.java:198)\n\tat reactor.core.publisher.MonoError.subscribe(MonoError.java:53)\n\tat reactor.core.publisher.Mono.subscribe(Mono.java:4400)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)\n\tat reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:77)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)\n\tat io.lettuce.core.AbstractRedisClient.lambda$null$5(AbstractRedisClient.java:458)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)\n\tat io.lettuce.core.protocol.RedisHandshakeHandler.lambda$fail$4(RedisHandshakeHandler.java:131)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)\n\tat io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)\n\tat io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)\n\tat io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)\n\tat io.lettuce.core.protocol.RedisHandshakeHandler.fail(RedisHandshakeHandler.java:130)\n\tat io.lettuce.core.protocol.RedisHandshakeHandler.lambda$channelActive$3(RedisHandshakeHandler.java:100)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)\n\tat io.lettuce.core.RedisHandshake.lambda$tryHandshakeResp3$1(RedisHandshake.java:105)\n\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)\n\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)\n\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)\n\tat java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)\n\tat io.lettuce.core.protocol.AsyncCommand.doCompleteExceptionally(AsyncCommand.java:139)\n\tat io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)\n\tat io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)\n\tat io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)\n\tat io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746)\n\tat io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681)\n\tat io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)\n\tat io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)\n\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\nCaused by: java.util.concurrent.CompletionException: io.lettuce.core.RedisConnectionException\n\tat java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)\n\tat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)\n\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n\t... 90 more\nCaused by: io.lettuce.core.RedisConnectionException\n\tat io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:75)\n\tat io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)\n\tat io.lettuce.core.RedisClient.lambda$transformAsyncConnectionException$22(RedisClient.java:781)\n\tat io.lettuce.core.DefaultConnectionFuture.lambda$thenCompose$1(DefaultConnectionFuture.java:253)\n\t... 82 more\nCaused by: java.util.concurrent.CompletionException: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://...classified(say localhost)...:26379?clientName\u003d...classified...]\n\tat java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)\n\tat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)\n\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n\t... 80 more\nCaused by: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://...classified(say localhost)...:26379?clientName\u003d...classified...]\n\tat io.lettuce.core.RedisClient.lambda$connectSentinelAsync$8(RedisClient.java:547)\n\tat reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)\n\t... 60 more\nCaused by: io.lettuce.core.RedisConnectionException: Cannot connect Redis Sentinel at redis://...classified(say localhost)...:26379?clientName\u003d...classified...\n\tat io.lettuce.core.RedisClient.lambda$connectSentinelAsync$6(RedisClient.java:527)\n\tat reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)\n\t... 54 more\nCaused by: io.lettuce.core.RedisCommandExecutionException: ERR max number of clients reached\n\tat io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)\n\tat io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)\n\t... 20 more\n"
</details>

#### Input Code

<details>

</details>

#### Expected behavior/code

This issue should not have come or automatically it should have resolved.

#### Environment

- Lettuce version(s): 6.18
- Redis version: 5.0.9

**Comment by mp911de** [comment]
The actual issue is: `ERR max number of clients reached`. That's nothing we can fix.
