### ISSUE TITLE
Lettuce not making connection alive even after sending the periodic ping using the connection

### ISSUE THREAD

**Issue by sandy123456754** [lettuce-io/lettuce-core#2163]
## Bug Report
.Lettuce not making connection alive even after sending the periodic ping using the connection

#### Current Behavior

I am using the lettuce client v6.1.6. we have a timeout on redis cluster of 300 seconds. If the connection is idle for 300 seconds, cluster closes the connection. Lettuce tries to reconnect using watchdog and gets reconnected properly. 
I don't have any control on redis cluster. so i can't change the timeout to zero. I am trying to make the connection alive for long time and sending the periodic ping to the cluster for every one minute but still reconnection is happening

2022-07-20 14:19:11.309 [lettuce-eventExecutorLoop-1-1] INFO  io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /X.X.X.X:6379
2022-07-20 14:19:11.803 [lettuce-eventExecutorLoop-1-2] INFO  io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /X.X.X.X:6379
2022-07-20 14:19:12.115 [lettuce-nioEventLoop-4-5] INFO  io.lettuce.core.protocol.ReconnectionHandler - Reconnected to X.X.X.X/<unresolved>:6379
2022-07-20 14:19:12.524 [lettuce-nioEventLoop-4-6] INFO  io.lettuce.core.protocol.ReconnectionHandler - Reconnected to X.X.X.X/<unresolved>:6379

After sending the periodic ping, i thought the connection will be alive and reconnection wont happen.

#### Environment

- Lettuce version(s): 6.1.6.RELEASE
- Redis version: 6.2.7

To check this issue i have used different command like exists periodically for every 1 minute, this is making the connection alive for long time but there is some problem with ping command which is not making connection alive.

**Comment by mp911de** [comment]
Redis Cluster connections uses multiple TCP connections to your Redis Cluster nodes, see the documentation: https://github.com/lettuce-io/lettuce-core/wiki/Redis-Cluster#connection-count-for-a-redis-cluster-connection-object

**Comment by sandy123456754** [comment]
I know. That's why I am getting each node connection using node ID from cluster connection and sending ping to each node but still reconnection is happening. Is there something I am missing?

**Comment by mp911de** [comment]
It could be due to the read-write/read-only nature of connections. If you use the node selection API (`RedisAdvancedClusterAsyncCommands.nodes(it -> true)`, `RedisAdvancedClusterAsyncCommands.readonly(it -> true)`) and run the ping command there, you should have hit all  node connections. Additionally, issue a `PING` on the default connection (`RedisAdvancedClusterAsyncCommands.ping()`).
