### ISSUE TITLE
When to exit from retry()

### ISSUE THREAD

**Issue by sandeshneupaneaa** [lettuce-io/lettuce-core#2164]
I am using Lettuce reactive API, version 6.1.8.RELEASE. 
and calling API as -> connection.get(key).retry().block();

After reading lettuce documentation and GitHub issues, I  still can't figure out the following:-
My question is very similar to this question-  https://stackoverflow.com/questions/67800202/when-is-it-safe-to-retry-redis-command-on-error-when-using-lettuce

1) how to determine if the failed command can be retried? There are a number of reasons that command might fail indefinitely and retry would lead to an infinite loop.

**Comment by sandeshneupaneaa** [comment]
Is there any way to retry failed commands only a couple of times?

**Comment by mp911de** [comment]
Yes, with `retry(n)` where `n` is the retry count as in `retry(3)`.
