### ISSUE TITLE
io.lettuce.core.protocol.ReconnectionHandler - Reconnected to 192.168.101.204:6379

### ISSUE THREAD

**Issue by yujunchengg** [lettuce-io/lettuce-core#2165]
springboot version:  2.3.2.RELEASE
lettuce-core version: 5.3.2.RELEASE
redis-server version: 5.0.14

when I use lettuce as spring-data-redis pool，Log always printing，I want to know how to deal with this，The details are as follows
![image](https://user-images.githubusercontent.com/36986915/180907397-3fdeb3e1-df42-420a-8a3b-c99874a26c9b.png)

**Comment by mp911de** [comment]
Looking at the timestamps, your Redis server is configured to disconnect idle clients after 30 seconds. Since this is server-based, you cannot do anything in Lettuce.
