### ISSUE TITLE
Avoid buffer copies in `RedisStateMachine`

### ISSUE THREAD

**Issue by jeffreye** [lettuce-io/lettuce-core#2173]
#### Is your feature request related to a problem? Please describe

This will be a performance improvement for all operations

#### Describe the solution you'd like

Less buffer, less copy. We can reuse the same buffer from Netty by slicing buffer.

#### Describe alternatives you've considered

NA

#### Teachability, Documentation, Adoption, Migration Strategy

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by mp911de** [comment]
Looking at the approach, it isn't exactly zero-copy, it's less copy as `UnpooledDirectByteBuf` holds a `buffer` and a `tmpNioBuf`. In any case, it's an improvement.
