### ISSUE TITLE
Support 'FCALL' commands to Call Lua-scripts that are loaded as Function in redis

### ISSUE THREAD

**Issue by sobhan-ssh** [lettuce-io/lettuce-core#2185]
## Support `FCALL` command, Redis 7 new feature

I wrote a Lua script, and loaded it as a function in my Redis using the below command:
`cat updateJobAndForwardMsgScript.lua | redis-cli -x FUNCTION LOAD REPLACE`

Then I was able to call my function in `redis-cli` as below:
`FCALL updateJobAndForwardMsg 4 key1 key2 key3 key4 arg1`

But when I wanted to implement it in my application using lettuce library I couldn't find any related method to support this new feature in Redis 7.

Here is the link to my StackOverFlow question, where I have described my problem more completly:
[Calling loaded Redis functions using lettuce](https://stackoverflow.com/questions/73426159/calling-a-redis-functionloaded-lua-script-using-lettuce-library)

It could be great if we could easily use this feature as below:
`redisCommands.fcall("functionName",  KeysNumber, Keys[], ARGS[]);`

**Comment by shanul28** [comment]
Also, is there a need to implement FUNCTION LOAD command as well apart from FCALL?

**Comment by mp911de** [comment]
Any reason you do not define a command interface returning `Mono` or `Flux`?

**Comment by shanul28** [comment]
Let say if I define a new command, then I'll have to define it's execution flow as well by extending or overriding provided classes, I'm talking about making changes in my own project, not to the lettuce repo.

**Comment by shanul28** [comment]
Also let me know if there are any development on this redis function support in lettuce, I'm in need of this feature urgently

**Comment by mp911de** [comment]
I think we're currently not sharing the same understanding. I'm recommending (what the SO answer proposes as well) using Lettuce Command interfaces where you define an interface along with an annotated method, see https://lettuce.io/core/release/reference/index.html#command-interfaces.reactive the details for a reactive variant.

You don't need to override any Lettuce-specific methods or types, instead you define your method signature and Lettuce is going to implement it for you.

**Comment by shanul28** [comment]
so this way I will be able to create FUNCTION LOAD & FCALL  command right? but still, I need to write logic on how `function load` will load the script into Redis, and return the library name. I want this all to happen in a reactive way. is there anything else I'll need to do apart from implementing the new command interface?

**Comment by mp911de** [comment]
I created a bit of documentation at https://github.com/lettuce-io/lettuce-core/wiki/Scripting-and-Functions#leveraging-scripting-and-functions-through-command-interfaces.

Other than that, Lettuce 6.3 will ship with `FCALL` and `FUNCTION` commands.

**Comment by shanul28** [comment]
Thanks, Mark, When Can we expect the release of Lettuce 6.3?
