### ISSUE TITLE
ConnectionWatchdog reconnecting to failed nodes

### ISSUE THREAD

**Issue by ieatlettuce** [lettuce-io/lettuce-core#2186]
#### Current Behavior

`ConnectionWatchdog` keeps logging warnings for failed redis nodes
```
i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 10.1.31.165:6379
i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [10.1.31.165:6379]: connect(..) failed: Invalid argument: /10.1.31.165:6379
```

Redis `CLUSTER NODES` command
```
a895fcedddb09e881f041c1a3228a9422a03bdb0 10.1.31.169:6379@16379 master - 0 1660313629081 0 connected 10923-16383
7ebe266a37fdd5f7905d8455188e0833f007f15e 10.1.31.165:6379@16379 master,fail - 1660312055068 1660312052055 2 connected
d9e6f39bf97d054ee0ce6eb356c9c0df974d8a47 10.1.31.171:6379@16379 master - 0 1660313631090 3 connected 0-5461
1feeb0ee08344cbc529c30bf4a6d914469cebae3 10.1.31.168:6379@16379 myself,master - 0 1660313624000 1 connected 5462-10922
```

#### Input Code

Usage of plain spring boot `RedisAutoConfiguration.class`  with properties

```
spring:
  redis:
    cluster:
      nodes: ${REDIS_CLUSTER_NODES}
      max-redirects: ${REDIS_CLUSTER_MAX_REDIRECTS}
```

#### Expected behavior/code

Expect lettuce to filter out failed cluster nodes and stop trying to reconnect.

#### Environment

- Lettuce version: 6.1.9.RELEASE
- Redis version: bitnami/redis-cluster:6.2.7-debian-11-r0

#### Possible Solution

Filtering out dead nodes via CLUSTER SLOTS query as in [Jedis client](https://github.com/redis/jedis/blob/master/src/main/java/redis/clients/jedis/JedisClusterInfoCache.java#L141)

**Comment by mp911de** [comment]
As long as a node is listed within the topology view, we're trying to connect to it. We are using `CLUSTER NODES` and you can implement your own partition filter via the Node filter in `ClusterClientOptions`.
