### ISSUE TITLE
Lettuce Batch Response times are degrading with time

### ISSUE THREAD

**Issue by purti-rajpal** [lettuce-io/lettuce-core#2188]
#### Current Behavior

We have a standalone java application with lettuce client that would fetch the data from Redis server. we are doing it in single threaded manner sequentially over a loop with pipelining and command flushing. At the beginning we observed the application thread is getting the response from redis in few nano seconds. But after thousand of iterations, observed there is a degradation in response time from redis.

##### Details

We have 125,000 hashes in the Redis server.  We are fetching these hashes in batches of 40 hashes using command flushing feature of lettuce. 

The code excerpt which is doing the fetch:

```
 public void run() {
        try (StatefulRedisConnection<String, String> connection = pool.borrowObject()) {
            RedisAsyncCommands<String, String> commands = connection.async();
            commands.setAutoFlushCommands(false);
            List<RedisFuture<?>> futures = new ArrayList<>();
            Map<String, Map<String, String>> result = new HashMap<String, Map<String, String>>();
            int arrayCount = keysArray.length;
            int m = 0;
            for (int l = 0; l < 1000000; l++) {
                for (int i = 0; i < 40; i++) {
                    futures.add(commands.hgetall(keysArray[m].toString()));
                    arrayCount--;
                    m++;
                    if (arrayCount <= 0) break;
                }
                commands.flushCommands();
                LettuceFutures.awaitAll(1, TimeUnit.SECONDS, futures.toArray(new RedisFuture[futures.size()]));
                if (arrayCount <= 0) break;
            }
        } catch (Exception E) {
            System.out.println("Something went wrong");
        }
    }
```

**keysArray holds the 125,000 keys present in redis server

We captured time for individual batch of 40 hashes and noticed the increasing trend. After ~1300 batches, batch execution time increases from single digit to double digit in milliseconds, there are 3125 batches. First few iterations can be ignored because it loads all the related classes.

![image](https://user-images.githubusercontent.com/102789957/186593520-36615311-5b17-494c-a0f6-2253cf92278f.png)

**Added debug statements to calculate the batch time, will attach complete program with debug statements to the issue

One sample output with debug statements containing timestamps for one batch of 40 hashes:

before: 2022-06-30 20:52:36.044
before for loop: 2022-06-30 20:52:36.044
after for loop: 2022-06-30 20:52:36.044
before flushCommands call: 2022-06-30 20:52:36.044
after flushCommands call: 2022-06-30 20:52:36.044
after awaitAll: 2022-06-30 20:52:36.067
after: 2022-06-30 20:52:36.067
batch time in milliseconds: 23

Almost entire batch time is contributed by "LetuceFutures.awaitAll" call. In the above example, this call is taking 23 ms, same as total batch execution time.

##### Analysis

We ran strace on the java process and observed the application thread connecting to redis will put the request in a pipeline and wait for the response. The communication from application server to redis happen through a lettuce event loop thread. We observed, once the lettuce event loop thread receives a response from redis it notify the application thread. Initially, the lettuce event loop thread does futex system call as soon as it get a response from redis but after thousands of iteration we see it doesn't futex after getting the response from redis and that causes delay in application thread getting the response from redis.

##### Strace analysis

Look into file strace.5232.. 5232 is the thread id of application thread.. this thread put a request to redis and wait ... Equivalent is >>>>> 18:46:14.131953 write(21, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000032>
Now thread 5258(letuce event loop thread) picks the request at something like >>>> read(21, "\1\0\0\0\0\0\0\0", 16) = 8 <0.000073>
Then it write to channel so that redis server can process >>> writev(52, [{iov_base="*2\r\n$7\r\nHGETALL\r\n$10\r\nEtASVnXiHV\r\n",.........................
It wait for the response from the redis server at epoll_wait(19, [{EPOLLIN, {u32=52, u64=139762530779188}}], 1024, -1) = 1 <0.000201>.....
Once the redis server send the response , it reads the response at read(52, "%10\r\n$12\r\npayment_mode\r\n$16\r\nCash on...................
As soon as it reads the resppnse , it should have woken the primary thread 5232..
Initially we could see there are futex calls as soon as it gets the response from redis but after after millions of request, I dont seen any futex call from 5258...
Which causes delay in waking/notifying the parent thread about response from redis server is already received.

#### Environment

- Lettuce version(s): 6.1.8
- Redis version: 6.2.6

##### Files Upload
[LettucePoolHashTestPipelineGet.java.zip](https://github.com/lettuce-io/lettuce-core/files/9422422/LettucePoolHashTestPipelineGet.java.zip)
[strace_lettuce_1thread_125000keys.tar.gz](https://github.com/lettuce-io/lettuce-core/files/9422429/strace_lettuce_1thread_125000keys.tar.gz)

**Comment by mp911de** [comment]
From a look at the code, did you notice that you're always awaiting all futures, including those been completed from the previous batch runs? That creates quite some GC and CPU pressure.

**Comment by purti-rajpal** [comment]
@mp911de, Thanks, I fixed the code like below, and it helped.
`public void run() {
        try (StatefulRedisConnection<String, String> connection = pool.borrowObject()) {
            RedisAsyncCommands<String, String> commands = connection.async();
            commands.setAutoFlushCommands(false);
        //    List<RedisFuture<?>> futures = new ArrayList<>();
            Map<String, Map<String, String>> result = new HashMap<String, Map<String, String>>();
            int arrayCount = keysArray.length;
            int m = 0;
            for (int l = 0; l < 1000000; l++) {
                List<RedisFuture<?>> futures = new ArrayList<>();
                for (int i = 0; i < 40; i++) {
                    futures.add(commands.hgetall(keysArray[m].toString()));
                    arrayCount--;
                    m++;
                    if (arrayCount <= 0) break;
                }
                commands.flushCommands();
                LettuceFutures.awaitAll(1, TimeUnit.SECONDS, futures.toArray(new RedisFuture[futures.size()]));
                if (arrayCount <= 0) break;
            }
        } catch (Exception E) {
            System.out.println("Something went wrong");
        }
    }

`
