### ISSUE TITLE
Client-Side cache pooling

### ISSUE THREAD

**Issue by jbaris** [lettuce-io/lettuce-core#2205]
#### Is your feature request related to a problem? Please describe

I would like to use a [ClientSideCaching](https://lettuce.io/core/release/api/io/lettuce/core/support/caching/ClientSideCaching.html) with [connection pooling](https://github.com/lettuce-io/lettuce-core/wiki/Connection-Pooling) enabled.

#### Describe alternatives you've considered

I have not a clear solution here, because the API is not the same for ClientSideCaching ([CacheFrontend](https://lettuce.io/core/release/api/io/lettuce/core/support/caching/CacheFrontend.html)) and the regular connection ([RedisCommands](https://lettuce.io/lettuce-4/release/api/com/lambdaworks/redis/api/sync/RedisCommands.html)).

**Comment by mp911de** [comment]
The problem with client-side caching is that it works for exactly one connection. As soon as pooling comes into play, you cannot ensure that the connection that has touched a key will receive the notification, so you must propagate all invalidations into a central component.

All that adds a massive amount of complexity.

**Comment by jbaris** [comment]
@mp911de thanks for your comment. 
What about to use the same Map instance (to store the client-cache) for all the connections? If it is a thread-safe implementation of Map (like ConcurrentHashMap, Guava or whatever) should solve that issue. I'm missing something?

**Comment by mp911de** [comment]
If your underlying `Map` is thread-safe, then this answers your question.
