### ISSUE TITLE
Why latency tracking is open by default?

### ISSUE THREAD

**Issue by DLUTTimeTDIT** [lettuce-io/lettuce-core#2208]
We had trouble online these days, because we found that JVM contains too many Histogram objects.  And each Histogram object contains a big long array, which is about 3000+ length. Because the latency tracking dynamic range is between 1000 nanoseconds and 3600000000000 nanoseconds.
     So I have several questions now:
    1. Why latency tracking is open by default, maybe most of the developers won't use this function.
    2. Why the latency tracking dynamic range is between 1000 nanoseconds and 3600000000000 nanoseconds, maybe most of the developers won't care nanoseconds precision.
   Sincerely, thank you.

**Comment by mp911de** [comment]
It's enabled if you have LatencyUtils on the class path. We enable features on a basis what we've learned in the past and if you don't want to use latency tracking, then update the configuration to disable it.
