### ISSUE TITLE
Support to validate connection host and port.

### ISSUE THREAD

**Issue by shangjin92** [lettuce-io/lettuce-core#2210]
#### Is your feature request related to a problem? Please describe
Currently, it only validate whether connection is open when verify the validity of redis connection. But sometimes, redis master will be switched, the vip address will pointed to the new redis master. But in redis connection pool, the connection still points to the discarded redis instance which has be slave, so it cannot write data by this connection.

```java
// io.lettuce.core.support.ConnectionPoolSupport.RedisPooledObjectFactory#validateObject
public boolean validateObject(PooledObject<T> p) {
    return p.getObject().isOpen();
}
```

#### Describe the solution you'd like

There is a way to point the latest redis master. When validate redis connection, it can validate whether the connection host and port is correct.

**Comment by mp911de** [comment]
Connection pool support isn't aware of clustering arrangements. If you want to use clustering and pooling, then you need to provide that kind of support for eviction yourself.
