### ISSUE TITLE
Questions regarding Lettuce performance/behavior during Elasticache Redis replica node failover

### ISSUE THREAD

**Issue by nathanielhsu** [lettuce-io/lettuce-core#2211]
I'm seeing some interesting behavior during cache node failovers and I'm wondering if this is expected or if there are ways around this. For context, I am using a Redis cluster with multiple shards and 3 replicas per shard.

Three questions:
1. When replica failovers happen, there is an extended period of time while the new node is coming up where calls are failing with LOADING exception. This makes sense as this node is still filling with data and I want to fail on calls here. My question here is what's the best way to work around this? If I implement a retry mechanism and retry the call to cache, it seems that half the time, I just get the same LOADING exception again. Is there a way to tell Lettuce to redirect the request to another cache read replica node if a LOADING exception happens? Should this be happening automatically?
2. I noticed that when replica failover happens, when the new node comes up, new connections get opened to both that node as well as the master node. The new connections to the new replica node makes sense, but why are there new connections opened to the master node as well? What's even more interesting is that these connections to the master node stay open forever and I end up with double connections to the master node permanently. Is this a symptom of having `autoReconnect` set to `true` for `ClusterClientOptions`? Should we set `autoReconnect` to `false` instead? Is there a way to avoid opening connections to the master node here? And if not, is there a way to reset the connections here so I don't see a permanent increase in connections to the master node?
3. When replica failover happens, we see a huge spike in latency for a few minutes? What's the best way to mitigate the impact of failover here?

Any insight would be appreciated here. Let me know if there are any questions. Thanks!

**Comment by mp911de** [comment]
To 1: You could enable adaptive refresh to determine what nodes are in a healthy state and which ones are catching up with replication. However, that refreshes need to happen in quick succession to identify the failover state and then to discover that the recovery has finished. Likely a retry utility in your code would make sense.

To 2: Connections are opened up lazily. The [documentation](https://github.com/lettuce-io/lettuce-core/wiki/Redis-Cluster#connection-count-for-a-redis-cluster-connection-object) explains the connection mechanism.

To 3: What is the subject of the latency? Command completion? If so, then you might want to enable adaptive refresh that triggers in a topology refresh on `MOVED`, persistent disconnect and other events. That should help with reducing the latency. However, commands are assigned to a particular node after calling a command method. The command either times out or is retried if the node comes back within the timeout. We currently do not requeue the command that is assigned to a node that has failed. Requeueing would be a neat extension.

**Comment by nathanielhsu** [comment]
Hi, thanks for the response here. Just a few follow ups on them. Here's our `ClusterTopologyRefreshOptions` for reference:

```
final ClusterTopologyRefreshOptions topologyOptions = ClusterTopologyRefreshOptions.builder()
                .enableAllAdaptiveRefreshTriggers()
                .enablePeriodicRefresh(Duration.ofMinutes(60))
                .dynamicRefreshSources(false)
                .build();
```

1. I do have `enableAllAdaptiveRefreshTriggers()` set for `ClusterTopologyRefreshOptions`. You mention that refreshes need to happen in quick succession though. What do you mean by that? Ideally I would think that `enableAllAdaptiveRefreshTriggers` should take care of scenarios such as failover and a node in LOADING state.
2. Got it. Still a little bit confused here though. Although connections are opened up lazily, why were new connections even opened up on the master node in the first place after the replica failover? We also have the `ReadFrom` strategy set to `ANY_REPLICA`. See attached screenshot below for a graph of the current connection count. The blue line is the primary node connections. Ignore the ups and downs in the primary node connections as those are due to autoscaling from another service which PUTs to the cache and is constantly creating and destroying new connections.
<img width="913" alt="Screen Shot 2022-09-30 at 12 23 42 AM" src="https://user-images.githubusercontent.com/12907522/193214442-f1b6a999-1f44-46f6-889b-1792f497e758.png">
3. Yeah subject of latency is command completion with a timeout at 25ms. I do have adaptive refresh set here, but I do still see a large spike in timeouts affecting almost 10% of traffic here for a few minutes when the failover happens and the old node is disconnected. And then this is followed by a period of an hour where the new node is in LOADING state which then ties back to the issue that I'm seeing in the first question I asked here.

**Comment by luneo7** [comment]
Hoping to help a little, this is the setting that we use with AWS Elasticache:
1 - dynamicRefreshSources set to true
2 - enablePeriodicRefresh set to 30s
3 - enableAllAdaptiveRefreshTriggers 
4 - we use a node filter as `node -> !(node.is(RedisClusterNode.NodeFlag.FAIL) || node.is(RedisClusterNode.NodeFlag.EVENTUAL_FAIL) || node.is(RedisClusterNode.NodeFlag.NOADDR));` to filter nodes with PFAIL/FAIL status and reducing connection failures during a fail over
5 - we configured a full jitter reconnect delay, with max delay of 5 seconds (https://aws.amazon.com/blogs/database/best-practices-redis-clients-and-amazon-elasticache-for-redis/)
6 - we use DirContextDnsResolver
7 - we set JVM DNS TTLs with lower settings for eg (`-Dsun.net.inetaddr.ttl=30` and `-Dsun.net.inetaddr.negative.ttl=5`)

With those settings we have a quicker recovery when we have a node failover

**Comment by mp911de** [comment]
Thanks for the update. Closing this issue as resolved.

**Comment by nathanielhsu** [comment]
Hi @luneo7  Thanks for sharing your configuration. I'll take a look here and see how I can leverage this.

@mp911de Could you take a look at my follow up to #2 above? I'm still a bit confused how lazy connections from Lettuce would lead to connections being opened on the primary node here when the ReadFrom strategy is set to `ReadFrom`.
