### ISSUE TITLE
can't connect when uri redis password contains '@'

### ISSUE THREAD

**Issue by mooncake020** [lettuce-io/lettuce-core#2212]
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
Caused by: io.lettuce.core.RedisConnectionException: Failed to connect to at least one node in [redis://*************@%27%40192.168.0.7%3A6379]
```
guess program use @ as delimiter .  consider use lastIndexOf   
</details>

#### Input Code

<details>
<summary>Input Code</summary>

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment]
You need to escape the `@` char.
