### ISSUE TITLE
Add another possible reason for `RedisCommandTimeoutException` to the FAQ

### ISSUE THREAD

**Issue by mindas** [lettuce-io/lettuce-core#2218]
## Feature Request

I recommend adding another reason for `RedisCommandTimeoutException` to the [FAQ](https://github.com/lettuce-io/lettuce-core/wiki/Frequently-Asked-Questions).

#### Is your feature request related to a problem? Please describe

This exception guaranteed to happen if:
* Lettuce is used in pooled mode (`GenericObjectPool` etc.)
* `connection.async().setAutoFlushCommands(false)` is used by the first user of said connection
* no `setAutoFlushCommands(true)` is applied at the end of the session of the first user
* another user of the above connection (re)uses the same connection from the pool expecting it to be `autoflush=true`

The above happens because Lettuce does not reset `autoFlushCommands` to its default state, `true` after the connection is returned to the pool.
This is not documented anywhere. One might expect this to be auto-reset as the setting is applied at the command level rather than connection level.

#### Describe the solution you'd like

A new section in FAQ to warn users about possible implications.

#### Describe alternatives you've considered

Treat this as a bug / fix it so that reset to true at the end of the session is not necessary.

#### Teachability, Documentation, Adoption, Migration Strategy

Not sure what to add here as the request is for documentation specifically.

**Comment by mp911de** [comment]
Fixed via [523973](https://github.com/lettuce-io/lettuce-core/wiki/Frequently-Asked-Questions/_compare/523973b83055be7aabb0ebf797214e1c7dd7e1bc...6b4d453a1f7fc282302eaf7cd7cb2aaff7d6d4bc)
