### ISSUE TITLE
Functional absence issue in Apache common-pool2 eviction

### ISSUE THREAD

**Issue by ggoowlgns** [lettuce-io/lettuce-core#2222]
#### Is your feature request related to a problem? Please describe

I found problem in my product using `lettuce` with apache `common-pool2`.
In common-pool's intentions, When Eviction thread is activated (if 'testWhileIdle' flag is on). It tests (validates) Idle Connections. 
But, nothing happens in lettuce idle connection.
Because of this issue, if connection isn't used for a long time Firewall makes tcp connection zombie. After that developer can't take any action until CommandTimeOutError occurs.

#### Describe the solution you'd like

Implementing additional method in `RedisPooledObjectFactory` from `BasePooledObjectFactory` is needed. Such as `activateObject`, `passivateObject` ..
Ping to Redis Server and make common-pool evict connection if connection is 
abnormal.

#### Describe alternatives you've considered

Actually in my product we use tcp keepalive settings to keep connection available. (send ping in tcp level) but, this solution is OS dependent and I think connection validation logic has to be included in application level.

#### Teachability, Documentation, Adoption, Migration Strategy

none of api is changed. no need to update documents

**Comment by mp911de** [comment]
The connection pool support in Lettuce is very light and might not be a good fit for each arrangement. If you require additional validations, please implement your own object factory.
