### ISSUE TITLE
Keys missing TTL, even though code sets expire on all keys

### ISSUE THREAD

**Issue by Strydom** [lettuce-io/lettuce-core#2224]
## Bug Report

We are seeing keys being written and no expire being added.

#### Current Behavior

It seems that on high load, something is causing keys to be written without their corresponding expire.
We have no explicit errors being thrown in our logs.

The reason I say under high load, is I am unable to reproduce the error locally, and it only happens very rarely on our test environment, but on production which is getting 100,000 requests a minute, we are seeing ~50% of the keys having no expire set.

```
# Keyspace
db0:keys=2085200,expires=1153093
```

#### Input Code

<details>
<summary>Input Code</summary>

```java
// Setup
@Component
class DisposableRedisClient(
    @Value("\${redis.host}") host: String,
    @Value("\${redis.port}") port: Int,
    @Value("\${redis.password}") password: String
) : DisposableBean {
    final val redisClient: RedisClient = RedisClient.create(
        RedisURI.builder()
            .withHost(host)
            .withPort(port)
            .withPassword(password.toCharArray())
            .withSsl(true)
            .build()
    )

    // We create a connection for the different types of processing we do, reactive reading, async batch reading, async batch writing
    final val readConnection: StatefulRedisConnection<String, String> = redisClient.connect()
    final val flushControlledReadConnection: StatefulRedisConnection<String, String> = redisClient.connect()
    final val flushControlledWriteConnection: StatefulRedisConnection<String, String> = redisClient.connect()

    init {
        // disable auto-flushing
        flushControlledReadConnection.setAutoFlushCommands(false)
        flushControlledWriteConnection.setAutoFlushCommands(false)
    }

    override fun destroy() {
        readConnection.close()
        flushControlledReadConnection.close()
        flushControlledWriteConnection.close()
        redisClient.shutdown()
    }
}

// Writing
override suspend fun write(placeholders: List<Placeholder>, trx: String): List<Placeholder> {
    if (placeholders.isEmpty()) {
        return placeholders
    }

    val commands = redisClient.flushControlledWriteConnection.async()

    // trx=caf2647e-f4a0-414e-8b15-7e98cf8ac41d
    val trxFutures = listOf(
        commands.xadd(trx, placeholders.associate { it.name to it.value }),
        commands.expire(trx, Duration.ofMillis(expireTime))
    )

    val keyFutures = placeholders.map { placeholder ->
        val key = getKey(placeholder.name, trx) // e.g. countryCode@e562f705-645e-4d04-8c5d-44a1ad4d6a27

        listOf(
            commands.xadd(key, placeholder.name, placeholder.value),
            commands.expire(key, Duration.ofMillis(expireTime))
        )
    }.flatten()

    val futures = trxFutures.union(keyFutures)

    commands.flushCommands()

    futures.asFlow().map { it.toCompletableFuture().await() }.collect {}

    return placeholders
}
```

</details>

#### Expected behavior/code

I  expect the expire command to be executed against the given key and be successful.

#### Environment

- Lettuce version(s): 6.1.8.RELEASE
- Redis version: 6.2.6.
  - AWS ElastiCache
  - Cluster mode off.
  - 1 primary, 2 replicas

**Comment by Strydom** [comment]
I've disabled manual flushing and the issue has gone away.

**Now the problem is latency,** the reason we wanted to buffer commands is because we are writing so many.
Redis was performing perfectly well with buffering enabled  ~5ms, now the latency is not one we can tolerate ~70ms.

<img width="734" alt="latency" src="https://user-images.githubusercontent.com/2946828/197232275-0a9ca27f-f736-4be0-83ea-232a720e6fb2.png">
<img width="729" alt="network-packets" src="https://user-images.githubusercontent.com/2946828/197232316-a5457f12-0f28-4ede-92eb-4cc5b8fb4b49.png">

The commands are executing in ~6 micro seconds and there are no slow commands running.

I was following the example given here https://github.com/lettuce-io/lettuce-core/wiki/Pipelining-and-command-flushing#command-flushing.
Having a look at other issues, it seems others have had problems with manual flushing.

Would be great to get an explanation for this issue 🙏

**Comment by mp911de** [comment]
Please do not use `setAutoFlushCommands(…)` unless you're bulk-loading data in a synchronized and single-threaded manner. Tweaking flush settings can very easily leave commands unflushed.

**Comment by Strydom** [comment]
Is there another way to enable batching?

**Comment by mp911de** [comment]
Redis utilizes pipelining for command processing regardless of the API you're using. Batching for two commands doesn't reflect any benefits compared to the complexity and bug-pronity that manual command control introduces.

**Comment by Strydom** [comment]
First, my code is not batching two commands but on average 20 commands per request.
Second, you can see from the graph I posted that there is a massive benefit in performance with batching, 5ms vs 70ms round-trip response times from redis.
The l[ettuce-io docs](https://github.com/lettuce-io/lettuce-core/wiki/Pipelining-and-command-flushing#performance-impact) even note up to a 5x performance gain from batching.

Unless you can think of any other reason/resolution for the massive increase in latency, it seems batching would be a worthwhile investment?

**Comment by mp911de** [comment]
> it seems batching would be a worthwhile investment?

It is in batch-loading scenarios a huge improvement because we can pack payload much denser than in single-command operations. Single-command is the mode for regular applications that occasionally interact with Redis.

**Comment by mp911de** [comment]
Closing this ticket as it is not actionable.
