### ISSUE TITLE
READONLY not restored with autoReconnect

### ISSUE THREAD

**Issue by joshleeb** [lettuce-io/lettuce-core#2226]
When `ClientOption.autoReconnect` is enabled, the client does not appear to restore readonly mode on a connection when it is refreshed.

#### Observed Behavior

By default `autoReconnect` is enabled. When we moved our connection pool to be filled with connections to Redis replicas rather than primaries we also introduced a call to READONLY whenever a new connection was established thinking that then the connection will be available and in readonly mode for the time that it is in the pool.

What we saw instead was occasional MOVED responses on read commands that touched the keyspace (e.g: HMGET, XREAD, etc) that were made using this pool of replica connections, indicating that connections were sometimes dropping out of readonly mode. Before discovering the `autoReconnect` feature, our workaround was simply to call READONLY before every read command.

Since disabling `autoReconnect`, we have been able to go back to calling READONLY only when a new replica connection is established and added to the pool. We have not observed the issue with elevated MOVED responses as we saw previously when `autoReconnect = true`. This suggests the Lettuce was silently reconnecting, but not restoring readonly mode on the new connection.

#### Expected Behavior

When `autoReconnect = true`, a reconnection restores the readonly state of the new underlying Redis connection. Or, if the readonly state cannot be reliably restored by the `autoReconnect` feature then it may be worth updating the [docs](https://github.com/lettuce-io/lettuce-core/wiki/Client-Options) to note that if users have code that relies on the connection being in readonly mode then they should take care to set `autoReconnect = false`.

#### Environment

- Lettuce version: 6.1.8.RELEASE
- Redis version: 6.2.6 (cluster)

**Comment by mp911de** [comment]
What type of connection are you using? Restoration of the read-only/read-write flag should happen after the reconnect re-activates the connection.

Please make sure that you have topology refresh enabled. Any changes in the Redis topology must be reflected within the client state to avoid `MOVED` redirections.

**Comment by joshleeb** [comment]
> What type of connection are you using?

We are using a `StatefulRedisConnection`.

> Please make sure that you have topology refresh enabled.

Topology refresh is enabled with a periodic refresh of 10s and `allAdaptiveRefreshTriggers` enabled.

**Comment by mp911de** [comment]
Have you tried to run `redis-cli` with `MONITOR` to see what commands get issued upon reconnect?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by joshleeb** [comment]
Apologies for not responding sooner. We have verified, through the `MONITOR` command, that the readonly state is restored during reconnection.

Thanks @mp911de for your help, and for closing the issue 🙏
