### ISSUE TITLE
Redis is  Sentinel Mode and OOM occurred in Java application when Redis was down.

### ISSUE THREAD

**Issue by javabank123** [lettuce-io/lettuce-core#2242]
## Bug Report

<details>
Redis is operating as Sentinel, and OOM occurred in Java application when Redis was down.

I couldn't find the cause, and below is part of Heap Dump.

![image](https://user-images.githubusercontent.com/32730346/199182733-3744dc24-0bf3-4881-b186-6dbf620b5f0b.png)

![image](https://user-images.githubusercontent.com/32730346/199182927-67260eb3-2db3-4422-b41e-eba9f8df461f.png)

</details>

#### Environment

- Lettuce version(s): lettuce-core:6.1.8
- Redis version: 4.0.14

**Comment by mp911de** [comment]
Please limit the request queue.
