### ISSUE TITLE
XTrimArgs Should Allow Limit = 0

### ISSUE THREAD

**Issue by Leoncanva** [lettuce-io/lettuce-core#2250]
#### Current Behavior

`XTrimArgs` asserts the maximum numbers of entries to trim is ` > 0`. Calling limit(0) results in exception thrown "Limit must be greater 0"

<details>
<summary>Stack trace</summary>

```java
Limit must be greater 0
java.lang.IllegalArgumentException: 
	at io.lettuce.core.internal.LettuceAssert.isTrue(LettuceAssert.java:208)
	at io.lettuce.core.XTrimArgs.limit(XTrimArgs.java:114)
```

</details>

#### Input Code

<details>
<summary>Input Java Code</summary>

```java
    var args = XTrimArgs.Builder.minId(minId).approximateTrimming().limit(0l);
    return commands.xtrim(streamKey, args);
```

</details>

#### Expected behavior/code

> Specifying the value 0 as count disables the limiting mechanism entirely.

[redis.io/commands/xtrim/](https://redis.io/commands/xtrim/)

> An explicit limit of 0 means unlimited (but note that it's not the default).

https://github.com/redis/redis/pull/8169

#### Environment

- Lettuce version(s): 6.1.8.RELEASE
- Redis version: >6.2.0

#### Possible Solution

```
        LettuceAssert.isTrue(limit >= 0, "Limit must be greater or equal to 0");
```

**Comment by mp911de** [comment]
That's fixed now.
