### ISSUE TITLE
Provide a way to get negotiated protocol version

### ISSUE THREAD

**Issue by ztyzbb** [lettuce-io/lettuce-core#2267]
#### Is your feature request related to a problem? Please describe

I got some Lua script to EVAL in Redis, and I need to support Redis >= 5.0. Redis 6.0 introduce RESP3 protocol, I want to get benefit from RESP3 as it provide better type conversion. I hope there is a way to get connection's negotiated protocol version, so I can use different Lua script with different Redis version.

#### Describe the solution you'd like

Currently, `StatefulRedisConnectionImpl`/`StatefulRedisSentinelConnectionImpl`/`StatefulRedisClusterConnectionImpl` all comes with a `getConnectionState`  method, maybe declare this method in `StatefulConnection`? So I can do this:
```java
((StatefulConnection<?, ?>)redisTemplate.getConnectionFactory().getConnection().getNativeConnection()).getConnectionState().getNegotiatedProtocolVersion()
```

**Comment by mp911de** [comment]
It's better to obtain the Redis version via INFO. If you require a specific protocol version, then configure Lettuce to use `ProtocolVersion.RESP3` via `ClientOptions`.

**Comment by ztyzbb** [comment]
> It's better to obtain the Redis version via INFO. If you require a specific protocol version, then configure Lettuce to use `ProtocolVersion.RESP3` via `ClientOptions`.

A good solution, thank you! Maybe I can get Redis version via INFO, and simply use RESP3 script if version >= 6, call `redis.setresp(3)` in EVAL doesn't affect current Redis connection's protocol version
