### ISSUE TITLE
Use one pool connection to interact with cache and pubsub

### ISSUE THREAD

**Issue by Distractic** [lettuce-io/lettuce-core#2295]
## Feature Request

Currently, I need to interact with redis for cache and pubsub too.
So, according to the documentation, I create a pool

```kt
pool = AsyncConnectionPoolSupport.createBoundedObjectPoolAsync(
                    { redisClient.connectAsync(codec, uri) },
                    poolConfiguration
                ).await()
```

So, the pool works well to get a connection to interact with cache (`StatefulRedisConnection`), but not for pubsub (`StatefulRedisPubSubConnection`)

#### Is your feature request related to a problem? Please describe

With one pool, we cannot get both connection type

#### Describe the solution you'd like

A pool system to choose the type of connection to use

**Comment by mp911de** [comment]
For Pub/Sub, a single (singleton) connection should be sufficient as Pub/Sub only adds listening capabilities. Once subscribed, you cannot use the Pub/Sub connection for other operations than subscribing or unsubscribing.
