### ISSUE TITLE
RedisTemplate.opsForValue().setIfAbsent(key, "1", expire, TimeUnit.SECONDS) return false

### ISSUE THREAD

**Issue by ztd770960436** [lettuce-io/lettuce-core#2309]
Boolean setResult = masterRedisTemplate.opsForValue().setIfAbsent(key, "1", expire, TimeUnit.SECONDS);

Most of the time, the return value is true, but occasionally it returns false, and it reappears stably. I don't know whether it is a configuration problem or other problems。

![image](https://user-images.githubusercontent.com/8468287/215752774-26208c64-d9f3-4f48-a61a-6f93b8024ab3.png)

**Comment by mp911de** [comment]
`SET … NX` returns either `OK` or `null` depending on the presence/absence of the key.

```
127.0.0.1:6379> SET key value EX 60 NX
OK
127.0.0.1:6379> SET key value EX 60 NX
(nil)
127.0.0.1:6379> SET key value EX 60 NX
(nil)
```

That being said, if that scenario matches your case, then everything works as expected.

**Comment by ztd770960436** [comment]
thanks

**Comment by ztd770960436** [comment]
However, my logic is used as a distributed lock. Normally, there will be no existing situation. Every time this problem occurs, check the Redis monitor to see that lettuce reconnects. The reason is that the command has been successfully executed before the Redis reconnection, and then the reconnection command has been executed again, so the result is false. So my question is how to solve this situation? thank you

**Comment by mp911de** [comment]
Unless there's a reliable way to reproduce the problem using Lettuce API, I do not consider this one to be a bug.

**Comment by CytFree** [comment]
@ztd770960436   I have encountered the same problem, have you solved it?
