### ISSUE TITLE
Outdated version of netty

### ISSUE THREAD

**Issue by rstosick** [lettuce-io/lettuce-core#2310]
## Bug Report

The version of netty currently used (`4.1.85.Final`) has a vulnerability and should be upgraded to `4.1.86.Final`
https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-3167773

I opened https://github.com/lettuce-io/lettuce-core/pull/2311 to fix it.

**Comment by mp911de** [comment]
Fixed via your PR #2311. Thanks a lot. FWIW, Lettuce isn't using the `netty-codec` library and we do not use HTTP.
