### ISSUE TITLE
Support socks5 proxy

### ISSUE THREAD

**Issue by qxo** [lettuce-io/lettuce-core#2324]
## Feature Request

ref PR: https://github.com/qxo/lettuce-core/tree/feature/supportSocks5Proxy

#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

ref PR: https://github.com/qxo/lettuce-core/tree/feature/supportSocks5Proxy

#### Teachability, Documentation, Adoption, Migration Strategy

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by mp911de** [comment]
Thanks for the suggestion and all your effort. We currently do not support SOCKS and do not plan to add support for SOCKS. Configuration only via System properties seems limiting and we have too little ask for proxy support otherwise. Therefore, we're not going to merge the pull request.

**Comment by qxo** [comment]
> Thanks for the suggestion and all your effort. We currently do not support SOCKS and do not plan to add support for SOCKS. Configuration only via System properties seems limiting and we have too little ask for proxy support otherwise. Therefore, we're not going to merge the pull request.

socksProxyHost /socksProxyPort  are Java SE 5.0+ system properties  provides SOCKS support for client TCP sockets.
ref: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html#:~:text=The%20SOCKS%20protocol%2C%20as%20defined%20in%20RFC%201928%2C,5.0%20provides%20SOCKS%20support%20for%20client%20TCP%20sockets.

and now it can be switch off: https://github.com/lettuce-io/lettuce-core/commit/b788ce20dd55b7b79138e16cd5452f89ceda0b57
