### ISSUE TITLE
Tips on Cluster Topology Refresh

### ISSUE THREAD

**Issue by stefanklas** [lettuce-io/lettuce-core#2333]
#### Current Behavior

When creating a redis cluster client, we have the following setup, where we set a topology refresh to be done every second.

```
clusterClient = RedisClusterClient.create(redisURI);
clusterClient.setOptions(ClusterClientOptions.builder()
    .autoReconnect(true)
    .sslOptions(sslOptions)
    .topologyRefreshOptions(ClusterTopologyRefreshOptions.builder()
            .enablePeriodicRefresh(Duration.of(1, ChronoUnit.SECONDS))
            .build())
    .validateClusterNodeMembership(false)
    .build());
```

What we observe when listening on the bus of the client as shown below, the topology calls keep creating new connections and then disconnecting these every second.

```
EventBus eventBus = clusterClient.getResources().eventBus();
        Disposable subscription = eventBus.get().subscribe(e -> {
            if (e instanceof ConnectedEvent) {
                log.info("Connection occurred");
            }

            if (e instanceof DisconnectedEvent) {
                log.info("Disconnection occurred");
            }
        });
```

We want to avoid this, as we plan to setup lettuce to use tls to connect to the redis cluster. Reconnecting every second with tls is having performance impacts.

![Screenshot 2023-02-16 at 17 23 02](https://user-images.githubusercontent.com/98832797/219440907-97d6e789-c3d7-4d70-898c-6ea460cadaa4.png)

Are there any tips on how we can reduce this behaviour and just keep the connections open for alot longer.

**Comment by stefanklas** [comment]
@jacob-pro

**Comment by mp911de** [comment]
A periodic refresh every second creates a lot of load, both on the client and server side. Generally, we recommend using a slow periodic refresh (e.g. every 30 minutes) and enabling [adaptive refresh](https://github.com/lettuce-io/lettuce-core/wiki/Client-options#cluster-specific-options) to trigger topology updates whenever a slot has been migrated.

Let me know whether this helps.

**Comment by mp911de** [comment]
Reusing connections for topology refresh came up as a request a few times. The key to such a feature would be defining the scope. Clearly, if the cluster is huge, we cannot keep connections to all nodes open all the time. Also, we should not use user-space connections for refresh as they might run blocking commands and we do not want to interfere with user-space connections.

Can you create a new ticket for the reuse (caching) of topology update connections?

**Comment by wmxl** [comment]
> I found that the adaptive refresh is too slow to update after a node failure. It also has the problem that once a node has gone offline it then continuously attempts to refresh spinning up new TLS connections each time.
> 
> Any refresh when TLS is enabled unfortunately has a noticeable impact on latency due to spinning up new connections.
> 
> Instead I have disabled both periodic and adaptive refreshes - and am triggering the refresh manually if we detect the cluster has changed. I am polling this via a cached connection:
> 
> ```java
> if (TopologyComparators.isChanged(clusterClient.getPartitions(), cachedConnection.clusterNodes().clone())) {
>        getClusterClient().refreshPartitions();
> }
> ```
> 
> This is working great now - although maybe it would be friendlier if there was a way to configure the Lettuce refresh to use an existing connection.

How do you maintain the cachedConnection.clusterNodes()?
