### ISSUE TITLE
What are the downside of disabling JFR 

### ISSUE THREAD

**Issue by asadyarkhan007** [lettuce-io/lettuce-core#2334]
We are running AppD in our pod along with our application. Our application use lettuce library for redis connectivity, for some reason, When we upgraded our lettuce library version to 6.1.3 in the application then we start getting error: **_Could not initialize JfrConnectionCreatedEvent #1767_**. 
So we found following link and tried to resolved:
[https://github.com/lettuce-io/lettuce-core/issues/1767](https://github.com/lettuce-io/lettuce-core/issues/1767)
**Based on above link there are two solutions:** 
1. Use the following statement `System.getProperty("io.lettuce.core.jfr",false);` to disable the jfr.
2. The second is to provide `--add-reads=jdk.jfr=ALL-UNNAMED` on jvm argument.

Could you guys tell me which one is better approach and what is the downside of disabling the JFR in lettuce?

**Comment by mp911de** [comment]
JFR events make sense if you use these. If you do not evaluate JFR events in your environment, disabling them is better.
