### ISSUE TITLE
Lettuce creates new TCP connections and terminates existing ones causing multiple request failures at the start of the load.

### ISSUE THREAD

**Issue by khushiluharuwalla** [lettuce-io/lettuce-core#2335]
#### Current Behavior

In the idle state,there are no reconnections happening from windows to ElasticCache redis but as soon as we start the load lettuce terminates existing TCP connections and creates new ones which is causing multiple failures.We have monitored the connections using "netstat" in idle state as well as under load and it is evident that the connections are not being reused if the idle time is high.Although,we observe very few failures once the connections are created(during the load ). This behaviour is only observed in windows services but things are working fine on linux.

We have set KeepAlive to true and also set the following TCP fields at the OS level as well client level but this also seems to not help.
tcp_keepalive_time-55
tcp_keepalive_intvl-1
tcp_keepalive_probes-3

#### Input Code

```
RedisURI.Builder builder = getRedisURIBuilder(properties, hosts);
        ClientResources res = getClientResources();
        SocketOptions socketOptions = SocketOptions.builder()
                .keepAlive(true)
       .keepAlive(SocketOptions.KeepAliveOptions.builder().count(3).interval(Duration.ofSeconds(1)).idle(Duration.ofSeconds(55)).build())
                .build();
ClusterClientOptions.Builder clientOptionsBuilder = ClusterClientOptions.builder();





ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enableAdaptiveRefreshTrigger(ClusterTopologyRefreshOptions.RefreshTrigger.MOVED_REDIRECT, ClusterTopologyRefreshOptions.RefreshTrigger.PERSISTENT_RECONNECTS)
                .adaptiveRefreshTriggersTimeout(properties.getRedisTopologyRefreshInterval(), TimeUnit.SECONDS)
                .build();

        redisClusterClient.setOptions(clientOptionsBuilder
                .socketOptions(socketOptions)
                .topologyRefreshOptions(topologyRefreshOptions)
                .build());
```
        

#### Expected behaviour/code

Lettuce should use the existing TCP connections instead of terminating and creating new ones.This is hampering the performance.

#### Environment

- Lettuce version(s):  6.0.2.RELEASE
- Redis version: 6.0.5

In case of linux the same logic works fine, there might be a possibility that lettuce is dependent on some OS field which is absent in our engine.

**Comment by mp911de** [comment]
Topology refresh creates new connections as topology updates should happen rarely and therefore, keeping a connection alive for e.g. 30 minutes without actually using it is waste of resources.
