### ISSUE TITLE
When ClusterTopologyRefresh is configured, can connection auto refresh cluster view?

### ISSUE THREAD

**Issue by nexttonever** [lettuce-io/lettuce-core#2337]
## Bug Report

After ClusterTopologyRefresh  is configured, does the connection created by RedisClusterClient auto refresh its partition view?

I found it is ok, when nodes increased, but it is not ok when nodes decreased.

error log:
`io.lettuce.core.RedisCommandExecutionException: CLUSTERDOWN Hash slot not served`

Any suggestion?

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment]
Yes, the topology is being refreshed according to your configuration. `CLUSTERDOWN Hash slot not served` is a server-side message that not all hash slots are distributed to be served or a master node went down. That isn't related to topology updates.

**Comment by nexttonever** [comment]
@mp911de 

Thanks for reply.

That means, if a node went down, connection cannot recover itsself,
but how about client?
Can client recover itsself in this kind of disaster?
(serveral node uri are provided, not noly one)
