### ISSUE TITLE
FullGC

### ISSUE THREAD

**Issue by zangchenyu0918** [lettuce-io/lettuce-core#2344]
using latency metrics,When the QPS is very large, it will frequently cause FullGC

![4c1af425e515059c77136026dbde881](https://user-images.githubusercontent.com/126791159/222453244-a5b0cdab-6569-47e9-baed-fe323e711cfd.jpg)

![a1097ace1377d8471a7798d267bcecc](https://user-images.githubusercontent.com/126791159/222453268-1c0d6808-27f4-470a-8223-8ccad279a711.jpg)

![6fc013aecba9723949693b228ad9aee](https://user-images.githubusercontent.com/126791159/222453278-7dcbc4f8-e51b-4160-8193-adbd2ebdf784.jpg)

**Comment by mp911de** [comment]
True.
