### ISSUE TITLE
period topology refresh cause JVM heap continue increasing

### ISSUE THREAD

**Issue by JadenHuang2023** [lettuce-io/lettuce-core#2347]
#### Current Behavior

I used redis cluster topology period refresh and I found the JVM heap memory continues increasing.

<details>
<summary>Stack trace</summary>
I used redis cluster topology period refresh and I found the JVM heap memory continues increasing.

I did some checking, It's related to the topology refresh mechanism.

If I disable period topology refresh, the issue is gone, but my case is redis cluster monitoring, I need to detect redis cluster changes in time.

Below is the JVM heap dump results:
Total heap cost:  1.8G 
io.netty.util.concurrent.FastThreadLocalThread (All 3 objects) cost almost 1.6G, referenced 398 objects

All of the 398 objects are the same, the byte[] likes this:

Class Name  | Shallow Heap | Retained Heap
byte[4194304] @ 0x704e00000  -ERR unknown command `HELLO`, with args beginning with: `3`, ..+PONG..+OK..$499..6e261c7850e35880d36a081d9ccc50bb1149cd17 10.0.1.26:6379@1122 master - 0 1677651741222 44 connected 8192-16383.300d42944ce8d1e0d4eb409d2377e363fd80869d 10.0.0.236:6379@1122 mys...|    4,194,320 |     4,194,320

byte[4194304] @ 0x705400000  -ERR unknown command `HELLO`, with args beginning with: `3`, ..+PONG..+OK..$499..6a0423345631f06aeacdb324093be2f11a1bcf55 10.0.5.120:6379@1122 slave 6e261c7850e35880d36a081d9ccc50bb1149cd17 0 1677651743631 44 connected.6e261c7850e35880d36a081d9ccc50bb1149c...|    4,194,320 |     4,194,320

byte[4194304] @ 0x706600000  -ERR unknown command `HELLO`, with args beginning with: `3`, ..+PONG..$40..6a0423345631f06aeacdb324093be2f11a1bcf55................................................................................................................................................|    4,194,320 |     4,194,320

......
......
......
Each byte[] cost almost 4M, so 398 * 4M = 1.6G almost.
<img width="495" alt="image" src="https://user-images.githubusercontent.com/105267882/222677432-64e56cae-ce46-4fe2-a232-99720587ac94.png">
<img width="892" alt="image" src="https://user-images.githubusercontent.com/105267882/222677543-e4994d48-1a4d-40b3-a5a4-83596cc790ee.png">
<img width="946" alt="image" src="https://user-images.githubusercontent.com/105267882/222677612-4758f38c-2c2a-4ba6-a560-e2db3d9f3756.png">

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
String redisUri = buildRedisUri(address);
ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
        .enableAllAdaptiveRefreshTriggers()
        .refreshTriggersReconnectAttempts(1)
        .adaptiveRefreshTriggersTimeout(30, TimeUnit.SECONDS)
        .enablePeriodicRefresh(15, TimeUnit.SECONDS)
        .build();
ClusterClientOptions clientOptions = ClusterClientOptions.builder()
        .autoReconnect(true)
        .topologyRefreshOptions(topologyRefreshOptions)
        .build();
ClientResources resources = null;
RedisClusterClient clusterClient = null;
StatefulRedisClusterConnection<String, String> connection = null;
try {
    resources = DefaultClientResources.builder()
            .ioThreadPoolSize(1)
            .computationThreadPoolSize(1)
            .nettyCustomizer(new NettyCustomizer() {
                @Override
                public void afterBootstrapInitialized(Bootstrap bootstrap) {
                    bootstrap.option(ChannelOption.ALLOCATOR, new PooledByteBufAllocator(false));
                    NettyCustomizer.super.afterBootstrapInitialized(bootstrap);
                }
            })
            .build();
    clusterClient = RedisClusterClient.create(resources, redisUri);
    clusterClient.setOptions(clientOptions);
    clusterClient.setDefaultTimeout(TIME_OUT_IN_MILLS, TimeUnit.MILLISECONDS);
    connection = clusterClient.connect();
    addShutdownHook(resources, clusterClient, connection);
    return connection;
} catch (Throwable t) {
   //close resources
    ...
    throw t;
}
```

</details>

#### Expected behavior/code

I used pooled heap buffer locator for netty,  because direct memory allocation is not friendly for monitoring.

I am not sure if there is a resource leak in the topology period refreshes or if any settings I used improperly.
Could you please have a look? Many Thanks.

#### Environment

- Lettuce version(s): lettuce-core:jar:6.1.8.RELEASE
- Redis version: 7.0.7

**Comment by mp911de** [comment]
Please use heap buffers and capture a heap dump. The netty documentation contains the actual system properties for preferring heap buffers.

**Comment by JadenHuang2023** [comment]
Thanks for your quick response.
Yes, I used the netty's pooled heap buffer: new PooledByteBufAllocator(false).

.nettyCustomizer(new NettyCustomizer() {
                @Override
                public void afterBootstrapInitialized(Bootstrap bootstrap) {
                    **bootstrap.option(ChannelOption.ALLOCATOR, new PooledByteBufAllocator(false));**
                    NettyCustomizer.super.afterBootstrapInitialized(bootstrap);
                }
            })

**Comment by JadenHuang2023** [comment]
When executing topology refresh, executing
`public void afterBootstrapInitialized(Bootstrap bootstrap) {
bootstrap.option(ChannelOption.ALLOCATOR, **new PooledByteBufAllocator(false)**);
NettyCustomizer.super.afterBootstrapInitialized(bootstrap);
}`
then creates an instance of PooledByteBufAllocator, I guess this is the problem but not sure now.

**Comment by JadenHuang2023** [comment]
I pasted heap dump in the "Stack trace" segment
