### ISSUE TITLE
Use redis inside docker for test

### ISSUE THREAD

**Issue by centralhardware** [lettuce-io/lettuce-core#2351]
#### Is your feature request related to a problem? Please describe

It would be great if make use docker environment to build redis. It allow to achieve reproducible results and get rid of difficulties with environment setup. 
I would like to investigate it in next weekend or about this time.

What do you think about it?

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Describe alternatives you've considered

-

**Comment by mp911de** [comment]
I'm not so keen on moving everything into Docker because that creates work on my side without actual benefits. Feel free to setup your own Dockerfile from the dependencies in our Makefile.
