### ISSUE TITLE
Redis cluster : behavior of Lettuce when a slave is gracefully shutdown

### ISSUE THREAD

**Issue by xLitil** [lettuce-io/lettuce-core#2352]
## Feature Request

Hi,

In the following conditions : 
- A node cluster with 3 masters et 3 replicas
- A Lettuce client with `ReadFrom.REPLICA_PREFERRED` and with topology refresh enabled. Cf attachment for the details

When I stop one replica with `SHUTDOWN` command (through redis-cli), the Lettuce client encounters some errors on `GET` like : 
- `io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)`

Is it possible to stop a replica "gracefully" (without error on Lettuce client) ?
Is it possible to add some documentation on that ? I don't found a chapter in the documentation for this question.

Regards

[RedisInjector.txt](https://github.com/lettuce-io/lettuce-core/files/10923115/RedisInjector.txt)

**Comment by mp911de** [comment]
No. If you stop a Redis node, then Lettuce will not disconnect. There's no way Redis can let clients know that it was stopped. Therefore, Lettuce assumes your Redis node is down/has crashed and attempts to reconnect. In that phase, commands are buffered. You can configure the disconnected behavior to also reject commands (see `ClientOptions`).
