### ISSUE TITLE
Add capability of cluster failover with takeOver option

### ISSUE THREAD

**Issue by SreedharReddyKallu** [lettuce-io/lettuce-core#2360]
### Discussed in https://github.com/lettuce-io/lettuce-core/discussions/2269

<div type='discussions-op-text'>

<sup>Originally posted by **SreedharReddyKallu** December  3, 2022</sup>
RedisClusterAsyncCommands is having api with force failover and soft failover but didn't find option for takeOver.
Redis documentation for same : https://redis.io/commands/cluster-failover/ </div>

**Comment by mp911de** [comment]
Fixed via #2358
