### ISSUE TITLE
cluster-require-full-coverage to "no" ,lettuce report an error when a node go down

### ISSUE THREAD

**Issue by arielzach** [lettuce-io/lettuce-core#2370]
#### Current Behavior

Hi, I have a Redis cluster in Elasticache with 2 nodes and their respective replicas. When I perform a failover on one of the nodes, Lettuce starts to give an error despite having the "cluster-require-full-coverage: no" configuration.

21:57:25.115 [lettuce-eventExecutorLoop-1-2] INFO  i.l.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /x.x.x.x:6379
21:57:25.130 [lettuce-nioEventLoop-4-1] WARN  i.l.core.protocol.ConnectionWatchdog - Cannot reconnect to [/x.x.x.x:6379]: Connection refused: /x.x.x.x:6379
21:57:28.023 [lettuce-nioEventLoop-4-2] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/x.x.x.x:6379]: Connection refused: /x.x.x.x:6379

This is the version I am using: 6.1.8.RELEASE

This is how I connect to the cache:

```java
    RedisURI redisUri = RedisURI.Builder.redis(host).withPort(conf.getPort()).build();

    redisUri.setSsl(conf.getSslEnabled());
      RedisCredentialsProvider credentialsProvider =
          new StaticCredentialsProvider(conf.getUser(), conf.getPassword().toCharArray());
      redisUri.setCredentialsProvider(credentialsProvider);

    DefaultClientResources clientResources =
        DefaultClientResources.builder()
            .reconnectDelay(
                Delay.fullJitter(
                    Duration.ofMillis(100), 
                    Duration.ofSeconds(5), 
                    100,
                    TimeUnit.MILLISECONDS)) 
            .dnsResolver(new DirContextDnsResolver())
            .build();

    ClusterTopologyRefreshOptions topologyRefreshOptions =
        ClusterTopologyRefreshOptions.builder()
            .refreshPeriod(Duration.ofSeconds(60))
            .enablePeriodicRefresh(true)
            .enableAllAdaptiveRefreshTriggers()
            .adaptiveRefreshTriggersTimeout(
                Duration.ofSeconds(30))
            .dynamicRefreshSources(true)
            .closeStaleConnections(true)
            .build();

    Predicate<RedisClusterNode> connectedNodes =
        redisClusterNode -> {
          ArrayList<RedisClusterNode.NodeFlag> failureNodeTags =
              Lists.newArrayList(
                  RedisClusterNode.NodeFlag.FAIL, RedisClusterNode.NodeFlag.EVENTUAL_FAIL);
          return redisClusterNode.getFlags().stream().noneMatch(failureNodeTags::contains);
        };

    RedisClusterClient redisClient = RedisClusterClient.create(clientResources, redisUri);
    redisClient.setOptions(
        ClusterClientOptions.builder()
            .nodeFilter(connectedNodes)
            .socketOptions(
                SocketOptions.builder()
                    .connectTimeout(
                        Duration.ofMillis(100))
                    .build())
            .timeoutOptions(
                TimeoutOptions.builder().fixedTimeout(Duration.ofMillis(conf.getTimeout())).build())
            .autoReconnect(true)
            .validateClusterNodeMembership(true)
            .pingBeforeActivateConnection(true)
            .topologyRefreshOptions(topologyRefreshOptions)
            .build());

    StatefulRedisClusterConnection<String, String> connection = redisClient.connect();
    connection.setReadFrom(ReadFrom.MASTER_PREFERRED);
```

The expected behavior is to continue writing to the nodes that are responding.

**Comment by arielzach** [comment]
Testing with a local cache, I was able to verify that it works as expected.

13:26:41.240 [lettuce-eventExecutorLoop-1-3] INFO  i.l.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /127.0.0.1:42001
13:26:41.240 [lettuce-eventExecutorLoop-1-2] INFO  i.l.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /127.0.0.1:42001
13:26:41.249 [lettuce-nioEventLoop-4-2] WARN  i.l.core.protocol.ConnectionWatchdog - Cannot reconnect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:41.251 [lettuce-nioEventLoop-4-1] INFO  i.l.c.protocol.ReconnectionHandler - Reconnected to /127.0.0.1:42002
13:26:43.240 [lettuce-nioEventLoop-4-8] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:44.941 [lettuce-nioEventLoop-4-5] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:46.631 [lettuce-eventExecutorLoop-1-8] INFO  i.l.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /127.0.0.1:42001
13:26:46.633 [lettuce-nioEventLoop-4-8] WARN  i.l.core.protocol.ConnectionWatchdog - Cannot reconnect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:46.635 [lettuce-nioEventLoop-4-2] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:48.139 [lettuce-nioEventLoop-4-7] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:49.635 [lettuce-nioEventLoop-4-4] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:51.039 [lettuce-nioEventLoop-4-1] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:51.935 [lettuce-eventExecutorLoop-1-7] INFO  i.l.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /127.0.0.1:42001
13:26:51.936 [lettuce-nioEventLoop-4-3] WARN  i.l.core.protocol.ConnectionWatchdog - Cannot reconnect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:52.936 [lettuce-nioEventLoop-4-6] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:54.541 [lettuce-nioEventLoop-4-3] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:56.135 [lettuce-nioEventLoop-4-8] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:57.034 [lettuce-eventExecutorLoop-1-8] INFO  i.l.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /127.0.0.1:42001
13:26:57.037 [lettuce-nioEventLoop-4-2] WARN  i.l.core.protocol.ConnectionWatchdog - Cannot reconnect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001
13:26:57.939 [lettuce-nioEventLoop-4-5] WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [/127.0.0.1:42001]: Connection refused: /127.0.0.1:42001

I have a question, the reconnection time is around 15s, how can I reduce it? The minimum time I was able to achieve was by setting this config: .adaptiveRefreshTriggersTimeout(Duration.ofSeconds(1)).

**Comment by mp911de** [comment]
You can configure the reconnect delay (backoff) via `ClientResources.reconnectDelay`. The reconnect delay defaults to an exponential delay with an initial delay of zero and a maximum delay of 30 seconds. You can use constant delays or delays with jitter, see the `Delay` class for further details.
