### ISSUE TITLE
Add option to disable tracing for individual commands

### ISSUE THREAD

**Issue by huangmiao** [lettuce-io/lettuce-core#2373]
l dont show ping hello command . set observationPredicate
![image](https://user-images.githubusercontent.com/5791417/228777361-2acd777e-1dfe-4dd9-89f2-1dedf46c58c5.png)
l use zipkin 
![image](https://user-images.githubusercontent.com/5791417/228777414-245ea4f2-3de9-478c-9b16-0c4e4188078a.png)
only change or add tag don`t remove ping and hello .. command 
Could you tell me where I can filter

**Comment by mp911de** [comment]
Right now, you can achieve that by wrapping the `Tracing` object and return a no-op span from `Tracer.Span.start(RedisCommand<?, ?, ?> command)` and do not finish the span on `Tracer.Span.finish()`.

**Comment by huangmiao** [comment]
![image](https://user-images.githubusercontent.com/5791417/228791792-1fb3920f-7d1f-4304-abbb-42d053db62a2.png)
![image](https://user-images.githubusercontent.com/5791417/228792394-8e4c024f-b683-4535-b9a3-cc70537d7f0b.png)

I probably looked at the logic of this piece, and I will come to this method

**Comment by huangmiao** [comment]
Can I provide the corresponding code to expand here, add ignore request

**Comment by huangmiao** [comment]
![image](https://user-images.githubusercontent.com/5791417/229009914-0cb2616d-a987-409a-8e6a-6e0923120318.png)
hi I found that the custom span can be loaded again after getting the result, which is convenient for us to customize some attributes

**Comment by huangmiao** [comment]
Now I have encountered a difficult problem. I need to record the results. I can’t get its output in the buried point. If the customized span can be called again in the output, it will be convenient for this block to perform some logic processing and other functions.

**Comment by huangmiao** [comment]
In fact, I hope that the customized span can be executed after redis completes the result, otherwise the corresponding response result will not be obtained

**Comment by mp911de** [comment]
We could consider an extension in the form of a predicate whether to trace individual commands.   A per-command `Tracing.isEnabled(RedisCommand)` could work, the predicate would be configured via `BraveTracing.Builder.tracePredicate(Predicate<RedisCommand>)`. 

Feel free to submit a pull request.

**Comment by huangmiao** [comment]
ok.
I submit code

**Comment by mp911de** [comment]
Would it be an option for you to switch to Micrometer Tracing (from Brave Tracing)? If so, then you could leverage the existing `ObservationPredicate` API from Micrometer. I'm currently in the process of adding Micrometer Tracing support to Lettuce (#2391)

**Comment by huangmiao** [comment]
![image](https://user-images.githubusercontent.com/5791417/233033145-35edb9dd-bbda-4b1b-8d7f-29a7609cf329.png)
I see that the code you submitted has been switched to the micrometer, and the observation method is adopted. At present, I only need to wait for the new version to be released.

**Comment by huangmiao** [comment]
![image](https://user-images.githubusercontent.com/5791417/233034449-4d291c3a-dd2b-4ee2-9803-faf71f6ca8d9.png)
Is it possible to add a listening event here? My requirement is to process the corresponding response results once.

**Comment by mp911de** [comment]
You can attach a callback to the future if you want to listen for responses.

**Comment by huangmiao** [comment]
That's what I thought too. At present, I can't receive the response data as before.

**Comment by andrewkruse** [comment]
Was there any traction on this? I am attempting to use micrometer with spring data redis but unfortunately... the tracing spits out the password if the HELLO command ever fails which is a no-go (we wont go into why its failing, its embarrassing...).

I attempted to wire myself in via spring with an `ObservationPredicate`, however the context has no data for me to creep on and exclude the observation that appears. 😢  I suspect I'm possibly in the wrong spot seeing as how the code I'm digging through says spring all over it, but would love to have some guidance if there is any.

All I really need is the ability to trash the one tag on the one span for the hello operation.

**Comment by mp911de** [comment]
`ObservationPredicate` is applied pretty early in the process when we create an `Observation` object. All the interesting data is being set after we created the `Observation` (command name, endpoint, command details).

Paging @marcingrzejszczak on how to suppress sending/handling an `Observation` on `Observation.stop()` by providing bits of configuration.

**Comment by mp911de** [comment]
Deferring `Observation` creation works well. We collect all details and populate `LettuceObservationContext` before we create the `Observation`. That allows a registered `ObservationPredicate` to react to `RedisCommand`.

**Comment by mp911de** [comment]
That change is in place now.

**Comment by andrewkruse** [comment]
Thank you for the guidance/int on the predicates being the wrong spot.

Here's the snippet to blast it away without needing these tweaks.

```
    @Bean
    fun noRedisHelloCommandError(): ObservationRegistryCustomizer<ObservationRegistry> =
        ObservationRegistryCustomizer<ObservationRegistry> { registry ->
            registry.observationConfig()
                .observationFilter { context ->
                    if (context is LettuceObservationContext) {
                        if (context.requiredCommand.type == CommandType.HELLO) {
                            context.removeHighCardinalityKeyValue("spring.data.redis.command.error")
                        }
                    }
                    context
                }
        }
```

**Comment by just-ysc** [comment]
@mp911de Hi, I'm using lettuce via spring data redis.
I want to use `ObservationPredicate` in order to exclude some commands(`HELLO`, `CLUSTER`, `INFO`) from tracing, but when using spring data redis, the `LettuceObservationContext` is not from `lettuce-core`. It's from `spring-data-redis`.
When do you think this change will be applied to `spring-data-redis`, too? And under these circumstances, is there any workaround to use `ObservationPredicate`?
The code snippet is as following:
```kotlin
@Bean
fun observationRegistryCustomizer(): ObservationRegistryCustomizer<ObservationRegistry> =
    ObservationRegistryCustomizer<ObservationRegistry> { registry ->
        registry.observationConfig()
            .observationPredicate { observationName, context ->
                if (context is LettuceObservationContext) {
                    if (context.requiredCommand.type == CommandType.HELLO || context.requiredCommand.type == CommandType.INFO) {
                        return@observationPredicate false
                    }
                }
                true
            }
    }
```

**Comment by mp911de** [comment]
As of Lettuce 6.3, there's a Lettuce-specific [`LettuceObservationContext`](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/tracing/LettuceObservationContext.java).
