### ISSUE TITLE
When upgrading to springboot2.6.9, the software should be upgraded to 6.1.8, and at the same time, the software should be upgraded to redis6.2.7. When the project is started, redis cannot be connected

### ISSUE THREAD

**Issue by cheruifeng** [lettuce-io/lettuce-core#2397]
When upgrading to springboot2.6.9, the software should be upgraded to 6.1.8, and at the same time, the software should be upgraded to redis6.2.7. When the project is started, redis cannot be connected

IllegalAccessError:classio/lettuce/core/protocol/CommandHandler illegally accessing “private”member of class io/lettuce/core/protocol/ChannelLogDescriptor
![image](https://user-images.githubusercontent.com/46208620/233831438-31d573d6-6e62-453d-8955-c23769207645.png)

**Comment by mp911de** [comment]
Looks like a dependency convergence issue that you might have two versions of netty or Lettuce on the class path.

**Comment by cheruifeng** [comment]
Many thanks,I'll check it out.
