### ISSUE TITLE
Intermittent NullPointerException when using zrange query

### ISSUE THREAD

**Issue by sajawaji** [lettuce-io/lettuce-core#2413]
## Bug Report
! java.lang.NullPointerException: Cannot invoke "io.lettuce.core.output.MultiOutput.add(io.lettuce.core.protocol.RedisCommand)" because "this.multi" is null
! at io.lettuce.core.StatefulRedisConnectionImpl.preProcessCommand(StatefulRedisConnectionImpl.java:263)
! at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:159)
! at io.lettuce.core.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:676)
! at io.lettuce.core.AbstractRedisAsyncCommands.zrange(AbstractRedisAsyncCommands.java:2374)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:568)
! at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:63)
! at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
! at jdk.proxy2/jdk.proxy2.$Proxy113.zrange(Unknown Source)

#### Current Behavior

We run a job to do some background work which calls zrange query to fetch list of ids, the exception occurs intermittently. 

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
List<String> getList{
RedisCommands<String, String> redisCommands = redisConnection.sync();
return redisCommands.zrange(key, 0, count - 1);
}
```

</details>

#### Environment

- Lettuce version(s): 3.0.0
- Redis version: 7

**Comment by mp911de** [comment]
This looks like you're sharing a connection across multiple threads. Please use a connection per thread when you're using transactions.

**Comment by sajawaji** [comment]
Thanks, I am able to fix it by synchronizing my method
