### ISSUE TITLE
Mset with TTL

### ISSUE THREAD

**Issue by chaurasiya-P** [lettuce-io/lettuce-core#2417]
If one need to save multiple key with their values and corresponding TTL, they have to do it by interacting with redis multiple times which increases IO operation. So to minimise this, there should be mset with TTL feature in redis. This feature could be very helpful.
Is there any other alternative way, we can save multiple keys with TTL without interacting with redis multiple times.

**Comment by mp911de** [comment]
This issue tracker contains Lettuce driver items. Please file your request at https://github.com/redis/redis/issues.
