### ISSUE TITLE
How can I stop reporting lettuce metric in SpringBoot project automatically?

### ISSUE THREAD

**Issue by jjjiiieee1** [lettuce-io/lettuce-core#2418]
We are using Lettuce 6.1.8.RELEASE in our production environment for getting some data from Redis.
I found that lettuce metric will be reported by MicrometerCommandLatencyRecorder automatically, such as lettuce_command_firstresponse_seconds.
If I do not report these metrics , how can stop reporting those?
If there are something configuration in application file?

**Comment by mp911de** [comment]
This is a Spring Boot concern as Spring Boot is configuring metrics.
