### ISSUE TITLE
set an empty password to no password

### ISSUE THREAD

**Issue by kell0gg** [lettuce-io/lettuce-core#2419]
#### Is your feature request related to a problem? Please describe

if the empty password(empty string, "") is set,
auth command is being executed instead of the ping command during [redis handshake](https://github.com/lettuce-io/lettuce-core/blob/2ad862f5a1db860d57236c21c473cfd9aefebfea/src/main/java/io/lettuce/core/RedisHandshake.java#L177-L187).

[In redis 6(or 7), auth command always returns OK](https://github.com/redis/redis/blob/e7a3d3d152c251cc25aed3d89a47a525812e72de/src/acl.c#L1423-L1425) if redis password is not set,
but earlier versions threw [an exception when auth command came into redis with no password set](https://github.com/redis/redis/blob/4.0/src/server.c#L2661-L2671).

Both redis are not set to password,but  I get different results for the auth command.
<img width="881" alt="image" src="https://github.com/lettuce-io/lettuce-core/assets/83701867/44a064d6-8e60-47c5-9033-51a016733a71">

#### Describe the solution you'd like

It would be nice if [hasPassword()](https://github.com/lettuce-io/lettuce-core/blob/2ad862f5a1db860d57236c21c473cfd9aefebfea/src/main/java/io/lettuce/core/StaticRedisCredentials.java#L52-L55) also checked for password length.

- asis

```java
    @Override
    public boolean hasPassword() {
        return password != null;
    }
```

- tobe

```java
    @Override
    public boolean hasPassword() {
        return password != null && password.length > 0;
    }
```

**Comment by mp911de** [comment]
An empty password is a valid Redis password, that's why we changed the password behavior during introduction of ACL's and RESP3 support.

**Comment by kell0gg** [comment]
I'm sorry, I hadn't considered that an empty password is valid.
I close it. thanks.
