### ISSUE TITLE
Lettuce Debug Mode Not Closing

### ISSUE THREAD

**Issue by Halimegenc** [lettuce-io/lettuce-core#2440]
We could not close the debug Mode in lettuce. It is writing too much logs to Server.

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment]
What is debug mode?
