### ISSUE TITLE
Update to Jakarta package

### ISSUE THREAD

**Issue by ToniChaz** [lettuce-io/lettuce-core#2443]
### Is your feature request related to a problem? Please describe
Currently, the lettuce-core project uses the javax package, which is being replaced by the jakarta package in the latest versions of Java. This poses a problem for users who want to use lettuce-core in environments that adopt the latest versions of Java, as javax dependencies are gradually being removed from new Java distributions.

### Describe the solution you'd like
I would like to request the implementation of the new jakarta package in lettuce-core, replacing the javax dependencies. This would allow users to use lettuce-core in the latest Java environments without compatibility issues.

Considerations:
- Update all javax references to jakarta in the lettuce-core source code.
- Ensure that existing functionalities are not negatively affected by this change.

### Describe alternatives you've considered
As an alternative, users could make local modifications to the lettuce-core source code to manually replace the javax dependencies with jakarta. However, this would require significant effort and would not be a scalable solution.

**Comment by mp911de** [comment]
> This poses a problem for users who want to use lettuce-core in environments that adopt the latest versions of Java, as javax dependencies are gradually being removed from new Java distributions.

What features exactly you're referring to? This issue is pretty unspecific as we have exactly two uses of extensions and neither one is going away.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
