### ISSUE TITLE
Array lists with set capacities in SimpleBatcher

### ISSUE THREAD

**Issue by luciopaiva** [lettuce-io/lettuce-core#2445]
## Feature Request

This is not exactly a feature request, but a potential _enhancement_ request. While working on #2444, I noticed this array list with a set capacity:

```java
List<RedisCommand<Object, Object, Object>> batch = new ArrayList<>(Math.max(batchSize, 10));
```

This logic actually appears three times inside `SimpleBatcher`. My questions are:

- is there any reason for setting the capacity of these array lists? (It's unlikely that it is bringing any noticeable performance enhancements)
- any specific reason for the `max(..., 10)`?

I'm asking this because in the code I'm working on, I thought about setting `@BatchSize()` to a huge value like `Integer.MAX_VALUE` in order to operate solely on manual flushes via `flush()` calls. The problem is that those lists are being preallocated according to the value in the annotation, so one quickly runs into an OOM if `@BatchSize()` is too big (that's how I found that code).

My enhancement proposal is to stop setting the capacity on those lists. In case my suggestion is welcome, I would also propose we further improve that code by not even having to allocate new lists inside `prepareForceFlush()` and `prepareDefaultFlush()`, but instead relying solely on the one created inside `flush()` (and thus avoid an unnecessary extra copy as well).

Thoughts? I'd be glad to create a PR for it, but I wanted to check here first if you think it makes sense.

Thanks!

**Comment by mp911de** [comment]
Preallocation makes some sense to avoid collection resizing. Indeed, the preallocation calculation is wrong, it should rather be `Math.min(batchSize, queue.size())`.

**Comment by mp911de** [comment]
That's fixed now.

**Comment by mp911de** [comment]
Feel free to submit a pull request. Happy to merge improvements if they make sense.
