### ISSUE TITLE
mget performance issues on cluster

### ISSUE THREAD

**Issue by ramezkumar72** [lettuce-io/lettuce-core#2459]
#### Is your feature request related to a problem? Please describe

mget is very slow with large number of keys in redis cluster setup
This is because the list of keys are partitioned by total number of slots (16384) instead of number of nodes in the cluster. Refer RedisAdvancedClusterAsyncCommandsImpl.java - public RedisFuture<List<KeyValue<K, V>>> mget(Iterable<K> keys)
Consider if I have Redis cluster with 2 shards. If i pass 100 keys to mget i would expect this to be executed in 2 round trips - one for each Redis node. But the keys are partitioned by 16384, so i get around 95 partition of commands, which takes more than 90 milli seconds instead few milli seconds.  

#### Describe the solution you'd like

put the mget keys in single partition which belongs to same redis node in a cluster

#### Describe alternatives you've considered

Currently to reduce the number of round trips i'm using hash tags with my custom hashing algorithm.
But this error prone and painful When the number of nodes changes in the cluster then i have to update my hash function

#### Teachability, Documentation, Adoption, Migration Strategy

Nil

**Comment by mp911de** [comment]
Cluster commands require a mapping to the same slot, it's not our limitation.
