### ISSUE TITLE
Massive TIME_ WAIT

### ISSUE THREAD

**Issue by 673885125** [lettuce-io/lettuce-core#2463]
spring:
  redis:
    lettuce:
      pool:
        enabled: false
  TCP    127.0.0.1:6379         127.0.0.1:56940        ESTABLISHED     21060
  TCP    127.0.0.1:6379         127.0.0.1:63874        ESTABLISHED     21060
  TCP    127.0.0.1:56940        127.0.0.1:6379         ESTABLISHED     7136
  TCP    127.0.0.1:63789        127.0.0.1:63790        ESTABLISHED     11092
  TCP    127.0.0.1:63790        127.0.0.1:63789        ESTABLISHED     11092
  TCP    127.0.0.1:63874        127.0.0.1:6379         ESTABLISHED     11092
  TCP    127.0.0.1:63877        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63882        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63885        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63887        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63889        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63899        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63900        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63901        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63902        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63904        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63907        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63909        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63910        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63911        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63912        127.0.0.1:6379         TIME_WAIT       0
  TCP    127.0.0.1:63915        127.0.0.1:6379         TIME_WAIT       0
  TCP    192.168.124.37:63794   192.168.124.37:63684   TIME_WAIT       0
  TCP    192.168.124.37:63795   192.168.124.37:63684   TIME_WAIT       0
  TCP    192.168.124.37:63798   120.233.20.242:36688   TIME_WAIT       0

 spring:
  redis:
    lettuce:
      pool:
        enabled: true
  TCP    127.0.0.1:6379         127.0.0.1:49281        ESTABLISHED     21060
  TCP    127.0.0.1:6379         127.0.0.1:49282        ESTABLISHED     21060
  TCP    127.0.0.1:6379         127.0.0.1:49441        ESTABLISHED     21060
  TCP    127.0.0.1:6379         127.0.0.1:49442        ESTABLISHED     21060
  TCP    127.0.0.1:6379         127.0.0.1:56940        ESTABLISHED     21060
  TCP    127.0.0.1:49281        127.0.0.1:6379         ESTABLISHED     23824
  TCP    127.0.0.1:49282        127.0.0.1:6379         ESTABLISHED     23824
  TCP    127.0.0.1:49441        127.0.0.1:6379         ESTABLISHED     23824
  TCP    127.0.0.1:49442        127.0.0.1:6379         ESTABLISHED     23824
  TCP    127.0.0.1:56940        127.0.0.1:6379         ESTABLISHED     7136

Enabling pooling will not cause a timeout, but will it have an impact on performance

**Comment by 673885125** [comment]
version lettuce-core:6.1.10.RELEASE

**Comment by mp911de** [comment]
https://stackoverflow.com/questions/33177370/what-could-cause-so-many-time-wait-connections-to-be-open
