### ISSUE TITLE
MGET sort of thing for Redis Hashes

### ISSUE THREAD

**Issue by arun-j98** [lettuce-io/lettuce-core#2490]
### Discussed in https://github.com/lettuce-io/lettuce-core/discussions/2489

<div type='discussions-op-text'>

<sup>Originally posted by **arun-j98** August 19, 2023</sup>
Hey, just wanted to ask like we have mget to get multiples keys-value pairs at once. Do we have something similar for getting redis hashes? UseCase: we have stored a multi level map {k1 : {f1: v1, f2, v2},  k2 : {f1: v1, f2: v2}} as redis hash. I want to pass k1, k2 as the list of keys and want to get the full data  for k1, k2 ==> {k1 : {f1: v1, f2, v2},  k2 : {f1: v1, f2: v2}}. I know redis-cli doesn't support mget sort of thing for hashes, but like does lettuce on its side might do some pipelining or something. 
Currently, we are doing this...we have a list of keys [k1, k2 ... kn] and for each key we are making a redis call. if the list is large then latencies are increasing which is obvious.  </div>

**Comment by arun-j98** [comment]
@mp911de Please can you help

**Comment by stevekradel-okta** [comment]
This probably doesn't belong as any sort of Lettuce feature as it sounds like you are using a custom data structure.  Lettuce already pipelines everything it can; consider if a lua script might provide a further boost.

**Comment by arun-j98** [comment]
We have a Key : Fields : Data 
We can use hget to get a particular key: field combination. hmget to get key : fields combination say k:f1, k:f2, k:f3 and hgetall to get all. Now given a list of keys, can get data for those keys all in one go? One go as in lettuce can make a connection and then get the data for these keys. Just like it is doing for mget(keys) without giving Cross slot error.

**Comment by mp911de** [comment]
`HMGET` operates on a single hash key. If you want to fetch `HMGET` from many hashes, then you need to issue these commands yourself.
