### ISSUE TITLE
Can Lettuce support transaction management for Redis clusters?

### ISSUE THREAD

**Issue by yangkangquan123** [lettuce-io/lettuce-core#2491]
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java

```
</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
private StatefulRedisClusterConnection<String, Long> longClusterConnection;
RedisClusterAsyncCommands<String, Long> commands = longClusterConnection.async();
// start transaction Compiler prompt method does not exist
commands.multi();
```

</details>

#### Expected behavior/code

In the project, Lettuce single connection was used to operate the Redis cluster. I would like to ask if Lettuce has a relevant API that can support caching operations in transactions

#### Environment

- Lettuce version(s): 6.1.10.RELEASE
- Redis version: 5.0

**Comment by mp911de** [comment]
No, there's no support for transactions in clusters. See the [reference docs](https://github.com/lettuce-io/lettuce-core/wiki/Transactions#transactions-on-clustered-connections) for further details.
