### ISSUE TITLE
What should I do if I want to cancel the ip cache of the redis cluster

### ISSUE THREAD

**Issue by FoSuCloud** [lettuce-io/lettuce-core#2497]
What should I do if I want to cancel the ip cache of the redis cluster

**Comment by mp911de** [comment]
What do you mean with IP cache? Do you mean `RedisCluster.getPartitions()` that holds the topology?

**Comment by FoSuCloud** [comment]
Yes, I don't want to save the network topology, I want to query the network topology before each redis request

**Comment by mp911de** [comment]
You can call `reloadPartitions()` or simply not use `RedisClusterClient` and use the single-connection approach instead.

**Comment by FoSuCloud** [comment]
thanks
