### ISSUE TITLE
io.lettuce.core.api.sync.RedisHashCommands#hdel doesn‘t work

### ISSUE THREAD

**Issue by wangsonggogo** [lettuce-io/lettuce-core#2507]
![image](https://github.com/lettuce-io/lettuce-core/assets/41051961/16127562-1d63-4177-91f6-b0210f76d7cd)
![image](https://github.com/lettuce-io/lettuce-core/assets/41051961/ccccc4ff-b2a8-4201-b847-4a896674bc3d)
![image](https://github.com/lettuce-io/lettuce-core/assets/41051961/67b729ae-f578-447e-be84-58a266d6e3a2)

with 6.1.6.RELEASE version

![image](https://github.com/lettuce-io/lettuce-core/assets/41051961/b3b24916-93ee-4e79-9494-6925f4cbc28a)
what is the param:K... fields for? the hash field name? or ?

**Comment by mp911de** [comment]
Hash field names.
