### ISSUE TITLE
Feature to subscribe to pubsub channel in MasterReplica setup

### ISSUE THREAD

**Issue by vitaliid** [lettuce-io/lettuce-core#2509]
#### Is your feature request related to a problem? Please describe

I have master-replica setup and using pubsub in the project. Current API allows me to configure MasterReplica connection and specify ReadFrom.REPLICA setting. I can use that connection to see channels, to publish messages but there is no possibility to subscribe to channel. So it makes useless whole MasterSlave config and setting ReadFrom for pubsub

#### Describe the solution you'd like

  ```
    RedisClient client = RedisClient.create();

      StatefulRedisMasterReplicaConnection<byte[], byte[]> connect = MasterReplica.connect(
                client,
                ByteArrayCodec.INSTANCE,
                messageBrokerConfig.getNodes(true).stream()
                        .map(RedisURI::create)
                        .toList());
        connect.setReadFrom(ReadFrom.REPLICA);
        RedisAsyncCommands<byte[], byte[]> commands = connect.reactive();
```

        //missing feature, like it is in pubsub commands   
        Flux<ChannelMessage<byte[], byte[]>> channels = commands .observeChannels();

        //or even better - possibility to specify channel
        Flux<ChannelMessage<byte[], byte[]>> channels = commands.observeChannels(channelName);

**Comment by mp911de** [comment]
Master/Replica isn't supposed to be used for Pub/Sub as notifications aren't broadcasted to replicas/the master. Please use single-connection Pub/Sub.
