### ISSUE TITLE
The lettuce client often reconnects. Is this a bug?

### ISSUE THREAD

**Issue by yangkangquan123** [lettuce-io/lettuce-core#2522]
#### Current Behavior

<details>
<summary>Stack trace</summary>
During project running, reconnection frequently occurs and the following error is reported:
[ lettuce-epollEventLoop-6-3 ]  io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3(ReconnectionHandler.java:174) - Reconnected to ....
![image](https://github.com/lettuce-io/lettuce-core/assets/131660963/ba60b049-7fda-48a2-9d27-9b20d063115b)

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```
![image](https://github.com/lettuce-io/lettuce-core/assets/131660963/325a21a6-36d2-46b3-b5d2-f21a0ad40c2e)

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]6.1.10.RELEASE
- Redis version: [e.g. 4.0.9] 5.0

**Comment by mp911de** [comment]
If it often reconnects, then it will have a reason, either network infrastructure is closing connections or Redis closes the connection.
