### ISSUE TITLE
lettuce-core and netty issue: java.lang.NoClassDefFoundError: io/netty/util/Recycler$EnhancedHandle

### ISSUE THREAD

**Issue by pierzegarra** [lettuce-io/lettuce-core#2525]
I'm working with these dependencies in a spring boot project: aws.sdk.version -> 2.20.161
lettuce-core -> 6.1.9.RELEASE version
netty -> 4.1.79.Final
I got this error:
Caused by: java.lang.NoClassDefFoundError: io/netty/util/Recycler$EnhancedHandle

**Comment by mp911de** [comment]
Looks like you have a dependency version mismatch with netty. `EnhancedHandle` has been introduced with [netty-4.1.90.Final](https://github.com/netty/netty/releases/tag/netty-4.1.90.Final). Please review your dependencies and ensure at least a consistent version across netty dependencies.
