### ISSUE TITLE
memory leak of direct memory 

### ISSUE THREAD

**Issue by Echo-Forever** [lettuce-io/lettuce-core#2531]
## Bug Report

io.lettuce.core.RedisException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 524288000 byte(s) of direct memory (used: 553648128, max: 1073741824)"}.

#### Current Behavior
when springboot application with lettuce to connect redis to retrieve big key It happens

<details>
use lettuce pool  to connect redis

</details>

**Comment by mp911de** [comment]
Allocating big chunks of direct memory can cause these issues if the memory setup doesn't match your capacity. You can try to switch to heap buffers by setting `-Dio.netty.noPreferDirect=true`.
