### ISSUE TITLE
Questions about using Lettuce with parallelStream.

### ISSUE THREAD

**Issue by fyakghooa** [lettuce-io/lettuce-core#2532]
Excuse me, because I'm unsure whether the issue I'm currently facing is a bug or not, I'm using a blank template to ask the question.

### Current behavior
Currently, I am migrating my service to use Lettuce as the Redis client in order to utilize Redis cluster mode with read-write separation functionality.
For this purpose, I have created two LettuceConnectionFactory beans: `lettuceClusterWriteConnectionFactory` and `lettuceClusterReadConnectionFactory`.

Below is the code for `lettuceClusterWriteConnectionFactory`, `lettuceClusterReadConnectionFactory`, and the pool configuration.
<details>
<summary>Java Code</summary>

```java

    @Bean
    public ClusterTopologyRefreshOptions clusterTopologyRefreshOptions() {
        return ClusterTopologyRefreshOptions.builder()
                .enablePeriodicRefresh(Duration.ofSeconds(30))
                .enableAllAdaptiveRefreshTriggers()
                .build();
    }

    @Primary
    @Bean("lettuceClusterWriteConnectionFactory")
    public LettuceConnectionFactory lettuceClusterWriteConnectionFactory(RedisClusterConfiguration redisClusterConfiguration,
                                                                         RedisProperties redisProperties,
                                                                         ClusterTopologyRefreshOptions clusterTopologyRefreshOptions) {


        LettucePoolingClientConfiguration.LettucePoolingClientConfigurationBuilder clientConfig = LettucePoolingClientConfiguration.builder()
                .readFrom(ReadFrom.MASTER)
                .poolConfig(poolConfig(redisProperties))
                .clientOptions(ClusterClientOptions.builder()
                        .autoReconnect(true)
                        .topologyRefreshOptions(clusterTopologyRefreshOptions)
                        .build());

        return new LettuceConnectionFactory(redisClusterConfiguration, clientConfig.build());
    }

    @Bean("lettuceClusterReadConnectionFactory")
    public LettuceConnectionFactory lettuceClusterReadConnectionFactory(RedisClusterConfiguration redisClusterConfiguration,
                                                                        RedisProperties redisProperties,
                                                                        ClusterTopologyRefreshOptions clusterTopologyRefreshOptions) {

        log.info("init lettuceClusterReadConnectionFactory");
        LettucePoolingClientConfiguration.LettucePoolingClientConfigurationBuilder clientConfig = LettucePoolingClientConfiguration.builder()
                .readFrom(ReadFrom.REPLICA)
                .poolConfig(poolConfig(redisProperties))
                .clientOptions(ClusterClientOptions.builder()
                        .autoReconnect(true)
                        .topologyRefreshOptions(clusterTopologyRefreshOptions)
                        .build());

        return new LettuceConnectionFactory(redisClusterConfiguration, clientConfig.build());
    }

    private GenericObjectPoolConfig<Void> poolConfig(RedisProperties redisProperties) {
        GenericObjectPoolConfig<Void> poolConfig = new GenericObjectPoolConfig<>();
        Optional.ofNullable(redisProperties.getLettuce())
                        .map(RedisProperties.Lettuce::getPool)
                                .ifPresent(pool -> {
                                    poolConfig.setMaxIdle(pool.getMaxIdle());
                                    poolConfig.setMinIdle(pool.getMinIdle());
                                    poolConfig.setMaxWaitMillis(pool.getMaxWait().toMillis());
                                    poolConfig.setMaxTotal(pool.getMaxActive());
                                    poolConfig.setTimeBetweenEvictionRunsMillis(pool.getTimeBetweenEvictionRuns().toMillis());
                                });
        return poolConfig;
    }
```

 </details>
 
And then, I conducted a load test, I found through Jaeger that the response time for certain `HGET` commands was extremely slow during the test. 
However, there were no indications of Redis responding slowly based on the Redis latency metrics. This leads me to suspect that there might be an incorrect usage of Lettuce in my code.

Here is the code snippet where the my system use the `HGET` command, `redisReader` is a customized redis connection service layer.

<details>
<summary>Java Code RedisReader</summary>

```java
public class RedisReader extends RedisTemplate<String, String> {

    public RedisReader() {
        setKeySerializer(RedisSerializer.string());
        setValueSerializer(RedisSerializer.string());
        setHashKeySerializer(RedisSerializer.string());
        setHashValueSerializer(RedisSerializer.string());
    }

    public RedisReader(RedisConnectionFactory connectionFactory) {
        this();
        setConnectionFactory(connectionFactory);
        afterPropertiesSet();
    }

    @NonNull
    @Override
    protected RedisConnection preProcessConnection(@NonNull RedisConnection connection, boolean existingConnection) {
        return new DefaultStringRedisConnection(connection);
    }
}
```

</details>

<details>
<summary>Java Code using to do the HGET command</summary>

```java
redisKeys.parallelStream()
                .map(redisKey -> redisReader.<String, String>opsForHash().get(redisKey, field))
                .map(result -> result == null ? null : JSON.parseObject(result, MyObject.class))
                .collect(Collectors.toList());
```

</details>

After changing `parallelStream` to `stream`, the issue of slow response for `HGET` commands disappeared.
Here is the code after modifying it to use stream:

<details>
<summary>Java Code using to do the HGET command with stream</summary>

```java
redisKeys.stream()
                .map(redisKey -> redisReader.<String, String>opsForHash().get(redisKey, field))
                .map(result -> result == null ? null : JSON.parseObject(result, MyObject.class))
                .collect(Collectors.toList());
```

</details>

I have three questions regarding the previous discussion, and I would greatly appreciate your insights:

1. Why did the slow response issue disappear when I changed from `parallelStream` to `stream`? I suspect it might be related to Lettuce, but I'm not entirely sure. Could you please help clarify this for me?
2. If the root cause of the issue lies with `parallelStream`, do you have any suggestions for using both `parallelStream` and Lettuce together?
3. When encountering this issue, I attempted to close the connection pool. However, I noticed that the response time difference between having the connection pool open and closed was minimal. I expected an improvement in response time when the connection pool was open. Could you please explain the possible reasons for this?

Thank you for your assistance.

Environment
Lettuce version(s): lettuce-core 5.3.2.RELEASE

**Comment by mp911de** [comment]
`parallelStream` uses the Common Fork/Join pool. Depending on other usage of the Fork/Join pool, you might encounter congestion. When using `stream`, then all JSON encoding in `map` happens on the calling thread.

Please note that you're using Lettuce through Spring Data that brings different aspects. Spring adds a bit of additional overhead and if you're willing to trade performance for developer productivity/an improved API, then this is the right way to go.

However, if you are looking for cutting-edge client performance, you should consider using the client directly, at least for critical functionality. Note that a lot of CPU pressure comes from JSON serialization.

**Comment by fyakghooa** [comment]
Hi @mp911de 
Thank you for your response.

I would like to inquire if this means that Lettuce also uses the Common Fork/Join pool? 
Therefore, Lettuce performance is affected when congestion occurs.

If the answer to the above question is affirmative, how could I configure a separate Fork/Join pool specifically for Lettuce, or to prevent Lettuce from using the Common Fork/Join pool?

Thank you once again for your response.

**Comment by mp911de** [comment]
> I would like to inquire if this means that Lettuce also uses the Common Fork/Join pool?

No, Lettuce uses its own thread pools, only `Stream.parallelStream()` uses by default the Common Fork/Join pool. 

Generally, if you want to parallelize Redis operations I recommend either using the async API or the reactive one which allow for much more control.

**Comment by fyakghooa** [comment]
Got it, thank you for your response, very appreciate your suggestions.
