### ISSUE TITLE
Bugs only  in the scan command, Other commands can be executed, such as get, hget,keys

### ISSUE THREAD

**Issue by MOLINTIAN** [lettuce-io/lettuce-core#2533]
#### Current Behavior
The background is the Redis cluster, which is down.
Lettuce core version is 6.1.5.RELEASE.
PartitionAccessor # getUpstream method error in determining valid Redis survival nodes.
Sorry, we cannot provide a stack, which involves leakage. The following source code error images are provided.

![9c1a8c7b563317919e0d3d9b725fa7a8](https://github.com/lettuce-io/lettuce-core/assets/43630100/ebe03a18-a539-4d0a-96da-cf1328fcc9df)

![3738c0010612b85cab425c6f5e633acd](https://github.com/lettuce-io/lettuce-core/assets/43630100/ab8a20d9-3f76-495a-bc15-c5c1b60e1fab)

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
    
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// this is my code.
public Set<String> patternDeleteCache(String pattern) {
        Set<String> deleteKeys = (Set<String>) redisTemplate.execute((RedisCallback<Set<String>>) connection -> {
            ScanOptions scanOptions = ScanOptions.scanOptions().match("*" + pattern + "*").count(1000).build();
            Cursor<byte[]> scan = connection.scan(scanOptions);
            Set<String> keys = new HashSet<>();
            while (scan.hasNext()) {
                keys.add(new String(scan.next()));
            }
            return keys;
        });
        if (CollectionUtils.isNotEmpty(deleteKeys)) {
            redisTemplate.delete(deleteKeys);
        }
        return deleteKeys;
    }
```

</details>

#### Environment

Lettuce core version is 6.1.5.RELEASE.
- Redis version: [e.g. 6.2.6]

**Comment by mp911de** [comment]
You can set a Node filter predicate at `ClusterClientOptions` to filter faulty nodes yourself.

**Comment by MOLINTIAN** [comment]
> You can set a Node filter predicate at `ClusterClientOptions` to filter faulty nodes yourself.

I upgraded to Lettuce-core 6.2.0.RELEASE and To automatically refresh the topology bean, add the following：
`ClusterClientOptions. Buider(). nodeFilter (it ->! (it. is (RedisClusterNode. NodeFlag. FAIL) | it. is (RedisClusterNode. NodeFlag. EVENTUAL-FAIL)). `

The configuration does not take effect for scanOptions
But it still failed and even reached the PartitionAccessor # getUpstream method
```
public Set<String> patternDeleteCache(String pattern) {
        Set<String> deleteKeys = (Set<String>) redisTemplate.execute((RedisCallback<Set<String>>) connection -> {
            ScanOptions scanOptions = ScanOptions.scanOptions().match("*" + pattern + "*").count(1000).build();
            Cursor<byte[]> scan = connection.scan(scanOptions);
            Set<String> keys = new HashSet<>();
            while (scan.hasNext()) {
                keys.add(new String(scan.next()));
            }
            return keys;
        });
        if (CollectionUtils.isNotEmpty(deleteKeys)) {
            redisTemplate.delete(deleteKeys);
        }
        return deleteKeys;
    }
```

**Comment by MOLINTIAN** [comment]
Thank you very much for your help.
After refreshing the dependency and restarting, it is ok.
