### ISSUE TITLE
Re-establish connections in the case of IP Address refresh in redis clusters

### ISSUE THREAD

**Issue by Ritika2481** [lettuce-io/lettuce-core#2535]
I'm working on a requirement to update our redis connection driver to accomodate new IP's whenever IP's are refreshed on redis clusters as we need to redeploy our apps to fetch the new IP's every time. Does Lettuce provide any built-in functionality to help with this? Can you help me with the steps to implement this in our service, if it is possible, or any sample example I can look at, something similar?

Following is the current code which is currently fetching a list of IP addresses directly using the resolveClusterNameToHosts method and then creating RedisURI objects based on these IP addresses:

> public StatefulRedisMasterReplicaConnection<byte[], byte[]> cacheConnection(AwsAsgHelper awsAsgHelper,
>                                                                                 RedisClient redisClient,
>                                                                                 @Value("${redis.autoscalingGroup}") String clusterName,
>                                                                                 @Value("${redis.auth.user}") String user,
>                                                                                 @Value("${redis.auth.password}") String password)
>     {
>         List<String> hosts = awsAsgHelper.resolveClusterNameToHosts(clusterName);
>         List<RedisURI> nodes = hosts.stream()
>                 .map(
>                         host -> RedisURI.Builder.redis(host)
>                                 .withAuthentication(user, password )
>                                 .withPort(6379)
>                                 .build()
>                 ).collect(Collectors.toList());
>         try
>         {
>             StatefulRedisMasterReplicaConnection<byte[], byte[]> connection = MasterReplica.connect(redisClient, new ByteArrayCodec(), nodes);
>             connection.setReadFrom(ReadFrom.ANY);
>             LOG.info("event=Redis-connection-successful");
>             return connection;
>         }
>         catch(Exception e )
>         {
>             LOG.error("event=Redis-connection-failed ", e);
>             return null;
>         }
>     }

**Comment by mp911de** [comment]
If you use domain names, then this will work out of the box. If you specify IP addresses as connection endpoints, then it won't work.

**Comment by Ritika2481** [comment]
> If you use domain names, then this will work out of the box. If you specify IP addresses as connection endpoints, then it won't work.

This is working currently. This is statically fetching  IP addresses and connecting to the redis clusters after fetching that list of IPs. 
I’m asking you whether there’s a built in way in lettuce which will allow dynamic/automatic fetching of IPs whenever IPs are refreshed in redis clusters

**Comment by Ritika2481** [comment]
Ohh got it. Thank you so much for the help! Closing this ticket now
