### ISSUE TITLE
Docs on metrics (wiki) are misleading

### ISSUE THREAD

**Issue by hkupty** [lettuce-io/lettuce-core#2538]
## Bug Report

[The metrics page](https://github.com/lettuce-io/lettuce-core/wiki/Command-Latency-Metrics#micrometer-options), on micrometer's settings, point out that `targetPercentiles` default to `50.0, 90.0, 95.0, 99.0, 99.9` as percent values, but this can be interpreted as the input values being on the range of `0.0` to `100.0` 

#### Current Behavior

![image](https://github.com/lettuce-io/lettuce-core/assets/2695819/d8bf0e77-0330-4a71-862d-e58354d180e6)

Of course setting up the wrong values lead to an error

#### Input Code

Repo not shared as it is private

<details>
<summary>Input Code</summary>

```kotlin
            val options = MicrometerOptions
                .builder()
                .histogram(true)
                .targetPercentiles(doubleArrayOf(50.0, 95.0, 99.0))
                .build()
```

</details>

#### Expected behavior/code

Docs show us input value in the actual format they need to be supplied, for example `0.5, 0.9, 0.95, 0.99, 0.999`.

#### Environment

- Lettuce version(s): 6.1.5.RELEASE
- Redis version: N/A

#### Possible Solution

Update the docs

#### Additional context

If this is described elsewhere, say in a `docs/` folder or in a javadoc-style page, it should be linked in the wiki as well.

**Comment by mp911de** [comment]
Thanks for the hint. That's fixed now.
