### ISSUE TITLE
Use of TimeoutOptions and SocketOptions Apparently Ignored (6.2.6.RELEASE)

### ISSUE THREAD

**Issue by rhodey** [lettuce-io/lettuce-core#2539]
#### Current Behavior
I am trying to configure both a connection timeout and command timeout for use with a `RedisClient`, the settings as I apply them are not working. I am using netcat `nc -l 6379` to spawn a tcp server on localhost 6379 to test connection timeout and command timeout behavior. Netcat logs incoming traffic to the console what I see is:

```
*2
$5
HELLO
$1
3
```

#### Input Code

<details>
<summary>Input Code</summary>

```java
public class Example {

  public static void main(String[] args) {
    SocketOptions socketOptions = SocketOptions.builder()
            .connectTimeout(Duration.ofMillis(5000))
            .build();

    TimeoutOptions timeoutOptions = TimeoutOptions.enabled(Duration.ofMillis(5000));

    ClientOptions clientOptions = ClientOptions.builder()
            .socketOptions(socketOptions)
            .pingBeforeActivateConnection(true)
            .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
            .timeoutOptions(timeoutOptions)
            .build();

    RedisThreadFactory threads = new RedisThreadFactory();
    ClientResources clientResources = DefaultClientResources.builder()
            .threadFactoryProvider((name) -> threads)
            .ioThreadPoolSize(2)
            .computationThreadPoolSize(2)
            .build();

    String host = "redis://localhost:6379";
    RedisClient client = RedisClient.create(clientResources, host);
    System.out.println(1111);
    client.setOptions(clientOptions);
    client.addListener(new ConnectionListener());
    StatefulRedisConnection<String, String> connection = client.connect();
    System.out.println(2222);
    connection.addListener(new ConnectionListener());
  }

  private static class ConnectionListener extends RedisConnectionStateAdapter {
    @Override
    public void onRedisDisconnected(RedisChannelHandler<?, ?> connection) {
      System.out.println("redis write disconnect");
    }

    @Override
    public void onRedisExceptionCaught(RedisChannelHandler<?, ?> connection, Throwable cause) {
      System.out.println("redis write exception");
    }
  }

  private static class RedisThreadFactory implements ThreadFactory {
    private int count = 0;
    @Override
    public Thread newThread(@NotNull Runnable runnable) {
      Thread thread = new Thread(runnable, "redis-" + count++);
      thread.setDaemon(true);
      return thread;
    }
  }
}
```

</details>

#### Expected behavior/code

I expect to have `1111` printed then after 5 seconds the `ConnectionListener` should receive a `onRedisExceptionCaught()` callback because netcat does not reply to the HELLO command. Instead I see only `1111` printed and then the program hangs forever on `client.connect()`.

#### Environment

- Lettuce version: 6.2.6.RELEASE
- Redis version: N/A

#### Possible Solution

I'm not sure where to start with this fix.

#### Additional context

Thank you for your attention towards this!

**Comment by mp911de** [comment]
`TimeoutOptions` apply on a per-command basis, the connect timeout refers to the TCP connect timeout. What you're looking for is the connection handshake timeout. It is configured from `RedisURI` and defaults to 60 seconds, that's probably why you figured the connect hangs forever. 

`SocketOptions` is pretty focused on the socket options (keep-alive, NoDelay, …).

The only two places that qualify for the handshake timeout is either `ClientOptions` or `TimeoutOptions` with a repurposing if the actual class.

**Comment by mp911de** [comment]
Closing as this ticket isn't actionable. If you would like us to look at this issue, please provide additional information and we will re-open the issue.
