### ISSUE TITLE
SetArgs is need to add 'get' param

### ISSUE THREAD

**Issue by Zhoutzzz** [lettuce-io/lettuce-core#2545]
#### Describe the solution you'd like
In redis 6.2 or later, set command can add 'get' param to instead getset commmand, and redis offical have been regarded it as deprecated. But in latest version of lettuce, I can not see this param. So, in the future version, this param maybe can add to SetArgs class, sincerely.

#### Teachability, Documentation, Adoption, Migration Strategy

**Comment by mp911de** [comment]
There's no `GET` param because of the return type limitations. What you're looking for is the `etGet(K key, V value, SetArgs setArgs)` command that issues a `SET` command with the `GET` argument, available since Lettuce 6.1.

**Comment by Zhoutzzz** [comment]
Tks.
