### ISSUE TITLE
For Pub sub cluster using the io.lettuce.core.pubsub.PubSubCommandArgs, due which does not make use of hash and does not distribute the channels across shards 

### ISSUE THREAD

**Issue by ramnaresh2051** [lettuce-io/lettuce-core#2555]
## Bug Report
For Pub sub cluster using the io.lettuce.core.pubsub.PubSubCommandArgs, 
And in this below overridden method, which always return null key 
@Override
    public ByteBuffer getFirstEncodedKey() {
        return null;
    }

due which does not make use of hash key and does not distribute the data(channel subscription) across the shards.

#### Current Behavior
ClusterDistributionChannelWriter --> 
ByteBuffer encodedKey = args.getFirstEncodedKey(); // this gets called to identify the encoded key, however due to PubSubCommandArgs above behaviour its always return null and complete data(channel subscription) goes to one shard only.

#### Expected behavior/code
Pubsub should make use of CommandArgs instead of PubSubCommandArgs Or should provide a option to override this.

#### Environment
- Lettuce version(s): [6.2.6.RELEASE]

#### Possible solutions
RedisPubSubReactiveCommandsImpl -- a option can be provided to pass CommandArgs while creating cluster client  as a client options.

**Comment by mp911de** [comment]
Care to elaborate on what you're trying to achieve? Cluster Pub/Sub messages get replicated to each cluster node so there's no point in applying key slot hashing.

On the other side, shared Pub/Sub, would benefit from such routing, see #1984

**Comment by ramnaresh2051** [comment]
So do we have any plan to implement #1984 ?

**Comment by mp911de** [comment]
I don't know about you, but I have a plan to eventually implement the feature. Getting support from users and the community would help to speed up the process.

> Intentionally for pubsub we have dropped slot hashing, did we face any performance issue for that ?

Yes, that is by intent. Routing Pub/Sub commands to the default connection avoids creating additional connections to cluster nodes.
