### ISSUE TITLE
Wrap a connection with a different Codec

### ISSUE THREAD

**Issue by mgroth0** [lettuce-io/lettuce-core#2564]
## Feature Request

Say I have a `StatefulRedisConnection<String, String>`. I would like to get from it a `StatefulRedisConnection<K,V>`, providing my a codec to do te conversions, without openning a new connection.

#### Is your feature request related to a problem? Please describe

Currently, it seems the only way to get a `StatefulRedisConnection` with a specific type for keys and values seems to be to literally open a new connection with `RedisClient.connect(codec)`. Opening a new network connection has a performance cost, and it should not be required to switch the codec.

#### Describe the solution you'd like

Something like `fun <K,V> StatefulRedisConnection<*,*>.forCodec(codec: Codec<K,V>): StatefulRedisConnection<K,V>`. This method would not open a new network connection.

#### Describe alternatives you've considered

One alternative is just to use a single codec that has more complex behavior that can support multipl types. This seems like a more difficult solution.

#### Teachability, Documentation, Adoption, Migration Strategy

I think it is straightforward. Is there any part of this proposal that would be challenging for users to understand?

**Comment by mp911de** [comment]
That isn't possible right now.

Codec reconfiguration will mess with already existing bits such as Pub/Sub codecs that are tied to the connection itself due to active subscriptions. Right now, applying a different codec would only affect the facade and any newly issued commands.

As this is a duplicate, closing in favor of #632.
