### ISSUE TITLE
Inquiry on how to enable redis command log

### ISSUE THREAD

**Issue by heowc** [lettuce-io/lettuce-core#2570]
## Feature Request

I would like to output the commands that occur in lettuce as logs.
However, what I found is that the log level of CommandEncoder is changed to TRACE. But I don't need DEBUG level
So I want to include the TRACE level and exclude the DEBUF level, but this requires code changes.

<img width="1176" alt="image" src="https://github.com/lettuce-io/lettuce-core/assets/22594101/a49cad98-ad08-42fa-acc1-fd71827ae910">

https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/protocol/CommandEncoder.java#L100...L105

#### Is your feature request related to a problem? Please describe

Is there a way to view the command other than this? Or how do you think about changing this?

**Comment by mp911de** [comment]
This isn't possible. However, you can register a command listener via `RedisClient` and listen to command events if that helps.
