### ISSUE TITLE
Commands hang for 10 seconds as a result of cluster failover

### ISSUE THREAD

**Issue by TerjeDahlstrom** [lettuce-io/lettuce-core#2572]
## Bug Report

Followup on https://github.com/lettuce-io/lettuce-core/discussions/2556
I've now done more investigating and think this is a bug.

Some commands hang when a `cluster failover` is issued during more than moderate load.

#### Current Behavior

When performing a `cluster failover` in a redis cluster (3 masters, 3 replicas), while issuing `set` commands using lettuce, the commands hang (for about 10 seconds), well after the failover has completed. This despite new commands to all three masters (the two original and the one promoted) completing successfully and quickly.

The observed bug is not 100% consistent and depends on load. On my machine it happens most of the times when doing 1000 `set` operations per second. Doing only 100 rarely, if ever, triggers the bug, and instead all commands finish promptly.

The behavior of Lettuce changes depending on whether a periodic topology refresh happens within 10 seconds from the failover. The described scenario is when periodic topology refresh is set to 3 seconds, guaranteeing it happens within the 10 seconds. With periodic topology refresh turned off, about one third of the commands (I'm assuming it is all commands issued to the node failing over) during the 10 second period hang, and quickly gets completed after the 10 seconds.

#### Input Code
```java
package test.reproducer;

import io.lettuce.core.RedisURI;
import io.lettuce.core.SetArgs;
import io.lettuce.core.TimeoutOptions;
import io.lettuce.core.cluster.ClusterClientOptions;
import io.lettuce.core.cluster.ClusterTopologyRefreshOptions;
import io.lettuce.core.cluster.RedisClusterClient;
import io.lettuce.core.cluster.api.StatefulRedisClusterConnection;

import java.time.Duration;
import java.time.Instant;
import java.util.UUID;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicLong;

public class Main {

    private final StatefulRedisClusterConnection<String, String> connection;
    private final AtomicLong calls = new AtomicLong(0L);
    private final AtomicLong slowCalls = new AtomicLong(0L);
    private final AtomicLong badCalls = new AtomicLong(0L);
    private final AtomicLong callsIssued = new AtomicLong(0L);

    public static void main(String[] args) {
        var clusterRefreshOptions =
                ClusterTopologyRefreshOptions.builder().enablePeriodicRefresh(Duration.ofSeconds(3)).build();
        var timeoutOptions = TimeoutOptions.builder()
//                .fixedTimeout(Duration.ofMillis(1000))
                .build();
        var clientOptions = ClusterClientOptions.builder()
                .topologyRefreshOptions(clusterRefreshOptions).timeoutOptions(timeoutOptions).build();
        var clusterClient =
                RedisClusterClient.create(new RedisURI("<IP>", <PORT>, Duration.ofMillis(500)));
        clusterClient.setOptions(clientOptions);
        var main = new Main(clusterClient.connect());
        main.run();
    }

    public Main(StatefulRedisClusterConnection<String, String> connection) {
        this.connection = connection;
    }

    public void run() {
        ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
        executorService.scheduleAtFixedRate(this::callRedis, 500, 1, TimeUnit.MILLISECONDS);
        ScheduledExecutorService statsExecutorService = Executors.newSingleThreadScheduledExecutor();
        statsExecutorService.scheduleAtFixedRate(this::stats, 500, 1000, TimeUnit.MILLISECONDS);

    }

    private void stats() {
        System.out.println("Calls: " + calls.get() + " Bad calls: " + badCalls.get()
                + " Slow calls: " + slowCalls.get() + " Calls waiting: " + (callsIssued.get() - calls.get()));
    }

    private void callRedis() {
        callsIssued.incrementAndGet();
        var startTime = Instant.now();
        connection.async().set(UUID.randomUUID().toString(),
                        "A very reasonable value",
                        SetArgs.Builder.ex(Duration.ofSeconds(60)))
                .handle((s, e) -> {
                    if (Duration.between(startTime, Instant.now()).compareTo(Duration.ofSeconds(5)) > 0) {
                        slowCalls.incrementAndGet();
                    }
                    calls.incrementAndGet();
                    if (e != null) {
                        badCalls.incrementAndGet();
                    }
                    return s;
                });
    }
}
```

#### Expected behavior/code

Maybe some queuing of commands is to expected during the failover, but I would expect all commands to rapidly be completed once the failover finishes.

#### Environment

- Lettuce version(s): 6.3.0.RELEASE
- Redis version: 6.2.7

**Comment by TerjeDahlstrom** [comment]
I would really appreciate any input regarding this. Is there a better way of configuring lettuce that mitigates this issue, or is it indeed, as I believe, a bug?
I will gladly provide more context or debugging information if it helps.
@mp911de

**Comment by TerjeDahlstrom** [comment]
After more troubleshooting this seems to be a Redis issue and not a problem with lettuce. Commands sent to the master being demoted, hang for a long time after the failover is otherwise finished. This means that a topology refresh has new commands going to the new master, and these commands finish quickly and successfully.
Why the old master keeps blocking commands after the cluster is rebalanced is still unknown.

**Comment by mp911de** [comment]
Thanks for letting us know.
