### ISSUE TITLE
Switch to `ConcurrentLinkedQueue` to avoid expensive `size` calls

### ISSUE THREAD

**Issue by okg-cxf** [lettuce-io/lettuce-core#2602]
## Feature Request

ConcurrentLinkedDeque has unnecessary overhead because it needs to maintain an extra volatile prev pointer. 

#### Is your feature request related to a problem? Please describe

No

#### Describe the solution you'd like

Replace with ConcurrentLinkedQueue instead

#### Describe alternatives you've considered

No

#### Teachability, Documentation, Adoption, Migration Strategy

N.A.

**Comment by okg-cxf** [comment]
see https://github.com/lettuce-io/lettuce-core/pull/2601

**Comment by mp911de** [comment]
Thanks a lot for reaching out. Do you have any metrics (or pointer) that underline the change?
