### ISSUE TITLE
Performance: Encoding of keys/values in CommandArgs when using a codec that implements ToByteBufEncoder

### ISSUE THREAD

**Issue by shikharid** [lettuce-io/lettuce-core#2610]
## Feature Request

Remove unwanted allocation when encoding `CommandArgs` when using a codec of type `ToByteBufEncoder`

#### Is your feature request related to a problem? Please describe

I was analysing cpu/memory for a jvm server that uses Redis heavily (order of 10s of thousands hmget/sec on ~10 connections) and noticed a good amount of CPU usage of the VM (~30% of total and ~70% of eventloops cpu time) comes from `CommandArgs.KeyArgument.encode`

![Screenshot 2024-01-24 at 9 35 39 PM](https://github.com/lettuce-io/lettuce-core/assets/10097451/c74062f9-9b25-4b2f-87df-37b1162ce35c) 

All the connections use a ByteArrayCodec. Majority of the time is basically Netty's bytebuf gc/pooling logic.
The reason seems to be our specific usecase where every hmget call has 100s of keys and this gets called for **each** key

I looked through the implementation and it felt like these allocs can be entirely avoided for the special case where user does all req/resp in byte arrays (like folks who use the ByteArrayCodec) or for users who can exactly estimate the size of key/val

Two disclaimers:
- The jfr sample used to analyse this is small (5 mins during peak load)
- I have not invested extensive time with lettuce code, so might have been foolish to assume my suggestion below works

#### Describe the solution you'd like

Relevant code is in `CommandArgs.KeyArgument.encode()`and `CommandArgs.ValueArgument.encode()`
```java

            if (codec instanceof ToByteBufEncoder) {

                ToByteBufEncoder<K, V> toByteBufEncoder = (ToByteBufEncoder<K, V>) codec;
                ByteBuf temporaryBuffer = target.alloc().buffer(toByteBufEncoder.estimateSize(val) + 6);

                try {
                    toByteBufEncoder.encodeValue(val, temporaryBuffer);
                    ByteBufferArgument.writeByteBuf(target, temporaryBuffer);
                } finally {
                    temporaryBuffer.release();
                }

                return;
            }
```
The solution will be replacing above with something like:

```java
          if (codec instanceof ToByteBufEncoder) {
             ToByteBufEncoder<K, V> toByteBufEncoder = (ToByteBufEncoder<K, V>) codec;
              // Below lines are basically what ByteBufferArgument.writeByteBuf does
              target.writeByte('$');
              IntegerArgument.writeInteger(target, toByteBufEncoder.estimateSize(val));
              target.writeBytes(CRLF);
              toByteBufEncoder.encodeValue(val, target);
              target.writeBytes(CRLF); 
              return;
            }
```

Now this has a caveat because of which I'm creating this issue, It assumes estimatedSize is not **"estimated" but "exact"**.  

Maybe we can give user the control by adding another method in ToByteBufEncoder which can tell us if the codec can predict exact sizes.  
In ByteArrayCodec we always can.

This ensures no additional allocs and essentially makes it garbage free.
Happy to contribute and impl the solution.

#### Describe alternatives you've considered

- Use a threadlocal on heap bytebuf as the temporary buffer, since we know that its lifecycle is method scoped (resizing as needed and discarding bytes occasionaly if it encodes a very large key)
- Somehow encode keys/vals in "batches" so as to allocate and copy to target once. Seems tricky to do 

#### Teachability, Documentation, Adoption, Migration Strategy

NA

**Comment by shikharid** [comment]
Also noticed this:
![Screenshot 2024-01-24 at 11 04 42 PM](https://github.com/lettuce-io/lettuce-core/assets/10097451/46f5837c-6d0a-4a6d-8ccd-4728d590c8db)

i.e.
A good chunk of memory allocs done in the lettuce threads were from creating `RedisStateMachine.State` objects.
Since its a very simple class annd its entire usage is inside this RedisStateMachine class, why not go along the lines of what Netty does with such hot objects, _cache them in a pool_. 
Can use netty's ObjectPool (used extensively across Netty).

Seems pretty simple:
- Take from the pool whenever doing new State()
- Reset its state and release the objects when its no longer needed ( `reset() and remove()`)

If somehow we miss releasing to the netty `ObjectPool` (reset not called before `RedisStateMachine` object was garbage collected), it won't be a memory leak as the pool itself keeps no reference (see `io.netty.util.Recycler`)

**Comment by shikharid** [comment]
Have done a crudish untested version of the changes needed, if project owners agree then will add a more formal version in separate PRs

1. [Zero copy encode/decode of key/values](https://github.com/shikharid/lettuce-core/commit/5a16e1d950e0963c1cec2a4bd104047d284bfbaa)
2. [RedisStateMachine.State object pool](https://github.com/shikharid/lettuce-core/commit/e39fd1a84e2c77f839378502f06ed5eb8c24abc4)

**Comment by shikharid** [comment]
Thanks, the preallocated Stack makes good sense.
Will write some jmh benchmarks and changes and share a PR soon.
Should I combine the changes in 1 PR or create two separate ones?

**Comment by mp911de** [comment]
Let's go with a single pull request that has two commits for easier reviewing.

**Comment by shikharid** [comment]
Just curious though, where does the number 32 comes from, like why won't we ever need more than that? 
Couldn't figure out based on commit msgs and skimming through RedisStateMachine

**Comment by mp911de** [comment]
32 is an estimate of Redis' response depth (array-in-array-in-object-…). Most commands key/value commands have single-depth while some extended Stream commands (such as XPENDING) have a nesting level of 6. I think that even 16 should be fine, but 32 brings us more on the safe side.

**Comment by shikharid** [comment]
Got it, Thanks.

**Comment by shikharid** [comment]
Hey, I have been caught up in some work last 2 weeks. Will do it this week and send a PR around the end.

**Comment by shikharid** [comment]
@mp911de added changes and benchmarks https://github.com/lettuce-io/lettuce-core/pull/2768

Good gains as per benchmarks, have a look

**Comment by mp911de** [comment]
Thanks a lot, this was a decent improvement.

**Comment by shikharid** [comment]
Thanks, any chance of a release soon which includes these?

**Comment by mp911de** [comment]
6.3.2.RELEASE is scheduled for March 15
