### ISSUE TITLE
keys command returning inconsistent results during master node failover with node filter

### ISSUE THREAD

**Issue by ashok-shukla** [lettuce-io/lettuce-core#2611]
Lettuce: 6.2.3.RELEASE
Redis: 6.2.6

## Bug Report
I have added ClusterClientOptions.getNodeFilter() when trying to create connection to redis cluster

ClusterClientOptions.builder().nodeFilter(redisNode ->
                        ! (redisNode.is(RedisClusterNode.NodeFlag.FAIL)
                        || redisNode.is(RedisClusterNode.NodeFlag.EVENTUAL_FAIL)
                        || redisNode.is(RedisClusterNode.NodeFlag.NOADDR))

Apart from this, i enabled enableAllAdaptiveRefreshTriggers, dynamicRefreshSources, enablePeriodicRefresh and autoReconnect options.

#### Current Behavior

This works fine for single keys.  But for keys command, it is returning inconsistent result during master node failover. 
We have 3 master nodes. During master node failover for some time, there will be 2 master nodes in RedisClusterClient and keys command executed on 2 master nodes, giving inconsistent result.  Without node filter, at least it was throwing exception, till failed master nodes removed from RedisClusterClient and we retried the exception to overcome this issue.

#### Expected behavior/code

with nodefilter, at least cross-slot commands should check all master up and then run the commands.

**Comment by mp911de** [comment]
If a slot isn't served, then you should see a `PartitionSelectorException` as Lettuce cannot find a node to send the command to. That's the single-key command part.

For `KEYS`, Lettuce attempts to scan all known master nodes. If there is one node missing, then the `KEYS` command isn't ran on the missing node. That is the consequence of not including nodes.

**Comment by ashok-shukla** [comment]
I did not see PartitionSelectorException for keys command, through i see PartitionSelectorException for get command, if node is not available.

I moved to scan command instead of keys, as that worked for me.
