### ISSUE TITLE
Establishing Redis client connections through a specified network interface

### ISSUE THREAD

**Issue by KarthikSubbarao** [lettuce-io/lettuce-core#2619]
#### Is your feature request related to a problem? 

Our application requires us to send traffic / establish a connection to a Redis cluster through a custom network interface (Not the default network interface enforced by the host).

#### Describe the solution you'd like

We can expose a helper function to specify the network interface (e.g. `eth1`) and update the logic in `initializeChannelAsync0` in `AbstractRedisClient.java` to have the Bootstrap object to connect to the remote address using the specified network interface 

```
public ChannelFuture connect(java.net.SocketAddress remoteAddress,
                             java.net.SocketAddress localAddress)
Connect a Channel to the remote peer.
```

See: https://netty.io/4.0/api/io/netty/bootstrap/Bootstrap.html#connect-java.net.SocketAddress-java.net.SocketAddress-

https://github.com/lettuce-io/lettuce-core/blob/761d60247159662ce1db8bc20318bc4b573bc010/src/main/java/io/lettuce/core/AbstractRedisClient.java#L430

**Comment by mp911de** [comment]
You should be able to achieve this by implementing and configuring a `NettyCustomizer`, specifically:

```java
ClientResources resources = ClientResources.builder().nettyCustomizer(new NettyCustomizer() {

    @Override
    public void afterBootstrapInitialized(Bootstrap bootstrap) {
        bootstrap.localAddress(new InetSocketAddress(…));
    }
}).build();
```
