### ISSUE TITLE
RedisScriptingCommands (Lua by Java)

### ISSUE THREAD

**Issue by SameerTi** [lettuce-io/lettuce-core#2787]
Hi,

I have a Quick query, I need to following 2 Redis calls into one lua script and call that as an Atomic operation using Lettuce RedisScriptingCommands.html (via methods like scriptLoad and eval).

Could you please help me with sample code?

•	Zrangebyscore	(It fetches some records)
•	Zrem		       (removes those records)
	
Regards,

**Comment by mp911de** [comment]
This issue tracker is to handle bug reports and enhancements. Check out community resources at https://redis.io/community/ for guidance on Lua.
