### ISSUE TITLE
EVAL & EVALSHA write scripts fail on AWS ElastiCache

### ISSUE THREAD

**Issue by jesfrk7** [lettuce-io/lettuce-core#483]
lettuce versions 4.3.1.Final, 4.3.0.Final

While working with a single AWS ElastiCache Redis cluster (1 master + 1 replica), I developed a Lua script for updating several structures. I was able to determine that a feature was added to lettuce in PR #366; which causes EVAL and EVALSHA commands to be ran against the configured replica instead of against the master.

I was able to work around this by setting ReadFrom on a connection dedicated to writing to "MASTER"; but it would be nice to not need a dedicated connection for this.

I see two possible approaching to this:

* Create evalRead,evalWrite variants on the command APIs
or 
* Have a user supplied configuration which specifies if eval/evalsha calls should be targeted as readOnly or not.

**Comment by mp911de** [comment]
To make things more clear: You're writing data with `EVAL`/`EVALSHA` and your requests are dispatched to a slave.

Before #366, all Lua commands were considered write (non-readonly) and users had no workaround to dispatch commands to a slave. Right now, there are various workarounds:

1. Using a dedicated connection
2. Using `ReadFrom.MASTER`
3. Using custom commands with a custom `ProtocolKeyword` that is not considered `READONLY`

```java
    String script = "…";
    String[] keys = {};

    String response = redis.dispatch(MyCommands.EVAL, 
            new KeyOutput<>(StringCodec.UTF8),
            new CommandArgs<>(StringCodec.UTF8).add(script)
            .add(keys.length).addKeys(keys));

    public enum MyCommands implements ProtocolKeyword {
        EVAL, EVALSHA;

        private final byte name[];

        MyCommands() {
            // cache the bytes for the command name. Reduces memory and cpu pressure when using commands.
            name = name().getBytes();
        }

        @Override
        public byte[] getBytes() {
            return name;
        }
    }
```

I see two possibilities right now:

1. Do nothing in the driver and use one of the mentioned ways to direct commands to the master
2. Introduce `MasterSlaveClientOptions` and some sort of `ReadOnlyCommandsConfiguration` (extend also `ClusterClientOptions` for consistency reasons)

There might be even a third possibility, inspecting commands in the `ReadFrom` API during node selection to route some Lua executions to slaves and some to master nodes, depending on the particular, user-provided `ReadFrom` implementation. This approach has the most flexibility but conflicts with caching. Nodes are cached (at least for Redis Cluster) on a slot basis and this approach would require another caching key.

I'd keep this ticket open to collect additional feedback over time. Introducing any kind of API to configure the behavior introduces additional complexity and I'm not convinced right now of the benefit.

**Comment by mp911de** [comment]
This doesn't seem to be an issue for the majority of users hence closing this ticket. We can revisit this one once we need to come back to it.
