### ISSUE TITLE
Send custom commands to redis

### ISSUE THREAD

**Issue by srijiths** [lettuce-io/lettuce-core#495]
Hi All,

I am experimenting with ReJson module. I installed it in my redis. Now , i want to use ReJson commands in lettuce client. Is it possible ? They have provided a python program to do so. How to replicate this in lettuce ?

```
import redis
import json

data = {
    'foo': 'bar'
}

r = redis.StrictRedis()
r.execute_command('JSON.SET', 'doc', '.', json.dumps(data))
reply = json.loads(r.execute_command('JSON.GET', 'doc'))
```
Any pointers would be great.

Thank You

**Comment by mp911de** [comment]
Lettuce supports custom commands via `dispatch(…)`, see [Custom commands](https://github.com/lettuce-io/lettuce-core/wiki/Custom-commands%2C-outputs-and-command-mechanics) in the wiki. Lettuce is likely to not support specific modules but expose an API so you're able to send the commands you need.

**Comment by srijiths** [comment]
@mp911de Thank You.

**Comment by srijiths** [comment]
@mp911de I tried with Custom commands to replicate above python code. But one issue is with in MyCommands Enum i cant put dot in a command like JSON.SET. That is what actually required by ReJson Module.

```
RedisClusterClient redisClient = RedisClusterClient.create("redis://password@localhost:7379");
		StatefulRedisClusterConnection<String, String> connection = redisClient.connect();
		RedisCodec<String, String> codec = StringCodec.UTF8;
		RedisAdvancedClusterCommands<String, String> sync = connection.sync();
		String response = sync.dispatch(MyCommands.JSONSET, new StatusOutput<String, String>(codec),
				new CommandArgs<String, String>(codec).addKey("doc").add(".")
						.addValue("{\"id\":\"1\",\"name\":\"x\"}"));
```

```
	public enum MyCommands implements ProtocolKeyword {
		JSONSET;
		private final byte name[];
		MyCommands() {
			name = name().getBytes();
		}
		public byte[] getBytes() {
			return name;
		}
	}
```
If there any workarounds ? Or Am i in right direction ?

Thank You.

**Comment by mp911de** [comment]
`ProtocolKeyword` is an interface that defines `bytes[] getBytes()` and `String name()`. Using `enum` is the most natural fit to ensure singleton instances but you're not limited to use the enum name or enum at all. You're free to implement an own class. Have you tried the following:

```java
public enum MyCommands implements ProtocolKeyword
{
	JSONSET("JSON.SET");

	private final byte[] name;

	MyCommands(String commandName) {
		name = commandName.getBytes();
	}

	public byte[] getBytes() {
		return name;
	}
}
```

**Comment by srijiths** [comment]
@mp911de I will try this. Thank You

**Comment by KiranSuvarna** [comment]
@srijiths I'm also experimenting on the reJSON using lettuce client. Is your custom commands working? Or do you have any other workarounds?
