### ISSUE TITLE
Introduce NettyCustomizer API

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#499]
Introduce `NettyCustomizer` to customize the netty bootstrap:

* Callback after `Bootstrap` is configured and before connecting
* Callback for channel initialization after executing `initChannel(Channel)`

Should be configured with `ClientResources`.

**Comment by mp911de** [comment]
@jongyeol do you want to give it a try whether `NettyCustomizer` is sufficient to customize the channel to your requirements?

**Comment by jongyeol** [comment]
Oh, thank you very much. 👍 
I checked some codes, and I have a question. As you know, order of handlers is important for inserting custom hander into pipeline.

https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/com/lambdaworks/redis/ConnectionBuilder.java#L78-L82

I wanna insert my handler to the position between `CommandEncoder` and `commandHandler`.

```
@Override
public void afterChannelInitialized(Channel channel) {
    channel.pipeline().addBefore(<here>, "my_custom_handler", new MyCustomHandler());
}
```

So, I want to use `CommandHandler`'s name to `<here>`, but it don't have handler name. And, I couldn't find `addBefore(<type>, ...)` or `addAfter(<type>, ...)` in Netty's `ChannelPipeline` class.

Do you have ideas? or, could you add names for existing handlers in Lettuce?

**Comment by mp911de** [comment]
You have two options:

1. `ChannelPipeline` is `Iterable<Entry<String, ChannelHandler>>` so you can iterate through existing pipeline items and identify the `ChannelHandler` you're trying to find
2. Netty generates default names for the handlers using `StringUtil.simpleClassName(handlerType) + "#0"`. The only named `ChannelHandler` is the initializer using `channelActivator` as name.

**Comment by jongyeol** [comment]
1. I can iterate it, but I cannot insert something under iteration. Isn't it?
2. It might be helpful, but it's not an explicit way. I mean that it depends on Netty's hidden codes.

**Comment by jongyeol** [comment]
I worried option2 because it's little implicit way. But, using both option1 and option2 is works well. Thank you. 😄 

https://gist.github.com/jongyeol/35ae23fee87e0426fef5faf5c417cc44#file-lettuce-disconnectedwritetimeoutexceptionandreconnecttest-java-L11-L21
