### ISSUE TITLE
.reactive() + pool + closing connections

### ISSUE THREAD

**Issue by fvigotti** [lettuce-io/lettuce-core#501]
Hi,
I'm trying to figure out the best way to use lettuce ( version: '5.0.0.Beta1' ) reactive in my application, at first 

I've read (ALMOST) everywhere that single connection is better for most use-cases, 
then : 
 - all example prefer to use shared (single) connection
 - there are a lot of examples in docs  that take a connection from the pool without releasing/closing it.. ( this is     misleading for entry users.. and will cause a lot of pain)
,  in my opinion shared connection are source of many wtf moments .. because maybe you think that you are not going to use transactions in redis.. until you discover that "blget" and other such blocking operations ARE transactions! so sharing connection you will trigger anticipated timeouts all around ( when connection gets shared while is waiting )  causing unexpected behaviour.

plus: I've tried for 2 days to get reactive-connector + connections pool to work, the problem is that connections must be closed, and you get the reactive only after the command,  so you have to remember to add doOnTerminate, with the .close/release operation so everything you because .reactive() doesn't close them and doesn't have a method to close the connection after the execution ( anyway reactive doesn't allow multiple commands in the stream but I could be wrong I'm pretty new in lettuce and projectreactor  ) so a way to tell the client to close ( or return to the pool ) the connection after the connection has become a reactive-stream due to the execution would be fine.

I don't want to share the pool around dependencies, and my alternative to share only a reactive-autoclosing connections is this : 

I leave  my final solution for further testing to who is interested and a request for a better alternative : 
```java

    protected Mono<RedisReactiveCommands<String, String>> getMonoReactiveConnectionWithDebug(LinkedBlockingQueue<String> debug) {

        Callable<StatefulRedisConnection<String, String>> create = () -> {
            StatefulRedisConnection<String, String> connection = redisClusterPool.borrowObject();
            debug.add("borrow");
            log.info("borrowed connection {} ", connection);
            return connection;
        };

        java.util.function.Consumer<StatefulRedisConnection<String, String>> dispose = c -> {
            debug.add("dispose");
            log.info("closing connection {} ", c);
            redisClusterPool.returnObject(c);
        };

        Function<StatefulRedisConnection<String, String>, Mono<? extends RedisReactiveCommands<String, String>>> buildStream =
                conn ->
                        Mono.just(conn.reactive())
                                .doAfterTerminate((v,e)->debug.add("TERMINATE"));

        Mono<RedisReactiveCommands<String, String>> autoclosing = Mono.using(create, buildStream, dispose, DISPOSE_EAGER_FALSE);
        return autoclosing;
    }

```

this is the test 
```java

    @Test
    public void test_behaviour_monoConnector() throws InterruptedException {
        final String TEST_NOT_EXISTENT_KEY = "KEY_NOT_EXIST" + Math.random();
        final CountDownLatch latch = new CountDownLatch(1);
        final LinkedBlockingQueue<String> debug = new LinkedBlockingQueue();

        redisClusterReactiveDatasource.getMonoReactiveConnectionWithDebug(debug)
                .flatMap(f -> {
                    Mono<String> monoRedis = f.get(TEST_NOT_EXISTENT_KEY)
                            .map(v -> {
                                debug.add("map");
                                return v;
                            })
                            .doOnNext(e -> {
                                debug.add("next");
                            })
                            .doOnSuccess((v)-> debug.add("success"))
                            .doFinally(signal -> {
                                debug.add("finally");
                            })
                            .doOnError(e -> {
                                debug.add("error");
                            });
                    if(monoRedis==null){ // javadoc say that MONO<V> of .get return null ??? don't believe that..
                        debug.add("null-redis");
                    }
                    return monoRedis;
                })
                .publishOn(reactor.core.scheduler.Schedulers.elastic())
                .doOnError(e -> {debug.add("external-error");})
                .doFinally(signal -> {debug.add("external-finally");})
                .doOnError(e -> {debug.add("external-error");})
                .subscribeOn(reactor.core.scheduler.Schedulers.elastic())

                .doAfterTerminate(()->latch.countDown())
        .subscribe(v -> debug.add(v));
        ;

        latch.await(300,TimeUnit.MILLISECONDS);
        Thread.sleep(100);
        assertThat(debug).containsExactly("borrow", "TERMINATE", "dispose", "success", "finally", "external-finally"); // success but not so obvious to predict.. at least for me ;)
    }
```

**Comment by mp911de** [comment]
Any reason why you closed this ticket?

You're totally right that connection pooling with reactive use requires rethinking resource usage. For now, if you require multiple connections, the best approach might be to bind connections to worker instances. If that's not possible, `doOnTerminate(() -> …release connection…)` is the way to release connections. 

A connection is not aware whether you obtained it via connection pooling nor it's scope of use (i.e. the bounds of your unit of work). It might be worth to mention this behavior in the docs.

**Comment by fvigotti** [comment]
Hi,
I've closed the ticket because I think that it's not very good written , I've wrote it quite hurry with "the work" but anyway I just wanted report some points that can be improved in documentation :)

also leaving a ticket (even if closed) in github with some code may help someone else with similar problems searching for a solution or a point of view :) 

thank you for your reply even with the closed ticket :)
