### ISSUE TITLE
PooledClusterConnectionProvider::getReadConnection Fails On Any Failed Node Connection Attempt

### ISSUE THREAD

**Issue by eliotw** [lettuce-io/lettuce-core#503]
Lettuce Version: 4.2.2

Currently in the PooledClusterConnectionProvider::getReadConnection method, a single failed node will prevent any connection from being returned. The getReadFromConnection() method, which is called from getReadConnection(), attempts to get a connection for all the nodes in the candidate list. If a single getConnection() call results in a RedisException, the exception is thrown all the way up the stack preventing the command from dispatching. 

The suggested solution is a change in behavior in PooledClusterConnectionProvider::getReadConnection to handle cluster degradation. 
> A slight change to exception behavior (from "fail on any failed connect" to "fail on all connection attempts failed") should do the job.

Another possible enhancement that would prevent the need to check for a functional connection to a failed node would be to exclude it from the candidate list. PooledClusterConnectionProvider::isReadCandidate has access to the node's connected state. This could return false if the node is not connected.

Test case:

1. Setup a cluster where a single master with three (two would probably also work) slaves. 
2. Establish StatefulRedisClusterConnection with a ReadFrom.SLAVE_PREFERRED setting
3. Send a command to the above master, see it succeed
4. Kill a single slave for the master
5. Send a command to the above master, an RedisConnectionException will be thrown

See https://groups.google.com/forum/#!topic/lettuce-redis-client-users/IcaGziyHpU4 for more details.

**Comment by eliotw** [comment]
@mp911de I took a stab at a possible solution for this issue and wanted to see what you thought: https://gist.github.com/eliotw/2efe0888a73cbeaba82d93038f011903

**Comment by mp911de** [comment]
@eliotw thanks a lot for looking into this issue. I pushed earlier today a bigger change to propagate async connection state through `PooledClusterConnectionProvider`. `readerCandidates` is an array of `CompletableFuture` right now. You're heading in the right direction and it makes sense to deal with unavailable nodes in a graceful way.

I think it makes sense to await the terminal connection state (synchronize all futures with `CompletableFuture.allOf(…)`, like it's now), obtain the healthy connections and cache these in `readerCandidates`.

**Comment by mp911de** [comment]
I pushed a change for the issue. Care to give it a try with `4.4.0-SNAPSHOT`?

```xml
<dependency>
  <groupId>biz.paluch.redis</groupId>
  <artifactId>lettuce</artifactId>
  <version>4.4.0-SNAPSHOT</version>
</dependency>

<repositories>
  <repository>
    <id>sonatype-nexus-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by eliotw** [comment]
@mp911de Looks good, thanks!
