### ISSUE TITLE
CommandHandler performs expensive queue check if requestQueueSize != Integer.MAX_VALUE

### ISSUE THREAD

**Issue by CodingFabian** [lettuce-io/lettuce-core#507]
The second most expensive hot spot in our application is a check lettuce performs in CommandHandler when requestQueueSize has been configured:

![screen shot 2017-04-12 at 13 08 43](https://cloud.githubusercontent.com/assets/176132/24954834/3fc39ce0-1f81-11e7-8710-0a1566eec264.png)

This happens in:
https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/com/lambdaworks/redis/protocol/CommandHandler.java#L288

```
        if (clientOptions.getRequestQueueSize() != Integer.MAX_VALUE
                && commandBuffer.size() + queue.size() >= clientOptions.getRequestQueueSize()) {
            throw new RedisException("Request queue size exceeded: " + clientOptions.getRequestQueueSize()
                    + ". Commands are not accepted until the queue size drops.");
        }
```

The JavaDoc for the queue, which in this case is java.util.concurrent.ConcurrentLinkedDeque says:
```
     * <p>Beware that, unlike in most collections, this method is
     * <em>NOT</em> a constant-time operation. Because of the
     * asynchronous nature of these deques, determining the current
     * number of elements requires traversing them all to count them.
     * Additionally, it is possible for the size to change during
     * execution of this method, in which case the returned result
     * will be inaccurate. Thus, this method is typically not very
     * useful in concurrent applications.
```

Options to fix this could be to manually count command enqueue and dequeue

**Comment by mp911de** [comment]
Good catch. I pushed a changed version to https://github.com/lettuce-io/lettuce-core/tree/issue/507-expensive-size.

Do you want to give it a try?

```xml
<dependency>
  <groupId>biz.paluch.redis</groupId>
  <artifactId>lettuce</artifactId>
  <version>4.4.0-SNAPSHOT</version>
</dependency>

<repositories>
  <repository>
    <id>sonatype-nexus-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by CodingFabian** [comment]
@mp911de the environment where I observed this (with like 1million pending commands) does not permit "trying". others are not really affected that much, but from a code review perspective i think the change should do the trick. thanks for taking care.

**Comment by mp911de** [comment]
That's fixed now.

**Comment by CodingFabian** [comment]
much appreciated
