### ISSUE TITLE
Lettuce is not throwing any exception when the redis server is down 

### ISSUE THREAD

**Issue by greyseal** [lettuce-io/lettuce-core#508]
Hi
I am using lettuce version biz.paluch.redis:lettuce:4.3.1.Final with redis sentinel configured. The way I am connecting is as:

```java
StatefulRedisMasterSlaveConnection<String, String> connection = 
MasterSlave.connect(redisClient, new Utf8StringCodec(),RedisURI.create("redissentinel://"+redisPassword+"@"+uri+"/0#mymaster"));

connection.setReadFrom(ReadFrom.MASTER);
connection.setTimeout(5, TimeUnit.SECONDS);
RedisAsyncCommands<String, String> redis = connection.async();
//Also tried setting timeout as **redis.setTimeout(5, TimeUnit.SECONDS)** but this also did not work.
```

Issue:
Not able to get any exception or connection time out when redis is down.

Steps to repro:

1. Start your application and make sure its up and running fine.
2. Then stop all the redis servers.
3.  Fire a query to get data from redis.

Result: No exception/timeout is thrown and the call got hung.
Expected: There should be a timeout or exception.

**Comment by mp911de** [comment]
Lettuce is working as designed by default. I/O interruptions are buffered by default and commands are replayed after reconnect. Adjust the behavior with [`ClientOptions`](https://github.com/lettuce-io/lettuce-core/wiki/Client-options), `disconnectedBehavior` in particular.

**Comment by greyseal** [comment]
Thanks. It worked.
