### ISSUE TITLE
Lots of memory occupied by firstInteger in CommandArgs

### ISSUE THREAD

**Issue by CodingFabian** [lettuce-io/lettuce-core#511]
<img width="1228" alt="screen shot 2017-04-14 at 13 45 25" src="https://cloud.githubusercontent.com/assets/176132/25042486/b7c280a6-2118-11e7-9658-0b88c6f67fd6.png">

I am analyzing the memory used in one of our bigger services. This dump has 2.5 million pending redis commands. half of those are hmset, which look like this:
<img width="900" alt="screen shot 2017-04-14 at 13 48 58" src="https://cloud.githubusercontent.com/assets/176132/25042540/261934fa-2119-11e7-95c6-b8008b9b88db.png">

the other half are expire commands which look like this:
<img width="891" alt="screen shot 2017-04-14 at 13 49 43" src="https://cloud.githubusercontent.com/assets/176132/25042550/3e714010-2119-11e7-9196-7c21569bfb0a.png">

from the code it looks like first integer is only remembered to be used again in case of a select command:
```
        if (local.getType().name().equals(SELECT.name())) {
            local = attachOnComplete(local, status -> {
                if ("OK".equals(status) && cmd.getArgs().getFirstInteger() != null) {
                    this.db = cmd.getArgs().getFirstInteger().intValue();
                }
            });
        }
```

would it be possible to read singularArguments.get(0) instead (making IntegerArgument.val visible)

this would free a significant amount of memory, and save some cpu for computation and gc for us.

potentially the same change can be done for firstString as well

**Comment by mp911de** [comment]
Thanks for finding that stuff. I think it makes sense to reconsider the first int/first string optimizations and the fields of `Command`. The only place where it might hurt a bit is Redis Cluster where we want to avoid serializing the first key multiple times.

**Comment by mp911de** [comment]
I found a couple other places to improve the memory footprint of lettuce usage.

**Comment by CodingFabian** [comment]
wow, great improvements @mp911de - thanks very much, this will help our gc pressure more than I thought :)

**Comment by mp911de** [comment]
I think there's even more possible. Currently, queues are linked lists that allocate/remove nodes on each change. Using `ArrayDeque` or something similar could prevent creating garbage in the first place as each command is queued/dequeued. Currently, `ConcurrentLinkedDeque` has the lowest latency for the price of GC and requires no external synchronization. With Lettuce 5, we might switch to `ArrayDeque` as the primary queue as all queue writes can happen inside the `EventLoop` thread.

**Comment by CodingFabian** [comment]
I will run a profiling with 4.4 and will let you know. the system in question is busy with 15k redis commands written per second. depending on redis performance it can back up significantly. reducing memory will help us for the queue, but also avoid lots of unnecessary gc.
