### ISSUE TITLE
LatencyStats leaves PauseDetectorListener registered

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#517]
`LatencyStats` registers with `PauseDetector` and adds it as `PauseDetectorListener` each time `LatencyStats` is built. `LatencyStats` removal (in `DefaultCommandLatencyCollector.shutdown()` and `DefaultCommandLatencyCollector.retrieveMetrics()` does not unregister `LatencyStats` from `PauseDetector` and leaves a pile of active objects in the heap. See Gitter discussion https://gitter.im/lettuce-io/Lobby?at=58fb958308c00c092aa6b739:

> NersesAM  19:40
good evening everyone. I have been using lettuce for quite some time now. The version we use is shaded 4.3.0.Final
Recently we changed the GC from CMS to G1 and we ran into a very strange problem.
> about 500 MB of heap is filled with stats objects.
> NersesAM 20:58
looking at the code it seems the cause is that org.LatencyUtils.LatencyStats.PauseTracker is a weakreference, and because a switch to g1 there aren't any Full GCs happening these objects keep piling up.
> NersesAM 21:19
but i still struggle to find where are all these objects created
> Mark Paluch 22:04
NersesAM Can you figure out where the objects are rooted, which objects have references on the ArrayList?

**Comment by qsLI** [comment]
> A similar case， seems LatencyUtils's bug.
> 
> [LatencyUtils/LatencyUtils#19](https://github.com/LatencyUtils/LatencyUtils/issues/19)

same case as https://mail.openjdk.org/pipermail/hotspot-gc-use/2017-March/002639.html  @mp911de
