### ISSUE TITLE
Possible Netty Version Conflict with Minecraft

### ISSUE THREAD

**Issue by willies952002** [lettuce-io/lettuce-core#521]
Stacktrace: https://gist.github.com/willies952002/82a4287c543b64a1c2812caffdddb172

Lettuce Versions Tested:
* 4.4.0-SNAPSHOT
* 5.0.0-SNAPSHOT

Environment:
* Java: 1.8.0_121 (64-bit)
* OS: Ubuntu 15.10 (64-bit)
* Redis: v=3.2.8 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=2e73af5ad294cbb2

How to reproduce:
1. Create a [Bukkit/Spigot](https://www.spigotmc.org/wiki/spigot/)/[Paper](https://paper.emc.gs) Plugin that uses lettuce to connect to a Redis server (Pub/Sub)
2. Upload plugin to, and (re)start, the server.

Thoughs: Since both Minecraft and Lettuce use netty, but probably entirely different versions, I have a feeling that this is caused by a netty version conflict.

**Comment by mp911de** [comment]
I wasn't able to find the source code of `paperdragon-1.11.2.jar:git-PaperDragon-"8d4dfd99"` to check the bundled netty version. 

Lettuce 4 and 5 are compatible with netty 4.0 and 4.1 whereas netty 4.0 must be greater or equal to version 4.0.35 (see https://github.com/lettuce-io/lettuce-core/wiki/Dependency-Compatibility-Matrix). 

You can give it a try with Lettuce 4.2.x.

**Comment by mp911de** [comment]
One more thing: You can swap to `Utf8StringCodec` instead of using `StringCodec` as `Utf8StringCodec` is implemented in a more compatible way.

**Comment by willies952002** [comment]
As the creator and maintainer of PaperDragon (which is one point on a long fork tree of the Minecraft Server), I can be sure that the bundled netty version is 4.0.23.Final

Btw, I gave 4.2.0-SNAPSHOT a try and it did work.

Also... how would I go about swapping the codecs? (preferably w/o recompiling lettuce)

**Comment by mp911de** [comment]
The parameter-less `connect()`/`connectPubSub()` methods default to `StringCodec`. You specify the codec in the connect method by invoking `connect(…)` with a codec instance:

```java
StatefulRedisPubSubConnection<String, String> connection = client. connectPubSub(new Utf8StringCodec());
```

**Comment by willies952002** [comment]
Okay, now 4.4.0-SNAPSHOT is working with that change, but 5.0.0-SNAPSHOT still has the same issue.
Gonna stick with 4.4.0-SNAPSHOT as it will work for what I'm trying to do.

Thank you for your help =)
