### ISSUE TITLE
Logger went crazy - unwanted debug messages

### ISSUE THREAD

**Issue by RedEpicness** [lettuce-io/lettuce-core#541]
Hello!

I have recently started getting a lot of DEBUG messagase from lettuce on my minecraft console. I have a library to send messages over redis pub/sub using lettuce. 

I have updated lettuce to version 5.0.0.M2 on the maven repository, and have shaded the netty libraries into a package of my own, reason being i work on an outdated minecraft server who's internal netty version is severely outdated.

After updating the debug message spam persists. I have no clue what I could have done wrong, it just started spamming out of nowhere. The server also doesn't work but i have been unable to debug with this amount of messages, so i'm stuck basically...

Paste of the entire log (semi-large):

https://pastebin.com/bL3LiJG8

Have a nice day,
Red_Epicness

**Comment by mp911de** [comment]
You might want to change your log levels. Please note that logger names changed from version 4.x to 5.x. In 4.x it the logger prefix is `biz.paluch.redis`, in 5.0 it's `io.lettuce.core`.

Closing this ticket as Lettuce works as designed.

**Comment by RedEpicness** [comment]
MY bad as marking it as an issue, I agree it is intended behaviour, but how do I change the log levels? If you could help me with that, as I could not find a solution myself. Thanks for the quick reply though.

**Comment by mp911de** [comment]
It depends on the log framework you use (and whether the environment takes control of log config aspects). Usually, you have a config file (log4j, log4j2, logback, java util logging) that specifies loggers. There are also tools (like Spring Boot, JBoss AS/WildFly) that wrap the logging subsystems and configuration is tool-specific. 

That said, there's no single answer to how to change log levels. Maybe you're better off asking that question within your Minecraft community.

**Comment by RedEpicness** [comment]
Found a workaround, thanks for the info!
