### ISSUE TITLE
Lettuce doesn't call QUIT when a pooled connection is destroyed.

### ISSUE THREAD

**Issue by robbiemc** [lettuce-io/lettuce-core#545]
As of lettuce 4.3.2.Final, when connections from a pool (e.g. `ConnectionPoolSupport.createGenericObjectPool`) are closed, `QUIT` doesn't seem to be called on them. 

Since redis doesn't automatically close idle connections by default, this results in the redis server slowly accumulating connections until it can't accept anymore. Setting a timeout in redis.conf should fix the issue, but it still seems like calling `QUIT` from `ConnectionPoolSupport.RedisPooledObjectFactory#destroyObject` would also be a good idea in case people aren't overriding the timeout.

**Comment by mp911de** [comment]
Lettuce never calls `QUIT` if a connection is closed. You're right that pooled connections are not closed if the connection is destroyed (pool shrink) which is a bug. `RedisPooledObjectFactory#destroyObject` is not overridden whereas it should be with a call to `Connection.close()`.
