### ISSUE TITLE
Rare NPE at StatefulRedisConnectionImpl.java:187

### ISSUE THREAD

**Issue by nikolayspb** [lettuce-io/lettuce-core#566]
Hello,

I use Lettuce 4.2.2

and several times I have seen NPE when invoking

`com.lambdaworks.redis.api.async.RedisStringAsyncCommands#setex`

```
Caused by: java.lang.NullPointerException: null
	at com.lambdaworks.redis.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:187)
	at com.lambdaworks.redis.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:1805)
	at com.lambdaworks.redis.AbstractRedisAsyncCommands.setex(AbstractRedisAsyncCommands.java:845)
```

But it happens under load in production. At speed of 20-40 requests per second to Redis.

Looks like concurrency issue. Could you easily spot any?

I would like to test with 4.3.3 version, but can not do it easily, because my other library depends on Netty 4.0.

**Comment by mp911de** [comment]
First, Lettuce 4.3.3 is compatible with both netty lines, 4.0 and 4.1.

It looks like you're using transactions on a single connection that is shared across multiple threads. Lettuce connections are thread-safe in general but transactions impose a state on the connection. Please assign each thread, that is executing transactional work a dedicated connection. If that's not possible, you might want to use pooling. Threads/code paths that don't do any transactional work may still share a single connection.

**Comment by nikolayspb** [comment]
In this code path I am not using transactions. I have deployed with Lettuce 4.3.3 and Netty 4.0.49 and seems to work well. I don't observe the same issue yet.

**Comment by mp911de** [comment]
The NPE is caused by a field access when the connection is in a transactional state hence the hint towards transactional use.

**Comment by nikolayspb** [comment]
I don't really use tx for that specific connection. My setup is like this. I have a single com.lambdaworks.redis.RedisClient (maybe it is the problem). And then I create connections

1. com.lambdaworks.redis.RedisClient#connect(com.lambdaworks.redis.codec.RedisCodec<K,V>)
2. com.lambdaworks.redis.RedisClient#connectPubSub()
3. com.lambdaworks.redis.RedisClient#connect()

First one for CRUD, second to listen expirations and third for Tx (single thread).
I experience that NPE at 1st CRUD connection, which I use in async mode RedisAsyncCommands<K,V>

something like this.
`return crudCommands.get(key)
                .toCompletableFuture()
                .thenApplyAsync(Optional::ofNullable, nettyHandlerExecutor);
    }`

But it is really rare. I have two nodes in prod and just single NPE at one of them since I deployed 21 hour ago.

**Comment by mp911de** [comment]
On a different note: `Optional::ofNullable` isn't a blocking operation hence you don't require `thenApplyAsync` (from a Lettuce perspective). This call makes only sense if the callback is blocking or you want to switch threads.

A single `RedisClient` is fine to create multiple connections. The client encapsulates mostly settings and thread pools.

If you don't interact with `StatefulRedisConnectionImpl.multi` directly (via reflection or similar), then your issue sounds like a multi-threading/visibility issue. The code block in Lettuce is [guarded against null](https://github.com/lettuce-io/lettuce-core/blob/b655300af1d6ebc8e56dfc657dcecee82882787e/src/main/java/com/lambdaworks/redis/StatefulRedisConnectionImpl.java#L187) so there's nothing to do for Lettuce to solve the ticket.

**Comment by nikolayspb** [comment]
1. Yes, I know ofNullable is not blocking. Just I change a thread here and then callbacks to CF which are added later are invoked in a custom thread, not in event loop thread.

2. Okay

3. Yes, that's my point. That it looks like  multi-threading/visibility issue in Lettuce StatefulRedisConnectionImpl. Looks like there a race condition here.
