### ISSUE TITLE
Optimization for ValueListOutput

### ISSUE THREAD

**Issue by CodingFabian** [lettuce-io/lettuce-core#573]
There are many cases where a ValueListOutput is used when the amount of returned values is known

like com.lambdaworks.redis.RedisCommandBuilder.zrange(K, long, long) will have stop-start and
com.lambdaworks.redis.RedisCommandBuilder.hmget(K, K...) will have keys.length

For that we could add a second constructor that takes an additional capacity argument for the array list. backwards compatible would be to use "10" as capacity.

what do you think?

**Comment by mp911de** [comment]
I think there's some potential to improve. Redis array responses contain the size in their header. When using streaming, outputs don't really require an eager initialization with `ArrayList` because the result is streamed to a `Subscriber` interface instead of the list.

It would make sense to distinguish and have a late initialization that either initializes `ArrayList` with the response size as soon as we receive the response or, for streaming, do not create `ArrayList` instances at all.

**Comment by CodingFabian** [comment]
Good idea, the latter is what I did for our use case already as soon as I discovered it. I really like the layered API of lettuce, so I can easily choose convenience or maximum control and performance.

**Comment by mp911de** [comment]
Together with a few other optimizations (Returning `Collections.emptyList()` if array response is empty) we end up with the following benchmark:

## 4.4

```
Benchmark                                                     Mode  Cnt    Score    Error  Units
ValueListOutputBenchmark.measure100Elements                   avgt   40  444,795 ± 11,781  ns/op
ValueListOutputBenchmark.measure100ElementsWithResizeElement  avgt   40  568,426 ± 11,864  ns/op
ValueListOutputBenchmark.measure16Elements                    avgt   40   66,082 ±  1,858  ns/op
ValueListOutputBenchmark.measure16ElementsWithResizeElement   avgt   40  131,118 ±  2,453  ns/op
ValueListOutputBenchmark.measureSingleElement                 avgt   40   12,097 ±  0,482  ns/op
ValueListOutputBenchmark.measureZeroElement                   avgt   40    0,278 ±  0,005  ns/op
```

## 4.3

```
Benchmark                                                     Mode  Cnt    Score    Error  Units
ValueListOutputBenchmark.measure100Elements                   avgt   40  641,254 ± 58,630  ns/op
ValueListOutputBenchmark.measure100ElementsWithResizeElement  avgt   40  661,805 ± 51,144  ns/op
ValueListOutputBenchmark.measure16Elements                    avgt   40  144,651 ± 24,637  ns/op
ValueListOutputBenchmark.measure16ElementsWithResizeElement   avgt   40  144,673 ± 36,781  ns/op
ValueListOutputBenchmark.measureSingleElement                 avgt   40   13,783 ±  2,029  ns/op
ValueListOutputBenchmark.measureZeroElement                   avgt   40    6,893 ±  1,297  ns/op

```

**Comment by mp911de** [comment]
Done.

**Comment by CodingFabian** [comment]
Quite a nice speedup :-)
