### ISSUE TITLE
Can't fetch RC1

### ISSUE THREAD

**Issue by jflebeau** [lettuce-io/lettuce-core#578]
Trying to test RC1, but gradle doesn't seem to be able to fetch it from Maven Central. 

Using `compile group: 'io.lettuce', name: 'lettuce-core', version: '5.0.0.RC1'`

**Comment by mp911de** [comment]
The binaries are available on Maven Central: https://repo1.maven.org/maven2/io/lettuce/lettuce-core/5.0.0.RC1/

Maybe you also need to declare Spring Milestones as repo (https://repo.spring.io/libs-milestone) to get Project Reactor 3.1.0 RC3.
