### ISSUE TITLE
Adaptive Topology Refresh and Node connections (Question)

### ISSUE THREAD

**Issue by jchurch33** [lettuce-io/lettuce-core#592]
I'm trying to understand how Adaptive Topology Refresh is supposed to work. In my fiddling with the client, when I use a global connection to a Redis Cluster, it never has any issue with following MOVED redirections, regardless of whether I enable adaptive refresh or not.

However, when I am using a connection to a specific node, it NEVER follows moved errors _regardless_ of whether I enable adaptive refresh.

Am I misunderstanding the intended usage of these options?

**Comment by mp911de** [comment]
A cluster connection routes requests to cluster nodes based on the first found key whereas node-specific connections are plain connections without any routing. 

Lettuce has two refresh modes: Scheduled and adaptive. Scheduled topology refreshes are based on timeouts. If the topology changes in between, then Lettuce would only update its topology view on the next run but not in between. That's exactly where adaptive refresh comes into play: If Lettuce runs into a persistent disconnect, `MOVED` or `ASK` redirection, then it triggers immediately a topology refresh.

Adaptive refresh is based on Redis operations replies, it adapts Redis replies as you operate. The [wiki](https://github.com/lettuce-io/lettuce-core/wiki/Redis-Cluster#refreshing-the-cluster-topology-view) contains a more detailed explanation how topology refreshes work.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by jchurch33** [comment]
You may
