### ISSUE TITLE
Add support for Redis streams

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#606]
See https://github.com/redis/redis-rcp/blob/master/RCP11.md

**Comment by mp911de** [comment]
Code lives on https://github.com/lettuce-io/lettuce-core/tree/streams

**Comment by aschober** [comment]
@mp911de is the plan to move streams support forward to the 5.0.x branch?

**Comment by mp911de** [comment]
Hey Allen, 
Redis Streams integration is going to happen for Lettuce 4.5 and 5.1. 5.0.x is a maintenance branch, bugfixes only.

**Comment by aschober** [comment]
@mp911de thanks for the info.

Not sure if this is helpful, but I was looking for the new reactive api + streams, so cherry-picked from `streams` to current `5.x` branch.

https://github.com/aschober/lettuce-core/tree/streams-5.x

**Comment by mp911de** [comment]
Awesome! Love to get early feedback, especially about the Java API design.

**Comment by mp911de** [comment]
Early artifacts with Redis Streams support are available:

```xml
<dependency>
  <groupId>biz.paluch.redis</groupId>
  <artifactId>lettuce</artifactId>
  <version>4.5.0.RedisStreams-SNAPSHOT</version>
</dependency>

<repositories>
  <repository>
    <id>sonatype-nexus-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

Currently missing: `XCLAIM`, `XDEL`, some `XGROUP` commands. `XGROUP DELGROUP` and `XGROUP SETID`  are not yet implemented in Redis.

Group and consumer names are `String` right now. I've got the impression they should be encoded according the selected `RedisCodec`.

**Comment by mp911de** [comment]
Added `XCLAIM`, `XDEL`, and `XTRIM` commands with fd16032532efba995ed9bc119263163f5582f148.

**Comment by mp911de** [comment]
Redis Stream support is now in place for Lettuce versions 4.5 and 5.1. Closing this ticket.

**Comment by rainhacker** [comment]
@mp911de  Thanks for adding Redis stream support in lettuce. Is there a documentation for this ?  I can't find an official lettuce one. Tried looking for tests as examples too, but couldn't find. 
Only link I found was this : https://www.javacodegeeks.com/2018/05/a-first-look-at-redis-streams-and-how-to-use-them-with-java.html
Not clear from the link how I can use of for master slave connection.

**Comment by mp911de** [comment]
@rainhacker There is Javadoc in the `StreamCommands` classes. Redis Streams are available for Redis Standalone, Master/Replica, and Redis Cluster.
