### ISSUE TITLE
Basic usage, example 1 in wiki is different to readme example.

### ISSUE THREAD

**Issue by boughtonp** [lettuce-io/lettuce-core#611]
The example 1 in the wiki doesn't work with Lettuce 4.4.1 Final shaded (connection doesn't have a get method).
https://github.com/lettuce-io/lettuce-core/wiki/Basic-usage

The example from the readme shows an extra step of calling `sync` method before issuing the Redis command, which does work:
https://github.com/lettuce-io/lettuce-core#basic-usage

Presumably the wiki page is referring to how it worked in a previous version.

**Comment by mp911de** [comment]
Good catch, thank you. The mentioned code reflected the usage pattern for Lettuce 3. That's fixed now.
