### ISSUE TITLE
Use channel thread to enqueue commands

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#617]
Using the channel thread to write the command makes a lot of sense because we could probably get rid of some synchronization code and subsequent channel I/O does not require further context switching. It would also unblock writes because we don't require synchronization to perform the actual channel write.

**Comment by nikolayspb** [comment]
Too me it is more a bug. I want invoke Lettuce CompletableFuture API and not to worry of caller thread being locked or catch an exception.

Is thrown in caller thread even though CompleteableFuture  API is used.

```
com.lambdaworks.redis.RedisException: Request queue size exceeded: 500. Commands are not accepted until the queue size drops.
```

**Comment by mp911de** [comment]
Any validation happens beforehand to fail fast. It does not make sense to accept a command and reject it later if the validation can happen early.

**Comment by nikolayspb** [comment]
Yes, fail-fast is good, but it should be wrapped in RedisFuture, then I handle it in CompletableFuture.

**Comment by nikolayspb** [comment]
Otherwise I have to handle exceptions in CompletableFuture and in caller thread.

**Comment by mp911de** [comment]
There's a point in handling failures inside the callbacks. Thanks a lot for your feedback.

I'd argue that you nevertheless need to handle errors in your call chain anyway – exceptions can happen due to other reasons before the actual command was constructed and dispatched (e.g. argument validation, infrastructure failures).

**Comment by nikolayspb** [comment]
As API user I would never prefer to get exceptions in caller thread.

All other exceptions could be caught or wrapped by the API implementation and return as CompletableFuture.

**Comment by mp911de** [comment]
We refactored how exception signals are propagated into RedisCommand objects if a command is not eligible for being written to Redis. Previously, we relied on `throws`. As of Lettuce 6, we're propagating the failure via `completeExceptionally(…)` so the calls to async/reactive API's no longer need to care about handling exceptions with a separate approach.
