### ISSUE TITLE
Introduce dedicated exceptions for NOSCRIPT and BUSY responses

### ISSUE THREAD

**Issue by DaichiUeura** [lettuce-io/lettuce-core#620]
(This is a same issue/request of Jedis' https://github.com/xetorthio/jedis/issues/1352.)

In order to handle NOSCRIPT response against EVALSHA, an exception message needs to be compared with "NOSCRIPT" string like below.

```
    try {
      client.evalsha(...);
    } catch (RedisException e) {
      if (!e.getMessage().startsWith("NOSCRIPT")) {
        // (Error handling...)
      }
      // No script in the script cache. Try with EVAL.
    }
```

If we have a specialized exception like RedisNoScriptException for "NOSCRIPT" response, the code above can be simplified:

```
    try {
      client.evalsha(...);
    } catch (RedisNoScriptException e) {
      // No script in the script cache. Try with EVAL.
    } catch (RedisException e) {
      // (Error handling...)
    }
```

It would be great if we could have such exception.

**Comment by mp911de** [comment]
Thanks for your suggestion. Makes sense to simplify exception handling.

**Comment by nikolayspb** [comment]
+1

**Comment by mp911de** [comment]
New exceptions:

* `RedisBusyException` (extending `RedisCommandExecutionException`) for `BUSY` errors
* `RedisNoScriptException` (extending `RedisCommandExecutionException`) for `NOSCRIPT ` errors

**Comment by mp911de** [comment]
That's done now for 4.5 and 5.0.
