### ISSUE TITLE
BITPOS should allow to just specify start.

### ISSUE THREAD

**Issue by christophstrobl** [lettuce-io/lettuce-core#623]
Both `start` and `end` are optional, still it should be possible to use `BITPOS` with `start` only.
> it is possible to just pass start, the operation will assume that the end is the last byte of the string

```bash
redis> SET mykey "\x00\xff\xf0"
"OK"
redis> BITPOS mykey 1 0
(integer) 8
redis> BITPOS mykey 1 2
(integer) 16
```

**Comment by mp911de** [comment]
That's fixed now.
