### ISSUE TITLE
[Question] Netty 4.0.x support

### ISSUE THREAD

**Issue by tkroman** [lettuce-io/lettuce-core#626]
Hi!
Is netty-4.0.x-compatible jar of 5.0.0-RELEASE published? I see that there is a `netty-40` profile in pom.xml, but at the same time #518 states otherwise. Should the pom (also, Travis config etc) be updated? Since Java 9 compatibility requires netty 4.1, that's probably a dead end anyway. But due to the fact that shading is no longer an option, it's pretty constraining :(

**Comment by mp911de** [comment]
Don't expect netty 4.0 support for Lettuce 5.

The profile you're seeing originates in code from the `master` branch which contains the 4.5.x development line. Code on the 5.x branches do not have a netty 4.0 profile anymore. 

It's correct that we dropped netty 4.0 support with Lettuce 5.0 to get remove our compatibility code and drop netty 4.0 constraints.
