### ISSUE TITLE
Enquiry:: Set Codec in Spring-Data-Redis

### ISSUE THREAD

**Issue by sudhanshu-gupta** [lettuce-io/lettuce-core#633]
I am using spring-data-redis -> LettuceConnectionFactory for connection. I have gone through the lettuce doc, and it says that it supports codec integration [here](https://github.com/lettuce-io/lettuce-core/wiki/Codecs)
I couldn't found similar integration for LettuceConnectionFactory. 
Is there a way to add CompressionCodec in LettuceConnectionFactory?

**Comment by mp911de** [comment]
It's possible to use custom codecs in front of a binary codec but that's a tough exercise with Spring Data. Please post your question on StackOverflow because this repo isn't really the right place for this topic.
