### ISSUE TITLE
API changes report for Lettuce

### ISSUE THREAD

**Issue by lvc** [lettuce-io/lettuce-core#639]
Hi,

I'd like to share report on API changes and backward compatibility for the Lettuce library: https://abi-laboratory.pro/java/tracker/timeline/lettuce/

BC — binary compatibility
SC — source compatibility

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/japi-tracker tool.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![lettuce-1](https://user-images.githubusercontent.com/1517837/32402686-e99b29bc-c13a-11e7-9f7d-85915f4b3b21.png)

![lettuce-2](https://user-images.githubusercontent.com/1517837/32402685-e97c051e-c13a-11e7-895d-fcb75cd5d1b3.png)

**Comment by mp911de** [comment]
Thanks a lot. A lot of changes are reported on internal API because there is no definition over public and internal API. Some API is required to be public because of visibility constraints across packages. Any plans to support architecture definitions in the future?

**Comment by lvc** [comment]
Hi,

The tool can filter analyzed packages and classes by a list or regexp. Does https://lettuce.io/lettuce-4/release/api/ lists only public packages and classes?

By the way,

Added report for snapshot version from https://oss.sonatype.org/content/repositories/snapshots/biz/paluch/redis/lettuce/:

![lettuce-3](https://user-images.githubusercontent.com/1517837/32767216-733eaa3c-c923-11e7-91ed-97a9ba460644.png)

Thank you.

**Comment by mp911de** [comment]
Nothing to do here now.
