### ISSUE TITLE
Debug logging of ConnectionWatchdog has wrong prefix after reconnect.

### ISSUE THREAD

**Issue by mlex** [lettuce-io/lettuce-core#645]
All ConnectionWatchdog debug logs are prefixed with a channel descriptor. This prefix is stored in the `logPrefix` field.

After a reconnect, the `logPrefix` is not updated, which leads to rather confusing log messages, because the channel descriptor in the log message does not represent the actually active channel. 

For example in the following log message the current channel is actually `/10.255.101.203:41124 
 -> /10.255.94.48:6381` while the log prefix shows `/10.255.101.203:33545 -> /10.255.94.48:6381`:

```
2017-11-09 10:12:40,958 [lettuce-nioEventLoop-5-15] DEBUG c.l.r.protocol.ConnectionWatchdog - [channel=0xeb2bc9b7, /10.255.101.203:33545 -> /10.255.94.48:6381, last known addr=/10.255.94.48:6381] channelInactive(ChannelHandlerContext(ConnectionWatchdog#0, [id: 0x8982a021, L:/10.255.101.203:41124 ! R:/10.255.94.48:6381]))
```

We found this bug in version 3.4.2.Final, but it is probably still relevant for latest SNAPSHOT.

**Comment by mp911de** [comment]
Thanks for the bug report. Please note that Lettuce 3.x isn't maintained anymore. Please upgrade to Lettuce 4 or 5.

**Comment by mlex** [comment]
Sorry, I meant 4.4.0.Final. My fault.

**Comment by mp911de** [comment]
That's fixed now.
