### ISSUE TITLE
Misleading wasRolledBack method

### ISSUE THREAD

**Issue by graineri** [lettuce-io/lettuce-core#662]
This only applies to Lettuce 5.x.

Taking a look at `TransactionResult` interface I noticed there is a `wasRolledBack` method which I find somewhat misleading since there is no such thing in Redis. 

I finally realized the intent of this method once I read `TransactionCommandTest`: it actually means that the transaction was discarded (this behavior is explained [here](https://redis.io/topics/transactions#a-hrefcommandswatchwatcha-explained)).

**Comment by mp911de** [comment]
Agree. Was rolled back would make up a much better name. I’d add a delegation and deprecate the current method.

Am 7. Dez. 2017, 13:03 -0800 schrieb Gabriel Raineri <notifications@github.com>:

**Comment by mp911de** [comment]
That's fixed now.
