### ISSUE TITLE
ConcurrentModificationException when connecting a RedisClusterClient

### ISSUE THREAD

**Issue by blahblahasdf** [lettuce-io/lettuce-core#663]
Hello, I'm using 4.2.0.Final and I've run across the following exception infrequently, but in bursts.  

```
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:857)
	at java.util.AbstractCollection.containsAll(AbstractCollection.java:317)
	at com.lambdaworks.redis.cluster.RoundRobinSocketAddressSupplier.get(RoundRobinSocketAddressSupplier.java:48)
	at com.lambdaworks.redis.cluster.RedisClusterClient.lambda$getSocketAddressSupplier$400(RedisClusterClient.java:805)
	at com.lambdaworks.redis.ConnectionBuilder.socketAddress(ConnectionBuilder.java:96)
	at com.lambdaworks.redis.AbstractRedisClient.initializeChannel(AbstractRedisClient.java:215)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectStateful0(RedisClusterClient.java:675)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectStateful(RedisClusterClient.java:639)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectClusterImpl(RedisClusterClient.java:519)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connect(RedisClusterClient.java:331)
```

The code in `RoundRobinSocketAddressSupplier` is not threadsafe if `partitions` is mutated externally.  This can happen during a topology refresh.

**Comment by mp911de** [comment]
Thanks a lot for reporting the issue. That's fixed now. Care to give `4.4.3-SNAPSHOT` a spin?

**Comment by blahblahasdf** [comment]
I don't believe the change will fix the bug.  The `ConcurrentModificationException` is being thrown because the `Partitions` collection is being modified not the `clusterNodes` collection (from the code in 4.4.2-final).  

This change will have the same behavior via the `RoundRobinSocketAddressSupplier.get()` -> `RoundRobin.isConsistent(Collection<? extends V> master)` because the same thread unsafe `Partitions` instance "`master`" is being passed through.

You may be able to fix this by making the `List` backing `Partitions` be a `CopyOnWriteArrayList` instead of a plain `ArrayList`.  However, I am not sure what the performance implications of such a change would be.

**Comment by blahblahasdf** [comment]
I looked a little closer and a change to `Partitions` is needed in addition to this change not instead of it.  In the original code on 4.4.2-Final either the `clusterNodes` or the `partitions` collections could throw a `ConcurrentModificationException`.

**Comment by mp911de** [comment]
Thanks a lot for having a look. `Partitions` is backed by two collections: `partitions` and `nodeReadView`. `partitions` is a mutable collection, all access to `partitions` is guarded with `synchronized`. `Partitions` implements `Collection<RedisClusterNode>` intending to expose a thread-safe read view, `nodeReadView` is immutable and used for that purpose. [Updating the `Partitions` object](https://github.com/lettuce-io/lettuce-core/blob/5027d602c24735916f1dcd11be0e0e3b44e5da47/src/main/java/com/lambdaworks/redis/cluster/models/partitions/Partitions.java#L90-L112) creates a new instance of `nodeReadView` that is kept immutable once created.

I'm currently trying to understand what's missing/whether something is still missing. I'd refrain from using `CopyOnWriteArrayList` in places that regularly modify collections as `CopyOnWriteArrayList` creates quite some garbage and locks.

**Comment by blahblahasdf** [comment]
I see now.  

I'm looking at the sources for 4.4.2-Final and there is no `nodeReadView` on `Partitions` on this version. Looking at current source for `Partitions` I agree with your assessment.  Using the `nodeReadView` looks threadsafe for iteration and will remove any chance for `ConcurrentModificationException` when iterating `master` (in the new fix to `RoundRobin`).  

The new changes will remove any chance for `ConcurrentModificationException` of the `this.collection` and it's always operating on a copy so I think it should be good.  

I will update to 4.4.3-Final.  Thanks for the fast response and sorry for the run around on the `Partitions` fix already being present.

**Comment by mp911de** [comment]
Thanks for your feedback. I find it valuable to not oversee things.
