### ISSUE TITLE
Hope this redis client can support the open source project tile38

### ISSUE THREAD

**Issue by icewukong** [lettuce-io/lettuce-core#674]
Tile38 is a memory based spatial data service, similar to redis. It supports the resp protocol and has a rich spatial query command, but some commands are not redis's built-in commands.

Can lettuce support these commands?
http://tile38.com/

**Comment by mp911de** [comment]
In short: No – Lettuce is a Redis client. 

I took an attempt with [spinach](https://github.com/mp911de/spinach) to support disque based on Lettuce which helped Lettuce to become more easy to extend. I don't have the knowledge nor the time to build dedicated Tile38 support. You can start building a client on top of Lettuce yourself as it's built quite modular with a couple of extension points.
