### ISSUE TITLE
reactive version of expire() command doesn't work in 5.0.1.RELEASE

### ISSUE THREAD

**Issue by mmostov** [lettuce-io/lettuce-core#686]
In the test code below, LettuceRedisClient is a thin wrapper around io.lettuce.core.RedisClient, which is connected to a RedisLabs cluster. 
With the following test, I can observe that async version of expire() call behaves as expected, however reactive version doesn't (regardless of the delay, before expiration is checked).

```
@Test
 @Parameters(method = "redisConnection")
 public void testReactiveZadd(String host, int port) throws Exception {
     final LettuceRedisClient client = new LettuceRedisClient(host, port, 1000L);
     UUID consumerId = UUID.randomUUID();
     String itemKey = "";
     byte[] key = LettuceRedisClient.buildShardedKey(consumerId, itemKey);
     byte[] member = "somevalue".getBytes(UTF_8);
     double sortValue = 1.0;
     long ttlMs = 1000;

     Mono<Long> mono = client.reactiveZadd(key, sortValue, member, ttlMs, TimeUnit.MILLISECONDS, t -> t.printStackTrace());

     mono.block(Duration.ofMillis(1000)); //wait for completion

     List<byte[]> zrangeResult = client.zrange(consumerId, itemKey, 0, 2)
                                       .get(10, TimeUnit.SECONDS); //supposed to return values in [1,2] range
     assertEquals(1, zrangeResult.size());
     assertArrayEquals(member, zrangeResult.get(0));

     //test that after expiration interval, value disappears
     Thread.currentThread().sleep(ttlMs*2);
     zrangeResult = client.zrange(consumerId, itemKey, 0, 2)
                                       .get(10, TimeUnit.SECONDS); //supposed to return values in [1,2] range
     assertEquals(0, zrangeResult.size());
}
```

Call to reactiveZAdd() executes the following code:
```
asyncCommands = connection.async();
reactiveCommands = connection.reactive();



......

public Mono<Long> reactiveZadd(@NonNull byte[] key, double sortValue, @NonNull byte[] item, long ttl, @NonNull TimeUnit ttlTimeUnit, Consumer<Throwable> errorCallback) {
    return reactiveCommands.zadd(key, sortValue, item)
                           .doOnError(t -> errorCallback.accept(t))
                           .doOnSuccess((v) -> {
                               //reactiveCommands.expire(key, TimeUnit.SECONDS.convert(ttl, ttlTimeUnit));
                               //BUG: reactive version of expire doesn't work
                               //fallback to async version of expire
                               asyncCommands.expire(key, TimeUnit.SECONDS.convert(ttl, ttlTimeUnit));
                           }).doOnError(t -> errorCallback.accept(t));
}
```

Make sure that:

- [ x] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/master/.github/CONTRIBUTING.md).
- [ x] You specify the lettuce version and environment so it's obvious which version is affected
- [x ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
I think I might be missing something. You're calling `expire(…)` within `doOnSuccess(Consumer)` and you're observing that expiry is not set.

Using a reactive API does not execute the command upon calling a method that returns a `Publisher` type but rather creates a handle. The actual execution (materialization) happens upon subscription (`.subscribe(…)`, `.block()`). The call within `doOnSuccess(…)` creates an `EXPIRE` command publisher but does not subscribe to it. 

Moving the call to `.then(…)` should lead to the desired execution.

**Comment by mmostov** [comment]
Please see u/test code, it calls block().  The issue is not that expire() doesn't execute, it does, the problem is that expire doesn't have expected effect - key is not expired (in reactive version, which is commented out in provided sample).

**Comment by mp911de** [comment]
Calling `.block()` executes only the `. zadd(…)` publisher with its callbacks, however there happens no subscription to the `.expire(…)` publisher. You can easily test that with calling `.zadd(…).block()` first, and then `.expire(…).block()`.

Please note that you shouldn't call `.block(…)`. There's [`StepVerifier`](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/test/java/org/springframework/vault/authentication/ReactiveLifecycleAwareSessionManagerUnitTests.java#L110) to properly test publishers.

**Comment by mmostov** [comment]
Thank you very much, now I understand my mistake!

-Michael
