### ISSUE TITLE
Considering support ssl enabled ElastiCache Master/Slave Cluster

### ISSUE THREAD

**Issue by wintersliu** [lettuce-io/lettuce-core#688]
Hi,

I have a ElastiCache Master/Slave Cluster (redis version 3.2.6) with SSL enabled. 
I want to switch from Redisson to Lettuce.
I know Redisson is able to establish a connection.
I am wondering if lettuce can support this static master/slave usecase.

**Comment by mp911de** [comment]
Thanks for your ticket. That issue is already in progress with #684, therefore, I'm closing this ticket here.
