### ISSUE TITLE
Balancing Load among Read Slaves

### ISSUE THREAD

**Issue by wintersliu** [lettuce-io/lettuce-core#692]
Hi, I am using ElastiCache with 1 master and 2 slaves and ReadFrom.SLAVE_PREFERRED enabled.
By looking at the monitor graph of get type commands count from CloudWatch, I see majority of the requests were directed to one slave.

**Comment by mp911de** [comment]
This is addressed via #676. Lettuce prefers the first host with the lowest latency (optimized for locality) and isn't optimized to max out utilization. Latency is measured from the client perspective which might be different amongst multiple clients/hosts.

#676 provides options to influence the behavior. You might have a better utilization of your infrastructure but that doesn't mean that your application performance improves unless you're blocking Redis/keep it busy for a significant amount of time.

**Comment by wintersliu** [comment]
Thanks, Mark. I will try that option.
