### ISSUE TITLE
Add ReadFrom.SLAVES_ROUND_ROBIN and ReadFrom.MASTER_SLAVES_ROUND_ROBIN

### ISSUE THREAD

**Issue by rainmaker7** [lettuce-io/lettuce-core#713]
Hi,
Since replication can be used for scalability using multiple slaves for read-only queries (https://redis.io/topics/replication)

I'd like to split read requests evenly (in round robin fashion) among Redis nodes. Don't see a way to pass a custom ReadFrom strategy. What are your thoughts on providing:
- ReadFrom.SLAVES_ROUND_ROBIN: Send requests in round robin fashion to all replicas
- ReadFrom.MASTER_SLAVES_ROUND_ROBIN: Send requests in round robin fashion to all Redis nodes (master + replicas)

**Comment by mp911de** [comment]
Round-Robin, in general, is an approach to distribute load. To implement round-robin, it requires holding state and know which host was selected/accessed. As of now, Redis Cluster caches the selected set of nodes on a per-slot basis until the next refresh. This is, to not select nodes all over assuming `ReadFrom` returns always the same result for a given set of input nodes.

Master/Slave does not (yet) cache the selected node set resulting from `ReadFrom`. 

`StatefulRedisMasterSlaveConnection` and `StatefulRedisClusterConnection` expose `setReadFrom(…)` methods in which you can pass custom `ReadFrom` implementations.

**Comment by rainmaker7** [comment]
Thanks. 
If I understand correctly, due to caching of nodes ReadFrom strategy does not get invoked per request for Redis Cluster (and possibly in future for Master/Slave). So even if I write a custom ReadFrom round robin strategy for Master/Slave setup, it may stop working in future. Also, it can't be used in case I want to use clustering in future.

The closest alternate I could find was in redisson which provides LoadBalancer (RoundRobin, Random etc)
https://github.com/redisson/redisson/wiki/2.-Configuration

Any recommendations on how I can solve this using lettuce ?

**Comment by mp911de** [comment]
Revisiting this topic again it could make sense to introduce a mechanism to decide whether `ReadFrom` has a deterministic behavior (as seen from an outside perspective) or whether `ReadFrom` can return different results on a per-call basis. This could result in a `isCacheable()` flag that tells the caller whether it should cache the node selection.

**Comment by SMT15** [comment]
It would be really helpful if there is a mechanism to evenly spread the load among replicas in Redis shards. For example, with `ReadFrom.SLAVE_PREFERRED ` we have the following CPU load (single core) in a particular shard:
1) master: 33%
2) slave-1: 85%
3) slave-2: 17%
4) slave-3: 25%
5) slave-4: 54%
6) slave-5: 30%
Currently our application access Redis cluster from 150 nodes.

**Comment by mp911de** [comment]
Thanks a lot for the numbers. They show a tendency towards a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution).

<img width="524" alt="screenshot 2018-03-14 10 31 24" src="https://user-images.githubusercontent.com/1035015/37393976-f4de8c58-2772-11e8-8906-546ae316737b.png">

Randomization won't really help. Achieving distribution that results in even (or at least similar) load requires coordination and metrics to coordinate reads. Your application servers are most likely distributed so they do not coordinate about which slave to read from. 

That said, you might want to implement your own `ReadFrom` strategy with server pinning for certain application server instances (i.e. 20% of application servers prefer slave 1, the next 20% prefer slave 2 and so on). This gives you the most control over preference without sacrificing performance or availability.
