### ISSUE TITLE
RuntimeExceptions thrown by implementations of RedisCodec are not handled well for TransactionCommands

### ISSUE THREAD

**Issue by blahblahasdf** [lettuce-io/lettuce-core#719]
Redis version: `biz.paluch.redis:lettuce:4.4.3.Final`

The handling of uncaught exceptions thrown by implementations of `RedisCodec` is awkward for `TransactionalCommand`s.  Instead of getting a `RedisException` immediately, as I would get for a non transactional command, the exception is swallowed and ultimately my command times out.  It would be much cleaner for the exception to manifest immediately instead of leaving the transaction in a pending state.  

This scenario can be seen through the following code paths.

`CommandEncoder.encode` properly handles uncaught exceptions thrown by `RedisCommand.encode` here.

```
        try {
            out.markWriterIndex();
            command.encode(out);
        } catch (RuntimeException e) {
            out.resetWriterIndex();
            command.completeExceptionally(new EncoderException(
                    "Cannot encode command. Please close the connection as the connection state may be out of sync.",
                    e));
        }
```

Here the command is killed and the `ByteBuf` is reset.  The `AsyncCommand` is killed here: 

```
    @Override
    public boolean completeExceptionally(Throwable ex) {
        boolean result = false;
        if (COUNT_UPDATER.decrementAndGet(this) == 0) {
            result = doCompleteExceptionally(ex);
        }
        return result;
    }

    private boolean doCompleteExceptionally(Throwable ex) {
        command.completeExceptionally(ex);
        return super.completeExceptionally(ex);
    }
```  

In the case of non transactional commands the `this.count` field will be at most `1` so when `decrementAndGet(this)` is called the `doCompleteExceptionally` is called and `CompletableFuture.completeExceptionally` is called which ultimately cleans up the command and propagates the exception.  However, in the case of `TransactionalCommand` the `this.count` field will be `2` and the decrement call will drop it to `1` and `doCompleteExceptionally` is never called.  This leaves the `TransactionalCommand` in a strange state where ultimately the timeout will kick in.

Here is a unit test showing the issue and what I would expect.

https://gist.github.com/blahblahasdf/5cf243baaa1f0d59ff37ebd7e8050260

**Comment by mp911de** [comment]
Good catch and thank a lot for reporting the issue. That's something we need to fix.

**Comment by mp911de** [comment]
That's fixed now.

**Comment by blahblahasdf** [comment]
Hi Mark, I finally got around to testing this and it doesn't work for my use cases.  I haven't had a chance to dig in to why the transactional command still times out (I did verify that your change does run the `doCompleteExceptionally` correctly but it still times out any way).

The unit test I attached doesn't pass either.

**Comment by mp911de** [comment]
Thanks for coming back. The issue you see here is that synchronous API usage does not await command completion (neither successful nor exceptional), see https://github.com/lettuce-io/lettuce-core/blob/c893778e64ccb5f75d4450695d0d8912f6c0efac/src/main/java/com/lambdaworks/redis/FutureSyncInvocationHandler.java#L50-L68

Therefore command, failures aren't seen by the client. Right now, I'm not sure whether adding synchronization is a good thing as this changes the performance behavior of all users that use transactions.

In any case, your codec should not raise exceptions. If you need to react to non-encodable commands, please handle this concern outside of the client.
