### ISSUE TITLE
[Question] How to eagerly initialise all the async connections while creating the client

### ISSUE THREAD

**Issue by s-aravind-flipkart** [lettuce-io/lettuce-core#727]

**Comment by s-aravind-flipkart** [comment]
It would be better if the same could be added in the documentation.

**Comment by mp911de** [comment]
Not quite sure what you mean. You connect with 

```java
RedisClient client = RedisClient.create(…);
StatefulRedisConnection<…> connection = client.connect();
```

and then you can use the connection.

**Comment by s-aravind-flipkart** [comment]
@mp911de I see first time i fire a request to Redis cluster using async connection at that moment only the connection is created as such. Is it possible to create all async connections eagerly. Today i do it in a hacky way of firing dummy requests at bootstrap.

**Comment by mp911de** [comment]
Using the NodeSelection API (connection.all().commands().ping()) should be the thing you’re looking for

Am 7. März 2018, 10:38 +0100 schrieb s-aravind-flipkart <notifications@github.com>:
