### ISSUE TITLE
How to set the log level and share connection for multiple queries

### ISSUE THREAD

**Issue by owenmao** [lettuce-io/lettuce-core#730]
Hi Developers,

Recently I am using lettuce 5.0.1 to write a restful api for query Redis, and got some questions.

Q1: how to set the log level?
there is a lot of DEBUG info print out on console. How can set the log level to ERROR or avoid this?
22:43:50.074 [pool-1-thread-63] DEBUG i.l.c.m.MasterSlaveConnectionProvider - getConnection(READ)
22:43:50.074 [pool-1-thread-63] DEBUG io.lettuce.core.RedisChannelHandler - dispatching command AsyncCommand [type=GEORADIUS, output=ValueSetOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]

Q2: how to share one connection?
When I use masterslave(one master two slaves) commands,  there is a lot of connection info like this
ReconnectionHandler Reconnected...
I hope the connection keep alive for long time and shared by multiple queries(like from different users concurrent queries ) rather than launching a new connection for each query.
My question is how to set up the connection in reusing and avoid the reconnected info?
part of code: 
    public static RedisClient redisClient = RedisClient.create();

    private ArrayList<StatefulRedisMasterSlaveConnection> tailCluster;

    public  ArrayList <StatefulRedisMasterSlaveConnection> getMasterConnectionList (){
        if (tailCluster != null){
            return this.tailCluster;
        }
        this.tailCluster = new ArrayList<>();
        redisClient.setOptions(ClientOptions.builder()
                .autoReconnect(true)
                .pingBeforeActivateConnection(true)
                .build());
        for(Iterator<Map.Entry<String, List<RedisURI>>> itor = tailNodesCluster.entrySet().iterator(); itor.hasNext();){
            Map.Entry<String, List<RedisURI>> kv = itor.next();
            StatefulRedisMasterSlaveConnection<String, String> connection =MasterSlave.connect(redisClient, new Utf8StringCodec(), kv.getValue());
            //connection.setTimeout(Duration.ofSeconds(300));
            connection.setReadFrom(ReadFrom.MASTER);
            tailCluster.add(connection);
        }
        return tailCluster;
    }

Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the lettuce version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
Log level settings depend on your environment and are not controlled/settable through Lettuce.

Creating connections upfront and keeping them throughout the application runtime is a good practice. You will see disconnects when:
* Redis closes connections because it exceeds client count
* Network partitions occur
* Network components forcibly close the connection because they don't see any traffic

For the future, please properly format your tickets. A wall of text/code isn't necessarily facilitating readability.

**Comment by owenmao** [comment]
Thanks for your reminder !
I got this by setting it up in application.properties under the resources folder. Since I use Spring Boot and it use log4j by default and use DEBUG level so it print huge info which is useless. Searched the similar issue before.
https://github.com/lettuce-io/lettuce-core/issues/541
