### ISSUE TITLE
Add AUTH option to MIGRATE command

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#733]
Migrate command supports as of 4.0.7 an AUTH option

```
 MIGRATE host port "" dbid timeout [COPY | REPLACE | AUTH password] KEYS key1
```

**Comment by vaibhaw-** [comment]
Hey
Which release (i.e. how soon) is this expected to be available? Will it be quicker if one submits a PR?

**Comment by mp911de** [comment]
This ticket has no milestone yet associated. Should be a good candidate for a first pull request as we need to extend `MigrateArgs` and a test only.

We should include this change in a patch release, see https://github.com/lettuce-io/lettuce-core/milestones for dates.

**Comment by vaibhaw-** [comment]
Thanks, I can try and take this up next week.
