### ISSUE TITLE
Question about large transactions

### ISSUE THREAD

**Issue by hookumsnivy** [lettuce-io/lettuce-core#738]
I'm using 5.0.2.RELEASE and processing **large** transactions - approximately 200k hsets. 
I'm not interacting with lettuce directly, but instead through Spring Boot 2.0.0 and Spring Redis Data 2.0.5. Both were recent upgrades and I was using jedis in the past without a problem.
I'm not familiar with Lettuce at all, so please forgive my lack of understanding if I say something wrong.

Committing the transaction takes an abnormally long time (I haven't let it finish) and only the MULTI command has been written to Redis before I kill the process. I've stepped through the code and I think I may have found the culprit:

The `addToStack` method in `CommandHandler`. Before adding the command to the stack, it is checking to see if the command is already in the stack. This operation gets more and more expensive each time a command is added as it has to iterate through the entire stack each time. 
Is this expected?
Is it necessary to make sure there aren't duplicates?

**Comment by mp911de** [comment]
This issue was addressed with #709 and the fixed version is available as snapshot build `5.0.3.BUILD-SNAPSHOT`. Care to upgrade and give the fix a try?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
