### ISSUE TITLE
AsyncPool, AsyncConnectionPoolSupport are nowhere to be found

### ISSUE THREAD

**Issue by fabienrenaud** [lettuce-io/lettuce-core#739]
[Official documentation](https://lettuce.io/core/snapshot/reference/#connection-pooling.asynchronous.usage) says there are no dependency required to implement async connection pooling with lettuce.
```java
RedisClusterClient clusterClient = RedisClusterClient.create(RedisURI.create(host, port));

AsyncPool<StatefulRedisConnection<String, String>> pool = AsyncConnectionPoolSupport.createBoundedObjectPool(
        () -> clusterClient.connectAsync(StringCodec.UTF8), BoundedPoolConfig.create());

// execute work
CompletableFuture<String> setResult = pool.acquire().thenCompose(connection -> {

    RedisAsyncCommands<String, String> async = connection.async();

    async.set("key", "value");
    return async.async.set("key2", "value2").whenComplete((s, throwable) -> pool.release(c));
});

// terminating
pool.closeAsync();

// after pool completion
client.shutdownAsync();
```

I copied that code with lettuce 4 and 5 but AsyncPool, AsyncConnectionPoolSupport, BoundedPoolConfig are nowhere to be found. The closest thing I found was `io.lettuce.core.support.ConnectionPoolSupport` but its methods are very different from the docs.

Only synchronous connection pooling has a dependency on commons-pool2 according to the docs.

Which is it?

**Comment by fabienrenaud** [comment]
I noticed that right after posting this issue yesterday so I checked the release docs too but they are identical: https://lettuce.io/core/release/reference/#connection-pooling.asynchronous.usage ...

**Comment by mp911de** [comment]
I adjusted the documentation. All Lettuce 5 builds include content from the Wiki which isn't specific to a version. The docs however mention:

> Asynchronous/Non-Blocking via a Lettuce-specific pool implementation (since version 5.1)
