### ISSUE TITLE
what should I do used share connection with lettuce5.x

### ISSUE THREAD

**Issue by IT-Glory** [lettuce-io/lettuce-core#763]
just open a conncetion like this: client.connect()
and then don't close it and sharing in different threads？

**Comment by mp911de** [comment]
Not exactly sure what you're up to. Care to elaborate what you want to achieve?

**Comment by IT-Glory** [comment]
OK, my application is concurrent and IO intensive type, and I want to use a single conncetion with lettuce5.x. Can you give an example？Thx!

**Comment by mp911de** [comment]
It's no more than [connecting](https://github.com/lettuce-io/lettuce-core/wiki/Getting-started) and holding the connection. Make sure to close the connection on application shutdown. Dependency injection helps quite a lot in such scenarios.
