### ISSUE TITLE
Timer with autoReconnect set to false - question

### ISSUE THREAD

**Issue by gszpak** [lettuce-io/lettuce-core#766]
Hi Mark,

I am using version 5.0.3.RELEASE.

Is there a way to disable `ClientResources.timer` creation when `autoReconnect` is set to false?
It seems that `timer` is only used by `ConnectionWatchdog` (so `autoReconnect==false` makes it idle), and while connecting to large number of Redises I get the following error from netty:
```
ERROR 2018-04-20 11:59:09.819 Slf4JLogger.java:error:161 : LEAK: You are creating too many HashedWheelTimer instances.  HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.
```

**Comment by mp911de** [comment]
Why don't you reuse `ClientResources` or at least the timer? The only possibility is providing your own `ClientResources` implementation.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
