### ISSUE TITLE
Add tracing support using Brave (OpenZipkin)

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#782]
We should investigate how we can integrate with OpenTracing to record spans. The integration should sit in a central place. We should provide a tracer abstraction to enable tracing on an optional basis.

**Comment by pfyod** [comment]
@mp911de Hi Mark. Why was it decided to add Zipkin specific instrumentation instead of OpenTracing (which can then be translated to Brave using https://github.com/openzipkin-contrib/brave-opentracing, if need be)?

**Comment by mp911de** [comment]
Because we work closely with Zipkin folks on other projects so it was sort of a natural choice to implement Zipkin first. Happy to add OpenTracing support. Care to submit a pull request?
