### ISSUE TITLE
Intermittent lettuce connection issue with encrypted Redis

### ISSUE THREAD

**Issue by Vishal-Nagpure** [lettuce-io/lettuce-core#786]
Hi, I am using the version 4.2.2.Final of lettuce. The Redis is set up in cluster mode on AWS with encryption enabled(in-transit and at-rest). The microservice is interacting with Redis through spring-data-redis (version 1.8.10.RELEASE) where lettuce is configured. 

  ```
final LettuceConnectionFactory lettuceConnectionFactory = new LettuceConnectionFactory(new RedisClusterConfiguration(redisClusterNodes));
        lettuceConnectionFactory.setTimeout(10000);
        lettuceConnectionFactory.setUseSsl(true);
        lettuceConnectionFactory.setVerifyPeer(false);
        lettuceConnectionFactory.setStartTls(false);
        lettuceConnectionFactory.afterPropertiesSet();
```

The service is facing below issue intermittently whenever it tries to GET/PUT data to Redis.

> org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is com.lambdaworks.redis.RedisException: com.lambdaworks.redis.RedisException: java.lang.IllegalArgumentException: Connection to myproduct-cache-0001-001.myproduct-cache.qasdb1.use1.cache.amazonaws.com:6379 not allowed. This connection point is not known in the cluster view

However, When the flag _shareNativeConnection_ of class _LettuceConnectionFactory_ is set to false, the caching works just fine.
https://docs.spring.io/spring-data/data-redis/docs/current/reference/html/#redis:connectors:lettuce

The downside of shareNativeConnection=false is that it opens and close the socket each time and does not share a single native connection.

**Comment by mp911de** [comment]
Lettuce validates the target connection point to ensure that the client does not connect to a node that is outside of the cluster. Please check what `CLUSTER NODES` reports and that you use the appropriate host names.

You can also disable this behavior by setting `ClusterClientOptions` with `validateClusterNodeMembership` set to `false`.

Please note, this is the Lettuce issue tracker, not the one of Spring Data Redis.

**Comment by Vishal-Nagpure** [comment]
Hi,

Thanks for your reply.

We have written a utility which is mimicking the actual service and has only one API which is performing GET/PUT on same Redis cluster through the same Pod over the same network.
That utility is working just fine. Hence, I believe there might not be an issue with cluster validation, otherwise, it would have come in utility as well. 

Also, when log level of lettuce(com.lambdawork.*) is set to DEBUG in actual service, it works fine too and able to GET/PUT data to Redis without cluster validation exception. Hence, suspecting an issue with any kind of timeout which we need to set. Any thoughts on this?

_I understand this is not the spring forum, but the suggested validateClusterNodeMembership of ClusterClientOptions is exposed only in spring-data-redis 2.0.0 version which requires spring 5 which has major breaking changes and a lot of efforts are involved._

Thanks,
Vishal

**Comment by mp911de** [comment]
Blocking of the node due to validation can happen if the Redis topology and the driver cache of the topology view don't match. This should be only a temporary issue in case you have enabled topology refresh.

Regarding Spring Data Redis 1.8.x, the only option is to hook into `LettuceConnectionFactory.afterPropertiesSet()` and get hold of the `client` field:

```java
public class MyLettuceConnectionFactory extends LettuceConnectionFactory {

	@Override
	public void afterPropertiesSet() {
		super.afterPropertiesSet();

		DirectFieldAccessor accessor = new DirectFieldAccessor(this);
		AbstractRedisClient client = (AbstractRedisClient) accessor.getPropertyValue("client");
		if(client instanceof RedisClusterClient){
			RedisClusterClient clusterClient = (RedisClusterClient) client;
			clusterClient.setOptions(…);
		}
	}
}
```

There won't be a backport of the client configuration API as this change involves numerous changed classes. Since the config API is using Java 8 types (`Duration`, `Optional`), it's a huge effort in backporting it.

I'm closing this ticket as there's nothing more we could do here right now.
