### ISSUE TITLE
NoClassDefFoundError: reactor/core/scheduler/Schedulers

### ISSUE THREAD

**Issue by skz363** [lettuce-io/lettuce-core#787]
Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the lettuce version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

 
Getting nested exception is java.lang.NoClassDefFoundError: reactor/core/scheduler/Schedulers 
when i added the below dependency to my pom.xml file 
<dependency>
    <groupId>biz.paluch.redis</groupId>
    <artifactId>lettuce</artifactId>
    <version>5.0.0.Beta1</version>
</dependency>
please solve this

**Comment by mp911de** [comment]
Please upgrade to Lettuce 5.0.4.RELEASE:

```xml
<dependency>
  <groupId>io.lettuce</groupId>
  <artifactId>lettuce-core</artifactId>
  <version>5.0.4.RELEASE</version>
</dependency>
```

**Comment by skz363** [comment]
Hi @mp911de can you please provide us with the java implementation to do SCAN and NEARBY query to the tile38 as we do through CLI. In the official java examples there are only get and set example.
Thanks for your help in advance :-)

**Comment by mp911de** [comment]
Sorry, I can't. I'm not familiar with Tile38 at all. Please also do not reuse already closed tickets. This makes it harder for other users to find related content. Keep in mind, you could be the next user looking for information. Thanks!
