### ISSUE TITLE
lettuce memleak problem

### ISSUE THREAD

**Issue by yanbingwei86** [lettuce-io/lettuce-core#796]
i dump the heap file and find that lettuce 3.4.3 use netty 4.0.34.Final verison.
![image](https://user-images.githubusercontent.com/10648835/41340037-fba8f9d0-6f28-11e8-81e4-036a0a04c8d1.png)
i should not use so much memory, and this versio may netty problem version, https://github.com/netty/netty/issues/5563

**Comment by mp911de** [comment]
Lettuce 3 is no longer maintained. Please upgrade the referenced netty version to a newer one or upgrade to Lettuce 5.
