### ISSUE TITLE
java.lang.ClassNotFoundException: reactor.core.scheduler.Schedulers

### ISSUE THREAD

**Issue by j-stefani** [lettuce-io/lettuce-core#801]
Getting the following exception when trying to create a RedisClient:
```
Caused by: java.lang.ClassNotFoundException: reactor.core.scheduler.Schedulers
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 174 common frames omitted

```
Using dependency:
```
<dependency>
    <groupId>io.lettuce</groupId>
    <artifactId>lettuce-core</artifactId>
    <version>5.0.4.RELEASE</version>
</dependency>
```
This brings in reactor-core 2.0.8.RELEASE which doesn't have `.scheduler.*`. If I explicitly bring in reactor-core 3.1.8.RELEASE, then I don't have the same issue. Is 3.1.8.RELEASE compatible with lettuce-core:5.0.4.RELEASE?

Thanks

**Comment by j-stefani** [comment]
This is what I get:
```
$ mvn dependency:list | grep reactor-core
[INFO]    io.projectreactor:reactor-core:jar:2.0.8.RELEASE:compile
```
I'm using Lettuce with a Spring Boot 1.4 project - perhaps there is some conflict? In any case, I guess I can override the 2.0.8 release explicitly.

**Comment by mp911de** [comment]
Hi Justin,
Spring Boot‘s dependency management overrides transient dependency versions. Boot 1.4 pulls in Reactor 2.

You should be able to either set the Version property or declare a dependency in your Pom-file
Am 15. Juni 2018, 15:52 +0200 schrieb Justin Stefani <notifications@github.com>:
