### ISSUE TITLE
lettuce does not retry after 6 attempt and hangs on further requests

### ISSUE THREAD

**Issue by bigbang4u2** [lettuce-io/lettuce-core#806]
I am creating connection like below

```
RedisClient client = RedisClient.create(this.redisUri);
final StatefulRedisConnection<String, byte[]> connection = client.connect(new StringByteCodec()); // Custom codec see below
  stringKeyBytesValueRedisASyncCommands = connection.async();

RedisFuture<byte[]> future = stringKeyBytesValueRedisASyncCommands.get("test")
byte[] value = future.get()
```

**StringByteCodec**

```
public class StringByteCodec implements RedisCodec<String, byte[]> {

	public static final ByteArrayCodec INSTANCE = new ByteArrayCodec();
	private static final byte[] EMPTY = new byte[0];
	private final Charset charset = Charset.forName("UTF-8");

	@Override
	public String decodeKey(final ByteBuffer bytes) {
		return charset.decode(bytes).toString();
	}

	@Override
	public byte[] decodeValue(final ByteBuffer bytes) {
		return getBytes(bytes);
	}

	@Override
	public ByteBuffer encodeKey(final String key) {
		return charset.encode(key);
	}

	@Override
	public ByteBuffer encodeValue(final byte[] value) {
		if (value == null) {
			return ByteBuffer.wrap(EMPTY);
		}

		return ByteBuffer.wrap(value);
	}

	private static byte[] getBytes(final ByteBuffer buffer) {
		final byte[] b = new byte[buffer.remaining()];
		buffer.get(b);
		return b;
	}

}
```
For testing my redis server config is keep-alive = 20 sec and idle-timeout is 30 sec 

If I try multiple requests continuously it works fine. But after making some requests and leaving it idle lettuce try to reconnect after every 30 sec, which is fine but it only does 6 times and after that it hangs. By hang I mean I am not able to make any requests. This is happening every time. Not sure whats going on . See trace logs here [https://gist.github.com/bigbang4u2/b33dfc392542727fc1481f08602c2069](url) Please help.

**Comment by mp911de** [comment]
The attached log (gist) does not show disconnects. Please provide a full log, otherwise there isn't anything we can do here.

**Comment by bigbang4u2** [comment]
There was no message after that, I tried this on other network and it turns out to be problem with my router which was dropping packet after every 10 mins and causing this issue. Its working me for now.

**Comment by mp911de** [comment]
Thanks a lot. Closing this one.
