### ISSUE TITLE
ReadFrom Setting on LettuceClientConfigurationBuilder

### ISSUE THREAD

**Issue by jaerith** [lettuce-io/lettuce-core#807]
I saw [a sample](https://gist.github.com/mp911de/67b63afe6873d0eb6be408a7a80fc890) mentioned from 
a few months ago, where the `LettuceClientConfigurationBuilder` could be specified to set the ReadFrom property, specifically the line:

`LettuceClientConfiguration configuration = LettuceClientConfiguration.builder().readFrom(ReadFrom.SLAVE).build();`

But it seems that the current version of `LettuceClientConfigurationBuilder` does not currently support that, based on the documentation and when I try to use it (i.e., spring.data.redis/2.0.8.RELEASE):

https://docs.spring.io/spring-data/data-redis/docs/current/api/org/springframework/data/redis/connection/lettuce/LettuceClientConfiguration.LettuceClientConfigurationBuilder.html#clientResources-io.lettuce.core.resource.ClientResources-

Do you know when it will become available?  Basically, I'm looking to have the best of both worlds, so that I can use Lettuce to have both high availability (i.e., Sentinel) and the option to read from slaves:

`LettuceClientConfiguration config = LettuceClientConfiguration.builder().readFrom(ReadFrom.SLAVE).build();
`
`redisConnectionFactory = new LettuceConnectionFactory(sentinelConfig, config);`

That should work, right?  And if the Builder is not yet ready (and will not be ready in the near future) to set the Configuration object properly, what would you recommend using in its place?

Thanks for all the hard work!

**Comment by mp911de** [comment]
This is the issue tracker for Lettuce, not Spring Data Redis. 

`ReadFrom` support for static Master/Slave and Sentinel Master/Slave setups is implemented with [DATAREDIS-580](https://jira.spring.io/browse/DATAREDIS-580)  and will be released as part of the [Lovelace](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Lovelace) release train. You can upgrade to one of the released milestones to try this functionality.

**Comment by jaerith** [comment]
Sorry about that.  I saw your name on both the Lettuce and Spring sites, and I thought that the issue was related more to Lettuce.  In any case, I appreciate the link to the information about the Lovelace release train.  Thanks again!
