### ISSUE TITLE
find many COMMAND send to cluster

### ISSUE THREAD

**Issue by r4b3rt** [lettuce-io/lettuce-core#808]
#### Current Behavior

found many COMMAND send to redis cluster,and the connection number change (not a fixed number)

#### Input Code

- Java

```java
@Bean
    public LettuceClientConfigurationBuilderCustomizer clientConfiguration() {
        return builder -> {
            final ClientResources clientResources = DefaultClientResources.builder()
                    .ioThreadPoolSize(4)
                    .computationThreadPoolSize(4)
                    .build();

            final SocketOptions socketOptions = SocketOptions.builder()
                    .keepAlive(true)
                    .tcpNoDelay(true)
                    .connectTimeout(Duration.ofSeconds(5))
                    .build();

            final ClusterTopologyRefreshOptions topologyRefreshOptions = builder()
                    .enablePeriodicRefresh()
                    .refreshPeriod(Duration.ofMinutes(10))
                    .enableAllAdaptiveRefreshTriggers()
                    .adaptiveRefreshTriggersTimeout(Duration.ofMinutes(1))
                    .build();

            final ClusterClientOptions clusterClientOptions = ClusterClientOptions.builder()
                    .socketOptions(socketOptions)
                    .topologyRefreshOptions(topologyRefreshOptions)
                    .autoReconnect(false)
                    .pingBeforeActivateConnection(true)
                    .build();

            builder.clientResources(clientResources);
            builder.clientOptions(clusterClientOptions);
        };
    }
```

#### Expected behavior/code

i check the redis cluster (3 master and 3 slave) setting
tcp-keepalive 60
timeout 300

how to hold the connection when idle in 300 seconds
shell we send PIND to redis cluster?

#### Environment
- Spring Boot version: [2.0.3.RELEASE]
- Lettuce version: [5.0.4.RELEASE]
- Redis version: [3.2.0]
- Linux version: [2.6.32-642.6.2.el6.x86_64]

**Comment by mp911de** [comment]
It's not quite clear what the actual issue is. Lettuce is configured with the code above to refresh the cluster topology every 10 minutes, this also means that each application instance opens new connections to all known cluster nodes to issue a `PING` along with other commands that are issued to initialize the connection. Lettuce closes these inspection connections once the topology refresh is finished.

**Comment by r4b3rt** [comment]
tks,i can change the topology refresh setting. btw i have 2 qustions
1. how to hold the connection with all cluster nodes when idle time more then redis timeout setting.
2. why send COMMAND to redis cluster? the COMMAND elapsed O(n)

**Comment by r4b3rt** [comment]
the debug log like this
```
RdiesStateMachine:81 [lettuce-eoiikEvebtKiio-6-4] Decode ClusterCommand [command=AsyncCommand [type=COMMAND,output=ArrayOutput [output=[restore-asking,-4 ...], empty stack: false
```

**Comment by r4b3rt** [comment]
when i setting with pool will ESTAB many connection with redis cluster(ss -ant|grep ESTAB)
but when i remove the pool setting , just one connection with redis cluster and many TIME_WAIT

**Comment by mp911de** [comment]
> 1. how to hold the connection with all cluster nodes when idle time more then redis timeout setting.

Redis disconnects clients from the server side if a connection is inactive and Lettuce attempts to reconnect. There's nothing we can do from the client side besides issuing a regular `PING` – that's something you need to do in your application.

> 2. why send COMMAND to redis cluster? the COMMAND elapsed O(n)

It's required to find out whether Redis provides `GEORADIUS_RO` and `GEORADIUSBYMEMBER_RO` command.

This is not a general discussion forum. If you have questions, please post these on StackOverflow.

Closing this ticket as the original question was answered.
