### ISSUE TITLE
FutureSyncInvocationHandler the statement "command.get ()" in the handlerInvocation method is unnecessary

### ISSUE THREAD

**Issue by zhangweidavid** [lettuce-io/lettuce-core#809]
I think the statement "command.get ()" in the handlerInvocation method is unnecessary.
It might be better to go straight back in the last statement

**Comment by mp911de** [comment]
Thanks for raising the issue. It's a bit hard to understand what you're trying to improve. It makes indeed sense to reuse and return the result of `LettuceFutures.awaitOrCancel(…)`. That style is already applied in `ClusterFutureSyncInvocationHandler`. Care to submit a pull request?
