### ISSUE TITLE
why   more  Reconnected ,then OutOfMemoryError? this is bug?

### ISSUE THREAD

**Issue by kivenhu** [lettuce-io/lettuce-core#813]
Class Name | Shallow Heap | Retained Heap
-- | -- | --
java.util.concurrent.ConcurrentLinkedDeque @ 0xc1d4bea8 | 24 | 720,675,288
disconnectedBuffer io.lettuce.core.pubsub.PubSubEndpoint @ 0xc1d4be50 | 88 | 850,699,368
endpoint, channelWriter io.lettuce.core.pubsub.StatefulRedisPubSubConnectionImpl @ 0xc1d4bd08 | 72 | 560
connectionFacade io.lettuce.core.protocol.ReconnectionHandler @ 0xc1deff58 | 56 | 2,048
reconnectionHandler io.lettuce.core.protocol.ConnectionWatchdog @ 0xc1d4b930 | 80 | 3,392
arg$1 io.lettuce.core.protocol.ConnectionWatchdog$$Lambda$766 @ 0xf4fd7560 | 24 | 24
task io.netty.util.HashedWheelTimer$HashedWheelTimeout @ 0xf4fd7578 | 56 | 80
tail, head io.netty.util.HashedWheelTimer$HashedWheelBucket @ 0xc1387a70 | 24 | 24
[355] io.netty.util.HashedWheelTimer$HashedWheelBucket[512] @ 0xc1382a60 | 2,064 | 14,328
wheel io.netty.util.HashedWheelTimer @ 0xc1382760 | 80 | 23,872
this$0 io.netty.util.HashedWheelTimer$Worker @ 0xc13827b0 | 32 | 96
<Java Local> io.netty.util.concurrent.FastThreadLocalThread @ 0xc1382810 lettuce-timer-4-1 Thread | 128 | 240
runnable io.netty.util.concurrent.FastThreadLocalRunnable @ 0xc13829e0 » | 16 | 16
Total: 2 entries |   |  
timer io.lettuce.core.protocol.ConnectionWatchdog @ 0xc1c5fff8 » | 80 | 488
timer io.lettuce.core.protocol.ConnectionWatchdog @ 0xc1e72fe8 » | 80 | 448
Total: 3 entries |   |  
pubsub org.springframework.data.redis.connection.lettuce.LettuceSubscription @ 0xc1e73ba8 » | 40 | 232
key java.util.concurrent.ConcurrentHashMap$Node @ 0xc1f112a8 » | 32 | 32

 

Class Name | Shallow Heap | Retained Heap | Percentage
-- | -- | -- | --
io.lettuce.core.pubsub.PubSubEndpoint @  0xc1d4be50 | 88 | 850,699,368 | 96.37%
java.util.concurrent.ConcurrentLinkedDeque  @ 0xc1d4bea8 | 24 | 720,675,288 | 81.64%
java.util.concurrent.ConcurrentLinkedDeque$Node @  0xf4fd81b0 | 24 | 45,041,856 | 5.10%
java.util.concurrent.ConcurrentLinkedDeque$Node @  0xf4fd7ef8 | 24 | 45,041,856 | 5.10%

 num     #instances         #bytes  class name
----------------------------------------------
   1:      25165824      603979776  io.lettuce.core.protocol.CommandArgs$KeyArgument
   2:         16968      118401096  [Ljava.lang.Object;
   3:       1579623       66149536  [B
   4:       1621274       51880768  java.util.concurrent.ConcurrentHashMap$Node
   5:           444       17204808  [Ljava.util.concurrent.ConcurrentHashMap$Node;
   6:         91706       11880832  [C
   7:         90020        2160480  java.lang.String
   8:         15203        1681752  java.lang.Class
   9:         14731        1296328  java.lang.reflect.Method
  10:         29702        1188080  java.util.LinkedHashMap$Entry

{"timeMillis":1531212189887,"thread":"lettuce-nioEventLoop-5-4","level":"INFO","loggerName":"io.lettuce.core.protocol.ReconnectionHandler","message":"Reconnected to 10.0
.200.168:6379","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":87,"threadPriority":5,"dateTime":"2018-07-10 16:43:09"}
{"timeMillis":1531212189888,"thread":"lettuce-nioEventLoop-5-3","level":"INFO","loggerName":"io.lettuce.core.protocol.ReconnectionHandler","message":"Reconnected to 10.0
.200.168:6379","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":83,"threadPriority":5,"dateTime":"2018-07-10 16:43:09"}

{"timeMillis":1531212262899,"thread":"nioEventLoopGroup-2-1","level":"WARN","loggerName":"io.netty.channel.DefaultChannelPipeline","message":"An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.","thrown":{"commonElementCount":0,"localizedMessage":"GC overhead limit exceeded","message":"GC overhead limit exceeded","name":"java.lang.OutOfMemoryError"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":21,"threadPriority":10,"dateTime":"2018-07-10 16:44:22"}

**Comment by mp911de** [comment]
Please stop dumping raw JSON and details. Instead, please describe what happens and what behavior you would expect.

**Comment by kivenhu** [comment]
ok~
In the use of redis-session, due to the abnormal redis service, the redis customer service terminal was reconnected and reconnected for more than a few hours. The service is OOM.

**Comment by mp911de** [comment]
Thanks a lot. It looks that a lot of commands were queued while the client was disconnected (that's the default behavior). The queue is unbounded by default and at some point, the whole memory is used for the queued commands. Take a look at [`ClientOptions`](https://lettuce.io/core/release/reference/#client-options), especially `disconnectedBehavior` and `requestQueueSize` parameters to limit the queue size.

**Comment by mp911de** [comment]
Seems there is nothing left to do here, hence closing this ticket.

**Comment by kivenhu** [comment]
Hello, also found a problem, the call chain has a lot of CommandHandler.channelRead execution statement, the longest lasted for 5 days. What's the reason for this? Thank you。

https://user-images.githubusercontent.com/3191835/43261030-e0295ae0-910d-11e8-8e82-4c0545103092.png
分类 | 持续时间(ms) | 时间占比(%) | 时间偏移量(ms)
-- | -- | -- | --
AbstractProxyInvoker.invoke | 15117909 | 100.00 | 0
JavassistProxyFactory$1.invoke | 143 | 0.00 | 0
JavassistProxyFactory$1.doInvoke | 143 | 0.00 | 0
HikariDataSource.getConnection | 1 | 0.00 | 2
com.mysql.jdbc.CallableStatement.execute | 3 | 0.00 | 11
com.mysql.jdbc.PreparedStatement.execute | 1 | 0.00 | 17
HikariDataSource.getConnection | 0 | 0.00 | 37
com.mysql.jdbc.PreparedStatement.execute | 1 | 0.00 | 41
HikariDataSource.getConnection | 0 | 0.00 | 135
com.mysql.jdbc.PreparedStatement.execute | 2 | 0.00 | 139
Custom.connect | 608266 | 4.02 | 79
CommandHandler.channelRead | 0 | 0.00 | 126
CommandHandler.channelRead | 0 | 0.00 | 28720
CommandHandler.channelRead | 0 | 0.00 | 28809
CommandHandler.channelRead | 0 | 0.00 | 28850
CommandHandler.channelRead | 0 | 0.00 | 92922
CommandHandler.channelRead | 0 | 0.00 | 231771
CommandHandler.channelRead | 0 | 0.00 | 244395
CommandHandler.channelRead | 0 | 0.00 | 244417
CommandHandler.channelRead | 1 | 0.00 | 27840
