### ISSUE TITLE
filter read candidate bad nodes

### ISSUE THREAD

**Issue by linzhouzhi** [lettuce-io/lettuce-core#818]
## Feature Request
hi lettucer
i change PooledClusterConnectionProvider class isReadCandidate method, for filter bad nodes.

file: src/main/java/io/lettuce/core/cluster/PooledClusterConnectionProvider.java

private boolean isReadCandidate(RedisClusterNode master, RedisClusterNode partition) {
        return master.getNodeId().equals(partition.getNodeId())
                || master.getNodeId().equals(partition.getSlaveOf())
                && (!partition.getFlags().contains(RedisClusterNode.NodeFlag.FAIL))
                && (!partition.getFlags().contains(RedisClusterNode.NodeFlag.EVENTUAL_FAIL))
                && (!partition.getFlags().contains(RedisClusterNode.NodeFlag.HANDSHAKE))
                && (!partition.getFlags().contains(RedisClusterNode.NodeFlag.NOADDR));
    }

**Comment by mp911de** [comment]
That's something to implement in a custom `ReadFrom` strategy. `RedisNodeDescription` is typically instance of `RedisClusterNode` and allows introspection in the strategy class.
