### ISSUE TITLE
Fall back to initial seed nodes on topology refresh when dynamicRefreshSources is enabled

### ISSUE THREAD

**Issue by stuartharper** [lettuce-io/lettuce-core#822]
#### Current Behavior
In Issue #338 I mentioned we experienced a problem around the use of AWS Elasticache and Lettuce not following DNS changes.

I eventually tracked this down to the way the dynamicRefreshSources is implemented. When set to true (default) then on startup the initial seed nodes are resolved and connections established. From that point onwards the DNS entries are never reresolved so if the entire cluster were to change the application looses connectivity permanently (until restart).

When dealing with elasticache most likely only individual nodes would change most of the time however when creating a cluster it's necessary to pick a maintenance window during which the cluster may not be available. I think it's entirely possible that after this window all of the underlying VMs may have changed.

#### Input Code
This is the way we connect which exhibits the problem. To reproduce easily (without waiting for maintenance windows etc) delete the elasticache cluster and create a new one of the same name. All of the underlying IP addresses will then change.
```java
ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enablePeriodicRefresh(Duration.ofSeconds(30))
                .dynamicRefreshSources(true)
                 .enableAllAdaptiveRefreshTriggers()
                .build();
        ClientOptions clientOptions = ClusterClientOptions.builder()
                .topologyRefreshOptions(topologyRefreshOptions)
                .build();

        RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration(clusterNodes);
        LettuceClientConfiguration lettuceClientConfiguration = LettuceClientConfiguration.builder()
                .clientOptions(clientOptions).build();
```
The Lettuce implementation of dynamicRefreshSources  can be seen here https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/cluster/RedisClusterClient.java#L1052

Setting dynamicRefreshSources to false fixes the problem for us because it goes back to the initialUris and resolves them from hostnames.

#### Environment

- Lettuce version:  5.0.4.RELEASE
- Redis version: 3.2.6 (AWS Elasticache)
- Spring boot: 2.0.2.RELEASE

#### Possible Solution
I don't know if this issue is a bug exactly but I think at a minimum it would be helpful to update the documentation so it's more obvious what the impact of that setting is in relation to DNS. The documentation does reference DNS in other areas and allows you to set other DNS resolvers but that has no impact because no attempt is being made to resolve DNS.

For an actual code fix the only thing I can think of is to resolve the initialUris when all hosts are marked as being down or having that as setting since the current solution means all connections are thrown away every time.

**Comment by MatanRubin** [comment]
I think you might reference the wrong issue in your opening line

**Comment by mp911de** [comment]
This isn't exactly what happens here. Lettuce resolves hostnames at two times:

* When connecting
* When reconnecting

Depending on the used DNS resolver (Default to JVM), caching may apply which interferes with DNS-based failover. Typically, Lettuce attempts to reconnect by using the known hostnames from either the initial seed URI or the known partition.

Using AWS ElastiCache, I'd recommend to not use `dynamicRefreshSources` as the DNS name for the entry point should be assumed stable. Using `DirContextDnsResolver` performs DNS lookups **without** caching. This may be, depending on the case, good or bad.

Can you elaborate on

> the initial seed nodes are resolved and connections established. From that point onwards the DNS entries are never reresolved

How did you conclude that DNS entries are never reresolved? I wasn't able to reproduce this case (given that the JVM is configured accordingly, see [Setting the JVM TTL for DNS Name Lookups](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-jvm-ttl.html#how-to-set-the-jvm-ttl)).

**Comment by stuartharper** [comment]
I'm observing the DNS behaviour two ways

1. Enabling logging debug and observing the output of the ConnectionWatchdog. This showed the application was forever trying to connect to the old IP addresses. 

2. TCP dump on port 53 to print out outgoing DNS requests (tcpdump -i eth0 udp port 53). From this I can see the initial requests going out as well as other hostnames the application connects to being periodically resolved (with the JVM TTL set) but not the redis hostname(s).

According to the lettuce docs the default resolver is netty's DNS resolver since 4.4. I did try setting it to use the JVM resolver via 

`ClientResources clientResources = DefaultClientResources.builder().dnsResolver(DnsResolvers.JVM_DEFAULT).build();
`
But it didn't make any difference. I also tried using `new DirContextDnsResolver()` to use no caching at all. 

From what I've seen the partition list is always used with the IP address that was initially resolved when connecting the first time. 

I'll put together a simple spring boot application to demonstrate the issue.

**Comment by stuartharper** [comment]
I've created a small hello world app based on the spring boot starter application here https://github.com/stuartharper/gs-spring-boot

The application can be launched via initial/gradlew bootRun

Access localhost:8080 will cause the application to write a key "Hello" and value "World" into the configured redis cluster. This will then be immediately read back as well. io.lettuce is set to debug so the connection details can be observed.

Configuration of redis is via \initial\src\main\resources\application.properties 
redis.hosts is the server:port to connect to and redis.dynamicRefreshSources controls the dynamicRefreshSources behaviour. 

Scenarios I tested:

1. Creating an AWS Elasticache cluster (clustered, engine 3.2.6, 1 shared with 2 replicas, multi-az) and allowed the application to connect to it and write in a value. While the application remains running delete the cluster and recreate it with the same name.

2. Two separate clusters of standard redis 3.2.9 with 3 nodes each. Using the local hosts file I simulated a DNS change from one cluster to the next.

Results:

1. With redis.dynamicRefreshSources set to true the application continues trying to access the IP address of the original Elasticache cluster even after local ping has been updated to the new IP. I left it running overnight and the application connection remained broken.
\
With  redis.dynamicRefreshSources set to false the application reconnects to the updated cluster around the same time as local ping returns the new IP

2. With redis.dynamicRefreshSources set to true the application connects to the IP contained in the hosts file and never switches to the second cluster even when the first is completely stopped.
\
With redis.dynamicRefreshSources set to false the application reconnected to the updated cluster  on the next refreshinterval 

Our main concern is around the AWS Elasticache maintenance window in during which multiple nodes may be replaced simultaneously. The docs say they will try to not replace too many at once but no guarantees are given https://aws.amazon.com/elasticache/elasticache-maintenance/

The concern is if the application loses connection to the cluster it will never reestablish it until it's restarted.

**Comment by mp911de** [comment]
Thanks a lot. Can confirm your above findings. Redis returns resolved addresses (IPv4 or IPv6) in `CLUSTER NODES` hence Lettuce does not re-resolve hostnames to addresses as there are no hostnames to resolve. `dynamicRefreshSources` uses only `CLUSTER NODES` details for subsequent topology refreshes.

In any case, I would recommend disabling `dynamicRefreshSources` when you're on AWS. The configuration hostname remains stable (i.e. it does not suddenly disappear) and resolves to a set of IP addresses that point to the cluster nodes.

**Comment by mp911de** [comment]
Currently, I'm not sure what to do with this ticket. `dynamicRefreshSources` purpose is to follow topology changes and not necessarily stick with the original seed nodes. Therefore I'd close this one with works as designed.

**Comment by stuartharper** [comment]
It would be good to update the documentation, there are some references to DNS caches in it which I think are slightly misleading given the actual behaviour. 

My other thought is if there's no topology to follow (i.e. all known nodes are down) maybe the seed node should be resolved again? 

I should also add that in our long running tests we found that we had to set `validateClusterNodeMembership` to false or else it occasionally failed on this.

**Comment by mp911de** [comment]
`validateClusterNodeMembership` is enabled by default to protect against connections to unwanted nodes. 
I updated the docs for dynamic refresh sources. 

> My other thought is if there's no topology to follow (i.e. all known nodes are down) maybe the seed node should be resolved again?

We can do that. I think that's a good resiliency measure to recover from scenarios where the entire cluster is replaced and the hostname is the only way how to find a valid entry point.

**Comment by mp911de** [comment]
I relabelled the ticket subject to reflect your proposed change.

**Comment by stuartharper** [comment]
Sounds good, thanks!

**Comment by mp911de** [comment]
That's fixed now.
