### ISSUE TITLE
StackOverflowError on ScanStream.scan(…).subscribe()

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#824]
#### Current Behavior

`ScanStream` terminates with a `StackOverflowError` if many elements (tested with 100000 keys) on subscription/completion.

#### Input Code

```java
RedisClient redisClient = RedisClient.create("redis://localhost");
StatefulRedisConnection<String, String> connect = redisClient.connect();

Flux<String> scan = ScanStream.scan(connect.reactive());
System.out.println(scan.count().block());
```

#### Environment

- Lettuce version(s): 5.1.0

**Comment by duke-cliff** [comment]
Will spring boot data 2.1.0 final version use this milestone?

**Comment by mp911de** [comment]
Spring Data Redis 2.1 will ship using Lettuce 5.1.0.RELEASE.
