### ISSUE TITLE
How to increase throughput of lettuce client 

### ISSUE THREAD

**Issue by s-aravind-flipkart** [lettuce-io/lettuce-core#825]
With lettuce client I'm increasing connections but the throughput is not increasing at all. Please could you provide the parameters for the same.

Tried with connectionPool no improvement as such. 

Setup:
The cluster of 6 nodes with 3 + 3.
Run Jmeter with parallel threads of 100 for fetching single key. The throughput  was 6700k/s. Tried increasing the connections no impact.

--

**Comment by mp911de** [comment]
Redis messages are typically extremely small so the most cost of operations lies in allocations (`RedisFuture`, `CommandArgs`, Output) and queue operations along with context switching (i.e. enqueuing a command and that command is read by another thread). These are sort of fixed cost and the only thing that you can do there is using processors with a higher clock frequency.

Realistically, the only thing that makes sense to increase throughput is batching of commands, sending multiple commands at once. Another way to view this is disabling command auto-flush (`StatefulConnection.setAutoFlush(false)`), issue a series of commands, and flush commands with `StatefulConnection.flushCommands(…)`. This type of operations changes the state of a connection so you either need to synchronize to avoid races or issue a connection per thread.

**Comment by s-aravind-flipkart** [comment]
@mp911de Please could you elaborate on the particular statement " changes the state of a connection " so if we are using the same connection across multiple threads setting autoflush as false and flushing with each command what are the repercussions as such.

**Comment by mp911de** [comment]
In the worst case, commands may remain submitted to the command queue but never flushed. Lettuce connections are thread-safe when the connection state is not mutated.

State-mutations are:
* Transactional use (the connection enters transactional state with `MULTI` and leaves it with `EXEC` or `DISCARD`)
* Changing the `autoFlush` state
* Flushing and submitting commands while `autoFlush` is `false`

The background is that the connection and commands build up a state (e.g. commands are queued but not sent to Redis yet) and without a coordinated state change, commands may remain not executed.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
