### ISSUE TITLE
Wrong behavior of Get command with custom Codec

### ISSUE THREAD

**Issue by creif** [lettuce-io/lettuce-core#829]
Good day , 
We have implemented a custom codec (JsonCodec)for redis which saves Objects as Json in redis.
We have some problems with execution of get commands against the redis.
During deserialization data arriving to codec contains characters that do not exist in value mapped by key being fetched from redis.

The scenario is as follows : 

- Redis is cleared before execution of commands

- Setting key core.current.device.state.9  - The value is checked in cli and it is correctly inserted

- Getting the key core.current.device.state.9 via sync get command and deserialization fails due to the fact that some extra characters are attached to the real value saved in redis (result of response appears in file response1.txt)

- Setting key core.current.device.state.9 to another value 

- Setting the core.current.device.state.9 key again via sync get command the same behavior as before (response of get in file response2.txt)

It seems that due to some reason during the get , inner data used by lettuce like $3 , $23 concatenated to returned object , and even data from last 2 commands is concatenated to returned object.
Can you please check based on given responses whether it is a problem in your code?
I did not find any issue similar to this .
If needed I can provide model of Json we are saving.
The version of lettuce is 5.0.4.RELEASE
Thanks
[response1.txt](https://github.com/lettuce-io/lettuce-core/files/2249790/response1.txt)
[response2.txt](https://github.com/lettuce-io/lettuce-core/files/2249791/response2.txt)
[JsonCodec.txt](https://github.com/lettuce-io/lettuce-core/files/2249792/JsonCodec.txt)

**Comment by mp911de** [comment]
Thanks for filing an issue. Please provide a reproducible test case, without that, we cannot reproduce the issue.

In any case, your `JsonCodec` is broken. `decodeKey(…)` renders `java.nio.DirectByteBuffer[pos=0 lim=49 cap=16777216]` as decoded key. Rather delegate key encoding/decoding to `StringCodec.UTF8`. `ObjectMapper` is instantiated in two places (costly operation) instead being reused, `decodeValue(…)` calls `ByteBuffer.rewind();` which can break decoding.

**Comment by creif** [comment]
Thank you for your input,
After I used the StringCodec the issue is not reproduced.
