### ISSUE TITLE
How can I use a cluster with multiple sentinals?

### ISSUE THREAD

**Issue by zhangweidavid** [lettuce-io/lettuce-core#830]
Hi @mp911de 

 I found that lettuce only supports one sentinel. How can I use a cluster with multiple sentinals?

**Comment by mp911de** [comment]
How so? 

```
RedisURI redisUri = RedisURI.Builder.sentinel("sentinelhost1", "mymaster").withSentinel("sentinelhost2").build();
RedisClient client = RedisClient.create(redisUri);
```

See also [Redis URI and connection details](https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details) for further details.

**Comment by zhangweidavid** [comment]
think you so much

**Comment by zhangweidavid** [comment]
thank you so much
