### ISSUE TITLE
Receiving extra connection/disconnection events on Redis server shutdown

### ISSUE THREAD

**Issue by yissachar** [lettuce-io/lettuce-core#831]
#### Current Behavior

I'm trying to use the connection events to listen for when a connection has been made or lost and take appropriate actions. However, I often get extra connection/disconnection events that I don't think should exist.

```
1. DisconnectedEvent [/127.0.0.1:55964 -> localhost/127.0.0.1:6379]
2. ConnectionDeactivatedEvent [/127.0.0.1:55964 -> localhost/127.0.0.1:6379]
Aug 07, 2018 4:20:42 PM io.lettuce.core.protocol.ConnectionWatchdog run
INFO: Reconnecting, last destination was localhost/127.0.0.1:6379
Aug 07, 2018 4:20:42 PM io.lettuce.core.protocol.ReconnectionHandler lambda$null$1
INFO: Reconnected to localhost:6379
3. ConnectedEvent [/127.0.0.1:55967 -> localhost/127.0.0.1:6379]
4. ConnectionActivatedEvent [/127.0.0.1:55967 -> localhost/127.0.0.1:6379]
5. DisconnectedEvent [/127.0.0.1:55967 -> localhost/127.0.0.1:6379]
6. ConnectionDeactivatedEvent [/127.0.0.1:55967 -> localhost/127.0.0.1:6379]
```

I am running Redis in Docker and just cycle through killing the container and restarting. The above logs are a for a single `docker stop <container>` command. You can see I get an additional event of each type after the initial disconnect events. This doesn't happen every time I kill the container, but it happens very frequently.

#### Input Code

```java
RedisClient redisClient = RedisClient.create("redis://localhost:6379");
redisClient.getResources().eventBus().get().subscribe(System.out::println);
redisClient.connect();
```

#### Expected behavior/code

I should only receive a disconnect event when the Redis server is shutdown instead of additional connection events.

#### Environment

- Lettuce version(s): 5.0.5.RELEASE
- Redis version: 4.0.10

**Comment by mp911de** [comment]
Can you elaborate which events (I added numbers to the log statements) you expect to not be emitted?

Connection events describe lifecycle events from a transport perspective, not a logical perspective.

**Comment by yissachar** [comment]
I would expect to only receive events 1 and 2, and all events beyond that should not be emitted. Prior to event 1 the Redis server has been killed, so I would expect to only receive a DisconnectedEvent and ConnectionDeactivatedEvent, and would not expect to receive ConnectedEvent/ConnectionActivatedEvent until I've restarted the server.

**Comment by mp911de** [comment]
What is the actual use case? What are you trying to solve?

Right now, I get the feeling that we might miss more user-space events such as `ConnectionCreated`/`ConnectionClosed` events that allow to identify when a connection object is created/disposed.

**Comment by yissachar** [comment]
When I receive a ConnectionActivatedEvent I try to reload various scripts into Redis (since this may be a new Redis instance coming online that does not have the scripts cached). The problem is that since this is a fake event, the script load stalls and eventually times out and for some reason I stop receiving any further connection events (connected or disconnected) no matter how many times I stop and restart Redis.

Here is the code you can use to reproduce this:

```
public class Main {

	private static StatefulRedisConnection connection;

	public static void main(String[] args) {
		RedisClient redisClient = RedisClient.create("redis://localhost:6379");
		redisClient.getResources().eventBus().get().subscribe((event) -> {
			System.out.println(event);

			if (event instanceof ConnectionActivatedEvent) {
				System.out.println("Loading script");
				if (connection == null) return;

				System.out.println(connection.sync().scriptLoad("return 'hello'"));
			}
		});
		connection = redisClient.connect();

		int i = 0;
		while (true) {
			i++;
		}
	}
}
```

Note that it looks like I may be able to workaround this by loading the scripts async instead, since that doesn't seem to exhibit this behaviour. However, I am still confused as to why I get these spurious events in the first place, as well as why the sync script load timing out causes the event subscription to stop working entirely.

**Comment by mp911de** [comment]
Please note that although events are published on a dedicated thread pool, they might interfere with blocking behavior on consumption. It's safe to invoke Redis functionality but that should happen asynchronously (e.g `connection.async().scriptLoad(…).whenComplete(…)`).

Reacting on `ConnectionActivatedEvent` is the right thing to do here as the actual target host might have changed (DNS entry changed so reconnect might hit a different IP address).

**Comment by yissachar** [comment]
Got it, async is working fine for me.

Still confused as to the multiple events though. Is this expected or not?

**Comment by mp911de** [comment]
Yes, multiple events are expected. See [Connection-Events](https://github.com/lettuce-io/lettuce-core/wiki/Connection-Events).
