### ISSUE TITLE
Is there a way to filter slaves in redis cluster whose replication link is down

### ISSUE THREAD

**Issue by s-aravind-flipkart** [lettuce-io/lettuce-core#833]
Some slaves master link is down at runtime if we are hitting the slave we get responses the link is down with master is there a way where we could point to master intermittently

**Comment by mp911de** [comment]
There is currently no way to filter these nodes. How do you discover that a particular node replication link is down? `INFO replication` or is there a flag in `CLUSTER NODES`?

**Comment by s-aravind-flipkart** [comment]
@mp911de Thanks for the quick response from info replication. Currently, the ReadFrom cannot be plugged to be used.

**Comment by mp911de** [comment]
You could query `INFO` from the individual nodes yourself and keep a table of that state somewhere around. I think overriding `RedisClusterClient.determinePartitions(…)` is the appropriate hook to fetch the data you need. Within a custom `ReadFrom` you can then filter nodes that do not have a master link. 

On a side note: Wouldn't it be easier to set `slave-serve-stale-data` to `yes` in your Redis config?

**Comment by s-aravind-flipkart** [comment]
@mp911de slave-serve-stale-data we are not using it as we don't do a bgsave in slaves. So whenever the slave resyncs the latest data on restart we cannot tolerate to show stale data.

**Comment by mp911de** [comment]
Closing this one as the question is answered.
