### ISSUE TITLE
Support for approximate trimming in XAddArgs

### ISSUE THREAD

**Issue by lizhaohui836** [lettuce-io/lettuce-core#846]
Thanks for support of redis5.0 timely.
Recently I plan to use streams in my application, but I found that 'XADD' have a special argument: ~ which that is much more efficient for capped streams. 
So, would you add supporter for '~' argument in XAddArgs. 
links: 
https://redis.io/topics/streams-intro#capped-streams

**Comment by mp911de** [comment]
It makes sense to extend `XAddArgs` to support approximate stream trimming.

**Comment by mp911de** [comment]
We should also provide an `XTRIM` variant with approximate trimming.
