### ISSUE TITLE
Azure master and secondary accesskey support

### ISSUE THREAD

**Issue by xukai286** [lettuce-io/lettuce-core#852]
## Feature Request
Azure master and secondary accesskey support

#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Teachability, Documentation, Adoption, Migration Strategy

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

Azure redis provide two access key for every redis cache databsae.
sometimes we will refresh the primary key but keep the secondary key. before we update the config file in the redis client. we will get an error"ERR invaid password" message. could  lettuce to support a password fail-over stratage to fall back to use the secondary password. If neither master nor secondary password is invalid. then thow the exception.

**Comment by mp911de** [comment]
Lettuce has no strong tailoring of customized Redis derivates. Adding additional code paths for authentication exceptions would contribute additional complexity to Lettuce and that's not really something we want. Authentication is distributed across the code to support various use cases (connect with auth, connect with auth as connection ping, user-triggered authentication, authenticate on reconnect plus the variants for Redis Cluster). The underlying code either expects a successful authentication or an immediate failure. Retry with a secondary password would require a huge refactoring.

Closing this ticket as we won't do the change.
