### ISSUE TITLE
Connection pooling opened too many connections to redis cluster when qps is high

### ISSUE THREAD

**Issue by lujia-zhang** [lettuce-io/lettuce-core#860]
Hi, currently I'm working on using lettuce as the redis client. We want to do pipeline and from what I understand, since async pipeline needs dedicated connection so we chose to do connection pooling. 
However when we do load test, the service opened hundreds of connections to redis cluster. I've being working on solve it but no luck so far. Could you please offer some suggestions? How can we reuse the connections without opening too many to redis cluster? From our logging, opening too many connections to redis cluster will harm the performance and will finally through exceptions:
 ```io.lettuce.core.RedisException: io.lettuce.core.RedisConnectionException: Unable to connect to host:port
...
Caused by: java.util.concurrent.CompletionException: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel
... io.netty.channel.ChannelException: Failed to open a socket.
...Caused by: java.net.SocketException: Too many open files
```
Following is our implementation.

Redis Client implementation:
```public class RedisCluster {
    public final RedisClusterClient clusterClient;
    public GenericObjectPool<StatefulRedisClusterConnection<String, String>> pool;
    private int adaptiveRefreshTimeout = 10; // in seconds

    public RedisCluster(Set<RedisURI> redisClusterURIs, int maxActive) {
        clusterClient = RedisClusterClient.create(redisClusterURIs);
        ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enableAllAdaptiveRefreshTriggers()
                .adaptiveRefreshTriggersTimeout(Duration.ofSeconds(adaptiveRefreshTimeout))
                .build();
        clusterClient.setOptions(ClusterClientOptions.builder()
                .autoReconnect(true)
                .cancelCommandsOnReconnectFailure(true)
                .disconnectedBehavior(ClusterClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                .topologyRefreshOptions(topologyRefreshOptions)
                .build());

        GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
        poolConfig.setMaxTotal(maxActive); // set to 8
        pool = ConnectionPoolSupport.createGenericObjectPool(
                () -> clusterClient.connect(), poolConfig);
    }
    public StatefulRedisClusterConnection<String, String> getConnection(boolean readFromSlaves) {
                StatefulRedisClusterConnection<String, String> conn = pool.borrowObject();
                if (readFromSlaves) {
                    conn.setReadFrom(ReadFrom.SLAVE);
                }
                return conn;
    }
    public RedisAdvancedClusterCommands<String, String> syncCommands() {
        StatefulRedisClusterConnection<String, String> conn = getConnection(true);
        RedisAdvancedClusterCommands<String, String> syncCommands = conn.sync();
        return syncCommands;
    }
    public RedisAdvancedClusterAsyncCommands<String, String> asyncPipeline() {
        StatefulRedisClusterConnection<String, String> pipelineConnection = getConnection(true);
        RedisAdvancedClusterAsyncCommands<String, String> pipeline = pipelineConnection.async();
        pipeline.setAutoFlushCommands(false);
        return pipeline;
    }
    public void close() {
        pool.close(); // Close the connection
        clusterClient.shutdown(); 
    }
}
```
Usage of redis cluster client in our service:
```
public class exampleService {
    private final RedisCluster redisCluster;
    private final RedisAdvancedClusterCommands<String, String> syncCommands;
    private int pipelineTimeout = 300; // Maximum time to wait for futures to complete.
    public exampleService(RedisCluster redisCluster) {
        this.redisCluster = redisCluster;
        this.syncCommands = redisCluster.syncCommands();
    }
    public String get(String key) {
        String value = syncCommands.get(key);
        return value;
    }
    public List<String> pipelineGet(List<String> keys) {
                RedisAdvancedClusterAsyncCommands<String, String> pipeline = redisCluster.asyncPipeline();
                List<RedisFuture<String>> futures = new ArrayList<>();
                List<String> values = new ArrayList<>();
                try {
                    for (String key : keys) { futures.add(pipeline.get(key)); }
                    pipeline.flushCommands();
                    boolean result = LettuceFutures.awaitAll(pipelineTimeout, TimeUnit.MILLISECONDS,
                            futures.toArray(new RedisFuture[futures.size()]));
                    if (result) {
                        for (RedisFuture<String> future : futures) { values.add(future.get()); }
                        return values;
                    } else {
                        logger.error("[lettuce] Failed to get redis keys in pipeline within timeout");
                        return null;
                    }
                } catch (Exception e) {
                    logger.error(e, "[lettuce - ClusterPipeline] Failed to get redis keys in pipeline for keys: %s", keys);
                    redisCluster.clusterClient.reloadPartitions();
                    logger.warn("[lettuce] reload cluster nodes when exception happens");
                    return null;
                } finally {
                    // return connection back to pool
                    redisCluster.pool.returnObject(pipeline.getStatefulConnection());
                    logger.info("[lettuce] return pipeline connection back to pool.");
                }
            }
}
```

**Comment by mp911de** [comment]
That's interesting. You're configuring a max total count of 8 connections and end up with hundreds.  How many nodes does your Redis Cluster have?

In general, Lettuce applies pipelining by default. `setAutoFlushCommands(…)` applies additional optimizations to reduce tiny TCP packets and to buffer commands instead of writing these to the transport. So actually, there's no need to use pooling here if you remove `setAutoFlushCommands(…)` and `flushCommands()` invocations.

**Comment by lujia-zhang** [comment]
Thanks for responding!

> That's interesting. You're configuring a max total count of 8 connections and end up with hundreds. How many nodes does your Redis Cluster have?
> 
So we have 3 hosts, and 32 processors per host, 6 shards, 3 replicas per shard. After I configured the pool size to 30, there are around 260 connections (I use `lsof -i -n -P  | grep 700 | grep java | wc -l` to count the connection.) Can you please explain how many tcp connections will a statefulconnection open? I'm a little bit confused.

> In general, Lettuce applies pipelining by default. `setAutoFlushCommands(…)` applies additional optimizations to reduce tiny TCP packets and to buffer commands instead of writing these to the transport. So actually, there's no need to use pooling here if you remove `setAutoFlushCommands(…)` and `flushCommands()` invocations.

What do you mean by 'Lettuce applies pipelining by default'? From the wiki I think using `setAutoFlushCommands(…)` and `flushCommands()` is the way to approach pipeline, but since `flushCommands()` will flush commands for the whole the connection I go with the connection pooling. We do have performance concerns for pipeline request. What's the better way you will suggest?

**Comment by mp911de** [comment]
The number of TCP connections per Cluster connection is up to `(2 * number of nodes) + 1` as each host that serves data requires a connection and optionally an additional `READONLY` connection per replica. So in your case that's 6 x 3(replicas) + 3 (masters) = 21 Redis processes -> 2 * 21 + 1 -> up to 43 connections per `StatefulRedisClusterConnection`.

> What do you mean by 'Lettuce applies pipelining by default'?

Lettuce writes commands immediately to the transport without awaiting the completion of a previous command. After re-reading the wiki, I think some confusion comes from the fact that Pipelining and Flushing are documented on the same page. We should change this and move command flushing into a page that relates more to batching/last bit optimizations.

**Comment by lujia-zhang** [comment]
Thanks for your clear explanation!  So if we have a connection pool, will the number of TCP connections affect the machine it running on and redis cluster performance? From my observance if the java service open too many tcp connections it will finally throws a `RedisConnectionException: Unable to connect`. So suppose if we use one shared `StatefulRedisClusterConnection` for all sync commands, what will happen if the load is very high? A more general question I want to ask is how should we configure the number of `StatefulRedisClusterConnection` for the service?

For batch request usage (pipeline), we do have latency concerns so want to use the flushCommands to save network resources. For our current implementation, we use connection pooling and each batch get request will borrow a `StatefulRedisClusterConnection` from the pool, send the batch request and return the connection back after finished. Is that the suggested way to go? If the qps is high, I think it might block waiting for new connection? What's your opinions on that?  

Appreciate your help!

**Comment by lujia-zhang** [comment]
Got it, thanks for your help @mp911de !

**Comment by fahuang24** [comment]
> That's interesting. You're configuring a max total count of 8 connections and end up with hundreds. How many nodes does your Redis Cluster have?
> 
> In general, Lettuce applies pipelining by default. `setAutoFlushCommands(…)` applies additional optimizations to reduce tiny TCP packets and to buffer commands instead of writing these to the transport. So actually, there's no need to use pooling here if you remove `setAutoFlushCommands(…)` and `flushCommands()` invocations.

We've observed the same thing - While using Synchronous Connection Pooling, the default maxTotal of clients is 8, and we tried set it to 10, but the number of clients would easily scale up and exceed the cap, e.g. up to our max number of threads in 1 worker 300. We are using lettuce in Dataflow, redis is GCP memorystore.
