### ISSUE TITLE
BraveTracing should support custom names for the service name

### ISSUE THREAD

**Issue by worldtiki** [lettuce-io/lettuce-core#865]
#### Is your feature request related to a problem? Please describe

It is likely for multiple Redis installations to coexist in a production environment.
Currently the service name for spans created by the Lettuce is hardcoded to "redis" which means that every service (using Lettuce client) will report spans with the service name "redis", regardless if they are using different Redis installations.

#### Describe the solution you'd like

There should be a builder for a BraveTracing that would allow users to provide a custom name to use for the service name for spans.

#### Describe alternatives you've considered

Didn't consider any alternatives.

#### Teachability, Documentation, Adoption, Migration Strategy

Currently a BraveTracing is created like this:
`BraveTracing.create(tracing)`
This could be changed to something like this (no name override):
`BraveTracing.builder(tracing).build()`
Or like this (with name override)
``BraveTracing.builder(tracing).serviceName("customNameHere").build()``

**Comment by worldtiki** [comment]
Draft implementation here: https://github.com/lettuce-io/lettuce-core/pull/866 if it's easier to explain and discuss the proposed changes.

**Comment by mp911de** [comment]
Awesome improvement. Thanks a lot for submitting a pull request. Tests are sort of flaky on Travis CI so don't get distracted by that.

**Comment by mp911de** [comment]
I enhanced your PR with customization hooks for `Span` and `Endpoint` and applied a round of polishing. That's now on `master`.
