### ISSUE TITLE
Commands do not work with List<T> result type

### ISSUE THREAD

**Issue by TheCycoONE** [lettuce-io/lettuce-core#869]
#### Current Behavior

Based on the documentation here: https://github.com/lettuce-io/lettuce-core/wiki/Redis-Command-Interfaces#response-types and the examples above, a Command interface should be able to specify a method that returns a List<Integer> or List<Long>. However doing so results in an error:

```
java.lang.IllegalArgumentException: Cannot resolve CommandOutput for result type java.util.List&lt;java.lang.Long&gt; on method public abstract java.util.List com.raveu.remote.app.v2.api.throttling.RedisCellCommands.throttle(java.lang.String,java.lang.Long,java.lang.Long,java.lang.Long,java.lang.Long)
	io.lettuce.core.dynamic.CommandSegmentCommandFactory.&lt;init&gt;(CommandSegmentCommandFactory.java:60)
	io.lettuce.core.dynamic.ExecutableCommandLookupStrategySupport$DefaultCommandFactoryResolver.resolveRedisCommandFactory(ExecutableCommandLookupStrategySupport.java:76)
	io.lettuce.core.dynamic.ExecutableCommandLookupStrategySupport.resolveCommandFactory(ExecutableCommandLookupStrategySupport.java:48)
	io.lettuce.core.dynamic.AsyncExecutableCommandLookupStrategy.resolveCommandMethod(AsyncExecutableCommandLookupStrategy.java:47)
	io.lettuce.core.dynamic.RedisCommandFactory$CompositeCommandLookupStrategy.resolveCommandMethod(RedisCommandFactory.java:273)
	io.lettuce.core.dynamic.RedisCommandFactory$BatchAwareCommandLookupStrategy.resolveCommandMethod(RedisCommandFactory.java:321)
	io.lettuce.core.dynamic.RedisCommandFactory$CommandFactoryExecutorMethodInterceptor.&lt;init&gt;(RedisCommandFactory.java:212)
	io.lettuce.core.dynamic.RedisCommandFactory.getCommands(RedisCommandFactory.java:192)
	com.raveu.remote.app.v2.api.throttling.RedisCellThrottle.&lt;init&gt;(RedisCellThrottle.java:29)
```

#### Input Code

RedisCellCommands.java
```java
interface RedisCellCommands extends Commands {
    @Command("CL.THROTTLE")
    List<Object> throttle(String key, Long maxBurst, Long tokensPerPeriod, Long periodsInSecond, Long tokens);
}
```

RedisCellThrottle.java
```java
public class RedisCellThrottle implements Throttle {
    private StatefulRedisConnection<String, String> redisConnection;
    private RedisCellCommands redisCommands;

    // ...

    @Autowired
    public RedisCellThrottle(StatefulRedisConnection<String, String> redisConnection) {
        this.redisConnection = redisConnection;

        RedisCommandFactory redisCommandFactory = new RedisCommandFactory(redisConnection);
        redisCommands = redisCommandFactory.getCommands(RedisCellCommands.class);
    }
```

#### Expected behavior/code

Should create an instance of RedisCellCommands.

#### Environment

- Lettuce version(s): [e.g. 5.0.5.RELEASE]
- Redis version: [e.g. 4.0.11]

#### Additional context

Everything works if I make the return type List<Object> and cast the elements when I use them instead. If this is expected behaviour then I find the documentation misleading.

**Comment by mp911de** [comment]
This behavior is correct. Response type resolution uses multiple aspects of the method signature to use the proper output type. So there are multiple things to say about this issue:

1. `List<Long>` is not assignable to `List<Object>`  (`List<Object>` comes via `ArrayOutput`)
2. Lettuce does not ship with a `CommandOutput<K, V, List<Long>>`. However, you can register a custom output yourself:

```
OutputRegistry registry = new OutputRegistry();
registry.register(ListOfLongOutput.class, ListOfLongOutput::new);

OutputRegistryCommandOutputFactoryResolver resolver = new OutputRegistryCommandOutputFactoryResolver(registry);
factory.setCommandOutputFactoryResolver(resolver);

static class ListOfLongOutput<K, V> extends CommandOutput<K, V, List<Long>>{

    public ListOfLongOutput(RedisCodec<K, V> codec) {
        super(codec, new ArrayList<>());
    }
    // impl comes here
}
```
3. Output resolution considers the Connections' `RedisCodec` and the registered output types to fill in generics. We provide `KeyListOutput` and `ValueListOutput` which would allow to use a different type than `List<Object>`. In your case above key and value types default to `String`.
4. There was no need to provide an `IntegerListOutput` as the only command that replies with `List<Long>` is `BITFIELD`.

**Comment by mp911de** [comment]
Keys and Values are `String`-typed in your example hence `KeyListOutput` resolves to `List<String>` and not `List<Long>`.

**Comment by TheCycoONE** [comment]
Ok, I understand. Sorry for the noise.
