### ISSUE TITLE
When the master-slave switchover occurs in the sentinel, the lettuce does not re-create the connection, causing the connection to be unavailable.

### ISSUE THREAD

**Issue by DemonJun** [lettuce-io/lettuce-core#872]
With environment:
Springboot-2.0.5.RELEASE
lettuce-5.0.5.RELEASE
redis-4.0.11

Reconnection only occurs when the node before the redis master-slave switch resumes work.

**Comment by DemonJun** [comment]
> Care to provide a script (description of steps that are necessary) how to reproduce the issue?

I use docker to deploy redis master-slave synchronization, use sentinel for master-slave state monitoring and failover, and lettuce configures the sentinel node information to connect with redis. However, when sentinel fails over, the lease connection redis has timed out. connection. But when the failed redisMaster node is working again, lettuce receives the notification and reconnects to the new redisMaster.

**Comment by mp911de** [comment]
Lettuce behaves as it should:

1. Master node fails
2. Commands sent to the master timeout eventually
3. Sentinel initiates reconfiguration
4. Lettuce picks up the new configuration and routes write calls to the new master.

Given the steps from above, everything behaves correctly.

**Comment by DemonJun** [comment]
@mp911de I found the reason. Lettuce does not recognize docker pause. If you use docker pause redis-master node, lettuce can't reconnect to the new master node. If it is docker stop, there is no problem.
