### ISSUE TITLE
Broken link to "Connecting to ElastiCache with Master/Replica" in wiki

### ISSUE THREAD

**Issue by LarryBattleWork** [lettuce-io/lettuce-core#873]
## Bug Report

On the [Getting started](https://github.com/lettuce-io/lettuce-core/wiki/Getting-started-%285.0%29) wiki page, the link to [Connecting to ElastiCache with Master/Replica](https://github.com/lettuce-io/lettuce-core/blob/5.0.5.RELEASE/src/test/java/io/lettuce/examples/ConnectToMasterReplicaUsingElastiCacheCluster.java) is broken.

#### Possible Solution

Should it point to [ConnectToMasterSlaveUsingElastiCacheCluster.java](https://github.com/lettuce-io/lettuce-core/blob/master/src/test/java/io/lettuce/examples/ConnectToMasterSlaveUsingElastiCacheCluster.java)?

**Comment by mp911de** [comment]
Thanks a lot. That's fixed now.
