### ISSUE TITLE
Update class paths in wiki

### ISSUE THREAD

**Issue by LarryBattleWork** [lettuce-io/lettuce-core#875]
## Bug Report

Some of the wikis have old class paths.

#### Current Behavior

https://github.com/lettuce-io/lettuce-core/wiki/Spring-Support contains:
- `<bean id="redisClient" class="com.lambdaworks.redis.support.RedisClientFactoryBean">`
- `<bean id="redisClient" class="com.lambdaworks.redis.support.RedisClusterClientFactoryBean">`

https://github.com/lettuce-io/lettuce-core/wiki/Redis-Command-Interfaces contains
- `com.lambdaworks.redis.protocol.CommandType`
- `com.lambdaworks.redis.protocol.CommandKeyword`
- `com.lambdaworks.redis.CompositeParameter`

https://github.com/lettuce-io/lettuce-core/wiki/ReadFrom-Settings contains
- `com.lambdaworks.redis.ReadFrom`

#### Expected behavior/code

https://github.com/lettuce-io/lettuce-core/wiki/Spring-Support should contain
- `<bean id="redisClient" class="io.lettuce.core.support.RedisClientFactoryBean">`
- `<bean id="redisClient" class="io.lettuce.core.support.RedisClusterClientFactoryBean">`

https://github.com/lettuce-io/lettuce-core/wiki/Redis-Command-Interfaces should contain
- `io.lettuce.core.protocol.CommandType`
- `io.lettuce.core.protocol.CommandKeyword`
- `io.lettuce.core.dynamic.support.CompositeParameterNameDiscoverer`

https://github.com/lettuce-io/lettuce-core/wiki/ReadFrom-Settings should contain
- `io.lettuce.core.ReadFrom`

**Comment by LarryBattleWork** [comment]
Updated the "CONTRIBUTING" link in the wiki footer. It was pointing to https://github.com/lettuce-io/lettuce-core/blob/master/CONTRIBUTING.md . Now points to https://github.com/lettuce-io/lettuce-core/blob/master/.github/CONTRIBUTING.md

**Comment by mp911de** [comment]
Awesome work, thanks for your support. I fixed the ReadFrom and Command Interfaces pages.
