### ISSUE TITLE
ReactiveCommandSegmentCommandFactory resolves StreamingOutput for all reactive types

### ISSUE THREAD

**Issue by yozhag** [lettuce-io/lettuce-core#879]
I'm using Redis Lettuce dynamic client as described in official documentation https://github.com/lettuce-io/lettuce-core/wiki/Redis-Command-Interfaces#command-interfaces.response-types

My commands interface looks exactly the same

```java
public interface RedisCommands extends Commands {
    @Command("GET")
    Mono<String> get(String key);
    Mono<Boolean> expire(String key, long seconds);
}

```

The problem is when method get cannot find value by key there's exception thrown instead of returning empty Mono.

```java
java.lang.IllegalArgumentException: Data must not be null
    at io.lettuce.core.internal.LettuceAssert.notNull(LettuceAssert.java:58)
    at io.lettuce.core.RedisPublisher$RedisSubscription.onNext(RedisPublisher.java:251)
    at io.lettuce.core.output.StreamingOutput$Subscriber.onNext(StreamingOutput.java:64)
    at io.lettuce.core.output.KeyListOutput.set(KeyListOutput.java:45)
    at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:373)
    at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:146)
    at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:624)
```

When using predefined RedisReactiveCommands get works fine, it returns empty Mono. So it seems like a bug to me.

The Redis Lettuce version being used is

```xml
       <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>5.0.1.RELEASE</version>
        </dependency>
```

Also checked with 5.0.4 RELEASE - issue remained

**Comment by mp911de** [comment]
Thanks for reporting this issue. This looks indeed like a bug as we're picking the wrong output here. The trace shows `KeyListOutput` whereas we should use `KeyOutput` (or `ValueOutput`) and make sure to not emit `null` values.

**Comment by mp911de** [comment]
The actual issue is that `ReactiveCommandSegmentCommandFactory` assumes all reactive result types support streaming. `Mono`, `Single`, and `Maybe` are single-item types and so the resolved output type does not fit the actual response processing strategy.

**Comment by mp911de** [comment]
That's fixed now.
