### ISSUE TITLE
About lettuce Pipelined operation in spring-data-redis and redis cluster

### ISSUE THREAD

**Issue by hongjhhh** [lettuce-io/lettuce-core#888]
Hello:
     I have a question about lettuce has been used in spring-data-redis ,when I use Pipelined operation in redis cluster .like this:
```
stringRedisTemplate.executePipelined(
                new SessionCallback<Object>() {
        // do some read
        //   do some read or write but depend on above read result
};
```

Can it work right in redis cluster?When I use redis cluster ,the redis keys are in different node by the cluster,for all i know ,the pipelined operation are send the request at one time,and receive response
one time,Can't it manage the different keys read and write operation in redis cluster.
thank you very much!

**Comment by mp911de** [comment]
This is not the forum for Spring Data Redis. Please post your question to Stackoverflow instead.
