### ISSUE TITLE
Dear,being a architect, I want to quickly learn the Lettuce5.x , how can I do?

### ISSUE THREAD

**Issue by zjpopo** [lettuce-io/lettuce-core#889]
Help support Lettuce!

Lettuce has always been a community project, not really backed or owned by any single (or group) of companies. While some maintainers used to work at companies supporting open source no one was working on it full time and there certainly isn't a huge company or team anywhere doing all this work.

---

As a group of volunteers you can help us in a few ways

- Giving developer time on the project. (Message us on [Twitter](https://twitter.com/LettuceDriver) or [Gitter](https://gitter.im/lettuce-io/Lobby) for guidance). Companies should be paying their employees to contribute back to the open source projects they use everyday.

**Comment by mp911de** [comment]
How about starting in our [Wiki](https://github.com/lettuce-io/lettuce-core/wiki)?

**Comment by zjpopo** [comment]
I am learning the code after downloaded. I want to know the realization principle and compare the features with Jedis-client

**Comment by mp911de** [comment]
Yes, then the Wiki is really the best place to start reading the documentation.

**Comment by zjpopo** [comment]
OK, I will do!
