### ISSUE TITLE
DefaultEndpoint#commandBuffer 

### ISSUE THREAD

**Issue by yinbingqiu** [lettuce-io/lettuce-core#896]
Hello ！

I recently read the architecture design of Lettuce. I have a question. When I was using the pipeline, I found that Lettuce cached all the `RedisCommands` waiting to be sent through a `commandBuffer` queue. However, if multiple threads are executing at the same time, multiple threads add data to the `commandBuffer` at the same time. At this time, I think there will be thread safety issues.Is your `DefaultEndPoint` bound to a variable in `ThreadLocal`?

**Comment by mp911de** [comment]
To make things more clear: Lettuce uses pipelining by default. It sounds as if you're using `flushCommands()` and `setAutoFlushCommands(…)`. If so, then you should not share a connection across multiple threads. Binding connections to `ThreadLocal` can be dangerous as connections can easily leak and once a thread stops.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
