### ISSUE TITLE
Flux that reads from a hash, processes elements and writes to a set, completes prematurely

### ISSUE THREAD

**Issue by vkurland** [lettuce-io/lettuce-core#897]
I create Flux by calling `ScanStream` to scan a hash, process elements and then write them to another Redis set by wrapping the call to `sadd()` in `flatMap()` or `concatMap()`. The problem is that the target set ends up with fewer elements than expected.

Consider the following code fragment:

    @Test
    public void test9() {

        final RedisClient client = RedisClient.create(RedisURI.create("127.0.0.1", 6379));

        try (StatefulRedisConnection<String, String> connection = client.connect()) {
            final RedisReactiveCommands<String, String> commands = connection.reactive();

            commands.flushall().block();

            Flux.fromStream(IntStream.range(0, 10_000).boxed())
                    .flatMap(num -> commands.hset(sourceKey, String.valueOf(num), String.valueOf(num)))
                    .blockLast(Duration.ofSeconds(10));

            final Long sourceSize = commands.hlen(sourceKey).block(Duration.ofSeconds(10));
            assertNotNull(sourceSize);
            assertEquals(sourceSize.longValue(), 10_000L);

            ScanStream.hscan(commands, sourceKey)
                    .map(KeyValue::getValue)
                    .map(Integer::parseInt)
                    .filter(num -> num % 2 == 0)
                    .concatMap(item -> commands.sadd(targetKey, String.valueOf(item)))
                    .blockLast(Duration.ofSeconds(10));

            final Long targetCard = commands.scard(targetKey).block(Duration.ofSeconds(10));
            assertNotNull(targetCard);
            assertEquals(targetCard.longValue(), 5_000L);

        } finally {
            client.shutdown();
        }
    }

This reads from the source hash using `ScanStream.hscan()`, picks every other element and writes them to the target set. This example uses concatMap() to pass Mono returned by the call to `commands.sadd()`. This test fails, the target set has only a few elements. Sometimes it is 5, sometimes 6 or more, but never expected 5000. The test also fails if I replace `concatMap()` with `flatMap()`

I have tried to stick `.log("category")` in front the call to `filter()`. I can see that it sends `request(1)` after every matching element but then I just see `onComplete()` after a few elements, surely much sooner than the expected 5000

I have tried to add `doOnError()` but it never catches any errors

The test works fine if the source is a regular set or a list rather than a hash. It seems to be limited to hashes.

the test shown above and a few other permutations can be found here:

https://github.com/vkurland/ltb/blob/master/src/test/java/ltb/LettuceTest.java

**Comment by mp911de** [comment]
That's fixed now. Care to give Lettuce `5.1.2.BUILD-SNAPSHOT` a try?
