### ISSUE TITLE
Gzipped data is not coming back as expected

### ISSUE THREAD

**Issue by johnnyquestep** [lettuce-io/lettuce-core#908]
I am trying to read  a key value pair, in this case value is already gzipped before loading.
when i read it back and try to decompress it i get invalid gzip header error . below is the sample code any assistance is greatly appreciated.

`	String test ="ASDF1234567890";
								byte[] bytes = test.getBytes();
								ByteArrayOutputStream bos = new ByteArrayOutputStream(test.length());
								GZIPOutputStream gzip = new GZIPOutputStream(bos);
								gzip.write(test.getBytes());
								gzip.close();
								byte[] compressed = bos.toByteArray();
								bos.close();
								for(Byte a :compressed) {
									System.out.print(a);
								}
								System.out.print('\n');
								  String decodedData = new String(compressed);

								System.out.println("compressed byte array ::: "+decodedData );
								RedisFuture<String> compfs = con.async().set("epkeytest", decodedData);

								RedisFuture<String> dcondaata= con.async().get("epkeytest");
								System.out.println("compressed returned data  ::: "+dcondaata.get() );
								byte[] b= dcondaata.get().getBytes();
								for(Byte a :b) {
									System.out.print(a);
								}

								ByteArrayInputStream bis = new ByteArrayInputStream(dcondaata.get().getBytes());
								GZIPInputStream gis = new GZIPInputStream(bis);
								BufferedReader br = new BufferedReader(new InputStreamReader(gis, "UTF-8"));
								StringBuilder sb = new StringBuilder();
								String line;
								while((line = br.readLine()) != null) {
									sb.append(line);
								}
								br.close();
								gis.close();
								bis.close();
								System.out.println("decompressed returned data  ::: "+sb.toString() );`

out put of the byte array print outs are below
31-117800000001151211811351525054495351-73-80520079-836611314000

31-17-65-67800000001151211811351525054495351-17-65-67-17-65-67520079-17-65-676611314000

what am i missing ?

**Comment by mp911de** [comment]
You're applying `String` conversion to your binary data. 

Creating a `String` from `byte[]` requires the byte array to contain valid character data. Converting arbitrary binary data to `String` and then back to `byte[]` changes the binary data because of `String` encoding.

You need to use binary values with Lettuce (See `ByteArrayCodec`).
