### ISSUE TITLE
JVM file Descriptor Count keep increasing with connection pooling

### ISSUE THREAD

**Issue by lujia-zhang** [lettuce-io/lettuce-core#921]
#### Current Behavior
JVM file Descriptor Count keeps increasing after we  deployed the app with Lettuce client. 

#### Input Code
This is how we config & create the rediscluster client and connection pool:

```java
        ClientResources res = DefaultClientResources.create();
        clusterClient = RedisClusterClient.create(res, redisClusterURIs);
        clusterClient.setDefaultTimeout(Duration.ofSeconds(params.getDefaultTimeoutSecond()));
        ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enableAllAdaptiveRefreshTriggers()
                .adaptiveRefreshTriggersTimeout(Duration.ofSeconds(adaptiveRefreshTimeout))
                .build();
        clusterClient.setOptions(ClusterClientOptions.builder()
                .autoReconnect(true)
                .cancelCommandsOnReconnectFailure(true)
                .disconnectedBehavior(ClusterClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                .topologyRefreshOptions(topologyRefreshOptions)
                .build());

        BoundedPoolConfig poolConfig = BoundedPoolConfig.builder()
                .maxTotal(12)
                .testOnAcquire()
                .build();
        pool = AsyncConnectionPoolSupport.createBoundedObjectPool(
                () -> clusterClient.connectAsync(StringCodec.UTF8), poolConfig);
```

How we make use of the connection:
```
                CompletableFuture<RedisAdvancedClusterAsyncCommands<String, String>> pipelineFuture = pool.acquire().thenApply(
                        conn -> {
                            conn.setReadFrom(ReadFrom.SLAVE);
                            RedisAdvancedClusterAsyncCommands<String, String> pipeline = conn.async();
                            pipeline.setAutoFlushCommands(false);
                            return pipeline;
                        });
                List<CompletableFuture<String>> futures = new ArrayList<>();
                List<String> values = new ArrayList<>();
                try {
                    for (String key : keys) {
                        CompletableFuture<String> future = pipelineFuture.thenCompose(
                                pipeline -> pipeline.get(key));
                        futures.add(future);
                    }
                    pipelineFuture.thenAccept(
                            pipeline -> {
                                pipeline.flushCommands();
                                // release connection
                                redisCluster.returnConnection(pipeline.getStatefulConnection());
                            }
                    );
                    boolean result = LettuceFutures.awaitAll(pipelineTimeout, TimeUnit.MILLISECONDS,
                            futures.toArray(new CompletableFuture[futures.size()]));
                    if (result) {
                        for (CompletableFuture<String> future : futures) {
                            values.add(future.get());
                        }
                        return values;
                    } else {
                        logger.error("[lettuce] Failed to get redis keys in pipeline within timeout");
                        return null;
                    }
                } catch (Exception e) {
                    redisCluster.refreshClusterSlotCache();
                    logger.warn("[lettuce] reload cluster nodes when exception happens");
                    return null;
                }
            }
```
#### Expected behavior/code

Since we set MaxTotal on the pool config, the max open files should have an upper bound instead of keep increasing.

#### Environment
- Lettuce version(s): 5.1.2.RELEASE
- Redis version: 3.2.8

**Comment by lujia-zhang** [comment]
> How many file descriptors (TCP connections) have you counted? How is your Redis Cluster configured (number of masters/replicas)?

After we deployed the application 4 days ago, the JVM file descriptor count increased from 350 to 440 and it keeps increased slowly. I think the count should not increased as time goes by since we set maxTotal. I also would like to know whether set maxIdle will help in our case. 

Our RedisCluster is setup with 24 hosts, 6 nodes on each host, 3 replicas per shard. The total cluster size is 48.

> Your code above does not release the connection. Is this intentionally?
For pipeline usage, we borrow a connection from the pool for each request and return the connection back to the connection pool after flush the commands. Will that cause leak?

**Comment by mp911de** [comment]
24 hosts with 6 nodes each result in 144 Redis Cluster nodes (Redis Cluster processes)?

A Redis Cluster Connection in Lettuce is composed of multiple node-connections of which each node connection requires a file descriptor (or TCP connection). Depending on `ReadFrom` the maximal number of transport connections for a Redis Cluster connection is `1 + (number of Redis processes * 2)`.

This is for:
* `1` A cluster connection has a default connection to issue non-keybound commands.
* `number of Redis processes`: Connection to master nodes to issue write commands.
* `number of Redis processes`: Connection to master or replica nodes to issue read commands.

According to this calculation, a single Redis Cluster connection represents between 1 to 145 TCP connections. Given the limitation from above, 12 connections, you can expect between 12 to 1740 TCP connections. Lettuce connects lazily to cluster nodes to not allocate all connections up-front. 
Having 440 connections/file descriptors allocated seems quite reasonable to me.

Please note: Lettuce uses pipelining by default. Changing `AutoFlush` is just an extra gain of performance. Please benchmark your application before using `AutoFlush` as pooling and state changes bring an extra level of complexity to your application. Ideally, you can simplify your code to just issue `GET` commands without all the pooling.

**Comment by mp911de** [comment]
I guess then there's nothing left to do for us. Closing this ticket.
