### ISSUE TITLE
How to use Connection Events for RedisTemplate in  Spring-Data-Redis?

### ISSUE THREAD

**Issue by dume2007** [lettuce-io/lettuce-core#922]
I defined RedisTemplate with LettuceConnectionFactory, but i have no idea to create Connection Events for example in https://github.com/lettuce-io/lettuce-core/wiki/Connection-Events. How to get RedisClient instance with RedisTemplate?

**Comment by mp911de** [comment]
Connection events are published through `EventBus` that you can access via `ClientResouces`. Either inject/obtain `ClientResources` from the application context or make sure to configure `LettuceConnectionFactory`  with `ClientResources` so you can get hold of it.

**Comment by dume2007** [comment]
```
@Bean
public LettuceConnectionFactory redisConnectionFactory() {
    ClientResources clientResources = ClientResources.builder().build();
    clientResources.eventBus().get().subscribe(event -> listenConnectEvent(event));

    LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
            .commandTimeout(Duration.ofMillis(idGeneratorConfig.getCommandTimeout()))
            .clientResources(clientResources)
            .build();

    log.warn("IDGeneratorConfig:{}", idGeneratorConfig);
    return new LettuceConnectionFactory(new RedisStandaloneConfiguration(idGeneratorConfig.getHost(), idGeneratorConfig.getPort()), clientConfig);
}
```
