### ISSUE TITLE
CommandDetailParserUnitTests should check for all existing redis commands

### ISSUE THREAD

**Issue by GhaziTriki** [lettuce-io/lettuce-core#927]
When implementing an API client, a good way to keep commands safe is to test how real commands are built. As example testing the arity of the `INCR` command is better than testing the arity of a fictional `theName` command.

**Comment by mp911de** [comment]
Care to elaborate? Unit tests should not duplicate data from remote systems but rather verify the code under test respects rules and leads to the desired functionality.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
