### ISSUE TITLE
Running out of ephemeral ports

### ISSUE THREAD

**Issue by ekkaitzen** [lettuce-io/lettuce-core#948]
Hi all, we are running out of ephemeral ports on a project with Redis cluster and pipelined operations.

Acording with issue #815 we have upgraded to Spring Data Redis 2.1.3 and Lettuce 5.1.3, but the problem persists.

How we can avoid this?

**Comment by mp911de** [comment]
Please enable connection pooling in Spring Data Redis to prevent connection creation at high rates.
