### ISSUE TITLE
Lettuce 4.4.4 Final Lettuce is making connections to master which was slave previously

### ISSUE THREAD

**Issue by s-aravind-flipkart** [lettuce-io/lettuce-core#949]
After the node was promoted from slave to master. After cluster topology refresh too the connections are made to the node which was promoted to master. These connections should have not been made at all.

**Comment by mp911de** [comment]
Can you provide a bit more context about what happened and why you think a particular node should not be used? It's quite hard to figure out from the description above what happened and what you expect to happen/to not happen.

**Comment by s-aravind-flipkart** [comment]
Lettuce Client version 4.4.4.Final
ReadFrom: Slaves
TopologyRefresh : 30 minutes

There are around N masters where one master failed over the newly promoted master still has connections from app server after 30 minutes also. The connections on the new-promoted master are still the same as the slave one. From the client list, I see read-only commands passed to the master

id=18097261 addr=10.34.65.69:38535 fd=1415 name= age=26352 idle=26352 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=18108395 addr=10.34.79.205:39019 fd=2004 name= age=25026 idle=7031 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hgetall
id=18097262 addr=10.34.94.206:44958 fd=1416 name= age=26352 idle=5880 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hgetall
id=18097043 addr=10.34.210.139:35016 fd=1197 name= age=26358 idle=316 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hgetall

The expectation was the after the failover the connections should have reduced on the Redis master.

**Comment by mp911de** [comment]
> The expectation was the after the failover the connections should have reduced on the Redis master.

That's not necessarily the case. 

Lettuce Cluster support retains connections to nodes that were contacted once until they disappear from the cluster topology. Lettuce's auto-reconnect feature comes into effect: As soon as a connection is disconnected, Lettuce attempts to reconnect to that node without regard to its previous/current role.

Is this just an observation you made or are there any issues that result from this behavior?

**Comment by s-aravind-flipkart** [comment]
@mp911de I'm running read-only as slaves. So at first before failover, the connections are made at slaves only. Once the failover has happened and once cluster topology is refreshed would have pointed to slaves right. 
It is an observation we are tracking the connections made to master. Usually, we have seen that once connections increases to more than 9k the Redis cluster goes into infinite failover mode. To avoid making connections to the newly made masters should we disable auto-reconnect. I was thinking that once topology refresh happens the connections should be closed and moved to new nodes applicable by ReadFrom strategy. Is there a way we could acheive the same.

**Comment by mp911de** [comment]
There's no way to change this behavior. Your only option is implementing your own Cluster client/command dispatch on top of Redis. Lettuce also has no notion of closing unused connections because we do not know whether a connection is currently in use. Connections are held open once they were created in [`PooledClusterConnectionProvider`](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/cluster/PooledClusterConnectionProvider.java).

`ReadFrom` is a function object and not an enumeration/indicator. It tells the cluster dispatcher which connection to use for a particular call and then we fetch a connection to the desired endpoint. It does not contain any information which nodes not to use.

**Comment by s-aravind-flipkart** [comment]
@mp911de Is there a way to close and reopen these connections on failover. We want to restrict connections to slaves only. Is there a way we could write a wrapper on the connection provider.

**Comment by mp911de** [comment]
`closeStaleConnections` closes connections to nodes, that are no longer listed in the topology. 

Looking into `PooledClusterConnectionProvider`, there's a lot of internal code that is not intended to be exposed as public API. If you want to implement such behavior, then the best would be to fork the project and create an overlay commit and release an own version of this library to your corporate artifact repository.

We're not going to change behavior at this point.
