### ISSUE TITLE
mget in the cluster performance issue on the client side

### ISSUE THREAD

**Issue by LinGoWei** [lettuce-io/lettuce-core#953]
We have a use case that we want to mget 100 keys in the cluster use RedisAdvancedClusterAsyncCommandsImpl.mget(). 

When we do stress tests on a single virtual machine with 4 cpu, more than 100 call mget(100...keys) times per second, vm cpu idle will down fastly and context switching high. Program run on the edge of crash.
![image](https://user-images.githubusercontent.com/6905006/50587009-0eb41e00-0eb7-11e9-8ad9-2f360e3b5f78.png)

As the official doc(https://github.com/lettuce-io/lettuce-core/wiki/Redis-Cluster) says, regular Redis Cluster commands are limited to single-slot keys operation, mget 100 keys will be dispersed 100 slots approximately, and then send commands to redis server concurrently by netty NIO, one context switching for sending command, next context switching for receiving response. 

Will I give up use redis cluster mode in this use case, and use client side partitioning ?

**Comment by mp911de** [comment]
Please provide a [minimal complete verifiable example](https://stackoverflow.com/help/mcve) so we can trace what's happening here.

**Comment by LinGoWei** [comment]
```
ExecutorService executors = Executors.newFixedThreadPool(4);

List<RedisURI> urls = new ArrayList<>();
urls.add(RedisURI.create("10.2.29.42", 7000));
urls.add(RedisURI.create("10.2.29.42", 7001));
urls.add(RedisURI.create("10.2.29.44", 7000));
urls.add(RedisURI.create("10.2.29.44", 7001));
RedisClusterClient client = RedisClusterClient.create(urls);
RedisAdvancedClusterAsyncCommands commands = client.connect().async();

List<List<String>> groupKeys = ... list of 100 str list 

for (List<String> keys : groupKeys) {
    executors.submit(new Task(keys));
}

private class Task implements Runnable {
    private List<String> keys;
    Task(List<String> keys) {
        this.keys = keys;
    }
    @Override
    public void run() {
        try {
            RedisFuture<List<KeyValue<String, String>>> future = commands.mget(keys.toArray(new String[keys.size()]));
            List<KeyValue<String, String>> result = future.get();
        } catch (Exception e) {
             e.printStackTrace();
        }
    }
}
```
@mp911de thanks for your reply, I feedback example

**Comment by LinGoWei** [comment]
> please confirm the node's free memory, if the node has no memory space, the mset() command would give the cluster huge pressure.
> I guess that if the cluster is full and has elimination algorithm, such as lru, the new keys would let cluster delete old keys and free up memory, this step would take a lot of time and the cpu rate would raise.

For this case, I can sure cluster node has free memory, and when i test it by mget, but not mget/mset together.  In addition, new cluster just set less 10w short string key-value.
And notice my point is performance issue on the client side, which a single virtual machine with 4 cpu

**Comment by mp911de** [comment]
According to the code here all is as it is expected. The JVM properly uses resources because of Lettuce's non-blocking I/O layer. If you find issues that we can streamline CPU usage with more light-weight activity (i.e. preventing unnecessary actions), I'm happy to assist you.

As of now, there's nothing left to do.

**Comment by kumari-jyoti** [comment]
Hi @LinGoWei Were you able to RCA this? 
We are facing similar issue, mget on 100 keys using lettuce mget RedisAdvancedClusterCommands<K,V>
Redis is receiving the commands but not able to fulfil in 500ms also and leading to timeout at client end followed by CB open.
Kindly let me know how you resolved it. Note: in our case, this is intermittent

**Comment by LinGoWei** [comment]
E-mail 已收到啦，谢谢！
