### ISSUE TITLE
Lettuce Client Goes out of Memory in seconds

### ISSUE THREAD

**Issue by coolfreakky** [lettuce-io/lettuce-core#959]
I am trying to pump load in Redis Cluster. The cluster comprises of 3 Masters and 6 slaves with 32GB of RAM on each node of the cluster.
I am only trying to perform SET operation using Lettuce Client to get the set throughput. All I am bothered presently is "FIRE & FORGET" wherein I am not concerned with output of the command submitted.
My client is running with 32 Threads on 32 core processor with 64 GB RAM. 
Problem I am facing is my Client goes Out of Memory very quickly like within 2-3 minutes with Heap reaching 64 GB and then stalling the complete application.
Each of my key size is around 100 bytes.
I am unable to run any kind of code or decide.

Attaching the code.

public class RunIt implements Runnable {

       static AtomicLong conCount = new AtomicLong();
       
       static String message = "AlphaBetalItsaysIneedtotypeItsaysIneedtotypeatle";
       //static GenericObjectPool<StatefulRedisClusterConnection<String, String>> connectionPool = null;
       
       public RunIt() {

       
       }

       @Override
       public void run() {

        
              //connectionPool = RedisConnectionMaker.getInstance().connection;

              connectToRedis();

              
       }

       
       private static void connectToRedis() {
              try {
                     
                     List<RedisCommand<String, String, ?>> futures = null;
                     StatefulRedisClusterConnection<String, String> lettuceConnection = null;
                     RedisCommand<String, String, ?> command = null;
                     
                     
                     while (true) {
                           try {
                                  

                                  lettuceConnection = RedisConnectionMaker.getInstance().connection;
                                         command = new Command<>(CommandType.SET, new StatusOutput<>(StringCodec.UTF8),
                                                       new CommandArgs<>(new Utf8StringCodec())                                                                     .addKey(String.valueOf(conCount.getAndIncrement())).addValue(message));                                  
                                  lettuceConnection.dispatch(command);                                  
                           }
                           catch (Exception e) {
                                  e.printStackTrace();                                  
                           } finally {
                                  if (command != null) {
                                         command = null;
                                  }
                                  if (futures != null) {
                                         futures = null;
                                  }                       
                                  if (lettuceConnection != null) {
                                         lettuceConnection.close();
                                  }           
                           }            
                     }
              } catch (Exception e) {
                     e.printStackTrace();
              } finally {
                     // connection.close();
              }
       }   
}

**Comment by mp911de** [comment]
The code above has at least two issues:

1. It looks as if you're creating connections in a while loop. This is unfortunate as it creates a lot of garbage. Open a single connection and reuse it across the JVM instance.
2. Command completion is not awaited. This way, you quickly create a lot of commands that are held in a queue and you eventually run out of memory. Use some sort of semaphore or await at least completion of a couple commands before firing an unbounded number of commands.
3. Why do you create an own `Command` object? It has no arguments and the async API exposes almost all Redis commands with proper method signatures. Custom `Command` objects can be useful if you need to invoke a module command or something very specific.

**Comment by coolfreakky** [comment]
Hi mp911de. Thanks for the reply. 
For point 1: We corrected it. We are now creating just 1 connection for 1 JVM instance.
For point 2:  We are now pumping like 6,40,000 set request /second via 32 threads. Code snippet below.
For point 3: We were trying with multiple options and hence came up with **command** object. However now we have removed them.

Even with the below code snippet wherein we are throttling with just 6,40,000 set request/second, my client goes out of heap . The JVisualVM/JConsole does not look good in terms of RAM. 
How do we achieve like even 5,00,000 SET request.

We have been through lettuce documentation like so many times but still not able to figure out how we ensure with FIRE&FORGET and consistent load I am able to run REDIS. With throttling I have ensured backpressure is handled but somehow we are not even able to run with like ~3,00,000 TPS SET operation.
We are certainly missing something. 

Code snippet is below:

`public class WorkerThread implements Runnable {
       
       String value = null;
       private StatefulRedisClusterConnection<String,String> connection;
       private Queue<RedisFuture<String>> futureList;

       // private String value;

       public void setParam(StatefulRedisClusterConnection<String,String> connection2, String value1,
                     Queue<RedisFuture<String>> futureList) {
              this.value = value1;
              this.connection = connection2;
              this.futureList = futureList;

       }

       @Override
       public void run() {
              RedisAdvancedClusterAsyncCommands<String, String> commands = connection.async();
              commands.setAutoFlushCommands(false);
              
              while(true) {
                     
                     for(int i=0;i<1000;i++) {
                     futureList.add(commands.set("a"+Long.toString(RedisTest.atomicLong.incrementAndGet()),  value));
                     
                     }
                     commands.flushCommands();
                     try {
                           Thread.sleep(50);
                     } catch (Exception e) {
                           
                           e.printStackTrace();
                     }
                     
                     
                     
              }
              
       }
       
       
       

}
`
There are 18 threads which in total is putting in 3,30,000 SET request/second. But this does not work.

**Comment by mp911de** [comment]
I'm having trouble to understand "3,30,000". Is it 330000 or is it 330?

If you're using just `SET`, then I recommend that you apply some sort of batching in the sense of collecting like 100 key/value pairs and issuing an `MSET` command.

I cannot give you a definitive answer to how to solve your issue as Lettuce is a Redis client and not a swiss-army knife that will address your requirement, I can only give you a suggestion how things could work:

The next level of load staging would be another control loop that issues like 100 commands. Keep a reference to the first `Future` you get from the `SET` (or `MSET` command) and await its completion. This way, you make sure, that any previous batch of commands was executed successfully and it gives you a certain buffer of active commands with the result that you await completion at least of some commands and you do not run into uncontrolled overloading scenarios.

I'm closing this ticket here as there is nothing more that Lettuce could do for you. Using the reactive API isn't really an option here as the latency between completion and a next command doesn't seem suitable for your requirement.
