### ISSUE TITLE
commandBuffer peforms expensive queue in channelInactive?

### ISSUE THREAD

**Issue by shrimptttttttttt** [lettuce-io/lettuce-core#960]
Hi, all
In branch below 4.5.x, channelInactive will add all queued command to command buffer. If the network is very unstable and qps/traffic is very high, the command buffer will become huge, and this object is can't be recycled by gc. Thus client server is full gc all the time. While I see you remove commandBuffer.addAll call in channelInactive. Is it because what I think? Thanks for you attention and look forward for your reply.

**Comment by mp911de** [comment]
Lettuce retains commands on disconnect to re-trigger these on reconnect. We applied some optimizations in command re-queueing, you might want to check out Lettuce 5 as well.

If that's what you're talking about, then everything works as designed, feel free to close this ticket. If you mean something different, then please elaborate.

**Comment by shrimptttttttttt** [comment]
`@Override
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {

        if (debugEnabled) {
            logger.debug("{} channelInactive()", logPrefix());
        }

        try {
            writeLock.lock();
            setStateIfNotClosed(LifecycleState.DISCONNECTED);

            if (redisChannelHandler != null) {

                if (debugEnabled) {
                    logger.debug("{} deactivating channel handler", logPrefix());
                }

                setStateIfNotClosed(LifecycleState.DEACTIVATING);
                redisChannelHandler.deactivated();
            }

            setStateIfNotClosed(LifecycleState.DEACTIVATED);

            // Shift all commands to the commandBuffer so the queue is empty.
            // Allows to run onConnect commands before executing buffered commands
            commandBuffer.addAll(queue);
            queue.removeAll(commandBuffer);

        } finally {
            writeLock.unlock();
        }

        if (buffer != null) {
            rsm.reset();
            buffer.clear();
        }

        if (debugEnabled) {
            logger.debug("{} channelInactive() done", logPrefix());
        }
        super.channelInactive(ctx);
    }`

Above is branch 3.5.x's code. We can see commandBuffer.addAll(queue) is called without queue size checked in method channelInactive. Because it's called without queue size checked, then commandBuffer can be very huge if channelInactive is being constantly called. But in branch 4.5.x's code, channelInactive won't call  commandBuffer.addAll(queue) as belows

`@Override
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {

        if (debugEnabled) {
            logger.debug("{} channelInactive()", logPrefix());
        }

        if (channel != null && ctx.channel() != channel) {
            logger.debug("{} My channel and ctx.channel mismatch. Propagating event to other listeners.", logPrefix());
            super.channelInactive(ctx);
            return;
        }

        synchronized (stateLock) {
            try {
                lockWritersExclusive();
                setState(LifecycleState.DISCONNECTED);

                if (redisChannelHandler != null) {

                    if (debugEnabled) {
                        logger.debug("{} deactivating channel handler", logPrefix());
                    }

                    setState(LifecycleState.DEACTIVATING);
                    redisChannelHandler.deactivated();
                }

                rebuildQueue();
                setState(LifecycleState.DEACTIVATED);

                channel = null;
            } finally {
                unlockWritersExclusive();
            }
        }

        rsm.reset();

        if (debugEnabled) {
            logger.debug("{} channelInactive() done", logPrefix());
        }
        super.channelInactive(ctx);
    }`


1. I am wondering what is the reason you remove commandBuffer.addAll(queue) in channelInactive?

2. Will commandBuffer.addAll(queue); call in method channelInactive version lower than 4.4.x cause heap size issue?

**Comment by shrimptttttttttt** [comment]
Sorry, I have to correct my question. I have this issue
My client server keep full gc all time. And I get the heap dump. And we found out that the ClientResource's transportBuffer holds 90w+'s Command. 

And I am wondering why...

**Comment by shrimptttttttttt** [comment]
And we stop the traffic, the client server is keeping full gc until OOM, and can't recover. Seems like the worker thread stop consuming the transportBuffer.

**Comment by mp911de** [comment]
I suggest limiting the request queue via `ClientOptions` (see https://github.com/lettuce-io/lettuce-core/wiki/Client-Options). Additionally, you can set `disconnectedBehavior` to reject commands while disconnected. Both settings will protect you from accepting too many command objects.

**Comment by shrimptttttttttt** [comment]
We have configured the ClientOptions max queue size as 4096, but the transport buffer sitll holds 90w+ Commands. We use 3.5.0.Final, by the way. 

And we also found out that we got ConcurrentModificationException as belows
`java.util.ConcurrentModificationException: null
        at java.util.ArrayDeque.delete(ArrayDeque.java:554) ~[na:1.8.0_172]
        at java.util.ArrayDeque.removeFirstOccurrence(ArrayDeque.java:375) ~[na:1.8.0_172]
        at java.util.ArrayDeque.remove(ArrayDeque.java:752) ~[na:1.8.0_172]
        at com.lambdaworks.redis.protocol.CommandHandler.queueCommand(CommandHandler.java:428) ~[lettuce-3.5.0.Final.jar:na]
        at com.lambdaworks.redis.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:372) ~[lettuce-3.5.0.Final.jar:na]
        at com.lambdaworks.redis.protocol.CommandHandler.write(CommandHandler.java:355) ~[lettuce-3.5.0.Final.jar:na]`

We know the problem above is solved in 3.5.1. But I want figure out the reasons with version 3.5.0.Final.

1. Why transportBuffer holds 90w+ Commands? As we have already configured max queue size as 4096?
2. When we stop the traffic, our client server keep full gc, and can't recover.
3. Are #1 and #2  related to transportBuffer.remove failure?

Thank you for your help.

**Comment by mp911de** [comment]
Lettuce 3.5 is out of maintenance for quite a long time and it's not supported anymore. Given the number of bugs we fixed around queue limitation in Lettuce 4 and 5, it's likely that these bugs still persist in Lettuce 3.5.

The actual problem with Lettuce 3.5 command queueing is that operations happen in different threads and that `ArrayDeque` is not bounded. This allows for conditions in which commands can be added although the queue should be bounded.

I strongly advise upgrading to Lettuce 5.

**Comment by mp911de** [comment]
Closing as there's nothing left to do here. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
