### ISSUE TITLE
Cluster syntax configuration should not one node in ConnectToRedisCluster.java?

### ISSUE THREAD

**Issue by zhaoyuguang** [lettuce-io/lettuce-core#963]
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

Cluster syntax configuration should not one node in ConnectToRedisCluster.java ?
---

* Reference documentation: https://lettuce.io/docs/
* Wiki: https://github.com/lettuce-io/lettuce-core/wiki
* Javadoc: https://lettuce.io/core/release/api/
* Gitter Chat: https://gitter.im/lettuce-io/Lobby
* Mailing list https://groups.google.com/d/forum/lettuce-redis-client-users or [lettuce-redis-client-users@googlegroups.com](mailto:lettuce-redis-client-users@googlegroups.com)
* StackOverflow: https://stackoverflow.com/questions/tagged/lettuce
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/LettuceDriver
* Also have a look at the readme for more information on how to get support:
  https://github.com/lettuce-io/lettuce-core/blob/master/README.md

**Comment by zhaoyuguang** [comment]
the demo why not like ?
List<RedisURI> list = new ArrayList<>();
list.add(RedisURI.create("redis://127.0.0.1:6379"));
list.add(RedisURI.create("redis://127.0.0.1:6380"));
RedisClusterClient clusterClient = RedisClusterClient.create(list);

**Comment by mp911de** [comment]
Thanks for clarification. `ConnectToRedisCluster` is a minimal example that does not cover all possible scenarios. While it's common in cloud environments to use a single load balancer connection entry point, other setups (such as static cluster setups) might use multiple connection points.
