### ISSUE TITLE
Do not require CLIENT LIST in cluster topology refresh

### ISSUE THREAD

**Issue by bentharage** [lettuce-io/lettuce-core#973]
We are using Lettuce 5.0.0 and spring-data-redis(v2.1.3) in our application.
We are using a redis cluster and CLIENT/CONFIG commands on redis has been removed for security reasons.

Our application is running without any flows when those commands are present but fails to connect to redis without them.

Following error occurs:
```
2019-01-28 13:55:47.482  WARN 25442 --- [           main] i.l.c.c.topology.ClusterTopologyRefresh  : Cannot retrieve partition view from RedisURI [host='localhost', port=7000], error: java.util.concurrent.ExecutionException: io.lettuce.core.RedisCommandExecutionException: ERR unknown command `CLIENT`, with args beginning with: `LIST`, 
 ```

Is there are any workaround to overcome this problem?

**Comment by mp911de** [comment]
Lettuce uses `CLIENT LIST` to determine the number of connected clients for load balancing. We could make this information optional. Lettuce uses the client count to determine a cluster node with the least number of clients to use that one as default node. The default node is used for Pub/Sub and key-less commands.

**Comment by mp911de** [comment]
That change is in place now.

**Comment by bentharage** [comment]
> That change is in place now.
Thank you very much for the reply @mp911de . Sorry to bother you again but is there a snapshot build that I can try before v5.2.0 is released?
