### ISSUE TITLE
Cluster client is stuck during a master-failover scenario

### ISSUE THREAD

**Issue by alessandrosimi-sa** [lettuce-io/lettuce-core#984]
#### Current Behavior

1 . The cluster client is connected to a cluster of 9 nodes, 3 primary and 6 secondary.
2. One of the master node fails and the secondary successfully take its place
3. During the master failover the client is sending messages to the failing master node
4. The client detects the new topologies (`Partitions` are correctly updated) but the client is stuck on the message already inside the connection the failing master node
5. The client is not able to process any other operations

If the `autoReconnect` is disable the client is able to continue to process messages.

#### Input Code

Here is the entire project with the simulation that shows the problem.

https://github.com/spaceapegames/aws-redis-cluster-test

#### Expected behavior/code

The client should redirect the commands to the new master and process them successfully, the test result should show no failures, just some slow responses.

#### Environment

- Lettuce version(s): 5.1.4.RELEASE
- Redis version: 3.2.x

**Comment by mp911de** [comment]
Care to elaborate about:

> but the client is stuck on the message already inside the connection the failing master node

Lettuce queues commands that were sent initially to the failed master node and it retries to re-issue these commands. The commands are not re-routed to the new master node after the topology refresh.

Is this what you're talking about?

**Comment by alessandrosimi-sa** [comment]
@mp911de thanks for responding so quickly!
The behaviour is no command is processed once the master node has failed.
```
1. send command, successful response
2. the cluster node goes down, but client hasn't detected yet
3. send command, failure (the node is down) and the command is queue, no response
4. keep sending message, no response
5. the client detects the new master
6. keep sending message, no response
7. the client is stuck in this status
```
while the version with `autoReconnect=false` is
```
1. send command, successful response
2. the node goes down, but client hasn't detected yet
3. send command, failure, failed response
4. keep sending message, failed response
5. the client detects the new master
6. keep sending message, successful response
```

**Comment by alessandrosimi-sa** [comment]
@mp911de I had another pass on test scenario and the "stuck" behaviour is caused by the implementation: the next command is executed when the current one is completed.
This is caused by the behaviour you mention: "The commands are not re-routed to the new master node after the topology refresh", if there is another issue open for this, I'm happy to close this one.
Thanks!

**Comment by mp911de** [comment]
On a related node: What happens right now is, that when a node is removed from the cluster (topology no longer contains the node), then Lettuce terminates the connection and commands that are queued get re-triggered to prevent loss of the commands.

Continuing on re-routing in case a node goes down: How would we know that we should retrigger commands? 

A node can go down. Partition refresh happens once in a while. Promotions from replica to master can happen. These events aren't connected to each other, the only connection is serialization across time.

Right now, attempting to connect these events feels like a heuristic. Happy to continue the discussion further to see whether we can get to an approach that works.

**Comment by mp911de** [comment]
Addendum: The underlying assumption is that a disconnect moves queued commands to a disconnected buffer. We could also cancel commands instead of moving these into a disconnected buffer.

**Comment by alessandrosimi-sa** [comment]
You are right about heuristic, when a command fail is hard to make a decision, but I'm wondering if the master-failover scenario is defined enough that is possible to do something.
In the current implementation the disconnect queue lives inside the `DefaultEndpoint`, and is flushed again in case or re-connection.
As you said, on possible solution is when the topology change the commands in the queue are taken the another `DefaultEndpoint` that is the new primary node.
Here a couple of options
1. The disconnect queue should live in an higher level and re-routing the commands when flushed. The problems are: the queue is shared by endpoints and message ordering.
2. The endpoint class can point to another node only if he covers the same slots range, by changing the underlying URL (I think is the address supplier). I don't know the implication of this solution.

**Comment by mp911de** [comment]
The disconnected queue is the disconnected queue because it is closely related to a connection and so to a single node. 

A similar thing came to my mind. As soon as the topology changes, we're propagating the new topology to our connection provider `PooledClusterConnectionProvider`. As part of the update, we're closing stale connections to nodes that are no longer part of the cluster.

At that time, we have three pieces of information available:
* Old topology
* New topology
* The list of connections and the connected/disconnected state

From that information we could check:
* Is a connection, that is currently disconnected a master in the old topology and a replica in the new one? If so, re-send commands
* Is a connection, that is currently disconnected a replica, and we have another replica that is online? If so, re-send commands

What do you think?

**Comment by mp911de** [comment]
Note: I re-labeled this ticket as an enhancement as this is something that could actually work.

**Comment by alessandrosimi-sa** [comment]
I agree about the `disconnected` queue. The semantic is correctly attached to a node.

Regarding the second point, let me see if I understood correctly.

The `PooledClusterConnectionProvider` class receives partitions updates and also it is aware of all connections (`writers` and `readers`) so it is in the perfect position to re-issue `re-send commands`, is that right?

I agree with the two scenarios but, once again, let me check if we are in the same page :-)
I think it is safe to swap nodes the covers the same slots range.

- Lets take an old topology with a master A that covers 0-8796 and replace with a new topology where master is marked as `FAILED` and a new master B covers the same range (0-8796), we can safely say the the message can be resend to the new one.
- Is that true? What happen if other commands are already in the queue? Maybe, as you suggested,  using the `PooledClusterConnectionProvider` we can guarantee that the first time a connection is created it will receive the commands of another connection.

Is that what you mean?

**Comment by mp911de** [comment]
> Do we have ordering issues?

I think yes, that we will always have ordering issues and we cannot make assumptions over the time at which a connection gets established to the newly promoted master node.
So the following is possible:


**Command sequence (application perspective):**

* SET (failure happens here)
* INCR
* GET

**Connection perspective:**

_Old master_
* (failure happens here)
* SET

_Topology update happens_

_New master_
* INCR
* GET

**Command re-send after topology update:**

_New master_
* SET

So the absolute command sequence on the **new master** would be:

* INCR
* GET
* SET (command replay)


So a question can arise: What do we want?
* Fast recorvery
* Correctness

I think we cannot argue against correctness. In any case, what you can do in the application is enabling global timeouts so commands do not linger around forever in the disconnect queue but get timed out. this way, you can reduce the recovery period.

**Comment by alessandrosimi-sa** [comment]
TBH, I much prefer a simple client library than a clever one ;-) I always felt is better to have few expected and well defined behaviours and let the application deal with the rest. I'm happy to drop this `enhancement`. We are going to use the lettuce client extensively in our systems so if I notice something I will be in contact again. Thanks for your time.

**Comment by mp911de** [comment]
I'm also inclined towards closing this ticket in favor of a proper timeout configuration.

Closing without a fix.

**Comment by umang92** [comment]
@mp911de  @alessandrosimi-sa  How was this issue fixed? I am facing a similar problem with Java client.
