### ISSUE TITLE
How can I use zpopmin by Spring RedisTemplate

### ISSUE THREAD

**Issue by shunminli** [lettuce-io/lettuce-core#988]
I can't found the zpopmin support at spring-data-redis 2.1.5.RELEASE...
How can I get lettuce  sync RedisSortedSetCommands by RedisTemplate?

**Comment by mp911de** [comment]
This is the Lettuce issue tracker, not the one of [Spring Data Redis](https://jira.spring.io/browse/DATAREDIS). If you cannot find a method that you would like to use, I propose to file a feature request in Spring Data Redis' [issue tracker](https://jira.spring.io/browse/DATAREDIS).

**Comment by shunminli** [comment]
I'm sorry.
