### ISSUE TITLE
so many dependencies!why not make it simple

### ISSUE THREAD

**Issue by jqncc** [lettuce-io/lettuce-core#990]
so many dependencies!why not make it simple.
the project takes up a lot of memory,because all sorts of dependency,but their function is to have a lot of repetition.
most hated!

**Comment by mp911de** [comment]
Thanks for your feedback. I'd like to reduce the number of dependencies. Do you have a proposal on how we could do so?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
