### ISSUE TITLE
Redis JAVA error after executing APIs continuous till 15 seconds and generates error of [[java.lang.OutOfMemoryError: unable to create new native thread] with root cause]

### ISSUE THREAD

**Issue by neheartRock** [lettuce-io/lettuce-core#993]
While using RedisAsync connection in my JAVA API with tomcat,
after running my API continuous fot 15 to 20 seconds, it will give me the error of...

**[[java.lang.OutOfMemoryError: unable to create new native thread] with root cause]**

> SpringBoot Version :: 5.1.3
tomcat :: 9.0.13
redis ::5.0.3
lettuce version :: lettuce-2.3.3

> Error Logs...

[rrlogs.txt](https://github.com/lettuce-io/lettuce-core/files/2936099/rrlogs.txt)

Thanks...

**Comment by mp911de** [comment]
Not exactly sure about the Lettuce version as this repo maintains only versions 3.x to 5.x.

In any case, it is very simple to overwhelm the client by using the asynchronous API and to run into OutOfMemory. Can you share a bit of code that is able to reproduce the issue?

**Comment by neheartRock** [comment]
Sure...

Here i am just opening the connection and closing the connection and run this API for more than 20 times and this error is generated...


![img_20190307_100444](https://user-images.githubusercontent.com/43150053/53932961-465f6200-40c2-11e9-83d2-2eb524d10017.png)

**Comment by neheartRock** [comment]
Issue is solved By using connection pooling mechanism...

**Comment by mp911de** [comment]
The issue is caused by constantly creating a client and a connection on each call. Either reuse `RedisClient` and `StatefulRedisConnection` or use pooling.

**Comment by neheartRock** [comment]
Yes..
