### ISSUE TITLE
Add support for XINFO

### ISSUE THREAD

**Issue by Erzhoumu** [lettuce-io/lettuce-core#996]
Hello, the docs has been checked, but i have not found the support for XINFO when using stream commands and eval is not working very well for "stream".
The XINFO command is very important when we want to know the essential info of the queue efficiently.  Especially for the monitor of the queue.

We want the lettuce and support the XINFO in the last vesion.
Thank you very much.

**Comment by mp911de** [comment]
`XINFO` has three subcommands with various response structures and so we decided to not immediately implement these commands as they also were likely to change.

You can execute `XINFO` using the `dispatch` method:

```java
List<Object> xinfo = redis.dispatch(MyKeywords.XINFO, new ArrayOutput<>(StringCodec.UTF8), new CommandArgs<>(StringCodec.UTF8).add("STREAM").add("stream-1"));

System.out.println(stream);

enum MyKeywords implements ProtocolKeyword {
    XINFO;

    @Override
    public byte[] getBytes() {
        return name().getBytes();
    }
}
```

**Comment by Erzhoumu** [comment]
Thanks~
